### ISSUE TITLE
Printer prints in portrait mode despite selecting landscape mode when printing labels

### ISSUE THREAD

**Issue by gamolinf** [OpenPrinting/cups#1003]
**Describe the bug**
When printing labels and setting the label size, the printer prints in portrait mode even when the landscape mode is selected.

**To Reproduce**
1. Set up the printer with the desired label size.
2. Select landscape mode in the print settings.
3. Print a label.
4. Observe that the output is in portrait mode instead of landscape mode.

**Expected behavior**
The printer should print labels in landscape mode when the landscape mode is selected.

**System Information:**
- Printer Model: BIXOLON SLP-DX220
- Fedora 40, KDE Plasma
- CUPS version [e.g. 2.4.2]

**PPD File Parametrs**
*OpenUI *PageSize/Media Size: PickOne
*OrderDependency: 10 AnySetup *PageSize
*DefaultPageSize: 60x40mm
*PageSize 60x40mm/60x40mm: "<</PageSize[170 113]/ImagingBBox null>>setpagedevice"
*CloseUI: *PageSize

*OpenUI *PageRegion: PickOne
*OrderDependency: 10 AnySetup *PageRegion
*DefaultPageRegion: 60x40mm
*PageRegion 60x40mm/60x40mm: "<</PageSize[170 113]/ImagingBBox null>>setpagedevice"
*CloseUI: *PageRegion

*ImageableArea 60x40mm/60x40mm: "0 0 170 113"
*PaperDimension 60x40mm/60x40mm: "170 113"

**Comment by michaelrsweet** [comment]
Please enable debug logging (`cupsctl --debug-logging`) and reproduce the problem, then attach the CUPS "error_log" file.

Thanks!
