### ISSUE TITLE
Unable to enable Sharing when modifying a printer from the CUPS web UI 

### ISSUE THREAD

**Issue by darian-au** [OpenPrinting/cups#1008]
**Describe the bug**
Unable to enable Sharing when adding or modifying a printer from the CUPS web UI (CUPS version 2.4.10).

**To Reproduce**
From the CUPS web UI in a browser:
Administration tab -> Manage Printers -> choose printer -> Modify Printer -> Continue
choose/tick Sharing: Share This Printer
continue onwards to complete modifying printer

**Expected behaviour**
Printer should be shared.

**Actual behaviour**
Printer is not shared.

**Workaround**
Manually modify `/etc/cups/printers.conf` and change "Shared No" to "Shared Yes"

**System Information:**
 - OS: Linux OpenWrt 23.05.3 aarch64 (Raspberry Pi 4)
 - Browser: Safari 16.6.1 on MacOS 11.7.10 Big Sur
 - CUPS version: 2.4.10

**Relevant Logs**
Observed logs when turning sharing off and then back on again from CUPS web UI (after above workaround).

`/var/log/cups/error_log`
```
D [11/Jul/2024:10:15:17 +1000] [CGI] cgiSetVariable: PRINTER_IS_SHARED=\"\"
I [11/Jul/2024:10:15:17 +1000] Setting USB printer-is-shared to 0 (was 1.)
```
```
D [11/Jul/2024:10:17:26 +1000] [CGI] cgiSetVariable: PRINTER_IS_SHARED=\"on\"
I [11/Jul/2024:10:17:26 +1000] Setting USB printer-is-shared to 0 (was 0.)
```
**Additional context**
Looking at the code changes in this [commit](https://github.com/OpenPrinting/cups/commit/d847b53e88d64faf2c4a0bf8fc19f7112060778c#diff-325c4165c1104f3e60bdbbcd3e6f2ff417e25cdb483688350a5f77d39699dcd4), possibly the handling for string "on" was removed at `cgi-bin/admin.c`?

```
1169 -    var = cgiGetCheckbox("printer_is_shared");
1170 -    ippAddBoolean(request, IPP_TAG_PRINTER, "printer-is-shared",
1171 -                  var && (!strcmp(var, "1") || !strcmp(var, "on")));
1162 +    ippAddBoolean(request, IPP_TAG_PRINTER, "printer-is-shared", cgiGetCheckbox("PRINTER_IS_SHARED"));
```

**Comment by darian-au** [comment]
On further investigation, I have tried out various previous versions of CUPS. The mentioned commit in the issue is probably a red herring. Versions 2.4.10; 2.4.9; 2.4.8 all exhibit the same Sharing problem, while version 2.4.7 doesn't. So there is likely a change in 2.4.8 when the Sharing problem started occuring. Additionally the Sharing problem occurs when I both Add or Modify a Printer.

**Comment by zdohnal** [comment]
Hi @darian-au !

Thank you for the investigation - it looks the new checkbox support was not complete, so that's why it didn't work - I've tried to implement it in the mentioned PR.

**Comment by zdohnal** [comment]
@darian-au if you could, it would be great if you tried the PR I've created.

**Comment by darian-au** [comment]
Thank you very much @zdohnal !

The Sharing checkbox is working much better now.

To apply the patch from your PR against the `2.4.x` branch I had to remove the changes for the Polish (pl) language templates. Luckily all the other differences seem to apply without problem. 
I tested a build locally and I can see the `CHECKED` value on the checkbox input fields of the rendered html.

Will you be applying the PR against the `2.4.x` branch for an upcoming `2.4.11` build?

**Comment by zdohnal** [comment]
@darian-au if the patch gets ack, then I will do my best (I have my responsibilities and I tend to switch among them, so I might forget) to apply the fix to the branch 2.4.x :) .

**Comment by tiendq** [comment]
> On further investigation, I have tried out various previous versions of CUPS. The mentioned commit in the issue is probably a red herring. Versions 2.4.10; 2.4.9; 2.4.8 all exhibit the same Sharing problem, while version 2.4.7 doesn't. So there is likely a change in 2.4.8 when the Sharing problem started occuring. Additionally the Sharing problem occurs when I both Add or Modify a Printer.

I believe there're several checkbox issue with OpenPrinting CUPS 2.4.10.

Even I checked `Share this Printer`, the added printer was still `Not Shared`. Manually edit file `/etc/cups/printers.conf` did not solve the issue, printer was still not shared and other computers on couldn't see it.

It was even worse, I ran `sudo cupsctl --remote-any` to allow access CUPS remotely but the checkbox `Allow remote administration` was still unchecked, interestingly if I checked it and restarted the service then boom. I could not remote access!!! Needed to run again `sudo cupsctl --remote-any`.

I was able to share my printer a few days ago then now I just installed the latest update of Pi OS (just released new update yesterday), and reinstall CUPS, then I could not share printer again :(

**Comment by GuillaumeRAMPON** [comment]
As a workaround, I aws able to force the sharing of the printer using command line : 
lpadmin -p <printer_name> -o printer-is-shared=true

**Comment by city41** [comment]
As another possible workaround, running `sudo cupsctl --share-printers` helped me. Suddenly my printer was visible on the network after doing that. I ultimately got a printer to work with all my clients within my network via cups and can't say what thing or combo of things finally did it unfortunately. I threw a lot of things at the wall. But if you're as stuck as I was, `cupsctl` might help.

**Comment by michaelrsweet** [comment]
@city41 There is a top-level checkbox on the admin page that controls whether printers are advertised on the network ("Share printers connected to this system"), and that is the same thing that the cupsctl command is changing... :)

**Comment by harold-miller** [comment]
> As another possible workaround, running `sudo cupsctl --share-printers` helped me. Suddenly my printer was visible on the network after doing that. I ultimately got a printer to work with all my clients within my network via cups and can't say what thing or combo of things finally did it unfortunately. I threw a lot of things at the wall. But if you're as stuck as I was, `cupsctl` might help.

This is what finally worked for me. Thank you!!
