### ISSUE TITLE
Get-Notifications in not correctly reporting changes in status

### ISSUE THREAD

**Issue by Vzor-** [OpenPrinting/cups#1013]
When I pause, then unpause a printer with a subscription, I get 2 events when I run "get-notifications"
```
notify-sequence-number: 1 integer {1}
notify-subscribed-event: 1 keyword {printer-stopped}
notify-text: 1 textWithoutLanguage {Printer "_127_0_0_1" state changed to stopped.}
printer-state: 1 enum {stopped}
printer-state-reasons: 1 keyword {paused}
printer-is-accepting-jobs: 1 boolean {false}
------------------------
notify-sequence-number: 1 integer {2}
notify-subscribed-event: 1 keyword {printer-state-changed}
notify-text: 1 textWithoutLanguage {Printer "_127_0_0_1" state changed to idle.}
printer-state: 1 enum {idle}
printer-state-reasons: 1 keyword {paused}
printer-is-accepting-jobs: 1 boolean {false}
```
The second of those events shows the printer is `idle`, but the state reason is erroneously reported as `paused`. If we manually get the state of the printer, we get
```
printer-state: 1 enum {idle}
printer-state-reasons: 1 keyword {none}
printer-is-accepting-jobs: 1 boolean {false}
```

1. Set up a printer subscription with `"Create-Printer-Subscription"`
2. Pause the printer, then unpause it
3. Get the events with `"Get-Notifications"`

This issue was tested on arm MacOS 14.3, as well as various arm Fedora versions. The newest cups version tested was 2.4.7, and the oldest tested was 2.3.3.

**Comment by michaelrsweet** [comment]
[master 5d1aaa79e] Fix printer-state-reasons/message in notifications (Issue #1013)

[2.4.x 95456db25] Fix printer-state-reasons/message in notifications (Issue #1013)
