### ISSUE TITLE
4x6*2 media I cannot get the cutter to activate.

### ISSUE THREAD

**Issue by Ernest156** [OpenPrinting/cups#1024]
Hello everyone, I'm looking for help and I hope someone has already had this problem and can help me solve it.
Trying the dnp line and have dnp rx1hs . I am able to get them to print , my issue is I cannot activate the cutter on any of them. It’s odd because the cutter does activate under test, but when printing an actual picture from my camera roll and selecting the 4x6*2 media I cannot get the cutter to activate. Any tips ?
Important note: when printing via an Android phone, it works just fine. Only when printing via iPhone does the
problem persists.

**Comment by zdohnal** [comment]
Hi,

IIUC you experience the problem when printing via iPhone - have you built our project for your phone?

If you haven't, please contact the Apple support for further help.

**Comment by Ernest156** [comment]
My setup consists of DNP RX1 and Orange Pi3B running Linux with CUPS and the most recent version of Gutenprint 5.3.5. Everything used to run smoothly and flawlessly until the iOS 17.5.3 update. Ever since the update, I am able to print; however, the guillotine or the 2-inch cut function is not working.
