### ISSUE TITLE
Epson Aculaser C4100

### ISSUE THREAD

**Issue by jean202222222** [OpenPrinting/cups#1036]
Hi
Epson Aculaser C4100 printer has LJ4, ESCP2, FX, I239X and GL2 emulations. Postscript was not a free option. So I have not this option.
eplaser driver doesn't work and associated URL doesn't work also. 
PCL drivers send all black page. It is not nice.
Best regards

**Comment by zdohnal** [comment]
I would recommend trying Epson driver for ESCP2 (it is called epson-inkjet-printer-escpr2 in Fedora, I don't know the name in other OSes), or foomatic driver for your printer which uses LJ4.
