### ISSUE TITLE
Handling of "air" key in the DNS-SD TXT record looks incorrect

### ISSUE THREAD

**Issue by alexpevzner** [OpenPrinting/cups#1037]
Hi,

According to the specification, the `"air"` key in the DNS-SD TXT record may take one of the following vales:
* "certificate"
* "negotiate"
* "none"
* "oauth"
* "username,password"

However, TXT record parser at the `cups/dest.c` file near the line 2811 (function `cups_dest_query_cb`) contains the following code fragment:

```
  if (!_cups_strcasecmp(key, "air") && !_cups_strcasecmp(value, "t"))
  {
    type |= CUPS_PTYPE_AUTHENTICATED;
  }
```

Obviously it does something different that specification requires (I guess it's just a copy-paste of some boolean flag decoder).

It doesn't seem that this issue causes any real problems, but anyway it worth being documenting here...

**Comment by zdohnal** [comment]
Hi Alex,

thank you for spotting this! For myself a link to the spec https://ftp.pwg.org/pub/pwg/candidates/cs-ippeve11-20200515-5100.14.pdf .

I can add those checks according the specifications, but at least oauth authentication is on the roadmap to be implemented in the future, so it might not work further down the line.

**Comment by alexpevzner** [comment]
Hi Zdenek,

I use also this one: https://developer.apple.com/bonjour/printing-specification/bonjourprinting-1.2.1.pdf . They sometimes differ from PWG specs in few details. Unfortunately, the latest publicly available version is 1.2.1, and newer versions were not published.

Regarding this issue, I guess it only breaks accuracy of the `CUPS_PTYPE_AUTHENTICATED` flag setting and not sure that anybody at all uses this flag. The real negotiation of the authentication parameters will be, most likely, implemented at the HTTP or IPP level. DNS-SD just doesn't provide enough details.

The issue itself could probably be fixed by rewriting the code as follows:
```
  if (!_cups_strcasecmp(key, "air") && _cups_strcasecmp(value, "none"))
  {
    type |= CUPS_PTYPE_AUTHENTICATED;
  }
```
assuming that any value except `none` implies the `CUPS_PTYPE_AUTHENTICATED` flag,

@michaelrsweet, WDYT?

**Comment by zdohnal** [comment]
I would go with enumerating valid values which indicate authentication to protect against random strings as values.

**Comment by alexpevzner** [comment]
At this case the device that requires some non-standard or not yet supported authentication (or just contains typo in the keyword) will be erroneously marked as not requiring authentication.

I think that in a case of broken/incompatible devices the risk of false positive detection the device as requiring authentication is safer to accept that the risk of false negative detection some device as not requiring authentication.

**Comment by michaelrsweet** [comment]
I think it is enough to mark anything other than “none” as requiring authentication. WRT values they intentionally mirror most of the uri-authentication-supported values (except basic and digest for historical reasons)

**Comment by alexpevzner** [comment]
>  WRT values they intentionally mirror most of the uri-authentication-supported values

BTW, uri-authentication-supported is 1setOf keyword and allows multiple values to be listed. For "air", it is not quite clear from the specification if it can contain a comma-separated list of keywords, or just a single keyword.

**Comment by michaelrsweet** [comment]
@alexpevzner So "air" is single-valued, and "uri-authentication-supported" is effectively too since each value corresponds to its mates in "printer-uri-supported" and "uri-security-supported".

The original Bonjour Printing spec says:

> The value specifies the type of authentication required for the service and MUST be one of the following:
>
> - “none”; No authentication is required.
> -  "certificate"; The service uses the Client's TLS certificate for authentication.
> -  “username,password”; The service requires Basic or Digest authentication with a username and password.
> -  “negotiate”; The service requires Negotiate authentication with Kerberos credentials.
>
> The default value is “none”. This key only has meaning for printers that support IPP and MUST NOT be included in TXT records for LPD or Socket queues.

The "one of the following" means 1 value...
