### ISSUE TITLE
Problems with ps converting pcl files too big

### ISSUE THREAD

**Issue by qingdaoqin** [OpenPrinting/cups#1042]
When converting ps to pcl on Kirin Server Edition, I encountered java memory overflow exception, the converted pc file is only 6M, but the converted pcl file reaches 157M, try to upgrade cups to 2.3.3op2 and execute the command cupsfilter -p to convert, it fails.

Environment: cups version 2.2.13, 
OS:Linux localhost.localdomain 4.19.90-23.8.v2101.ky10.x86_64 #1 SMP Mon May 17 17:08:34 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

<img width="797" alt="企业微信截图_20240902102058" src="https://github.com/user-attachments/assets/16720098-083f-46d6-9b34-87560d499790">
<img width="848" alt="企业微信截图_20240902102141" src="https://github.com/user-attachments/assets/763a12f1-5059-4371-a69b-ce8a8640d862">

**Comment by zdohnal** [comment]
Does the Java code run any filter provided by CUPS project? We don't provide any filters written in Java...
