### ISSUE TITLE
How to execute a specific command before printing?

### ISSUE THREAD

**Issue by SeeleVolleri** [OpenPrinting/cups#1045]
Hi guys, I am using HP Laserjet 1020 plus (hp laserjet 1020), the hplip propriteriy driver requires manual execute `hp-firmware` to download the firmware, then start printing. Otherwise the printer just sitting there watch me find why it doesn't work.

**System Information:**
 - OS and its version: [Debian12 running docker `olbat/cupsd:latest(PRETTY_NAME="Debian GNU/Linux trixie/sid")`]
 - Application [cups webui print test page]
 - CUPS version [e.g. 2.4.10]

**Additional context**
Docker running using
```
$ docker run -d --name=cups \
--net="host" \
--privileged=true \
-e TZ="Asia/Shanghai" \
-v /dev:/dev \
-v "/etc/avahi/services:/etc/avahi/services" \
-v /var/run/dbus:/var/run/dbus \
olbat/cupsd
```

```
root@Sumeru:/# lpstat -l -e
_1020_Sumeru network none ipps://%E6%83%A0%E6%99%AE%201020%20%40%20Sumeru._ipps._tcp.local/cups
HP_LaserJet_1020_USB_S413MJ9_HPLIP permanent ipp://localhost:631/printers/HP_LaserJet_1020_USB_S413MJ9_HPLIP hp:/usb/HP_LaserJet_1020?serial=S413MJ9
```

**Comment by ValdikSS** [comment]
Make the udev rule on your host to run the command you need upon connecting. You can check such a rule in either hplip or foo2zjs.

**Comment by georgeraraujo** [comment]
Looks like a job for [Tea4CUPS](http://www.pykota.com/software/tea4cups/), more specifically with a prehook.
The Debian Wiki has [an entry](https://wiki.debian.org/CUPSTea4CUPS) with a description of the capabilities of Tea4CUPS with examples.

**Comment by SeeleVolleri** [comment]
Thanks, I tried and works as I expected!
