### ISSUE TITLE
CUPS-PDF printing in SUSE not print second file in a multi-file print job

### ISSUE THREAD

**Issue by Kishi4u** [OpenPrinting/cups#1053]
Hi
We have installed CUPS-PDF version cups-pdf-3.0.1-lp152.3.5.x86_64 and configured it on our SUSE Linux servers. Printing to PDF files is working however, when the print job has multiple PDF files the print job is not working. With reference to blogs https://github.com/OpenPrinting/cups/issues/213, we have set the parameter *cupsManualCopies: True in cups-pdf.ppd file, but still the issue is not resolved.

Looking for some expert advise to resolve the issue.

Thanks
Kishore K.

**Comment by zdohnal** [comment]
Hi,

cups-pdf is not part of CUPS project, so please report to their bug tracker. In general, printing of multiple files works in CUPS 2.4.10, so the issue is not in printing multiple files in general.

**Comment by Kishi4u** [comment]
Hi 
Thanks for your response
Can you share the bug tracker where to report the issue ?

**Comment by zdohnal** [comment]
The rpm which ships cups-pdf should have a link to upstream project or its web site once you inspect it.
