### ISSUE TITLE
Weird symbols when trying to add printer

### ISSUE THREAD

**Issue by r3n3647** [OpenPrinting/cups#1060]
**Describe the bug**
If you try to add a printer in CUPS web interface using the administration tab -> add printer you will get only some weird symbols (empty squares, white question-marks in black rhombus, underlines...) in step 2/5 in 'connection' field instead of some existing printer or some useful URI.

**To Reproduce**
1. Go to CUPS web interface -> administration tab -> add printer -> step 2/5
2. it does make no difference if there is a printer connected to server or not 
3. see garbage in 'connection'

**Expected behavior**
If there is a printer connected to the server the field 'connection' should show its URI - not some weird mojibake.

**System Information:**
 - ArchLinux 6.10.10-arch1-1 x86_64 GNU/Linux
 - any Browser
 - CUPS version 2.4.10

**Additional context**
Any additional information which are relevant to the issue.

**Comment by zdohnal** [comment]
Fixed by https://github.com/OpenPrinting/cups/commit/eb34f2698 and https://github.com/OpenPrinting/cups/commit/21a392d87 .
