### ISSUE TITLE
Print Requests No Longer Directed To Print Queue

### ISSUE THREAD

**Issue by Terry1955** [OpenPrinting/cups#1062]
2024-09-26 

The system sees the printer. Printer is enabled. Print request stopped going to print queue after recent CUPS update. Documents will not print.

Running MX 23 (Xfce) 

CUPS version 2.4.2-3+deb12u7

Bug report attached. 

[troubleshoot.txt](https://github.com/user-attachments/files/17151326/troubleshoot.txt)

**Comment by michaelrsweet** [comment]
The attach file indicates that cupsd isn't running. Might be a "partial update" issue, but not specific to the CUPS project.

Verify that you have done a complete update, then try starting the CUPS service with whatever command your Linux distro uses - probably "systemctl start cups.service" or similar. If it doesn't start, look at the systemd logs.
