### ISSUE TITLE
Unpicked Presets in GNOME 46

### ISSUE THREAD

**Issue by Nico7as** [OpenPrinting/cups#1064]
Hi, 
First, I apologize in advance if it's not the right place to post this issue. I've looked into GNOME's Gitlab, but can't find my way to the proper project... Sorry for asking it here, and asking you to do the triage...

**Describe the bug**
In Fedora 46 with GNOME. Some printers presets are picked up by the Print Dialog, others aren't.
For example : 
- Color, numbers of pages per side, are picked up.
- Two-sided presets aren't...

**To Reproduce**
1. Install several instances of the same printer, with differents presets, in particular for two-sided printing.
2. Open a document with a GTK4 app, such as Papers
3. Open the Print Dialog, select the preset-printer with two-sided print preset
4. Go to the Page Setup Dialog menu
5. See that the Two-sided printing is set to One Side, insted of Two Sides - like in the preset.

**Expected behavior**
Every preset should be picked up by the Print Dialog

**Screenshots**
![Print_Dialog-GTK4-presets_issues-1](https://github.com/user-attachments/assets/726bfe0e-990a-45a1-8654-db84df85b9a7)
![Print_Dialog-GTK4-presets_issues-2](https://github.com/user-attachments/assets/6de1c650-4531-4780-af93-73a01384efb8)
![Print_Dialog-GTK4-presets_issues-3](https://github.com/user-attachments/assets/ef9b38fd-1db7-4656-9aba-4be4b35022fc)

**System Information:**
 - Fedora 46
 - Print Dialog GTK 4  (its worse with the GTK3 version...)
 - CUPS version : I don't no, the last one to date in Fedora 46 (29/09/2024)

**Additional context**
I'm french teacher, I print a lot. My computer is in french.
I could try and retry this on a english set up computer, if it helps.

**Comment by michaelrsweet** [comment]
I'm really not sure what GNOME project this belongs to, but it definitely is an issue in the GNOME print dialog code. Best place to start is with Fedora support, who can direct it to the correct upstream project...
