### ISSUE TITLE
Printing fails (cups-pki-invalid)

### ISSUE THREAD

**Issue by sampie** [OpenPrinting/cups#1072]
There is a longterm issue of printers failing to print due to cups-pki-invalid error. Deleting certificate file helps for a while, but the problem reoccurs. The problem occurs even if printer's certificate has been renewed.

There is a report here:

https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1973441

It would even help a great deal if it would be known how to disable this pki check from cups.

**Comment by michaelrsweet** [comment]
What needs to happen is the desktop software should display this alert with an option for resetting (deleting) the certificate. That is outside the scope of this project. Ordinarily the certificate should not change for a while (default on most printers is 10 years for their self-signed certs).

Disabling the PKI check disables an important security check. If you don't want the protections of TLS then change the queue to not use IPPS (that's part of the device URI). Run:

    lpstat -v

to get the device URI and then:

    lpadmin -p PRINTER -v URI

with any instances of "ipps" changed to "ipp" in the URI.

**Comment by sampie** [comment]
Hi, my printer certificate is valid until 2029. Still cups says cups-pki-invalid from time to time. I checked the certificate (/etc/cups/ssl/m552.local.crt) and it indeed was valid until 2029 and still cups gave this error.

**Comment by sampie** [comment]
The certificates look pretty much the same, but the certificate serial numbers are different. True, it seems like printer re-generates its certificate after a week or so.  I am just wondering if this is a normal behavior of printers or clearly a bug in them that should be fixed by manufacturers. Somehow, these printers do work with MS Windows without problems.

**Comment by michaelrsweet** [comment]
Unless you are using the IPP Class driver on Windows, the connection to the printers will not be encrypted... And yes if they are regenerating their certificates that often, that is a clear firmware bug in the printer.

**Comment by sampie** [comment]
The printer management console actually says: "A self-signed identity certificate is installed by default. Though it ensures data security through encryption, it is not accepted for authentication."

So, I think in any case the self-signed certificates should not be used for authentication of any form.

**Comment by michaelrsweet** [comment]
Self-signed certificates *are* used for authenticating connections - pinning ("trust on first use") is the mechanism used for self-signed certs (think ssh). Anonymous TLS could be used to encrypt without authentication, but really what's the point - it becomes trivial to intercept the traffic (bye bye encryption) and you have no guarantee you are actually talking to your printer.

**Comment by sampie** [comment]
I submitted a ticket to HP asking technical assistance and information regarding this issue.

**Comment by sampie** [comment]
I am trying to disable TLS and get the printer to work.

$ lpstat -v
device for HP_Color_LaserJet_M552_5F80BF: implicitclass://HP_Color_LaserJet_M552_5F80BF/

It seems I don't have instances with ipps. 

$ sudo lpadmin -p HP_Color_LaserJet_M552_5F80BF -v ipp://HP_Color_LaserJet_M552_5F80BF/
$ lpstat -v
device for HP_Color_LaserJet_M552_5F80BF: ipp://HP_Color_LaserJet_M552_5F80BF/

Anyway, if I convert implicitclass to ipp, when trying to print I get an error saying that the printer might not be connected.

**Comment by michaelrsweet** [comment]
"implicitclass" is something from the cups-browsed project. You don't want to use that.

Instead, run "lpinfo -v" to find the proper (direct) URI, which will start with "ipp", "ipps", or "dnssd".

**Comment by sampie** [comment]
Thank you! Printing started to work with direct URIs and ipp protocol.

**Comment by Poikilos** [comment]
That isn't really a solution though--it is just saying not to use certs... It is still happening on Linux Mint 23 and I have to delete certs regularly, even though using the URI `implicitclass://Lexmark_C3326dw/` which **gets re-added within 1 second even if I delete the printer...** Also, some ppl say ipps is default for them. Also, is the one in linux distros (such as Linux Mint 23 having this problem) maintained by OpenPrinting or Apple? Apple has an open issue for it: https://github.com/apple/cups/issues/6141

**Comment by zdohnal** [comment]
@Poikilos based on the uri you have cups-browsed (not part of CUPS) running, which adds the printer automatically. Disable and stop the service and the printer stays deleted.

**Comment by tillkamppeter** [comment]
> What needs to happen is the desktop software should display this alert with an option for resetting (deleting) the certificate. That is outside the scope of this project. Ordinarily the certificate should not change for a while (default on most printers is 10 years for their self-signed certs).

This would be the solution for desktop systems. Needs to be implemented somewhere in the desktop. Perhaps CPDB could get support for error response pop-ups, where the errors and responses are defined in each backend.

**Comment by vsessink** [comment]
To resolve this long standing issue, I made `/etc/cups/ssl` a softlink to `/tmp/`, so that every restart of the client computer will reset the certificates.

As a personal note, I must say it's fascinating to see that software that is supposed to actually disclose information in print - i.e. readable for anyone that walks by the printer, values _confidentiality_ over _availability_ in the process. (For the uninitiated: security in computing breaks down into three components: confidentiality, integrity and availibility).

Thinking about it, it makes sense: whenever OpenPrinting makes end users cry (*) for not being able to print - again! - this helps keeping the information confidential.

Please note that even removing a printer does not seem to remove the certificate. Again: this helps confidentiality. Openprinting simply helps you keep your documents secret.

(*) unfortunately, I'm not joking - or even exaggerating.

**Comment by Poikilos** [comment]
> software that is supposed to actually disclose information in print - i.e. readable for anyone that walks by the printer, values _confidentiality_ over _availability_ in the process. (For the uninitiated: security in computing breaks down into three components: confidentiality, integrity and availibility).

lol true. Gotta keep that plain text 2 feet away encrypted.

**Comment by jamesdrake101** [comment]
@michaelrsweet 

> What needs to happen is the desktop software should display this alert with an option for resetting (deleting) the certificate. That is outside the scope of this project. Ordinarily the certificate should not change for a while (default on most printers is 10 years for their self-signed certs).

My certificates change every 3 months because I use Let's Encrypt. While my browser will seamlessly accept the new certificate, I have to remember to essentially clear CUPS every three months.
I am not a TLS connoisseur, but what exactly is preventing CUPS from behaving like Safari which will see my new quarterly Let's Encrypt certificate and think "well, the chain checks out, at the top there's a root CA ensuring trust, we're good to go" or something?

I have set the following:

```
sudo defaults write /Library/Preferences/org.cups.PrintingPrefs.plist AllowAnyRoot -bool NO
sudo defaults write /Library/Preferences/org.cups.PrintingPrefs.plist AllowExpiredCerts -bool NO
sudo defaults write /Library/Preferences/org.cups.PrintingPrefs.plist Encryption -string Required
sudo defaults write /Library/Preferences/org.cups.PrintingPrefs.plist SSLOptions -string "DenyTLS1.0"
sudo defaults write /Library/Preferences/org.cups.PrintingPrefs.plist TrustOnFirstUse -bool NO
sudo defaults write /Library/Preferences/org.cups.PrintingPrefs.plist ValidateCerts -bool YES
```

I still can't get CUPS to look at the certificate presented by the printer, whatever that is at any given point in time, and, I dunno, validate it like any browser has been doing for the last 20 odd years?

What am I missing?

**Comment by michaelrsweet** [comment]
@jamesdrake101 
> ...
> My certificates change every 3 months because I use Let's Encrypt. While my browser will seamlessly accept the new certificate, I have to remember to essentially clear CUPS every three months. I am not a TLS connoisseur, but what exactly is preventing CUPS from behaving like Safari which will see my new quarterly Let's Encrypt certificate and think "well, the chain checks out, at the top there's a root CA ensuring trust, we're good to go" or something?

CUPS 2.5 and later will support validation against well-known (CA) roots installed on the system - the code has been in place for a while now and libcups (the CUPS 3.0 library project) was recently released with this functionality. We're hoping to get a beta of 2.5 out "soon"...

**Comment by jamesdrake101** [comment]
Thanks for the reply!


> CUPS 2.5 and later will support validation against well-known (CA) roots installed on the system - the code has been in place for a while now and libcups (the CUPS 3.0 library project) was recently released with this functionality.

Is there any way I can ram the Let's Encrypt CA and intermediaries into whatever certificate store CUPS is currently using? Purity is not a concern so I'd be happy to take a workaround.


> We're hoping to get a beta of 2.5 out "soon"...

Great news, thanks again.

**Comment by michaelrsweet** [comment]
@jamesdrake101 Not sure, plus it'll depend on which platform since we only normalized the cert handling code in 2.5 and later... :/

**Comment by jamesdrake101** [comment]
Fair enough. I am on macOS and not fully familiar with how it stores secrets; I checked in the obvious place (system and user keyring) and cached (presumably TOFUd) CUPS certs are not there at least.
