### ISSUE TITLE
Cannot install libcups2 2.4.2-3+deb12u8 package on OpenMediaVault

### ISSUE THREAD

**Issue by ArbaazPatwari** [OpenPrinting/cups#1074]
**Describe the bug**
Error installing libcups2 2.4.2 libcups2 2.4.2-3+deb12u8. I tried to install updates on my NAS running OpenMediaVault. This cups package failed to install multiple times when I pressed 'install updates'. I got an error 500 - internal server error. I wrote an email to the Debian Printing Team, and the update/ software's home page was linked to this GitHub repository so I wanted to check it out. I don't think I saw any other user report the issue so I will (hopefully this is the right place).

**To Reproduce**
1. Go on OpenMediaVault Admin Dashboard.
2. Navigate tabs System > Update Management > Updates
3. Install 'libcups2 2.4.2-3+deb12u8' common unix print system - core library package.

**Expected behavior**
Packages to install cleanly with no error.

**Screenshots**
![error_installing_cups_update_omv](https://github.com/user-attachments/assets/60b26022-9597-4c36-bc9a-a970e05df39e)

**System Information:**
 - OS: OpenMediaVault version 7.4.9-1 (Sandworm). Linux Kernel: 6.6.47+rpt-rpi-2712
 - OpenMediaVault Admin Dashboard
 - CUPS: libcups2 2.4.2-3+deb12u8

**Additional context**
Other packages installed fine. This update could not install properly.

**Comment by zdohnal** [comment]
Hi,

please report the issue to Ubuntu bug report system - https://help.ubuntu.com/stable/ubuntu-help/report-ubuntu-bug.html.en .

**Comment by ArbaazPatwari** [comment]
Hi,

I can do that but why should the Ubuntu developers do it? Isn't it a cups
or Debian software issue? Or even OMV.

Arbaaz P.
Arbaaz P.

**Comment by zdohnal** [comment]
The issue is with installing the Ubuntu package, we as upstream project don't provide OS specific packages, distribution developers/maintainers do - they take our upstream releases and package them into formats you can install via repositories.

**Comment by zdohnal** [comment]
Ah, my bad! I saw .deb suffix and thought it is Ubuntu/Debian - so then report to your OS - OMV :) . Either way, this error is not something we can fix.

**Comment by ArbaazPatwari** [comment]
Ah ok
Arbaaz P.
