### ISSUE TITLE
Nested cups classes

### ISSUE THREAD

**Issue by tchartron** [OpenPrinting/cups#1075]
Hello there, i'll try to explain why i would need nested printer classes and i hope it'll be easy to understand.

I have a scenario where i have a cups class lets call it `CLASS-01` which has some 203 dpi printers in it.
I have another printer which is 300dpi and i need to make it work with the 203dpi printers. 
I added a setting to use 300dpi by default with this printer through the `~/.cups/lpoptions` file and it works as expected.

Now when i add this printer to the`CLASS-01` class, cups ignores this printer setting and prints using the class settings which is 203dpi.

So i thought i would create two classes one called `CUPS-203` and one called `CUPS-300`. Configure them to use 203 and 300 dpi respectively, then create another cups class called `MASTER` with no particular setting and put classes `CUPS-203` and `CUPS-300` into it as nested classes.

That would i hope allow me to use 203dpi printers together with 300dpi printers.

But i get the message `lpadmin : Nested classes are not allowed.`.

What do you think of such a configuration, i know it makes things a bit complicated but i cannot think of another solution for this to work as expected.

Hope that makes sense and maybe someone will point me in another direction to make this work.

Thanks a lot anyway.

**Comment by michaelrsweet** [comment]
So one of the problems with nested classes is that it is hard to properly implement a "round robin" algorithm that scales with the nesting. Early versions of CUPS didn't protect against this and would (in your example) just alternate print jobs between class-203 and class-300, which would then round-robin within the class. This (naturally) wasn't what the user wanted, so we added code to block that configuration to avoid confusion.

My recommendation for this situation is to simply add all of the 203 and 300 dpi printers to the third class. Yes, you will then then need to update 2 classes whenever you add or remove a printer, but you will at least get the expected behavior.

**Comment by tchartron** [comment]
Hi @michaelrsweet, thanks for providing these details. I understand the round robin implementation is problematic using nested classes.

Thank you for your suggestion but i must have missed some details, adding all the 203 and 300 dpi printers to the third class together won't work because the 300 dpi printer needs a parameter in the lpoptions file like this : 
```shell
Dest PM45-300-01 Resolution=300dpi
```
Without this setting the 300dpi printer won't scale the document properly on the page.

I use the `lp` command to print like this :

```shell
# On the 300dpi printer directly (scaling works thanks to the `Resolution=300dpi` setting)
lp -d PM45-300-01 -o fit-to-page
# On the cups class (scaling does not work because setting `Resolution=300dpi` is being ignored even when it's the 300dpi printer belonging to the class that processes the print job)
lp -d CUPS-CLASS -o fit-to-page
```

On the image below, on the left a label printed using the cups class that was processed by a 203dpi printer, on the right, the same label, printed on the same cups class but that was processed by the 300dpi printer (ignoring the `Resolution=300dpi` setting that is set on the printer because it was processed using the cups class)

![IMG_1205](https://github.com/user-attachments/assets/617408e2-7897-4f37-81f0-93ca1d85d5c7)

**Comment by michaelrsweet** [comment]
Without knowing the drivers you are using, it is hard to say specifically. Ordinarily I would set the default resolution for the 300dpi printers to 300dpi, otherwise you are depending on the client/user to specify the correct resolution. The command to do that is:

    lpadmin -p PRINTER -o Resolution=300dpi

**Comment by michaelrsweet** [comment]
(run that command for every 300dpi printer)

**Comment by tchartron** [comment]
Hi @michaelrsweet, thanks for your help, i tried running this command on the 300dpi printer and then sending a print job on the class it belongs to, same problem, when the 203dpi printer processes the job it looks ok, when it's the 300dpi that prints the job it looks like the image i posted above (too small, not fitted properly to the page).

I'll just move the 300dpi to a class with only 300dpi printers and do the same with 203dpi printers.
It seems not possible to get them to work together in the same cups class.

Thanks for helping anyway 👍🏼
