### ISSUE TITLE
JobKillDelay and JobKillDelay has incorrent value of 30 seconds in cupsd.conf man page

### ISSUE THREAD

**Issue by l1gi** [OpenPrinting/cups#1086]
**Describe the bug**
JobKillDelay and JobKillDelay has incorrent value of 30 seconds in cupsd.conf man page.
```
scheduler/cupsd.h:87:
#define DEFAULT_TIMEOUT         300     /* Timeout during requests/updates */                                 
...
scheduler/job.h:131:
VAR int                 JobKillDelay    VALUE(DEFAULT_TIMEOUT),
```

**To Reproduce**
```
$ man cupsd.conf
...
       JobKillDelay seconds
            Specifies the number of seconds to wait before killing the filters
            and backend associated with a canceled or held job.   The  default
            is "30".

       JobRetryInterval seconds
            Specifies  the  interval between retries of jobs in seconds.  This
            is typically used for fax queues but can also be used with  normal
            print  queues whose error policy is "retry-job" or "retry-current-
            job".  The default is "30".
...
```
**Expected behavior**
```
The default is "300".
```

**Comment by michaelrsweet** [comment]
[master 4e3aaa5e3] Fix cupsd.conf man page defaults (Issue #1086)

**Comment by l1gi** [comment]
The commit 4e3aaa5 is not part of last 2.4.2. Any reason for it, please?

https://github.com/OpenPrinting/cups/commit/4e3aaa5e3c95d168b60fc7fca4a48f4a081393c1

Thanks,
m.

**Comment by zdohnal** [comment]
@l1gi nobody pinged me :D .

Now on the serious note - I'm sorry, I've missed the fact it could be/was expected to be ported into backported to 2.4.x. I do some checkup on the issues which would make sense+are important enough to be backported to 2.4.x, but this one fell off the hook.

It would be great if you pinged me next time if you want to backport something - if it makes sense I'll do my best. Otherwise we keep fixes in the master by default.

**Comment by l1gi** [comment]
Hi Zdenek,

no big issue, this is just a man page change. But I would like to ask you to backport this one into the next release if possible. I will keep in mind to speak up once I need it next time.

Thank you,
m.

**Comment by zdohnal** [comment]
@l1gi if you look above my previous comment, there is a commit for 2.4.x from yesterday ;) .

I use HEAD commit of branch 2.4.x for releases of series 2.4.x, so it will be in 2.4.13 - however we are getting a deadlock in cupsd during testing, so I would like to have it fixed before the next release.

Any help is welcome :) .

**Comment by l1gi** [comment]
Thank you, Zdenek! :)
