### ISSUE TITLE
USB backend: Add support for Toshiba printers that don't report a serial number

### ISSUE THREAD

**Issue by eventx-zack** [OpenPrinting/cups#1087]
installed cups on the raspberry pi5
cups version: 2.4.10
trying to connect multiple Toshiba (TEC B-SX4) printers via USB, but could not identify them, same device uri (usb://TEC/B-SX4)
followed the discussion here https://github.com/OpenPrinting/cups/issues/170, and run the following command on the raspberry  OS
```
sudo backend/usb
```
the result
```
DEBUG: Loading USB quirks from "/us/share/cups/Usb"
DEBUG: Loaded 120 quirks.
DEBUG: list devices
DEBUG: libusb get device_ list=7
DEBUG2: 1SerialNumber is not present.
DEBUG2: Printer found with device ID: MFG: TEC; CMD: TPCL; MDL: B- SX4; CLS: PRINTER;
DES: TEC B-SX4; Device URI: usb://TEC/B-5X4
direct usb://TEC/B-SX4 "TEC B-SX4" "TEC B-SX4" "MFG: TEC; CMD :TPCL; MDL: B-SX4 ; CL S:PRINTER; DES: TEC B-SX4; " ""
DEBUG2: iSerialNumber is not present.
DEBUG2: Printer found with device ID: MFG: TEC; CMD: TPCL; MDL: B-SX4; CLS: PRINTER;
DES: TEC B-SX4; Device URI: usb://TEC/B-SX4
direct usb://TEC/B-SX4 "TEC B-SX4" "TEC B-SX4" "MFG: TEC; CMD: TPCL; MDL: B-SX4 ; CL S:PRINTER; DES: TEC B-SX4; " ""
```
@michaelrsweet  is it support to read the Toshiba printer serial no? could u pls help check, thanks!

**Comment by eventx-zack** [comment]
anyone can help take a look? thanks!

**Comment by michaelrsweet** [comment]
@eventx-zack If the printer doesn't support the (standard for 2 decades) iSerialNumber property on the USB bus then you are basically SOL. macOS tries to report the local interface numbers but that can change across boots or if you unplug and plug the printer in, cycle the power, etc. so we never duplicated it in the libusb-based code used on Linux.
