### ISSUE TITLE
AirPrint Color selection not work

### ISSUE THREAD

**Issue by sebastianroesner** [OpenPrinting/cups#1100]
If i select my Printer via AirPrint and Print a document it will always be printed in Color. 
The selction on my device does Not work.
If i select Color - printed in Color
If i selected bw - printed in Color 
![image](https://github.com/user-attachments/assets/150f0f64-d2c8-47fa-8ffd-13c2240711e5)

Futter Information:
I have installed cups in a Debian 12 lxc Container on proxmox. 8.2.2
Cups Version 2.4.2
iOS Version 18.1
Brother HL-4570CDW
Printer is added via network.

Everything Else Like Duplex selection or paperformat works Great.

**Comment by zdohnal** [comment]
It was known issue in the earlier versions of series 2.4.x. Do try the latest version 2.4.11 and see if it is fixed. Other issue might be what color option your application sends - if it sends none, PPD and then server default print-color-mode is applied (in those cases you have to change the print queue default by lpadmin/lpoptions).

Let us know if it works, thank you!

**Comment by sebastianroesner** [comment]
@zdohnal I have installed cups via "apt install cups". With this method always the version 2.4.2 will be installed on my Debian LXC.

How can I install the newest version?

**Comment by zdohnal** [comment]
File an issue for your distribution - they will know what patches they apply and they can provide you a testing packages with newer version.
