### ISSUE TITLE
Enhance human-readable texts for IPP attributes representing media types options and its choices

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/cups#1101]
**Is your feature request related to a problem? Please describe.**
Based on this s-c-p's [report](https://github.com/OpenPrinting/system-config-printer/issues/380) it looks sometimes even human-readable texts for options and its values too cryptic for normal users. We can't do much about classic PPDs, since they are deprecated, going to be removed and such qualified texts should be written by vendor who provides the classic PPDs, but IPP 2.0 printers and generated PPDs from IPP can be handled by CUPS. 

**Describe the solution you'd like**
Mention gsm values in human-readable text for media type options.

**Comment by michaelrsweet** [comment]
OK, so such values are NOT standardized, so there is no way we can standardize the localizations to include them.

FWIW, there *is* a "media-weight" member attribute that provides these details, but it isn't widely implemented.

**Comment by zdohnal** [comment]
@michaelrsweet thx, Mike! I guessed some parts of values are standardized by IANA, but was not sure about human-readable strings were as well.

**Comment by michaelrsweet** [comment]
The [PWG Media Standardized Names](https://ftp.pwg.org/pub/pwg/candidates/cs-pwgmsn21-20230915-5101.1.pdf) specification provides English names, and the PWG does provide a sample English .strings localization file [here](https://ftp.pwg.org/pub/pwg/ipp/examples/ipp.strings).

That said, the semantics of the "media-type" keywords are not tightly defined and are more "general categories" that are useful for end-users to specify media type. For example, "Plain Paper" (stationery) is a generic media used for printing, while "Letterhead" (stationery-letterhead) has a pre-printed letterhead for correspondence and "Inkjet Paper" (stationery-inkjet) is generic media optimized for inkjet printing.

The "media-col" attribute supports a large number of separate member attributes for specific media properties, including:

- "media-back-coating": The coating (if any) on the back side of the media
- "media-color": The color of the media, if any
- "media-front-coating": The coating (if any) on the front side of the media
- "media-grain": The grain of the media (direction of fibers - X, Y), which can affect how the media curls or folds (and can affect whether a given media will work in a printer)
- "media-hole-count": Number of pre-punched holes
- "media-order-count": Number of sheets in a sequence - think a ream of sheets of different colors, pre-printed content, and/or shapes (e.g. tabs).
- "media-pre-printed": The pre-printed content on the media, if any
- "media-recycled": The type and amount of recycled material used in the media
- "media-thickness": The thickness of the media in hundredths of millimeters (0 means less than 0.01mm, a typical 90gsm sheet of paper is 0.1mm thick)
- "media-tooth": The roughness/texture of the media
- "media-tracking": For labels, how the printer determines the separation of labels on the backing medium (mark, gap (space), web (hole), continuous)
- "media-weight-metric": The weight in grams per square meter

As you might expect, most of these values are only used for "production" printing work flows. And typically if a printer supports media that requires special handling (beyond the generic categories) then it will report vendor media type names for the user to pick, and the vendor localization strings will provide the necessary details.

**Comment by cutlery** [comment]
Thanks for this deep dive, @michaelrsweet and @zdohnal .
