### ISSUE TITLE
not able to get correct printer status

### ISSUE THREAD

**Issue by eventx-zack** [OpenPrinting/cups#1104]
we are using cups to connect Toshiba B-SX4 printer via USB, but the printer status is always `idle`, even though the printer actually status is `pause` or `head open`, `paper jam`, etc.

and also the print job status is `completed`, but actually the printing is failed due to the printer error, like the printer status is `pause` or `head open`, `paper jam`, etc.

want to ask is it possible to get specific printer or job status?

**Comment by eventx-zack** [comment]
@michaelrsweet could u help check on it, thanks!!

**Comment by eventx-zack** [comment]
hi @zdohnal, thanks for reply, we installed CUPS 2.4.10 to raspberry pi5, then connect Toshiba B-SX4 printer via USB, the printer status in the CUPS website is always `Idle`, even though the printer actually status is pause or head open, paper jam, etc.
using IPP to do `Get-Printer-Attributes`, return `idle`
using IPP to do `Get-Job-Attributes`, return `completed`


<img width="400" alt="image" src="https://github.com/user-attachments/assets/f2acd409-ca45-4051-abe7-9aa6710d4cbf">
<img width="1164" alt="image" src="https://github.com/user-attachments/assets/e833cab8-9f3b-42c5-9628-b8948b30b0fa">

is that mean Toshiba B-SX4 printer not support `IPP-over-USB`?

**Comment by zdohnal** [comment]
The status on the CUPS website is the status of the print queue installed in CUPS - it can be the same as with the actual printer status if the printer can send such information - a simple USB backend cannot do such a high-leveled thing, it only can report simple errors like if the printer is turned off or other USB related error.

In general the status message on the page is an internal status of the queue in relation to cupsd daemon, but it can match with printer status, if the printer and connection to it is able to share such information. IPP requests you did look like you sent the requests to the print queue object in cupsd, not to the actual printer. To get more information about the printer via USB the printer has to support IPP-over-USB and there has to be a proxy between IPP and USB like ipp-usb.

[How to find out whether the device supports IPP-over-usb](https://docs.fedoraproject.org/en-US/quick-docs/cups-useful-tricks/#_how_to_find_out_if_my_usb_device_supports_ipp_over_usb).

**Comment by eventx-zack** [comment]
oh, checked `lsusb -v` output
the result seems like not support  IPP-over-USB
ref: https://docs.fedoraproject.org/en-US/quick-docs/cups-useful-tricks/#_how_to_find_out_if_my_usb_device_supports_ipp_over_usb
![image](https://github.com/user-attachments/assets/c0f489c1-d4df-4a8f-bd0a-231054fca0ad)

anyway, thanks for the clarification! @zdohnal
