### ISSUE TITLE
Support for .gpd Files?

### ISSUE THREAD

**Issue by RabbitRetro** [OpenPrinting/cups#1110]
**Problem:**
I have been trying to use a Panasonic KX-P2123 dot matrix printer in Linux. I found the .ppd file on the [www.openprinting.org](https://www.openprinting.org/printer/Panasonic/Panasonic-KX-P2123) website. However, the printer prints out "_if you can read this, you are using the wrong driver for your printer._" when I do a test print in the Linux Mint "**Printers**" utility. I did manage to install the appropriate driver in Windows 10 and successfully print out a test page in that operating system. I located the GPD files for different Panasonic models after they had been installed in this location:
**C:\Windows\System32\DriverStore\FileRepository\prnpa001.inf_amd64_*\Amd64**

**Solution:**
Make it possible to use GPD files the same way PPD files can be used in Linux with CUPS. (The GPD files would go into an **/etc/cups/gpd/** folder and a **/usr/share/gpd/** folder.)

**Alternative Solution:**
A possible alternative solution would be a program or script to convert from GPD to PPD files.

**Additional:**
Take the definition of GPD files:
[Introduction to GPD Files](https://learn.microsoft.com/en-us/windows-hardware/drivers/print/introduction-to-gpd-files)
...and compare it to the definition of PPD files:
[PPD File Specification](https://web.mit.edu/PostScript/Adobe/Documents/5003.PPD_Spec_v4.3.pdf)
A zip file with sample PPD and GPD files is included.
[PanasonicKX-P2123.zip](https://github.com/user-attachments/files/18085369/PanasonicKX-P2123.zip)

**Comment by michaelrsweet** [comment]
GPD files are not something we can support in CUPS - it depends on the Microsoft GDI which isn't compatible with any of the rendering paths on Linux/Unix.
