### ISSUE TITLE
Lists Offline Printers as Available in CUPS

### ISSUE THREAD

**Issue by emilianospinoso** [OpenPrinting/cups#1112]
**Description**
When using the lpstat command to query the list of available printers, all printers are listed as if they are online, even when some printers are powered off or disconnected from the network

**Steps to reproduce the issue:**
1-Connect a network printer to the system (e.g., HP DeskJet 2800 series).

2-Run the following command to list the printers and their statuses:
**lpstat -p**
_Example Output:_
```
root@vetscan:~# lpstat -p
printer HP_DeskJet_2800_series_69AF01 is idle. enabled since Wed 11 Dec 2024 04:08:55 PM CET
printer HP_ENVY_6000_series_A94180 is idle. enabled since Wed 11 Dec 2024 04:04:08 PM CET
```

3-Turn off or disconnect the printer from the network.

4-Run the same command again:
**lpstat -p**

Example Output:
```
root@vetscan:~# lpstat -p
printer HP_DeskJet_2800_series_69AF01 is idle. enabled since Wed 11 Dec 2024 04:08:55 PM CET
printer HP_ENVY_6000_series_A94180 is idle. enabled since Wed 11 Dec 2024 04:04:08 PM CET
```

**Expected behavior**
The lpstat command should accurately reflect the state of the printers:
Online printers should be listed as available.
Offline or disconnected printers should either be marked as unavailable or omitted from the output.

**System Information**
OS and Version: Debian GNU/Linux 12 (bookworm)
Kernel Version: Linux 6.1.0-25-amd64
CUPS Version: 2.4.11 and  2.4.7 (default from apt) 
Printer Models:
HP DeskJet 2800 Series [69AF01]
HP ENVY 6000 Series [A94180]

_____________________________________________________________________________________________________________________________
**Additional context**
I also attempted to **manually remove the printer** using the following command:
**lpadmin -x <printer_name>**
However, the command did not work as expected. The printer still appears in the CUPS printer list when running lpstat -p or lpstat -a. It seems the removal process is not completing successfully, and the printer remains listed in the system.

**Example:**
1-Initial Printer Status (with the printer turned on):
```
espinoso@PR780:~/Desktop$ lpstat -p
printer HP_DeskJet_2800_series_69AF01 is idle. enabled since Wed 11 Dec 2024 09:54:32  
printer HP_ENVY_6000_series_A94180 is idle. enabled since Wed 11 Dec 2024 09:54:22
```

2-Turned off the printer and executed the following command to remove it from CUPS:
`espinoso@PR780:~/Desktop$ sudo lpadmin -x HP_DeskJet_2800_series_69AF01`

3-Checked the printer list again using lpstat -p:
```
espinoso@PR780:~/Desktop$ lpstat -p
printer HP_DeskJet_2800_series_69AF01 is idle. enabled since Wed 11 Dec 2024 10:38:16  
printer HP_ENVY_6000_series_A94180 is idle. enabled since Wed 11 Dec 2024 09:54:22
```

Despite running the removal command, the printer (HP_DeskJet_2800_series_69AF01) still appears in the list. This issue persists even after turning off the printer and removing it via lpadmin -x.

This behavior indicates that the printer removal process is not functioning as intended, and CUPS continues to display the printer in its list.

**Attachments with lpinfo -v command  **
![lpLogs](https://github.com/user-attachments/assets/5583c991-c403-492a-9cff-52bc7f1352f5)

**Comment by michaelrsweet** [comment]
The lpstat command reports the status of the print queues, not the printers themselves.

**Comment by emilianospinoso** [comment]
Sorry to ask again, but do you know which tool from CUPS we could use to check the status of the printers?

**Comment by michaelrsweet** [comment]
If the printer supports IPP, you can use ipptool to check things, but otherwise there isn't a generic way to do so without actually trying to print.
