### ISSUE TITLE
'ubuntu-bug cups' Support for Linux Mint (Command Does Not Work in CUPS version 2.4.7)

### ISSUE THREAD

**Issue by RabbitRetro** [OpenPrinting/cups#1113]
**Problem:**
The command "ubuntu-bug cups" does not work in my Linux Mint "wilma 22 x86_64" install.

**Solution:**
Allow us to report bugs in CUPS (apt install package) while using Linux Mint

**Additional context:**
Here is what the command ended up outputting:

> $ ubuntu-bug cups
> 
> *** Collecting problem information
> 
> The collected information can be sent to the developers to improve the
> application. This might take a few minutes.
> ............................................................................
> 
> *** Problem in cups
> 
> The problem cannot be reported:
> 
> This does not seem to be an official Linux package. Please retry after updating the indexes of available packages, if that does not work then remove related third party packages and try again.
> 
> Press any key to continue... 
> 
> No pending crash reports. Try --help for more information.

**Comment by zdohnal** [comment]
Looks like distro issue - please contact Ubuntu support.
