### ISSUE TITLE
Slowness in jobs

### ISSUE THREAD

**Issue by brunohdossantos** [OpenPrinting/cups#1114]
Previously I used version 2.3.3 and to fix some slowness issues, we changed the settings on each printer to socket and also added the ?waiteof=false setting to its URL. After migrating to 2.4.2 this setting no longer seems to work, is this "waiteof=false" parameter still valid?

**Comment by zdohnal** [comment]
I can't speak about local patches in your distro, but waiteof in socket backend works fine in upstream. But the URI option only prevents waiting for the printer to stop sending data, so slowness might be in filters.

If the driver and connection are the same, I would inspect filters whether they take more time than in 2.3.3 or whether the filter chain is the same. Depending on driver there can other players in the game like ghostscript.

The best source of knowledge about this is your distro support - they will know the status which package versions are in your system and what patches are applied.

Do let us know if you can reproduce the issue with the latest CUPS (2.4.11) and cups-filters family (2.x - libcupsfilters, libppd, cups-filters).

**Comment by zdohnal** [comment]
I've compared the performance of socket backend with waiteof=false in URI and it was the same with 2.3.3op2 and 2.4.11.

**Comment by brunohdossantos** [comment]
Was this test with a virtual printer or a physical printer? Testing with the virtual PDF really doesn't have any performance issues.

**Comment by zdohnal** [comment]
It was printing to a real HP printer with classic driver from hplip.

**Comment by brunohdossantos** [comment]
I will try to run a test with 2.4.11, to see if I have the same problem with it that I am having with 2.4.2.
