### ISSUE TITLE
IPP everywhere PPD path change regression

### ISSUE THREAD

**Issue by 10ne1** [OpenPrinting/cups#1115]
Hello

**Describe the bug**
A regression was caused by [this commit](https://github.com/OpenPrinting/cups/commit/68506acf467b79f1fde053b85edbfe1ec30b2f85) which moved the PPD file creation from lpadmin to the scheduler.

The old code in lpadmin used the path `PrinterRoot` which is `/var/cache/cups/printers/ppd/`
while code in cupsd uses `ServerRoot` which is `/etc/cups/ppd/`.

This is a problem because on my systems the rootfs including /etc is mounted RO and cannot be written at runtime as opposed to /var/cache so the new cupsd ppd generation background thread fails.

[This is relevant line](https://github.com/OpenPrinting/cups/blob/2e3f15832140454e2d21b327bfa4b05612b50b9a/scheduler/ipp.c#L5472) in cupsd.

**To Reproduce**
Compare the PPD creation path between the old lpadmin code and the new cupsd scheduler ppd creation code.

**Expected behavior**
The PPD file used to be under `PrinterRoot` and I would expect it to be there as well to avoid regressions on RO rootfs..

**System Information:**
 - OS and its version: Gentoo, ChromeOS, ArchLinux
 - Application
 - CUPS version 2.4.x

A trivial fix was to just replace ServerRoot -> PrinterRoot in the `*/ppd/*` paths inside scheduler/ipp.c.
Would this be an acceptable upstream solution (I can send a patch)?
Any other suggestions how to fix this regression? Thank you!

**Comment by michaelrsweet** [comment]
PrinterRoot is not a standard cupsd.conf or cups-files.conf directive.

CUPS expects a read-write ServerRoot and won't work with a read-only filesystem.
