### ISSUE TITLE
rastertozebrakiosk unable to get backchannel info from kr203

### ISSUE THREAD

**Issue by cjnslm-pt** [OpenPrinting/cups#1117]
I tryed to change the timeout for the cupsBackChannelRead() but it always returns empty, no info whatsoever.
Checked permitions for the execution of the filter since it was modified to dump into temp folder the backchannel data to no avail.
A bit unsure where to go from here.

**Comment by zdohnal** [comment]
What is kr203? Based on search it is a label/receipt printer?

Data from backend and printer are passed over backchannel - if printer and backend do not send data via backchannel, then filter can't catch anything.

Socket backend sends anything it gets from the printer via backchannel. USB connection has this quirk set:

```
203 # All Zebra devices (https://bugs.launchpad.net/bugs/1001028) (Apple #5395)
204 0x0a5f unidir no-reattach
205
```

looks there is an issue with Zebra printers about their printing performance, so it was decided to disable bidirectional support, which disables the backchannel.

You can comment out the quirk in /usr/share/cups/usb/org.cups.usb-quirks and see if there is no performance issues and bidi connection works, do send us ```lsusb``` output - we can whitelist the specific model if there are no issues with it.
