### ISSUE TITLE
cups treats ppi option as integer, cups-filters treat it as string

### ISSUE THREAD

**Issue by kfazz** [OpenPrinting/cups#115]
cups encode.c treats parameter ppi as an integer, but it should be a string.

the image filter drivers expect the form ppi=300x600
to specify source image dpi for images where it is asymmetric.

relevant option parsing code from cups-filters image:
```
  if ((val = cupsGetOption("ppi", num_options, options)) != NULL)
  {
    if (sscanf(val, "%dx%d", &xppi, &yppi) < 2)
      yppi = xppi;
    zoom = 0.0;
  }
```

I encountered this issue trying to print full-sized images without scaling on a dymo 450 label printer.
This bug causes images to print across 2 labels when trying to use the 300x600dpi graphics mode.

This should print a single label:
lpr -o ppi=300x600 -o scaling=0 -o PageSize=w167h288 -o PageRegion=w167h288 -o Resolution=300x600dpi -o DymoHalftoning=Default -o DymoPrintDensity=Medium -o DymoPrintQuality=Graphics -o MediaDimensions=w167h288 ~/Desktop/test_Graphics_portrait.png

where the png is a 664*2224 image without any dpi metadata.
Instead the ppi option gets sanitized to 300, and the image gets printed across 2 labels.

ubuntu bug report: https://bugs.launchpad.net/cups/+bug/1917074

[cups_ppi_patch.txt](https://github.com/OpenPrinting/cups/files/6052795/cups_ppi_patch.txt)

**Comment by michaelrsweet** [comment]
The ppi attribute is defined as an integer. It was never intended to support asymmetric resolutions. The usage in cups-filters is broken.
