### ISSUE TITLE
Does cups not recognise correctly which print qualities my printer supports?

### ISSUE THREAD

**Issue by Golddouble** [OpenPrinting/cups#116]
I use the printer HP ENVY 5544 in Linux:
https://www.cnet.com/products/hp-envy-5540-all-in-one-multifunction-printer-color/
This is a colour printer with 2 ink cartridges. The cartridges have integrated print heads, so that it is possible to print only with the black cartridge in it.
I only use this printer with the black cartridge in it and print B/W.

Before I have changed to Linux, I have used this printer in windows. There I was able to choose between the print qualities "draft, normal and optimal".

Why do I mention windows?
Because I don't know what print qualities this printer supports. And I think that the print settings in Windows shows which print qualities this printer can handle, because the printer driver in Windows is exactly tuned to this printer.
-> So I guess, that this printer supports only the print qualities "draft, normal and optimal" and nothing other.

But in Linux when I go into ...
localhost:631
... I have the print qualities "normal, draft, best, and High-Resolution-Photo" (Exactly in this order. That's strange, because I would expect, that the order would represent an ascending quality.)

So, according to windows my printer only supports 3 print qualities, but Linux gives me 4 print qualities.
Isn't this a contradiction?
I wonder, if this is a cups error?

Why do I think, that this could be a cups error? Please have a look at the following experiments:

**1st Experiment series: Focus lies on brightness of the print:**

**A)**
Print 1 in Windows with "draft".
Print 2 in Linux with "draft".
Result: Print 2 is much darker than print 1.
-> I would expect, that both prints have the same brightness.

**B)**
Print 1 in Windows with "draft".
Print 2 in Linux with "normal".
Result: Both prints have the same brightness.
-> This looks like "Linux normal" is "Windows draft".

**C)**
Print 1 in Linux with "draft".
Print 2 in Linux with "normal".
Result: Print 1 is much darker then print 2.
-> I always thought, that "draft" does use less ink than "normal", but when "draft" prints darker than "normal", then this would need more ink. So this is a contradiction.

**2nd Experiment series: Focus lies on dry-time when duplex printing is active:**

**A)**
Print 1 in Windows with "draft".
Print 2 in Linux with "draft".
Result: In Windows the printer waits some seconds before pulling the paper back in, so that the ink can dry. In Linux the printer only waits always 1.8 seconds, independent of how much ink was used for the image.
-> So I have asked me: Does "dry time" not work in Linux? But I found out: Yes it works, but with the print quality "normal". See 2.B)

**B)**
Print 1 in Windows with "draft".
Print 2 in Linux with "normal".
Result: Both prints do wait some seconds before pulling the paper back in.
-> It looks like "Windows draft" matches "Linux normal". Strange!

**C)**
Print 1 in Linux with "draft".
Print 2 in Linux with "normal".
Result: Print 1 does not wait some seconds before pulling the paper back in (only 1.8 seconds). But print 2 waits some seconds before pulling the paper back in.
-> As Print 1 is much darker than print 2, I would expect, that in print 1 the dry time would be longer than in print 2, but it is the other way round.

**Summary:**
In windows I have 3 print-qualities to choose from, but in Linux I have 4. But one of this 4 (-> "draft") does not work as expected. Concretely: It is too dark and "dry time" does not work.

Is this a cups error?

Would appreciate some comments. Thank you.

**Comment by michaelrsweet** [comment]
@Golddouble The notion of print quality is not a simple worse-to-best mapping. Different drivers will expose different settings based on how they want to expose the printer capabilities. Moreover, different drivers will use different printer languages and print modes that can have dramatic effects on the output you get.

So first I need to know what driver you are using on Linux.

**Comment by Golddouble** [comment]
Thank you.

I print driverless via USB-connection, because this printer supports Airprint.

Here is the ppd:
[driverless.ppd.zip](https://github.com/OpenPrinting/cups/files/6091106/driverless.ppd.zip)


(Please note:
I already also have tried to use the print-driver from HP. 
When I use this driver, it's mainly the same, but prints with the combination 
"Linux normal" and "HP-driver" are darker (too dark) 
than the combination
"Linux normal" and "driverless (Airprint)"
So I prefer printing with "Airprint", because the brightness is better.)

**Comment by michaelrsweet** [comment]
@Golddouble That's *not* the "driverless" PPD, that is the HPLIP PPD.

**Comment by Golddouble** [comment]
Is it? OK. I don't know. Sorry when I was wrong.

My first prints, I have made with the HP-driver. But then I wanted to change to driverless-printing. 
So how did I change to driverless printing?

Answer:
I have not deinstalled HPLIP and I also have not deinstalled cups. 
But I have installed in addition "ipp-usb_0.9.17-1+48.2_amd64.deb" .

After, I have made this:
1. -> Xfce settings -> print settings -> "add" -button
2. Then I have chosen "usb":
![driverless1](https://user-images.githubusercontent.com/13977359/110247289-c481c800-7f6b-11eb-8bd3-15f368a54677.jpg)
3. After a dialog-field "search for driver" appeared. It automatically has found it.
4. After I had a new entry (printer) in "Xfce settings -> print settings"
-> So I thought: Ah, this is now my driverless printer.

A) Why did I think, that this is now my driverless printer?
Answer: Because printing with this new printer with the setting "Linux normal" was brighter than printing with the old printer setting "Linux normal". So I thought: Ah it's really different.

B) I guess, that each printer that is shown in "-> Xfce settings -> print settings" has its corresponding ppd-file? Right? Or am I also wrong here?

C) I'm confused anyway. I read on some sites that the *ppd file is the driver. On other pages I have read that the *ppd file is not a driver at all. And somehow I have read, that the ppd-file is called "queue". Confused.

D) However. It doesn't matter whether I printed without a driver or with "HPLIP PPD". What I wrote above about printing with "draft" quality applies anyway. See post 1.

E) But your question was:
> first I need to know what driver you are using on Linux

How can I find out this? In which folder can I find the driver? And what is the file extension of a linux driver?

Thank you.

**Comment by michaelrsweet** [comment]
@Golddouble I am not familiar with Xfce's print setup dialogs, but it doesn't look like it is giving you the option of IPP-USB or IPP Everywhere. You might need to look under the network printers since ippusbxd provides access to IPP-USB printers over the loopback (localhost) interface.

If you use the CUPS web interface (localhost:631) it *should* show up as a network printer with the "IPP Everywhere" driver.

**Comment by Golddouble** [comment]
You are right. I have found it under network printers now. Thank you.
I have attached the ppd of the real driver-less printer now. See point 2) below.


So here is the situation now:
1. I have the HPLIP ppd. 
According to localhost:631 it supports the print qualities "normal, draft, best, and High-Resolution-Photo".
[HPLIP.ppd.zip](https://github.com/OpenPrinting/cups/files/6107065/HPLIP.ppd.zip)

2. I have the driverless ppd. 
According to localhost:631 it supports the print qualities "normal, draft, best"
[the real driverless ipp.ppd.zip](https://github.com/OpenPrinting/cups/files/6107039/the.real.driverless.ipp.ppd.zip)

3. In Windows the Windows driver supports "draft, normal and optimal"

-----> The HPLIP driver is the only that gives 4 print qualities. First I thought: Great Linux supports more than windows. But when I want to print with draft quality together with the HPLIP printer, then the print is too dark and "dry time" does not work. It feels like this would be a nirvana mode.

So what's wrong with this draft mode in HPLIP driver? 
Does this mean, that the ppd is wrong? Or is this a cups error?

Thank you. Very interested in this.

**Comment by michaelrsweet** [comment]
@Golddouble This is a driver issue. and we do not develop [HPLIP](https://sourceforge.net/projects/hplip/), that is a separate project.

The "driverless" print queue is using IPP and telling the printer, via IPP, what quality to use when printing. All CUPS does is generate a bitmap and lets the printer handle converting it as needed.
