### ISSUE TITLE
Debian: testlang gets garbage language setting (on 32-bits, x86)

### ISSUE THREAD

**Issue by OdyX** [OpenPrinting/cups#117]
Hello @michaelrsweet ,

while trying your upstream commit to fix #85 it seems that the i386/x86 build fails with this error:
```
Running language API tests...
LOCALEDIR=locale ./testlang
cupsLangGet("UåWè¾É"): FAIL (got "C")
cupsLangGet("UåWè¾É") again: FAIL (got "C")
```

This seems to be either a failure of `cups_dentry_t::filename`, or of `test_language()`.

**Comment by michaelrsweet** [comment]
Weird, I'm not seeing this in the Github builders. Can you check the contents of the "cups/locale" directory in the build directory?

**Comment by OdyX** [comment]
I've tested to add a cross-build to i686 on Github actions, and the testlang run fails there too.

**Comment by michaelrsweet** [comment]
@OdyX OK, so I still need to see the contents of that locale directory - something is messed up there!

**Comment by michaelrsweet** [comment]
(sorry for the mistaken close of this, I had two git issues open and didn't pay attention...)

**Comment by michaelrsweet** [comment]
I've added an "ls -al locale" in the makefile before testlang is run, just to see what is going on...

**Comment by michaelrsweet** [comment]
OK, so this remains weird. I added unit tests for the cupsDir functions (long overdue, but they are simple wrappers on Linux) as well as the "ls -al locale" and I can't figure out why the test is still failing.

Will continue to look at this but definitely not obvious to me...

**Comment by michaelrsweet** [comment]
[master 91fe48974] Make sure 'lang' is initialized.

The "lang" variable wasn't initialized, but the 64-bit runtime cleared the stack while the 32-bit runtime doesn't... :(

(and *none* of the code scanning programs caught it...)

**Comment by OdyX** [comment]
Oah. That was a tough one. Nice job!
