### ISSUE TITLE
@privateinclude@ not defined in `cups-directories.m4` file

### ISSUE THREAD

**Issue by surajkulriya** [OpenPrinting/cups#119]
We are using `@privateinclude@` in `makedefs.in` file for creating `makedefs` file but its not defined there. So upon generating `Makedefs` file we are getting `privateinclude	=	@privateinclude@` on line no 218, which I guess is a weird behaviour.
Also on line no 239 we have `PRIVATEINCLUDE	=	$(BUILDROOT)@PRIVATEINCLUDE@`. I guess this is a typo. Perhaps right side `PRIVATEINCLUDE` must be lowercase. 
Do correct me if I am missing out something.
Thanks

**Comment by michaelrsweet** [comment]
I'm dropping the private include functionality - it was used at Apple to allow some developers to access private APIs (that change randomly) but that isn't a good way forward for OpenPrinting. I just forgot to remove the private includes.

**Comment by michaelrsweet** [comment]
[master 40ca30488] Remove private include functionality (Issue #119)
