### ISSUE TITLE
ppd_file_t "emulations" member leaked in _ppdOpen()

### ISSUE THREAD

**Issue by j39m** [OpenPrinting/cups#124]
This member [is populated in _ppdOpen()](https://github.com/OpenPrinting/cups/blob/5e12b76b3d3c1e89cc2949d55d3c176f5ca63f03/cups/ppd.c#L1200) but not freed in `ppdClose()`. (Context: apple/cups/issues/5562)

Would you accept a patch to add the corresponding frees into `ppdClose()`?

**Comment by michaelrsweet** [comment]
[master 2bc7b0ef2] Free emulations (Issue #124)
