### ISSUE TITLE
order indication in job listing is not explanatory

### ISSUE THREAD

**Issue by jschwender** [OpenPrinting/cups#133]
the term ascending/descending order gives only a sort order, but not a direction of that order. I suggest:
                  "jobs in pending order, next on top"
completed: "jobs in completion/canceling/abortion order, most recent on top"
          all:    "jobs in order of reception, earliest on top"  or maybe "…oldest on top"

**Comment by michaelrsweet** [comment]
@jschwender Linking this to your PR. If you update your PR with your proposed text we can go from there...
