### ISSUE TITLE
[driverless] Missing InputSlot in PDD from Canon TS6150

### ISSUE THREAD

**Issue by DavideRossi** [OpenPrinting/cups#136]
The printer has a read feed and a main tray but I cannot select it in the printer dialog.
It seems like the root cause is a missing InputSlot in the PDD produced by CUPS (and in that produced by cups-filters, see https://github.com/OpenPrinting/cups-filters/issues/351).

**Comment by michaelrsweet** [comment]
@DavideRossi Can you run the following command and provide us with a copy of the output?

```
ippfind --exec ipptool -tv '{}' get-printer-attributes.test \;
```

Thanks!

**Comment by DavideRossi** [comment]
Sure, here it is.
[ippfind.txt](https://github.com/OpenPrinting/cups/files/6135001/ippfind.txt)

**Comment by michaelrsweet** [comment]
@DavideRossi  OK, thanks. I see "media-source-supported" in there with three values (auto, main, rear) which should show up in the PPD.

What version of CUPS are you using?

**Comment by DavideRossi** [comment]
2.2.7

**Comment by michaelrsweet** [comment]
Ah, OK. I think you'll find that CUPS 2.3.x fixes these issues for you...

**Comment by momist** [comment]
I have the Canon TS8150 and am using CUPS 2.3.1-9.  I have the same issue, no access to select the rear feed, or change the paper type.

**Comment by michaelrsweet** [comment]
@momist Make sure you have an updated cups-filters package - CUPS 2.3.1 will have the fixes for using the IPP Everywhere driver from lpadmin or the web interface, but not the auto-added one from cups-browsed.

**Comment by momist** [comment]
Thank you Michael.  I am using Mint 20.1, and have just reinstalled cups-filters and cups-filter-core-drivers using Synaptic.  The system dialogue for my printer still has choice of paper-source, paper-typ and output-tray greyed out.  Could you please give me some more guidance?
