### ISSUE TITLE
Add support for job-sheets-col

### ISSUE THREAD

**Issue by michaelrsweet** [OpenPrinting/cups#138]
[Copying this request from Kurt Pfeifle over from the old Apple CUPS repository]

One common request is for banners to be printed on different media from the rest of the job. Previously users would make custom PostScript banner pages to override the MediaSource or MediaColor so that banners appeared on colored paper, for example. But now that MFPs tend to support PDF and PostScript is no longer the ideal printer language, we need a proper solution.

The IPP "job-sheets-col" attribute (PWG 5100.7) extends "job-sheets" by adding a media-col member that can specify the media requirements for the banner. We should support it.

**Comment by KurtPfeifle** [comment]
Short question: will support for job-sheets-col still be added during 2.4 development? Or is it now postponed until 2.5. I'm confused by the last entry from Aug 31, 2021.

**Comment by KurtPfeifle** [comment]
> Short question: will support for job-sheets-col still be added during 2.4 development? Or is it now postponed until 2.5. I'm confused by the last entry from Aug 31, 2021.

I found this now, which cleared up my question: https://github.com/OpenPrinting/cups/milestone/6

**Comment by michaelrsweet** [comment]
[master 074526b03] Add job-sheets-col support (Issue #138)
