### ISSUE TITLE
bad error message

### ISSUE THREAD

**Issue by 532910** [OpenPrinting/cups#148]
https://github.com/apple/cups/issues/5737

Web interface says:
Modify Printer <PRINTER> Error
Unable to modify printer: Unable to copy PPD file.

/var/log/cups/error_log says:
```
E copy_model: empty PPD file
E [Client 28] Returning IPP server-error-internal-error for CUPS-Add-Modify-Printer (ipp://localhost/printers/<PRINTER>) from localhost.
```

The real error is that openprinting-ppds crashes with MemoryError:
https://github.com/vitorbaptista/pyppd/issues/2

**Comment by michaelrsweet** [comment]
@532910 I'm not sure there is an easy way for us to relay the logged error message back to the client. Will investigate further...

**Comment by michaelrsweet** [comment]
@532910 I've added some more specific error messages here, but for this particular failure you'd see the following error:

```
Unable to modify printer: cups-driverd failed to get PPD file - see error_log for details.
```

[master cf32336d4] Show better error messages when a driver interface fails (Issue #148)
