### ISSUE TITLE
Suggest ipp backend use same heuristic for copies_remaining as squashing 'copies' job parameter

### ISSUE THREAD

**Issue by karlrelton** [OpenPrinting/cups#149]
As per [https://github.com/apple/cups/issues/5732]

Currently backend/ipp.c sets its working variable copies_remaining to either the user requested copies (from argv[4]) or truncates it to 1. The truncation happens if the printer appears to support hardware copies, OR we are streaming from stdin.

The test of hardware copies comes from copies_sup, which comes from querying the printer 'copies-supported' attribute - which on a first read seems plausible.

However there are flows out there in the wild which pass to the ipp backend a prepared raster file (argv[6]) which has had software copies already applied (e.g. by pdftopdf where *cupsManualCopies: True). The same copies argument (argv[4]) is passed to both pdftopdf and the eventual ipp backed (as is typical).

Then, if the targetted device reports back that hardware copies are not supported (or, as in my actual printer copies-supported = 1-1) the copies_remaining gets set to argv[4] and so I end up with n*n copies physically printed.

If the ipp backend also honoured *cupsManualCopies in determining copies_remaining then this problem would be solved.

-----

If you want to avoid cupsManualCopies (in the hope of moving away from ppds) ...

ipp.c new_request() calls _cupsConvertOptions which has its own heuristics for dealing with the number of copies (to pass on to the printer). In particular if the format is a multi-page image or application/vnd.cups-raster it assumes software copies have been applied upstream and so it truncates copies (to pass on to the printer) to 1.

It seems to me that if the ipp backend already has such hard-wired heuristic code here, then the same heuristic could be applied to the copies_remaining ... i.e. forcing it to 1 for certain formats where we expect upstream software copies.

**Comment by michaelrsweet** [comment]
Will investigate, but if those "flows in the wild" aren't following the CUPS driver interface then you will predictably get erroneous results...

**Comment by karlrelton** [comment]
Thanks for looking into this. By 'in the wild' I should clarify ...

Ubuntu cups-browsed, for example, sees printer advertised though avahi, as accepting image/urf on ipp. cups-browsed creates a printer queue on cups, with a ppd that includes cupsManualCopies: True

Then on printing, cups sets up a filter chain including pdftopdf which applies the manual copies, and eventually to a urf temp file.

Then the ipp backend fetches copies-supported: 1-1 from the printer, which with its logic starts applying multiple copies (via the copies_remaining variable) ... and hence n*n are physically produced.

In the past this outcome didn't _actually_ happen, because the ppd was erroneously 'cupsManualCopies: true' (lower case true). So you effectively had 2 bugs that cancelled each other out!

Now one bug (cupsManualCopies) has been fixed, the scene is set for this bug report to bite ...

**Comment by michaelrsweet** [comment]
@karlrelton If CUPS is doing the printing, the pdftopdf filter will *pipe* its output to the backend. If you are passing a temp file to the backend then it is explicitly not supposed to have the copies pre-applied. We can't change the current behavior without breaking other printers...
