### ISSUE TITLE
Missing support for defaultToStandardPreset

### ISSUE THREAD

**Issue by terr72** [OpenPrinting/cups#15]
I was looking into a way to reset the printer dialogue settings (like orientation or duplex printing) to the default values defined at http://localhost:631/printers/ after every print job.

While the MacOS version of CUPS has support for `defaultToStandardPreset` in `~/Library/Preferences/org.cups.PrintingPrefs.plist`, the Linux/UNIX version doesn't seem to support this setting at all.
At least I wasn't able to find an entry for it by grepping the source.
Consulting the docs also didn't indicate a similar configuration variable.

Is the absence of this intended?
Or am I missing something?

**Comment by michaelrsweet** [comment]
This is a question for your desktop environment of choice - they all implement their own print dialogs and their own policies. CUPS itself has no control over it aside from providing the APIs that would allow them to discover what the default values are.
