### ISSUE TITLE
cupsctl --remote-any and --remote-admin toggles the other before it is set

### ISSUE THREAD

**Issue by l1gi** [OpenPrinting/cups#158]
cupsctl has strange behavior at least while setting --remote* options:

```
# cupsctl | grep remote
_remote_admin=0
_remote_any=0
# cupsctl --remote-any
# cupsctl | grep remote
_remote_admin=0
_remote_any=1
# cupsctl --remote-admin
# cupsctl | grep remote
_remote_admin=1
_remote_any=0
```

As you can see it disables the other remote options before it set the requested one. The only way how to get enabled both of them is to run

`# cupsctl --remote-any --remote-admin`

while they are both switched off.

This is because in the first stage of cupsAdminSetServerSettings() (cups/adminutil.c) remote_admin and remote_any variables get set to either 0/1 if they are changing or to -1 if untouched.

```
573    if ((val = cupsGetOption(CUPS_SERVER_REMOTE_ANY, num_settings, settings)) != NULL)
574    {
575      remote_any = atoi(val);
576  
577      if (remote_any == old_remote_any)
578      {
579       /*
580        * No change to this setting...
581        */
582  
583        remote_any = -1;
584      }
585    }
586    else
587      remote_any = -1;
588  
589    DEBUG_printf(("1cupsAdminSetServerSettings: remote_any=%d", remote_any));
```

But later the value is treated just if it has the values either 0 or 1.

```
847  	if (remote_admin)
848  	  cupsFilePrintf(temp, "  Allow %s\n",
849  	                 remote_any > 0 ? "all" : "@LOCAL");
```

remote_any is -1 (though it is set) if we select --remote-admin.

The wrong logic is in the whole function. I doubt it was an intention. If so it is very confusing.

**Comment by michaelrsweet** [comment]
@l1gi Can you attach a copy of your cupsd.conf file?

**Comment by l1gi** [comment]
Sure. Untouched:
[cupsd-before.txt](https://github.com/OpenPrinting/cups/files/6189873/cupsd-before.txt)

After --remote-any:
[cupsd-after-any.txt](https://github.com/OpenPrinting/cups/files/6189876/cupsd-after-any.txt)

After --remote-admin:
[cupsd-after-admin.txt](https://github.com/OpenPrinting/cups/files/6189880/cupsd-after-admin.txt)

**Comment by l1gi** [comment]
Hi Michael, any news on this, please? Do you plan to fix it should I implement some temporary workaround? Thank you.

**Comment by michaelrsweet** [comment]
@l1gi Sorry, I've been working on the OAuth support but will be getting back to this soon.

**Comment by michaelrsweet** [comment]
Sorry for the long delay:

[master 3698e1ff9] Fix an interaction between --remote-admin and --remote-any (Issue #158)

**Comment by l1gi** [comment]
Thank you, Michael!
