### ISSUE TITLE
Global job options that apply to all printers

### ISSUE THREAD

**Issue by DemiMarie** [OpenPrinting/cups#16]
On my system, I need to ensure that `fitplot` is always set to `true` across all printers, so that QubesOS trusted PDFs print correctly.  However, I was only able to figure out how to set it on a per-printer basis.

**Comment by michaelrsweet** [comment]
First, "fitplot" is the old option name. "print-scaling" is the current option (and provides more control).

As for global default options, there is currently no way to do this. The best you can do is to set this for every printer on your system.

**Comment by DemiMarie** [comment]
Are global defaults planned?

**Comment by michaelrsweet** [comment]
@DemiMarie No.
