### ISSUE TITLE
Typo in Mopria Compatibility

### ISSUE THREAD

**Issue by tbigby-kristin** [OpenPrinting/cups#161]
Hi team,

In relation to the Airprint and Mopria Compatibility (#126) merge:

It looks like there is likely a typo in `scheduler/dirsvc.c` on line 443, `morpria` not `mopria`:

```
  keyvalue[count  ][0] = "morpria-certified";
  keyvalue[count++][1] = "1.3";
```

I just noticed this while reading the merge, not through testing. So I'm not sure if it has any impact or not.

The functionality looks excellent and like it could really simplify our BYOD & iPad printing setup.

Thanks very much, Tony

**Comment by michaelrsweet** [comment]
[master b2cc6c392] Fix spelling error (Issue #161)
