### ISSUE TITLE
Need some help with RTL preparations and l10n

### ISSUE THREAD

**Issue by yarons** [OpenPrinting/cups#162]
I've created a Hebrew version and configured Crowdin to use my GitHub fork and now approved users can actually use it to translate CUPS instead of changing *.tmpl files and the main .po for their language (the only missing part is the .desktop file and I'm trying to find some solution but it's not such a big deal compared to the rest of the challenges).

The version I created requires some CSS modifications to appear properly (I already know what to change) but there are some glitches I couldn't fix.

This is the correct Hebrew version (Administration screen):
<img width="802" alt="Screen Shot 2021-03-28 at 23 19 41" src="https://user-images.githubusercontent.com/406826/112768636-900ea280-9025-11eb-8ca1-aa1fbd869080.png">

This is the incorrect Hebrew version (Administration screen - No CSS modifications - some strings remain in English):
<img width="960" alt="Screen Shot 2021-03-29 at 0 29 05" src="https://user-images.githubusercontent.com/406826/112768681-cea45d00-9025-11eb-9717-9bdd616df222.png">

I'm not sure it's related but it's also giving me a hard time, in Firefox there's some sort of indentation between the window border and the first header menu item (OpenPrinting CUPS), when switching to RTL it doesn't appear at all and although it doesn't seem very significant it's just not working, this is how it looks like in the English native web interface:
<img width="760" alt="Screen Shot 2021-03-29 at 0 34 51" src="https://user-images.githubusercontent.com/406826/112768922-1677b400-9027-11eb-95c2-349386ed4e5f.png">

I can't find this indentation in Chromium:
<img width="564" alt="Screen Shot 2021-03-29 at 0 40 26" src="https://user-images.githubusercontent.com/406826/112768993-6d7d8900-9027-11eb-9d64-66a3dfcea85d.png">

Apparently adding `dir="rtl"` doesn't work as expected and there are several left/right specific cases to handle (floats for example).

I was thinking about adding the `dir="rtl"` in the translated index and in the tmpl files but it should be permanent so in case the source is modified, this direction should stay intact and I'm not sure adding this manually is the way to go (unless you believe it does).

Furthermore, sometimes not all the strings are loaded, as you can see in the incorrect screenshot, I'm not sure why it happens but I can provide logs if needed.

I've also created a Docker file to allow compiling and testing without touching the installed version which is pretty convenient when it comes to localization testing (I'm not sure what to do with it and if it's necessary for someone other than myself).

Thanks.

**Comment by michaelrsweet** [comment]
@yarons I don't have a lot of experience with RTL languages and HTML/CSS, but I suspect you may just want to update the header.tmpl file to include a supplemental CSS file (call it "cups-rtl.css" that overrides the classes for header, footer, row/thirds/halves, body, etc. to specify the text direction and "float: right;" as needed. It may also be necessary to include the language information in the HTML header (in both index.html.in and header.tmpl) so that the browser knows what to do.

WRT Crowdin, I've not had any experience with that solution but am happy if it helps to bring more localizations to CUPS - there is (unfortunately) a *lot* to localize and not everyone is able to devote the time needed to do all of the work...

**Comment by michaelrsweet** [comment]
@yarons I found the following excellent resource on RTL CSS: <https://rtlstyling.com/posts/rtl-styling/>.

So we can update the existing cups.css to include overrides when the direction is rtl, and then you just need to add `dir="rtl"` to the initial `html` element in index.html.in and header.tmpl.in.

**Comment by yarons** [comment]
I have some new additions in my fork, it works somehow but I'm not pleased, I still have lots of work to do with the CSS, the relevant branch in my fork is l10n_master.

**Comment by yarons** [comment]
> WRT Crowdin, I've not had any experience with that solution but am happy if it helps to bring more localizations to CUPS - there is (unfortunately) a _lot_ to localize and not everyone is able to devote the time needed to do all of the work...

Yup, sadly t's not open source, there are other alternatives such as Weblate but we will not some more preparation work to use these systems (Crowdin supports HTML natively).

Regarding the `po` file, that's pretty straight forward but we can certainly tag the strings and add some comments and screenshots if relevant, I just wouldn't do that until we've agreed on a specific localization solution, these both systems support screenshots anyway, it's just impossible to migrate between those easily.

You can see my current work here: https://crowdin.com/project/cups
I'd love to add you as an additional manager.

Thanks!

**Comment by jschwender** [comment]
Actually, cups has only 600 lines of html for translation, whereas po files have 4000 lines and man pages another 5000…6000 lines. The html part is the easiest to translate, as you always see the full context. I agree that translating po files is helpful with tools that give you more context. For example Launchpad Translation tool gives you similar suggestions and full path and line number of occurrence in the source. I have very good experience with pootle, a very helpful tool which helps to ensure that translations are consistent. This is open source. Deepl is also very helpful as a translation support tool, it reduces translation process to check where the AI makes glitches.

**Comment by yarons** [comment]
@jschwender Hey, without getting into specific details, these tools are considered obsolete.

Weblate is the open source translation platform leader, it's much more robust than Launchpad or Pootle (Although there are small patches here and there, I wouldn't say these are actively developed, it's more like life support).

IIRC DeepL is commercially licensed but Weblate supports it as long as you enter the API key.

Translating the `po` and `man` pages required some initial work but luckily we have community to support that so it shouldn't be the devs responsibilty although their help is still needed every now and then.

The new localization tools are great time savers and being actively developed (and have a pricing model to support the development).

**Comment by jschwender** [comment]
@yarons, i do not disagree. I do not stick to Launchpad's tool or Pootle. I just appreciate tools that improve consistency control and give me context. Pootle does that, Launchpad is a working example (that is by definition not obsolete), and if Weblate even adds a better git integration, ok. I admit i did not know that weblate supports deepl – sounds interesting.

**Comment by yarons** [comment]
@jschwender Sorry if I sounded a bit rude, it's due to some other conversations I had in the past and also becuase I keep trying to influence Launchpad to add more features, they don't seem to cooperate sadly.

LOL, I'll try and see if we can fit the strings limit and with your permission I'll ask for hosting on their platform.
There's also an option for self hosting if you think it's interesting (yet more expensive).

**Comment by michaelrsweet** [comment]
@yarons Have your questions been answered? I'll be happy to merge changes once you have them ready...

**Comment by yarons** [comment]
It's hard for me to test it because I need to rebuild this in a docker each and every time I'm making some changes, it looks fine for now but it's still not perfect and for some reason some of the terms appear in English although I've translated them and I'm pretty sure I saw them translated before I made some CSS changes and rebuilt.

Is there a way to quickly test CSS modifications without rebuilding the project?

Thank you!

**Comment by michaelrsweet** [comment]
@yarons Running "make testserver" will start a CUPS server (by default on port 8631) that will pull from the local source directory.

**Comment by yarons** [comment]
Tried the testserver approach, it's not so convenient for testing HTML/CSS changes.

For some reason the build process is ommiting the headers which leads me to a situation where the header is in English (including the top menu) and the rest is in Hebrew, I'm still trying to figure out what I'm doing wrong.

**Comment by michaelrsweet** [comment]
@yarons Hmm, it should just be making symlinks to the source directory, so as long as you are editing the generated and not the ".in" files for your development the changes should show up in the browser. (You can copy the generated files back to the ".in" files as needed afterwards and re-add `@CUPS_VERSION@` in the ".in" file...)

**Comment by michaelrsweet** [comment]
I *think* the main issues/questions being asked have been resolved. Tracking future localization strategies in issue #216.
