### ISSUE TITLE
Support running IPP backend not as root

### ISSUE THREAD

**Issue by DemiMarie** [OpenPrinting/cups#17]
The IPP backend only needs to run as root when it needs access to Kerberos keytabs.  Otherwise, it is more secure to run it as an unprivileged user.

**Comment by michaelrsweet** [comment]
Well, cupsd runs as root and the backend is well-audited. Until such time that we can eliminate the Kerberos stuff, it needs to stay the way it is.

For your own local installation you can force it to run as a regular user by running (as root);

    chmod 755 /usr/lib/cups/backend/ipp
