### ISSUE TITLE
USB backend: Add support for printers that don't report a serial number

### ISSUE THREAD

**Issue by michaelrsweet** [OpenPrinting/cups#170]
@wawaclem filed an [Apple CUPS bug](https://github.com/apple/cups/issues/5914) concerning Dymo printers and the USB backend.

Basically, Dymo doesn't report the printer serial number (a *required* value in the IEEE 1284 standard) in the device ID, which prevents you from using more than one Dymo printer connected to a given system.

The solution is to read the USB serial number string when the device ID does not contain a serial number.

**Comment by michaelrsweet** [comment]
@wawaclem We are already reading the serial number from the device if there is no serial number in the IEEE 1284 device ID string. Can you run the following command and report what you get back?

```
lpinfo -l -v
```

Thanks!

**Comment by michaelrsweet** [comment]
I tweaked the code to use the USB serial number if the 1284 serial number was blank:

[master 75ee54aca] Use the device serial number if the 1284 serial number is empty (Issue #170)

However, I was unable to reproduce this issue with my Dymo LabelWriter 450 Twin Turbo.

Holding this open for @wawaclem to provide additional information...

**Comment by michaelrsweet** [comment]
Actually, looking back on the original bug, it looks like the 1284 ID has a bogus (hardcoded) serial number. Prepping a different change to use the USB serial number first...

**Comment by michaelrsweet** [comment]
[master fb3bdc46e] Prefer USB serial number over 1284 serial number (#170)

The new code also uses the iManufacturer and iProduct strings if the 1284 device ID doesn't have them.

**Comment by wawaclem** [comment]
<code> lpinfo -l -v </code>

Device: uri = usb://DYMO/LabelWriter%20450?serial=01010112345600
        class = direct
        info = DYMO LabelWriter 450
        make-and-model = DYMO LabelWriter 450
        device-id = MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;
        location = 


<code> dmesg | more </code>

[   23.633333] usb 1-1.3: new full-speed USB device number 4 using xhci_hcd
[   23.780535] usb 1-1.3: New USB device found, idVendor=0922, idProduct=0020, bcdDevice= 1.12
[   23.780556] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   23.780575] usb 1-1.3: Product: DYMO LabelWriter 450
[   23.780592] usb 1-1.3: Manufacturer: DYMO
[   23.780609] usb 1-1.3: SerialNumber: 16121409362443
[   23.850806] usblp 1-1.3:1.0: usblp0: USB Bidirectional printer dev 4 if 0 alt 0 proto 2 vid 0x0922 pid 0x0020
[   23.852909] usbcore: registered new interface driver usblp
[   77.565458] usblp0: removed
[   77.573064] usblp 1-1.3:1.0: usblp0: USB Bidirectional printer dev 4 if 0 alt 0 proto 2 vid 0x0922 pid 0x0020


<code> lsusb -v </code>

Bus 001 Device 004: ID 0922:0020 Dymo-CoStar Corp. LabelWriter 450
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0922 Dymo-CoStar Corp.
  idProduct          0x0020 LabelWriter 450
  bcdDevice            1.12
  iManufacturer           1 DYMO
  iProduct                2 DYMO LabelWriter 450
  iSerial                 3 16121409362443
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0020
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xc0
      Self Powered
    MaxPower                2mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         7 Printer
      bInterfaceSubClass      1 Printer
      bInterfaceProtocol      2 Bidirectional
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0001
  Self Powered

<br>

Effectively if the 1284 ID has a bogus (hardcoded) serial number if preferable to use the usb serial number first

Many thanks for your support and your reactivity

**Comment by michaelrsweet** [comment]
@wawaclem Thanks for the confirmation. If you are up to it, try building current CUPS master and just run the built USB backend, e.g.:

```
git clone https://github.com/OpenPrinting/cups.git
cd cups
./configure
make
backend/usb 2>/dev/null
```

You should now see two Dymo printers with the correct serial numbers...

**Comment by wawaclem** [comment]
@michaelrsweet Always with bad serial number ...

<code>
backend/usb
</code>
<br><br>

direct usb://DYMO/LabelWriter%20450?serial=01010112345600 "DYMO LabelWriter 450" "DYMO LabelWriter 450" "MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;" ""
direct usb://DYMO/LabelWriter%20450?serial=01010112345600 "DYMO LabelWriter 450" "DYMO LabelWriter 450" "MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;" ""

**Comment by michaelrsweet** [comment]
@wawaclem OK, can you pull the latest code and try that again?

And this time don't redirect stderr, just run `backend/usb` by itself so we can see the debug messages.

Thanks!

**Comment by wawaclem** [comment]
@michaelrsweet I did it but no debug message printout, I have the same output ... I don't understand

**Comment by michaelrsweet** [comment]
@wawaclem Just to confirm, what OS are you using?

**Comment by michaelrsweet** [comment]
@wawaclem ... and if you are using macOS, try updating to the current master code - I mirrored the fix for the libusb-based code to the macOS IOKit code.

**Comment by wawaclem** [comment]
@michaelrsweet For this test I was on a raspberry pi 3b+ with raspberry os lite based on debian 10, tomorrow I'll test on a Debian 10 and on macOS 10.15

**Comment by wawaclem** [comment]
@michaelrsweet Same result ...

Debian 10 :

root@pctest:/cups# backend/usb 
direct usb://DYMO/LabelWriter%20450?serial=01010112345600 "DYMO LabelWriter 450" "DYMO LabelWriter 450" "MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;" ""
direct usb://DYMO/LabelWriter%20450?serial=01010112345600 "DYMO LabelWriter 450" "DYMO LabelWriter 450" "MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;" ""
root@pctest:/cups# 


Mac OS 10.15 :

wawa@MacBook cups % backend/usb
direct usb://DYMO/LabelWriter%20450?serial=01010112345600 "DYMO LabelWriter 450" "DYMO LabelWriter 450" "MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;" ""
direct usb://DYMO/LabelWriter%20450?serial=01010112345600 "DYMO LabelWriter 450" "DYMO LabelWriter 450" "MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;" ""
wawa@MacBook cups %

**Comment by michaelrsweet** [comment]
@wawaclem That is *weird*, you should be getting debug messages on Linux (at least). Just to confirm, from the source you checked out you did:

    git pull
    make

before re-running your tests?

**Comment by wawaclem** [comment]
@michaelrsweet Yes I confirm, I've also deleted and cloned again the source and verified the code and confirmed that I've the good version with yours debug code message before compile again ... I also don't understand ...

**Comment by michaelrsweet** [comment]
@wawaclem OK, can you try `./backend/usb` on the off chance the shell is looking in the CUPS server bin directory first?

**Comment by wawaclem** [comment]
@michaelrsweet No change, same result

**Comment by ChrisMLawson** [comment]
Testing with two Dymo LabelWriter 450 on Ubuntu 20.04.2 LTS

chris@lenovo:~/cups/cups/backend$ sudo ./usb
DEBUG: Loading USB quirks from "/usr/share/cups/usb".
DEBUG: Loaded 181 quirks.
DEBUG: list_devices
DEBUG: libusb_get_device_list=6
DEBUG2: iSerialNumber="20082313022474"
DEBUG2: Printer found with device ID: MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600; Device URI: usb://DYMO/LabelWriter%20450?serial=20082313022474
direct usb://DYMO/LabelWriter%20450?serial=20082313022474 "DYMO LabelWriter 450" "DYMO LabelWriter 450" "MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;" ""
DEBUG2: iSerialNumber="20102618552794"
DEBUG2: Printer found with device ID: MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600; Device URI: usb://DYMO/LabelWriter%20450?serial=20102618552794
direct usb://DYMO/LabelWriter%20450?serial=20102618552794 "DYMO LabelWriter 450" "DYMO LabelWriter 450" "MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;" ""

**Comment by wawaclem** [comment]
@michaelrsweet After multiple tests I found the problem !!! The package libusb-1.0-0-dev was missing, after add it and compile again that's work great
But I am surprised that without this package there is no blockage for configuration or compilation

root@raspberrypi:/cups# backend/usb
DEBUG: Loading USB quirks from "/usr/share/cups/usb".
DEBUG: Loaded 172 quirks.
DEBUG: list_devices
DEBUG: libusb_get_device_list=6
DEBUG2: iSerialNumber="14102510593150"
DEBUG2: Printer found with device ID: MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600; Device URI: usb://DYMO/LabelWriter%20450?serial=14102510593150
direct usb://DYMO/LabelWriter%20450?serial=14102510593150 "DYMO LabelWriter 450" "DYMO LabelWriter 450" "MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;" ""
DEBUG2: iSerialNumber="16121409362443"
DEBUG2: Printer found with device ID: MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600; Device URI: usb://DYMO/LabelWriter%20450?serial=16121409362443
direct usb://DYMO/LabelWriter%20450?serial=16121409362443 "DYMO LabelWriter 450" "DYMO LabelWriter 450" "MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;" ""
root@raspberrypi:/cups#

**Comment by michaelrsweet** [comment]
@wawaclem It would have fallen back on the usblp character device implementation if libusb couldn't be found on Linux. macOS always uses the IOKit API (usb-darwin.c) so *it*, at least, should have shown the changes.

Oh, well. As long as this is fixed I am happy. Thank you @ChrisMLawson for the independent verification as well!

**Comment by kuipou** [comment]
I have a similar problem but with a BeePRT 480 when connected DEBUG2: iSerialNumber is not present.
```
pi@solana:~/cups $ cd backend/
pi@solana:~/cups/backend $ sudo ./usb
DEBUG: Loading USB quirks from "/usr/share/cups/usb".
DEBUG: Loaded 98 quirks.
DEBUG: list_devices
DEBUG: libusb_get_device_list=5
DEBUG2: iSerialNumber is not present.
DEBUG2: Printer found with device ID: MFG:Beeprt ;CMD:XPP,XL;MDL:BY-480BT;CLS:PRINTER;DES:BY-480BT; Device URI: usb://Beeprt/BY-480BT
direct usb://Beeprt/BY-480BT "Beeprt BY-480BT" "Beeprt BY-480BT" "MFG:Beeprt ;CMD:XPP,XL;MDL:BY-480BT;CLS:PRINTER;DES:BY-480BT;" ""
DEBUG2: iSerialNumber is not present.
DEBUG2: Printer found with device ID: MFG:Beeprt ;CMD:XPP,XL;MDL:BY-480BT;CLS:PRINTER;DES:BY-480BT; Device URI: usb://Beeprt/BY-480BT
direct usb://Beeprt/BY-480BT "Beeprt BY-480BT" "Beeprt BY-480BT" "MFG:Beeprt ;CMD:XPP,XL;MDL:BY-480BT;CLS:PRINTER;DES:BY-480BT;" ""
pi@solana:~/cups/backend $
```
