### ISSUE TITLE
[2.3.3-op2] Can't print on Samsung ML-1640 series with splix driver

### ISSUE THREAD

**Issue by altermetax** [OpenPrinting/cups#171]
Hi, since the cups 2.3.3op2 update I can't properly print on my Samsung ML-1640 series. Please note that cups 2.3.3op1 works correctly.

When I try to print, 3 separate situations can occur:

- The printer immediately prints an error:
```
INTERNAL ERROR - FALSE
POSITION: 0x768da (485594)
SYSTEM: h6fwsim_snipe/xl_pa_sim
LINE: 254
VERSION: SPL 5.07 06-27-2006
```
- The printer starts blinking as if it were printing, waits several minutes, then prints an error (different from the first one):
```
INTERNAL ERROR - Incomplete Session by time out
POSITION: 0x3a57 (14935)
SYSTEM: h6fwsim_snipe/os_hook
LINE: 1060
VERSION: SPL 5.07 06-27-2006
```
- The printer prints correctly.

I first opened a thread on the Arch Linux forum because that's the distro I'm using: https://bbs.archlinux.org/viewtopic.php?id=265299

This happens with the splix drivers and also with the official Samsung drivers. The cups logs don't seem to acknowledge any issue.
Downgrading to cups 2.3.3op1 fixed it.

**Comment by zdohnal** [comment]
Hi @altermetax ,

you encountered the issue which has a proposed fix in #160 .

Currently we are trying to figure out the correct timeout for bulk transfer, but we need feedback from users of affected devices.

Please report this issue to Arch CUPS maintainer with the link to [PR](https://github.com/OpenPrinting/cups/pull/160) and ask him to provide you a testing packages with the patch from PR applied.

**Comment by altermetax** [comment]
Thank you. I built an Arch package with that patch on my own and it seems to work correctly. I have now submitted a bug report on Arch to ask for its addition.

**Comment by vinibali** [comment]
For me on version 1:2.3.3op2-3 the good old ML-2010 works again. Thanks for time and effort!
