### ISSUE TITLE
Support for Munbyn, Rollo and Beeprt label printers

### ISSUE THREAD

**Issue by proski** [OpenPrinting/cups#172]
Munbyn, Rollo and Beeprt label printers provide Linux driver with a modified rastertolabel executable, also called rastertolabelbeeprt in some packages. There are versions for Raspberry Pi (32-bit ARM) and for x86_64. The PPDs for all those devices use `*cupsModelNumber: 20`, which is not supported by the current rastertolabel sources (the supported numbers are 0, 16, 17, 18, 19 and 32).

I believe it should be acceptable to reverse engineer support for those drivers by observing the output of rastertolabelbeeprt. A wrapper could be user to run the patched rastertolabel from CUPS and rastertolabelbeeprt and compare their outputs.

I might find time to work on it on my own, but no promises. In any case, I want to share the information I have so far and ask if anyone has attempted it before.

**Comment by michaelrsweet** [comment]
@proski Given that we are trying to get out of the printer driver business, I'm not keen on adding more printers to rastertolabel. A better path forward would be to post this request to my [LPrint project](https://github.com/michaelrsweet/lprint) which is trying to provide a Printer Application (use with CUPS or standalone) for all of the label printers supported by rastertolabel...

**Comment by proski** [comment]
Thanks for the information! LPrint looks like an interesting project.

I was able to run `rastertolabelbeeprt` from `cupsfilter` and compare the result to the patched `rastertolabel`. It looks like I'll be able to make them do the same thing. Thankfully, it doesn't appear that any compression is involved. Then I'll port the code to LPrint.
