### ISSUE TITLE
cupsd.conf MaxSubscriptions* directives not documented

### ISSUE THREAD

**Issue by jsmeix** [OpenPrinting/cups#177]
It seems the following cupsd.conf directives are not documented
```
MaxSubscriptions
MaxSubscriptionsPerJob
MaxSubscriptionsPerPrinter
MaxSubscriptionsPerUser
```
because in current CUPS GitHub master sources they appear only in those files
```
scheduler/subscriptions.c
scheduler/subscriptions.h
scheduler/conf.c
test/4.4-subscription-ops.test
test/run-stp-tests.sh
``` 

Is there a reason why they are not documented?
E.g. are they perhaps not meant to be set by the user?

FYI background information:

We (i.e. SUSE) got the following customer issue report (excerpts):
```
While troubleshooting a cupsd problem (print jobs did not get
forwarded to Windows Print Server / lpstat ran into timeouts etc.)
we found in /var/log/cups/error_log the following lines : 

D ... cupsdAddSubscription: Reached MaxSubscriptions 100 (count=100)

D ... Create-Printer-Subscriptions client-error-too-many-subscriptions: There are too many subscriptions.

E ... Returning IPP client-error-too-many-subscriptions for Create-Printer-Subscriptions (/) from x.x.x.x

There is a MaxSubscriptions directive,
which is unfortunately not explained in cupsd.conf(5),
but increasing the same plus MaxClients resolved the problem 
```

**Comment by michaelrsweet** [comment]
These *should* be documented, and it is possible they never got added to the man page (previously we focused on the HTML documentation). But the directives have been there since CUPS 1.2...

**Comment by michaelrsweet** [comment]
[master 10e4edb35] Add missing MaxSubscriptionsXxx docos (Issue #177)

**Comment by jsmeix** [comment]
@michaelrsweet 
it seems https://github.com/OpenPrinting/cups/commit/10e4edb359ecc20782c99fe6d0a4b5dbbc88ac09
does not add the missing directives but replaces existing directives.

For example it seems MaxJobs got replaced by MaxSubscriptions
because in a current git clone from today I have
```
# find . -type f  | xargs grep -il 'MaxSubscriptions'
./scheduler/subscriptions.c
./scheduler/subscriptions.h
./scheduler/conf.c
./man/cupsd.conf.5
./doc/help/man-cupsd.conf.html
./test/4.4-subscription-ops.test
./test/run-stp-tests.sh

# find . -type f  | xargs grep -il 'MaxJobs'
./scheduler/job.h
./scheduler/conf.c
./scheduler/job.c
./scheduler/ipp.c
./cgi-bin/admin.c
```
while in a git clone from some days before I have
```
find . -type f  | xargs grep -il 'MaxSubscriptions'
./scheduler/subscriptions.c
./scheduler/subscriptions.h
./scheduler/conf.c
./test/4.4-subscription-ops.test
./test/run-stp-tests.sh

# find . -type f  | xargs grep -il 'MaxJobs'
./scheduler/job.h
./scheduler/conf.c
./scheduler/job.c
./scheduler/ipp.c
./cgi-bin/admin.c
./man/cupsd.conf.5
./doc/help/man-cupsd.conf.html
```

**Comment by michaelrsweet** [comment]
Ugh, I must not have checked "in selection for the find/replace I did when copying MaxJobsXxx to MaxSubscriptions. Fixed:

[master eda69a24c] Fix errant find/replace that messed up the jobs documentation (Issue #177)
