### ISSUE TITLE
RPi - Not adding printers

### ISSUE THREAD

**Issue by The-Tourer** [OpenPrinting/cups#183]
fresh install on RPI Raspbian - 

error_log says : 

```
W [02/May/2021:17:47:27 +0530] Notifier for subscription 94 (dbus://) went away, retrying!
W [02/May/2021:17:47:27 +0530] Notifier for subscription 96 (dbus://) went away, retrying!
W [02/May/2021:17:47:27 +0530] Notifier for subscription 98 (dbus://) went away, retrying!
W [02/May/2021:17:47:27 +0530] Notifier for subscription 100 (dbus://) went away, retrying!
W [02/May/2021:17:47:27 +0530] Notifier for subscription 102 (dbus://) went away, retrying!
W [02/May/2021:17:47:27 +0530] Notifier for subscription 104 (dbus://) went away, retrying!
W [02/May/2021:17:47:27 +0530] Notifier for subscription 106 (dbus://) went away, retrying!
W [02/May/2021:17:47:27 +0530] Notifier for subscription 108 (dbus://) went away, retrying!
W [02/May/2021:17:47:27 +0530] Notifier for subscription 110 (dbus://) went away, retrying!
W [02/May/2021:17:47:27 +0530] Notifier for subscription 114 (dbus://) went away, retrying!
W [02/May/2021:17:47:27 +0530] Notifier for subscription 118 (dbus://) went away, retrying!
W [02/May/2021:17:47:27 +0530] Notifier for subscription 122 (dbus://) went away, retrying!
```

below was the error when I tried to "test" before installation:

```
    Add 2 Printer Subscriptions w/Lease                                  [FAIL]
        RECEIVED: 0 bytes in response
        status-code = server-error-internal-error (Invalid group tag.)
        IPP request failed with status server-error-internal-error (Invalid group tag.)
```

so when I try to add the printer, after selecting the PPD file, it says "page cannot be reached"

the PPD file is getting uploaded to the /PPD folder.

what am I missing?

[cups-str-2021-05-02-pi.html.txt](https://github.com/OpenPrinting/cups/files/6411397/cups-str-2021-05-02-pi.html.txt)

[error_log.txt](https://github.com/OpenPrinting/cups/files/6411399/error_log.txt)

**Comment by michaelrsweet** [comment]
@The-Tourer OK this is really weird, what version of Raspbian/Raspberry Pi OS are you using?

I just ran a build on a Pi Zero W I have running for this purpose and it completed the test suite without errors...

**Comment by The-Tourer** [comment]
`PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

**Comment by michaelrsweet** [comment]
@The-Tourer That's what I am using as well...

One thing to make sure (once you install it) - the default libcups is installed in `/usr/lib/arm-linux-gnueabihf` which might interfere with a locally installed copy.

**Comment by The-Tourer** [comment]
I'm inside that folder. but I'm not sure about anything that says libcups in there. am I doing this wrong?

**Comment by The-Tourer** [comment]
all looks good - still not able to do it.

steps I did:

- Formatted the SD Card, used the Raspberry tool to install the 322-bit Rasbian on Pi 3B+ - 
- updated it
- now the same issue is coming when installing

[cups-str-2021-05-07-pi.html.txt](https://github.com/OpenPrinting/cups/files/6439334/cups-str-2021-05-07-pi.html.txt)

**Comment by michaelrsweet** [comment]
@The-Tourer Still not able to reproduce on my end...

Let's back up for a second - what version of CUPS are you trying to build?

**Comment by The-Tourer** [comment]
the latest one from cloning the GIT using the below command & then following steps in the install.md file.

`git clone https://github.com/OpenPrinting/cups.git`

weird enough, the library CPPFLAGS isn't picking from the below once I give the `make test` command?

pi@raspberrypi:~/cups $ make test
Using ARCHFLAGS=
Using ALL_CFLAGS=-I.. -D_CUPS_SOURCE -I/usr/include/libusb-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include -DDBUS_API_SUBJECT_TO_CHANGE -D_FORTIFY_SOURCE=2 -D_REENTRANT -I/usr/include/p11-kit-1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT  -Wall -Wunused -Wno-char-subscripts -Wno-deprecated-declarations -Wno-format-truncation -Wno-format-y2k -Wno-switch -Wno-unused-result
Using ALL_CXXFLAGS=-I.. -D_CUPS_SOURCE -D_FORTIFY_SOURCE=2 -I/usr/include/p11-kit-1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT  -Wall -Wunused -Wno-char-subscripts -Wno-deprecated-declarations -Wno-format-truncation -Wno-format-y2k -Wno-switch -Wno-unused-result
Using CC=gcc
Using CXX=gcc
Using DSOFLAGS=-Wl,-soname,all -shared
Using LDFLAGS=
Using LIBS= -lavahi-common -lavahi-client -lgnutls -lz -lpthread -lm -lcrypt   -lz

**Comment by michaelrsweet** [comment]
@The-Tourer I'm sorry, I have no clue what is going wrong for you.

**Comment by The-Tourer** [comment]
just curious - which OS are you trying this on? a fresh install on raspbian 32 bit os?

**Comment by michaelrsweet** [comment]
@The-Tourer I'm using current Raspberry Pi OS (aka Raspbian) that I put on my SD card using belenaEtcher (<https://www.balena.io/etcher/>) from my Mac.

**Comment by michaelrsweet** [comment]
Sorry, haven't been able to duplicate and I don't know what else to do here. Perhaps the Raspbian or Debian folks can help more...
