### ISSUE TITLE
Set "Host: localhost" on all IPP requests targeted to the loopback address

### ISSUE THREAD

**Issue by alexpevzner** [OpenPrinting/cups#185]
Under some circumstances, Avahi announces local services under the name different from `localhost`. It cannot be controlled by service itself, even if service attempts to use `localhost` name, Avahi may override it.

It breaks printing on some IPP over USB devices. IPP over USB specification explicitly requires that the `Host:` header to be set as either `localhost` or `localhost:port`. Although most of devices allows arbitrary syntactically correct value to be set to the `Host:` header, some of them are more restrictive. 

As example, you may look to the following `ipp-usb` ussue: https://github.com/OpenPrinting/ipp-usb/issues/29

Ideally, this problem should be fixed at Avahi side. However, experience shows that fixing something related to the `localhost` announces in Avahi may take years :-(

The proposed workaround is to modify CUPS so that it will always set `Host: localhost:port`, if IPP request is directed to `127.0.0.1` or `::1` addresses, regardless of printer's host name, obtained from Avahi

**Comment by michaelrsweet** [comment]
I thought we were already doing this, but will verify.

**Comment by alexpevzner** [comment]
According to logs from OpenPrinting/ipp-usb#29, no. But may be, it is some old version of CUPS, coming with some distro

**Comment by michaelrsweet** [comment]
No, we were just adding the port number...

[master 8ea6ed3b8] Use localhost host header for loopback/domain sockets (Issue #185)
