### ISSUE TITLE
SAP spool administration: OS system commands

### ISSUE THREAD

**Issue by Moezd2203** [OpenPrinting/cups#191]
Our company is currently trying to manage SAP printouts via CUPS.
The installation of CUPS went without problems.

But during test prints in SAP with access method E (external output mangement), we encountered the problem that the OS commands of the CUPS LOMS (logical output management system) are not defined in SAP. Here is an example from the currently used OMS (VPSX):
![image](https://user-images.githubusercontent.com/84381208/119121181-67a39300-ba2d-11eb-8724-ec00b0136a30.png)

Where can we find the commands for CUPS or do we have to define them ourselves?

CUPS runs on a linux server.

Thank you in advance for any feedback.

**Comment by michaelrsweet** [comment]
@Moezd2203 Unfortunately, I don't think you'll find anyone on the OpenPrinting team with SAP experience. You might ask the SAP folks - after all, CUPS is the standard printing system on all Linux systems, and has been for almost 20 years, so I'm shocked that they don't already have something in place for this!
