### ISSUE TITLE
Xerox B210 does not work with CUPS

### ISSUE THREAD

**Issue by andrejpodzimek** [OpenPrinting/cups#198]
(Initial side note: TBH, after #197 I sincerely doubt that CUPS will work properly on ArchLinux; it has severe TLS-related problems. However, even with the plaintext `localhost:631` GUI, Xerox B210 on USB cannot be configured.)

The printer doesn’t appear anywhere in the *Add Printer* or *Find New Printers* pages. There is nothing about it in the logs either (`LogLevel debug`).

Apparently the printer [may have worked](https://forums.fedoraforum.org/showthread.php?325480-Xerox-B210-prints-gibberish-unexpectedly) for someone at some point, but it is unclear whether this was over the network (which I won’t do, for security reasons) or over USB (which doesn’t seem to work at all).

The printer appears on USB:

```
Bus 005 Device 015: ID 0924:42ea Xerox B210
```

[This is from `lsusb -v`.](https://github.com/OpenPrinting/cups/files/6625239/xerox_b210_lsusb.txt)

This is from `dmesg`:
```
[317190.562900] usb 5-4.1: new high-speed USB device number 13 using xhci_hcd
[317190.656252] usb 5-4.1: New USB device found, idVendor=0924, idProduct=42ea, bcdDevice= 1.00
[317190.656260] usb 5-4.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[317190.656262] usb 5-4.1: Product: B210
[317190.656263] usb 5-4.1: Manufacturer: Xerox
[317190.656265] usb 5-4.1: SerialNumber: 3438009620
[317190.694959] audit: type=1130 audit(1623251740.832:12739): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ipp-usb comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[317190.717149] usblp 5-4.1:1.0: usblp0: USB Bidirectional printer dev 13 if 0 alt 0 proto 2 vid 0x0924 pid 0x42EA
[317190.717213] usbcore: registered new interface driver usblp
[317190.747576] usblp0: removed
```

The distro is ArchLinux with kernel `5.12.9`. Relevant packages:
```
cups 1:2.3.3op2-3
cups-filters 1.28.8-1
cups-pdf 3.0.1-6
cups-pk-helper 0.2.6-4
cups-xerox-b2xx 1.0-1
libcups 1:2.3.3op2-3

foomatic-db 3:20210528-1
foomatic-db-engine 4:20200206-1
foomatic-db-gutenprint-ppds 5.3.4-1
foomatic-db-nonfree 3:20210528-1
foomatic-db-nonfree-ppds 3:20210528-1
foomatic-db-ppds 3:20210528-1
```

What I’ve tried thus far:

* [This package](https://aur.archlinux.org/packages/cups-xerox-b2xx/#news). It doesn’t work. No change.
* [This weird script from Xerox](https://www.support.xerox.com/en-kw/product/xerox-b210-printer/content/145484) It doesn’t work. It installs lots of files (PPDs, binaries of unknown origin and other nonsense) into `/opt/xerox`, `/opt/smfp-common`, `/usr/share/cups` and `/usr/lib/cups`, but otherwise does **nothing**. The printer doesn’t work.
* The printer’s built-in test page. The printer prints out its configuration when powered on. It explicitly says that USB is enabled.
* Blacklist / unload / reload the `usblp` module. (Does it need to be blacklisted with this printer?) Well, it probably doesn’t matter, because it did not change anything.

Can this printer work with CUPS? Xerox claims it does have some Linux support, but thus far this doesn’t seem to be the case. And, the most importantly, **how does one debug this problem**? What can I do to provide more information?

**Comment by andrejpodzimek** [comment]
After (numerous) further hacks, I spotted this in `/var/log/cups/error_log`:

```
D [09/Jun/2021:18:23:37 +0200] [CGI] ppdc: Unknown token \"Vx\" seen on line 1 of /usr/share/ppd/cms/B205sc.cts.
E [09/Jun/2021:18:23:37 +0200] [cups-driverd] Bad driver information file \"/usr/share/ppd/cms/B205sc.cts\"!
D [09/Jun/2021:18:23:37 +0200] [CGI] ppdc: Unknown token \"Vx\" seen on line 1 of /usr/share/ppd/cms/B210sc.cts.
E [09/Jun/2021:18:23:37 +0200] [cups-driverd] Bad driver information file \"/usr/share/ppd/cms/B210sc.cts\"!
D [09/Jun/2021:18:23:37 +0200] [CGI] ppdc: Unknown token \"Vx\" seen on line 1 of /usr/share/ppd/cms/B215sc.cts.
E [09/Jun/2021:18:23:37 +0200] [cups-driverd] Bad driver information file \"/usr/share/ppd/cms/B215sc.cts\"!
```

The problematic files came from [this package](https://aur.archlinux.org/packages/cups-xerox-b2xx). So I removed that package and uninstalled / re-installed [the Xerox weirdness](https://www.support.xerox.com/en-kw/product/xerox-b210-printer/content/145484), but nope, the printer is still neither detected nor usable.

There was initially no `Xerox` keyword in the logs whatsoever, but I somehow managed to strongarm CUPS (using `system-config-printer`) to add an undetected printer using a completly bogus URI `usb:/Xerox_B210_Series?serial=3438009620`. (I guess there’s no reason why this URI should exist and work &mdash; and indeed, it does **not** work.)

Anyhow, I guess this shows that even if printer auto-detection and USB communication somehow worked, there would still be plenty of problems. (And USB printer auto-detection doesn’t work to start with.)

**Comment by andrejpodzimek** [comment]
Here’s a cross-link to [my post on Xerox user forums](https://forum.support.xerox.com/t5/Printing/Xerox-B210-doesn-t-work-under-Linux-with-CUPS/td-p/243318).

**Comment by andrejpodzimek** [comment]
A few hours of unsuccessful experiments later, I think there may be more to it than just a CUPS problem. It may be the case that the printer (Xerox B210) is a useless pile of junk.

* It doesn’t work on Linux via USB.
* It doesn’t print on Linux via ethernet.
* It doesn’t work on Windows via USB.
* I haven’t tried Windows and ethernet and don’t really care any more, because I don’t use Windows and don’t have regular access to that system.

In other words, this printer **does not print** anything other than its own configuration and status pages.

Over the ethernet I can connect to the printer’s web interface, which works fine (and claims that USB is enabled, which does not seem to be the case).

However, there is simply no way to print. CUPS does detect the printer on the network (over DNSSD) and can also configure it via IPP, but all attempts to print say *Filter failed*.

A struggle with [broken CUPS](https://github.com/OpenPrinting/cups/issues/197) combined with a broken printer is a guaranteed way to ruin one’s day.

**Comment by debiantriage** [comment]
@andrejpodzimek

Your `lsusb -v` output shows

>   bInterfaceClass            7 Printer
      bInterfaceSubClass      1 Printer
      bInterfaceProtocol       4

It is an IPP-over-USb device. Please read https://wiki.debian.org/CUPSDriverlessPrinting, particularly sections 13, 14 and 15. I am not familiar with the packages supplied by Arch but would suggest installing ipp-usb and setting up a print queue as follows:`lpadmin -p testq -v ipp://... -E -m everywhere`.

-- 
Brian.

**Comment by andrejpodzimek** [comment]
I had had `ipp-usb` installed the whole time, but to no avail, it just didn’t work.

Anyhow, I simply returned the printer, because it was not worth the effort. That said, I won’t be able to debug the problem any further. Time lost on it may have outweighed the costs of thousands of pages printed in a public copy center.

If this bug report prevents *one* person from buying this printer and losing lots of time, then at least filing it may have been time well spent.

**Comment by Hodorevskiy** [comment]
I found the following solution: 
1. found the port to which the  printer is connected
ls /dev/usb*
hiddev0 **lp1**
2. when adding the printer, specified the path to the device URI:
**parallel**:/dev/usb/lp1
The printer is working!
