### ISSUE TITLE
Content obscured by the footer

### ISSUE THREAD

**Issue by grahamperrin** [OpenPrinting/cups#199]
### Examples

At https://openprinting.github.io/cups/ it's nearly impossible to click the three or more references: 

![image](https://user-images.githubusercontent.com/192271/121802498-82d07f80-cc34-11eb-93b7-94335851b2d5.png)

<https://openprinting.github.io/cups/doc/overview.html#BEGIN> … from the _what_? At least one line is entirely invisible: 

![image](https://user-images.githubusercontent.com/192271/121802536-c5925780-cc34-11eb-90b6-8728054f06dd.png)

<https://openprinting.github.io/cups/doc/relnotes.html> how many notes are invisible? 

![image](https://user-images.githubusercontent.com/192271/121802618-2588fe00-cc35-11eb-8712-056be5499855.png)

**Comment by michaelrsweet** [comment]
@grahamperrin What browser and operating system? I also cannot reproduce.

**Comment by grahamperrin** [comment]
Sorry, I missed the previous e-mail about this. 

On closer investigation, the bug occurs when [Diigo](https://addons.mozilla.org/addon/diigo-web-collector/) is enabled. Extraordinary, I've been using the extension for years, never saw anything like this: 

https://user-images.githubusercontent.com/192271/123497400-32d6bd00-d625-11eb-9281-c9728a11ee43.mp4

Firefox 89.0.1, FreeBSD 14.0-CURRENT.
