### ISSUE TITLE
Print queues disabled due to wrong paper size specified

### ISSUE THREAD

**Issue by chalmerssys** [OpenPrinting/cups#20]
I have problem where cups print queues on a server become disabled when jobs with wrong paper size are sent.
Queues in both server and client have error policy "retry-job" or "abort-job" set but jobs are not retried or aborted, instead the print queue on the server gets disabled.

D [29/Oct/2020:11:56:02 +0100] [Job 204] PID 10101 (/usr/lib/cups/backend/papercut) stopped with status 4.
I [29/Oct/2020:11:56:02 +0100] [Job 204] Backend returned status 4 (stop printer)

If I eliminate the papercut backend the ipp backend has the same behaviour.

cups is version 2.3.0 on the server.

An URI on the server:

DeviceURI papercut:ipp://129.16.xxx.xxx:631/ipp

URI on client:
DeviceURI ipp://ourserver.chalmers.se:631/printers/sv-339-color4

This seems broken?

Currently I have to run a shell script that remove jobs and enables queues or else the all queues will soon be disabled...

**Comment by chalmerssys** [comment]
I noticed something that might have triggered this, a lot of the installed printers on clients had this setting:

*DefaultInputSlot: Unknown

This seems to be a bad setting, the queue seems not to be disabled if this is set to Auto. If InputSlot is set to Auto it is not possible to change it back to Unknown again with the lpadmin command.

**Comment by michaelrsweet** [comment]
This looks like a PPD issue - while "Unknown" can be used by some PostScript printers to indicate there is no default paper tray, it isn't allowed by CUPS (and it seems not by PaperCut, either...)

**Comment by chalmerssys** [comment]
So what is causing the problem? The ppd is created when adding the printer with lpadmin and "-m everywhere". Is it the printers fault??
