### ISSUE TITLE
Open browser after printing is done

### ISSUE THREAD

**Issue by hasgardee** [OpenPrinting/cups#202]
I know this is not within the scope of this project. I actually want to open a url in the browser after printing is done. I tried system("open URL") and exec functions. Those functions run without error. But the browser is not opening.I tried the same system() from a single .c file and compiled with clang and gcc.it works(./a.out). But it did not work inside my printer module. Is it because of the printer module having limited permissions? Is there any way to do that?

I used this project to create printer module(convert doc to pdf and save): https://github.com/rodyager/RWTS-PDFwriter
OS: Mac BigSur

**Comment by jsmeix** [comment]
I am not a Mac user (I use Linux) so I don't know details about Mac systems.
As far as I know the printing system on Mac OS runs within a rather restricted "sandbox".

In general on Unix-like systems the actual print job processing by the printing system
is done as a different user than the user who submitted a print job to the printing system.

Cf. the section "Background Information regarding Print as PDF versus Save as PDF" in
https://en.opensuse.org/SDB:Printing_to_PDF
that describes a similar case where the printing system cannot do
things that the user who submitted a print job can do on its own.

**Comment by michaelrsweet** [comment]
@hasgardee This isn't something you can do generally from a backend. The IPP backend uses an XPC service (running as the logged-in user) to "trampoline" into the user session to get Kerberos credentials, and I suspect you could do something similar to open a web page, but this isn't something I'd normally recommend doing...
