### ISSUE TITLE
Need some help with buffering

### ISSUE THREAD

**Issue by Kamuri-chan** [OpenPrinting/cups#205]
Hi, I have a set of label printers and use CUPS to send the files to them, but actually the process is really slow, as the printer has to fire up, buffer and then print. 
It is possible to create some kind of buffer, that waits 10 seconds for jobs (with or without merging them into one),  and then sends it to the printer?

**Comment by michaelrsweet** [comment]
@Kamuri-chan Sorry, no. If the printers are supported by [LPrint](https://www.msweet.org/lprint) you'll probably find it will print things faster...
