### ISSUE TITLE
lpadmin, -m everywhere and Tea4CUPS

### ISSUE THREAD

**Issue by debiantriage** [OpenPrinting/cups#210]
I have Debian's ippeveprinter set up: `/usr/sbin/ippeveprinter -f application/pdf ippeveprinter`. Its URI was obtained from the driverless utility and queue creation attempted with: `lpadmin -p testq -v tea4cups:/URI -E -m everywhere`. This results in 

> Unable to connect to ":0": Name or service not known

Is there a way round this or is it never going to be possible to wrap a backend with the everywhere model?

**Comment by michaelrsweet** [comment]
@debiantriage The IPP Everywhere model only works for IPP and IPPS URIs, because the PPD is dynamically generated from the capabilities returned for the queue/printer.

**Comment by debiantriage** [comment]
**@michaelrsweet** Colour me disappointed, but the response wasn't entirely unexpected. Thanks. Back to the drawing board!

**Comment by michaelrsweet** [comment]
One possible workaround: create the queue with the real URI and then change the device URI afterwards, e.g.:

```
lpadmin -p myprinter -E -m everywhere -v ipp://...
lpadmin -p myprinter -v Tea4cups://...
```

**Comment by debiantriage** [comment]
Success! The colour has changed to _happy._ The idea is appreciated.
