### ISSUE TITLE
[General query] Regarding rastertoepson support for new printers

### ISSUE THREAD

**Issue by adhiti33** [OpenPrinting/cups#214]
I am trying to use rastertoepson.c to get prn file for Epson M200 printer. Regarding this would like to know extent of support provided by rastertoepson for all Epson printers.

1> Does it support all epson printers ?
2> Is it updated based for latest inkjet printer ?
3> Do you suggest usage rastertoepson.c or usage of printer drivers provided by Epson ?

**Comment by michaelrsweet** [comment]
@adhiti33 It is unlikely that the rastertoepson driver will work with this printer. Gutenprint is the typical driver for older Epson printers like this.

**Comment by adhiti33** [comment]
@michaelrsweet M200 is not so old. It is still running. My aim is to cover most epson printers in general so was looking for rastertoepson filter printer file generation.

https://www.epson.co.in/Ink-Tank/Ink-Tank-System-Printers/EcoTank-M200-Multifunction-B%26W-Printer/p/C11CC83412
