### ISSUE TITLE
[Documentation / Clarification]  OpenPrinting CUPS versus Apple CUPS

### ISSUE THREAD

**Issue by rubyFeedback** [OpenPrinting/cups#215]
Hey guys,

I went to this homepage: https://openprinting.github.io/cups/

I recently also read this article: https://retrohacker.substack.com/p/bye-cups-printing-with-netcat

And was skimming through reddit.

Which leads me to the question: what exactly is the difference between OpenPrinting
CUPS and Apple CUPS? Who is the main developer who forked off cups or the
group that did so and when?

I don't expect a huge article, but what I think may help, also perhaps other people,
is if the webpage at https://openprinting.github.io/cups/ would contain a few
sentences or a paragraph (or extending that paragraph) to explain what exactly
OpenPrinting CUPS is, how it differs from the older CUPS and Apple CUPS.
Right now I used to think OpenPrinting is different altogether and cups the older
stack, but it seems my assumption as wrong. Which is why it may be useful
to clarify this a bit better on the homepage, on a first glance; or alternatively,
an additional page "About" or something, with a few more details, and a mention
to this from that main webpage. At any rate please feel free to close this issue
at any moment in time.

**Comment by michaelrsweet** [comment]
@rubyFeedback We will look into doing something more on the web site and maybe in the README file for future releases. I have documented things fairly extensively in my most recent [CUPS plenary slides](https://ftp.pwg.org/pub/pwg/liaison/openprinting/presentations/cups-plenary-may-2021.pdf#page=5) at the OpenPrinting summit we held in May, but to summarize:

- I am under contract to help produce a "final" Apple CUPS 2.3.5 release, but Apple is no longer actively developing new CUPS features for macOS
- OpenPrinting and Apple will share security and bug fixes going forward
- OpenPrinting has taken over development of new CUPS features and is working on the next CUPS feature release (2.4)

**Comment by michaelrsweet** [comment]
[master a8414c0b3] Add clarification that OpenPrinting CUPS is the most current, and that Apple CUPS is what ships with macOS and iOS (Issue #215)
