### ISSUE TITLE
Printing in colour, lpadmin vs. ipp2ppd

### ISSUE THREAD

**Issue by chalmerssys** [OpenPrinting/cups#220]
A while ago I sent in bug report #182 regarding print options and printing to kerberos authenticated queues with Mac OS.
Now I have upgraded my Mac to Monterey which seems to contain the fix. Happily it works much better now!
But there seems to be at least one problem. When adding the queue with the Mac GUI, everything seems to work.
I notice that the ppd in this case is created by ipp2ppd. If I add the queue with lpadmin options seems to work, with the notable exception of switching between color & b/w. One is stuck with b/w (server default) for these queues. 
The printer is a Kyocera TaskAlfa 5052ci. 
Is this something that could be fixed? Please let me know if I could help by sending in log files etc.

**Comment by chalmerssys** [comment]
Additional observations: 
1. I tried printing to a HP Color LaserJet MFP E87650 instead. Same result.
2. When creating the queue with lpadmin, the print dialog is missing the "Black & White" tick box between "Copies" and the "Two-Sided" tick box.

**Comment by michaelrsweet** [comment]
@chalmerssys For macOS-specific issues like this, you really need to file the bug against the [Apple CUPS](https://github.com/apple/cups/issues) Github project or (better) via the Feedback Assistant application.
