### ISSUE TITLE
A deadlock bug due to the reacquiring the same lock

### ISSUE THREAD

**Issue by ycaibb** [OpenPrinting/cups#243]
Hi, developers, thank you for your checking. Should the second lock statement be the unlock statement? I guess it is a mistake. Or it is on purpose due to other reasons?
https://github.com/OpenPrinting/cups/blob/1da735b3f0cf258eba0836b54796dc99c4950ac3/cups/tls-darwin.c#L287-L294

**Comment by zdohnal** [comment]
@ycaibb Looks like a typo, but I'm not able to verify since I don't have a Mac OS machine, where this code is used. @michaelrsweet maybe knows more.

**Comment by michaelrsweet** [comment]
@ycaibb Good catch! This code is actually only used when building for iOS and only when making a self-signed cert for server mode (not that common a scenario), but I've pushed a fix here and on the Apple CUPS repo:

[master 4d058a7ed] Fix potential deadlock (Issue #243)

**Comment by ycaibb** [comment]
@michaelrsweet @zdohnal Thanks!

**Comment by ycaibb** [comment]
@michaelrsweet Hi, could it be considered as a deadlock vulnerability, wreaking a DoS? Would it be possible to collaboratively apply CVE for this? Thank you very much.

**Comment by michaelrsweet** [comment]
@ycaibb Since this isn't a general issue (you can't ship servers for iOS and macOS doesn't use this code) I don't see why we'd bother with a CVE.
