### ISSUE TITLE
In MacOS, through PPD file application / vnd.cups-pdf, the PDF generated after printing cannot be added to PJL

### ISSUE THREAD

**Issue by xiaokun111** [OpenPrinting/cups#258]
In MacOS, through PPD file application / vnd.cups-pdf, the PDF generated after printing cannot be added to PJL

There are several questions:

1. Pdf 1.3 generated by quartz pdfcontext cannot be added to PJL

2. Cgpdftopdf failed to add PJL

How to add PJL to the generated PDF?

**Comment by michaelrsweet** [comment]
@xiaokun111 macOS does not support PJL-wrapped PDF.

**Comment by michaelrsweet** [comment]
(for future reference, please report macOS bugs to Apple, either on the Apple CUPS Github project or to bugreport.apple.com)

**Comment by xiaokun111** [comment]
Thanks for @michaelrsweet

This question bothered me for a month. I checked a lot of information. You are the most authoritative answer
