### ISSUE TITLE
Authentication Failure with network IPP printer

### ISSUE THREAD

**Issue by IronFractal** [OpenPrinting/cups#273]
I am trying to set up the ability to print on my college's printers. My college has both SMB and IPP for printing.

I am having issues because when I try to print cups uses my local username for the account on my computer rather than my school's username/password.

I have tried editing the /etc/cups/printers.conf to ask for a username/password etc...

I tried to print and entered my username and password when prompted but it did not use the supplied credentials.

**Comment by zdohnal** [comment]
No response for two weeks, closing.
