### ISSUE TITLE
Zebra GK420D print upside down

### ISSUE THREAD

**Issue by mmoor3** [OpenPrinting/cups#280]
We are moving from RHEL 6.9 CUPS 1.4.2 printing a label on a Zebra printer.  We are moving to SLES 15.2 CUPS 2.2.7, the same print job prints upside down on the SLES side.  We have pulled the zebra.ppd compiled for 2.1.3 and are using that as a driver in CUPS.  We have played with both the LandscapeOrientation and ParamCustomPageSize Orientation to have the image flip, but the image always comes out upside down.

**Comment by michaelrsweet** [comment]
This was an intentional change - the labels were upside down compared to the other label drivers.
