### ISSUE TITLE
Dot in printer name is displayed in URL-encoded form in Web UI

### ISSUE THREAD

**Issue by mikhailnov** [OpenPrinting/cups#283]
I added a printer named "pbc-builder-rosa2021.1", but it is shown in the Web UI as 'pbc-builder-rosa2021%252E1', dot symbol is URL-encoded

screenshot:
![image](https://user-images.githubusercontent.com/15802528/140671877-202e69d9-5130-44f3-99f2-d495530d05b1.png)

https://localhost:631/printers/pbc-builder-rosa2021%252E1

Printing to it via `lp -d pbc-builder-rosa2021.1` works.

cups-2.3.3op2 (sorry, did not try git master)

**Comment by mikhailnov** [comment]
H, how did I get into such page? I tried to cancal all tasks for the printer there and it failed because there is no such printer. This problem does not happen normally:
![image](https://user-images.githubusercontent.com/15802528/140673729-2598bc54-d53a-4173-9898-e98b63ab1ab1.png)
I wonder how to reproduce it...

**Comment by zdohnal** [comment]
Hi @mikhailnov ,

thank you for reporting the issue!

I haven't been able to reproduce the issue as well (cups-2.3.3op2 nor cups-2.4b1), so let's close the issue until you have a stable reproducer.
