### ISSUE TITLE
cups 2.4.0 renders incorrect HTML

### ISSUE THREAD

**Issue by egore** [OpenPrinting/cups#299]
When accessing http://localhost:631 I only see a white page. The issue seems to be a missing closing bracket in the title-attribute:

    <title>Startseite - CUPS 2.4.0/title>

Version: 2.4.0
Environment: Arch Linux, x86_64

**Comment by zdohnal** [comment]
Hi Christoph,

thank you for reporting the issue!

The closing bracket was accidentally removed in commit b76a97a only in German version of index.html.

Fixed by commit aa250753007
