### ISSUE TITLE
./configure: line 8363: .: filename argument required

### ISSUE THREAD

**Issue by evanmiller** [OpenPrinting/cups#301]
When resolv.h is not found or found to be unusable, these lines error out on Mac OS X 10.4.11:

https://github.com/OpenPrinting/cups/blob/7a7ef6b180a35f64eee12db982a245da69e17574/configure#L8363-L8368

I'm not sure what those lines are supposed to be doing. Any tips appreciated!

**Comment by zdohnal** [comment]
Hi @evanmiller ,

thank you for reporting the issue!

IIUC those lines include the header files which would be included by resolv.h if it was present.

It would be great if you attached your config.log (with .txt suffix) here for examination what exactly went wrong.

Thank you in advance!

**Comment by evanmiller** [comment]
Found the bug (or a bug):

https://github.com/OpenPrinting/cups/blob/7a7ef6b180a35f64eee12db982a245da69e17574/config-scripts/cups-network.m4#L15

Should be a comma, not a period.
