### ISSUE TITLE
Add Xerox Workcentre 3025 driver to the driver database

### ISSUE THREAD

**Issue by d4f5409d** [OpenPrinting/cups#305]
The driver: https://www.support.xerox.com/support/workcentre-3025/downloads/enus.html?operatingSystem=linux&fileLanguage=en

**Comment by zdohnal** [comment]
Hi,

CUPS itself ships only several label printer drivers and generic drivers, the project does not aim to ship other drivers.

On the top of that, drivers are deprecated in CUPS and they will be removed in CUPS 3.0, so we don't plan on adding any new classic driver into CUPS at any case.
