### ISSUE TITLE
jobs lost on submission of large batches of jobs

### ISSUE THREAD

**Issue by vliaskov** [OpenPrinting/cups#308]
SLES15-SP3
cups-2.2.7 or cups-2.3.3

A customer submits large batches of jobs in the background and sees some of the jobs are often lost. 
E.g. submitting 200 jobs on a dummy printer  (created with: lpadmin -p dummy -E -v file:/dev/null)

```
for ((j=1;j<=10;j++)); do for ((i=1;i<=20;i++)); do
	/usr/bin/lpr -P $printer -J000file${i}_${j} -U $user sysqueue$i/* >log${j}_${i} 2>&1 &
done; done
```

(where sysqueue* directories contain pdf files) quite often results in less than 200 jobs being submitted and processed.

When doing an strace on the lpr commands above, I often see -EAGAIN returned for the cups.socket:
```
connect(3, {sa_family=AF_UNIX, sun_path="/run/cups/cups.sock"}, 22) = -1 EAGAIN (Resource temporarily unavailable)
``` 
However, I am not sure this is connected to the lost jobs. I believe -EAGAIN returns happen even for jobs that are actually submitted.

Is there a relevant cupsd config option that was missed? /etc/cups/cupsd.conf includes the following:
```
DefaultPolicy default
MaxLogSize 0
MaxJobs 15000
MaxClients 4096
```
On the other hand, submitting e.g. 100 jobs always results in the expected number of jobs.

Is this a known scalability issue? Any advice on further debugging this issue? 

If that is a known issue solved in newer versions, are there any possibly relevant patches that I can backport from upstream?

**Comment by zdohnal** [comment]
Hi @vliaskov ,

I've tried to reproduce the issue with the latest master (sending 200 jobs -file /etc/fstab via lpr to dummy printer) - every job arrived into cupsd (according logs) and it was completed.

I recommend checking cups debug logs and try to find anything related to the missing jobs - or capturing packet traffic during submitting jobs.

**Comment by frazhome** [comment]
Hello  zdohnal,

I also have such issue.

200 spooljobs where created but 47 got lost
the message is "/usr/bin/lpr: Error - The printer or class does not exist."

I run this test with cups 2.4.2 from suse.
My environment is running a cupsd with a lot of queues (> 3000 Queues).

I also  made a test with the testspeed.c from scheduler-directory.
but this takes really long :-(

I startet with 
scheduler/testspeed -c 50 -r 2
testspeed: Simulating 50 clients with 2 requests to /run/cups/cups.sock with no encryption...
testspeed: Started child 28585...
testspeed: Started child 28586...
testspeed: Started child 28587...
testspeed: Started child 28588...
testspeed: Started child 28589...
testspeed: Started child 28590...
testspeed: Started child 28591...
testspeed: Started child 28592...
testspeed: Started child 28593...
testspeed: Started child 28594...
...
estspeed(28624): 2 requests in 0.0s (0.008s/r, 125.7r/s)
testspeed(28622): 2 requests in 0.0s (0.008s/r, 122.7r/s)
testspeed: Ended child 28624 (0)...
testspeed: Ended child 28622 (0)...
testspeed: 50x2=100 requests in 0.0s (0.000s/r, infr/s)

with three request it got stucked.
testspeed -c 50 -r 3
testspeed: Simulating 50 clients with 3 requests to /run/cups/cups.sock with no encryption...
...
testspeed: Ended child 28702 (0)...
testspeed: 11x3=33 requests in 82.0s (2.485s/r, 0.4r/s)

In my opinoin there is something fundamental broken :-(

regards
Franz

**Comment by zdohnal** [comment]
The possible issue I can think of here is that the listening backlog gets full from too many requests at the same time.

@frazhome are you able to patch CUPS, rebuild and install it for testing? The ```listen()``` function is in ```cups/http-addr.c```:

```
248  /*
249   * Listen...
250   */
251 
252   if (listen(fd, 128))
253   {
254     _cupsSetHTTPError(HTTP_STATUS_ERROR);
255 
256     close(fd);
257 
258     return (-1);
```

Please try raising the second argument to 256 and check if the performance improves.

**Comment by vliaskov** [comment]
@zdohnal we finally have positive feedback from customers facing this issue that using unlimited backlog i.e.:

`if (listen(fd, -1))`

solves the issue for them.

Would this be sufficient feedback for including this change upstream?

Or would you only consider an increased, but still limited, backlog as proposed in the previous comment above (changing `128` to `256`) ?

Let us know.

**Comment by jsmeix** [comment]
@zdohnal 
could you explain why it needs to be limited at all?

What is wrong when there are thousands of requests
on a big print server to let it handle all of them?

Perhaps to avoid possible DOS attacks?
But is that really something which should be implemented
by a hardcoded(!) rather small limit inside cupsd?

**Comment by zdohnal** [comment]
I agree with INT_MAX for backlog parameter - IIUC Mike's response, it will work for Linux and MacOS as well.

It could be a configure option, but it does not seem to matter, since the max will adjusted by the system where cupsd is running and people who would want lower value (users on small local networks) might not care.

**Comment by rma-x** [comment]
FYI, these days Linux also defines (in `/usr/include/bits/socket.h`):
```
/* Maximum queue length specifiable by listen.  */
#define SOMAXCONN       4096
```
I am not sure when this was introduced and how portable it is, but it could be used as a default, if present, with fallback to INT_MAX.

**Comment by michaelrsweet** [comment]
@rma-x The problem with `SOMAXCONN` is that it doesn't account for the kernel configuration parameter or default kernel value (which might be different from the glibc build you are using...)

Using `INT_MAX` asks for the maximum allowed by the kernel.
