### ISSUE TITLE
A potential data race error on g.read_thread_stop?

### ISSUE THREAD

**Issue by ryancaicse** [OpenPrinting/cups#309]
In the method `print_device`, creating a thread `read_thread`
https://github.com/OpenPrinting/cups/blob/495c524f0fd6d28e36c50eda39adbf8db4faf708/backend/usb-libusb.c#L313-L320

In the thread `read_thread`, accessing g.read_thread_stop without locking
https://github.com/OpenPrinting/cups/blob/3b3d904121ffe992db65cbbe0b4df5f2514d7701/backend/usb-darwin.c#L961-L964

In the method `print_device`, accessing g.read_thread_stop without locking
https://github.com/OpenPrinting/cups/blob/3b3d904121ffe992db65cbbe0b4df5f2514d7701/backend/usb-darwin.c#L829-L831

**Comment by michaelrsweet** [comment]
@ryancaicse Because `read_thread_stop` is an `int`, it will be atomically read or written on any 32+ bit processor and is so is safe to test/set without using the mutex. We'd only need to use the mutex if we were doing a non-atomic calculation (like incrementing it).

**Comment by ryancaicse** [comment]
@michaelrsweet Thank you for your answers.
