### ISSUE TITLE
EPSON_AL-M2300 margin drift

### ISSUE THREAD

**Issue by recip** [OpenPrinting/cups#312]
The left margin drifts by 10+ mm from page to page while printing. Every new job starts magrin in the right place. 
The source of printing makes no difference.
System is Debian v.11.1, all components are uptodate.
An example CUPS log is attached.
[error_log.gz](https://github.com/OpenPrinting/cups/files/7744936/error_log.gz)

**Comment by zdohnal** [comment]
Hi @recip ,

thank you for reporting the issue! The current CUPS upstream version is 2.4.0, so it would be great if you contacted Debian support for more debugging.

I don't have the device myself, so I've checked the outputs from filters used for the driver where I could - the filters used are pdftopdf and foomatic-rip. pdftopdf output looks ok, foomatic-rip calls pdftops filter and renderer gs (ghostscript). Postscript file from pdftops looks fine, so there can an issue in renderer, which produces a binary file and I don't know a correct viewer to check whether the output is correct.
