### ISSUE TITLE
About the installation of MacOS print driver

### ISSUE THREAD

**Issue by Guozht** [OpenPrinting/cups#318]
1. After I install the print filter (/usr/libexec/cups/filter) and PPD file (/library/printers/PPDs), how can I search and display my print driver in the window of adding printer in the system? Is my path correct?
2. After adding relevant information about ICA scanning driver in PPD file, my scanning device cannot be displayed in image capture. What is the deployment and installation of ICA device?

**Comment by michaelrsweet** [comment]
@Guozht Apple is your best bet for support on macOS.
