### ISSUE TITLE
Unknown Operation "purge-jobs"! on class page when canceling jobs

### ISSUE THREAD

**Issue by tielur** [OpenPrinting/cups#325]
When trying to use the `Cancel All Jobs` on the class page, I get a `Unknown Operation "purge-jobs"!` error. I noticed in this commit https://github.com/OpenPrinting/cups/commit/96be8b6c6eee221df6820e2a6fd3f068223aa911 that everything that was `purge-jobs` was changed to `cancel-jobs`. Is this something that needs to be changed in the [class.tmpl](https://github.com/OpenPrinting/cups/blob/master/templates/class.tmpl#L14) as well?

**Comment by tielur** [comment]
If the answer to the above is "yes" I'm more then happy to open a PR

**Comment by zdohnal** [comment]
Hi @tielur ,

thank you for reporting the issue and good catch! Yes, it is a leftover after the change, the option in class.tmpl should be ```cancel-jobs```.

I've applied the changes in commit 2ff120a.

**Comment by tielur** [comment]
Awesome! Thanks
