### ISSUE TITLE
No Drivers for Samsung SCX Series on Fedora Linux

### ISSUE THREAD

**Issue by mahyarmirrashed** [OpenPrinting/cups#330]
There is an issue where some of the Samsung drivers are missing on Fedora Linux. Specifically, it seems like all the SCX #### Series drivers are missing. They are, however, available on HP's website: https://support.hp.com/ca-en/drivers/selfservice/swdetails/samsung-scx-4623-laser-multifunction-printer-series/17157060/swItemId/fp-191129-2

I was told to report this to the CUPS developers.

**Comment by debiantriage** [comment]
> The Unified Linux Driver is a unified driver package that includes all of the drivers for Samsung printers and scanners for Linux.

The ULD package is non-free . Debian would not distribute it. Neither, I think, would Fedora.

The issue is one for the distributions, not CUPS.

**Comment by zdohnal** [comment]
Hi,

CUPS is not meant to ship all drivers and regarding driver's packaging it is as Brian said - the project is non-free, so no open-source OS would distribute it in their official free repositories.
