### ISSUE TITLE
Add TSPL support to rastertolabel

### ISSUE THREAD

**Issue by GravisZro** [OpenPrinting/cups#331]
I would like to see the `rastertolabel` filter add support for TSPL.  Yes, TSC invented TSPL then expanded it to TSPL2 and put out a [massive manual](https://kubesail.com/blog-images/blog-printer-tspl.pdf) but very little is needed since TSPL has a `BITMAP` command.  Other companies [use TSPL and have manuals](https://www.meto.com/metoprint/files/meto_print_programming_manual_tspl_ez_en.pdf) which may mean they are using TSC components.

Someone actually wrote an [image to TSPL converter in javascript](https://github.com/kubesail/raster-to-tspl-js/blob/main/print.js) but it's really just sending this:
```
\r\nSIZE `label width` mm, `label height` mm
\r\nSET TEAR ON
\r\nSET CUTTER OFF
\r\nSET PEEL OFF
\r\nDENSITY `darkness`
\r\nCLS
\r\nBITMAP 0,0,`bitmap width`,`bitmap height`,1, `1-bit image data`
\r\nPRINT 1,1
\r\n
```

If you _really_ wanted, you could send a raw raster data and make a program in TSPL to decode it.  However, I'm pretty sure that could be done with ZPL and you didn't.

**Comment by michaelrsweet** [comment]
@GravisZro We are not expanding the sample drivers bundled with CUPS - the future of CUPS is in printer applications and IPP Everywhere compatible printers.

For rastertolabel, the logical replacement is my [LPrint printer application](https://github.com/michaelrsweet/lprint).

**Comment by GravisZro** [comment]
Does LPrint make the label printers available through CUPS or do applications need to use it specifically?

**Comment by michaelrsweet** [comment]
@GravisZro LPrint makes it available as an IPP Everywhere printer for CUPS or any other IPP client. (plus the command-line interface for printing directly)
