### ISSUE TITLE
add support for Epson ET-2720 series

### ISSUE THREAD

**Issue by bryanpedini** [OpenPrinting/cups#332]
Hi 👋🏻 (newcomer here)

Don't know if it's acceptable in this new community I'm diving into, but I would like to make a feature request for my Epson ET-2721 that I would like to setup wirelessly with a real working setup (not the wireless functions of the printer itself, but with a Raspberry Pi 3 b+).
I would also like to contribute as much as possible for what little I know about C or drivers, tho I physically have the printer for testing.

If this is not the right place I ask for forgiveness and clarification on where to start to add a new supported printer (where to file an issue, where to start debugging, etc).

Thank you in advance for this awesome piece of FOSS software already,
Bryan.

**Comment by michaelrsweet** [comment]
@bryanpedini This printer supports AirPrint, so it will work with the IPP Everywhere ("-m everywhere") driver.

**Comment by bryanpedini** [comment]
Ya? Didn't know, thank you a lot for the info.
Perhaps we could add it to the [list of supported printers](https://www.openprinting.org/printers)?

**Comment by tillkamppeter** [comment]
We will not add driverless IPP printers (AirPrint, Mopria, IPP Everywhere, Wi-Fi Direct Print) to the [OpenPrinting database](https://openprinting.org/printers), as it is a tedious work which will not be of much help. Non-driverless printers are ether legacy or specialty printers, so will get to be more and more a minority under all printers around, and the standard way to go is simply connect the printer and start printing.

What we should do is prominently tell on our front page [GitHub repo for static part of the site](https://github.com/OpenPrinting/openprinting.github.io) and at the top of the printers page [GitHub repo for our database web app](https://github.com/OpenPrinting/foomatic-db-webapp) that most printers are driverless IPP and also how to check when buying. We also need to tell on the printers page that we only list non-driverless printers (but driverless ones could have slipped in, so being in the list does not need "requires a driver").
