### ISSUE TITLE
Can i view documents on web interface or command line?

### ISSUE THREAD

**Issue by alprde** [OpenPrinting/cups#336]
Can i view documents on web interface or command line? /var/spool/cups directory is not useful for me.

**Comment by zdohnal** [comment]
Hi @alprde ,

CUPS is not meant to be a document viewer, so no such functionality is in CUPS itself or it is planned. FYI /var/spool/cups contains documents which are sent by applications to CUPS, not the printed documents.
Viewing those documents in /var/spool/cups is not needed in common usage - you usually view them only when you debug problems with printed documents, so IMO it is fine to copy the file somewhere, change ownership and view with classic document viewers.

**Comment by alprde** [comment]
Thank you for the answer. I am developing a web interface that works with cups for the company I work for. In this application, I connect to the cups server remotely with cups-client and run terminal commands (like lpstat). That's why I want to check which files the users are printing on the application I've developed and whether there is anything harmful in its content.
