### ISSUE TITLE
Misalignment of programming document in cups web interface 

### ISSUE THREAD

**Issue by Chandresh2702** [OpenPrinting/cups#344]
The programming manual portion of cups in the web interface has some misalignment, making certain pages difficult to read.

![Screenshot from 2022-03-02 17-51-30](https://user-images.githubusercontent.com/75661901/156361603-93cadbb0-787b-4120-a290-8b7af6e95924.png)
![Screenshot from 2022-03-02 17-51-33](https://user-images.githubusercontent.com/75661901/156361610-61e73bda-b57d-43d5-8dff-7c79d7d27608.png)
![Screenshot from 2022-03-02 17-51-41](https://user-images.githubusercontent.com/75661901/156361615-2db94b63-eced-4fef-90c5-b03e54a94165.png)
![Screenshot from 2022-03-02 17-51-47](https://user-images.githubusercontent.com/75661901/156361621-5076d657-8cd6-4980-89a8-e993f3755a38.png)
![Screenshot from 2022-03-02 17-51-52](https://user-images.githubusercontent.com/75661901/156361625-29c9bf4f-83ae-4630-8b86-10472a6e78a1.png)
![Screenshot from 2022-03-02 17-51-58](https://user-images.githubusercontent.com/75661901/156361626-069d686f-f610-40cc-9ee2-3e6fd5208127.png)

These help documents are also available on the openprinting website, where they function properly; however, in the cups web interface, the header clashes with the header of the html file, resulting in the overflow.

I can open a PR to resolve this issue in some time.

**Comment by zdohnal** [comment]
Hi @Chandresh2702 ,

thank you for reporting the issue!

Unfortunately, I don't see any issue which you've captured by your screenshots (Fedora 35, cups-2.3.3op2). What CUPS version do you have and what Firefox version do you use?

Maybe even cookies or browser plugins/script can IMHO influence this, so it would be great if you tried it in clean Firefox without plugins and cookies.

**Comment by Chandresh2702** [comment]
@zdohnal  i tried after cleaning all data of my firefox but problem is still there.

**Comment by jsmeix** [comment]
I also experience since some longer time that the actual content
is placed where some kind of header and footer is (example below)
or even that some header and footer is placed over the actual content
(right now I found no example for the latter).

E.g. currently on my openSUSE Leap 15.3 system with Firefox
`https://openprinting.github.io/cups/doc/man-cancel.html`
shows as last readable line in the content area
(left aligned on white background)
```
Copyright © 2021 by OpenPrinting. 
```
while the actually two more lines of content
```
                Copyright © 2020-2021 OpenPrinting.    CUPS License
```
are shown in some kind of footer area
(centered on gray background)
where it is not visible that "CUPS License" is a link
(except one hovers the mouse pointer over it).

For comparison
`w3m -dump https://openprinting.github.io/cups/doc/man-cancel.html | less`
shows as last lines
```
Copyright © 2021 by OpenPrinting.
Copyright © 2020-2021 OpenPrinting.

  • CUPS License
```

**Comment by Chandresh2702** [comment]
@zdohnal I think this issue is created after the release of 2.3.3op2 as i inspected those files which are affected and they had gone under some changes after that could you please try one creating this issue with newer version of cups.

**Comment by zdohnal** [comment]
@Chandresh2702 thank you, you're absolutely right! I'm able to reproduce the issue with the latest 2.4.1. I'll look into it tomorrow, if you're able, PRs are always welcome! :)

@jsmeix thanks for the tips! To be honest, I'm not quite sure how CUPS pages on the OpenPrinting site are generated... I'll ask Mike in the future.

**Comment by Chandresh2702** [comment]
@zdohnal I have opened a PR addressing this issue could you review it once. thanks you :)

here are some of screenshots after code change.
![Screenshot from 2022-03-02 18-14-16](https://user-images.githubusercontent.com/75661901/156486818-4007ee38-3c30-4414-8b7b-06f38b3a477f.png)
![Screenshot from 2022-03-02 18-14-19](https://user-images.githubusercontent.com/75661901/156486834-6131fe24-9eae-4fe7-8bb3-483d6d12735f.png)
![Screenshot from 2022-03-02 18-14-25](https://user-images.githubusercontent.com/75661901/156486841-f5a5ca6a-8955-475c-a774-4e50db74481c.png)
![Screenshot from 2022-03-02 18-14-28](https://user-images.githubusercontent.com/75661901/156486846-21c33986-b65f-4fef-97ae-76cb1693074d.png)
![Screenshot from 2022-03-02 18-14-30](https://user-images.githubusercontent.com/75661901/156486849-768863da-ca73-4f50-8478-87b508841ce7.png)
![Screenshot from 2022-03-02 18-14-35](https://user-images.githubusercontent.com/75661901/156486852-d04e0d11-66db-46d3-b817-c3605d83302e.png)
![Screenshot from 2022-03-02 18-14-37](https://user-images.githubusercontent.com/75661901/156486855-55b12a09-0586-4d62-b734-fd676b5cf7c5.png)
 
Please let me know if there is anything further that needs to be done in this regard.

**Comment by zdohnal** [comment]
Fixed by https://github.com/OpenPrinting/cups/commit/77bcfb2b16ec25f5439ed92d53b5a3d09e36539f
