### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by VorpalBlade** [OpenPrinting/cups#348]
The readme at https://github.com/OpenPrinting/cups has the following section:

> [...] we provide a mailing list for CUPS users and developers to ask questions and discuss issues at https://linuxfoundation.groups.io/g/printing.

That link is broken and redirects to https://linuxfoundation.groups.io/static/groupnotfound

**Comment by VorpalBlade** [comment]
NB: I discovered this while I was trying to find an appropriate location to ask a question about the future of legacy corporate network printers that do not support IPP, since apparently lpd:// + PPDs will be phased out in the future, I'm wondering how I will be able to print at my university in the future, since Linux is not officially supported there (only the comp-sci deparement use it), and all we got (after much complaining) was an lpd URI and a PPD. Getting IPP Everywhere set up there seems like an ordeal and likely unsuccessful or at least time consuming.

**Comment by michaelrsweet** [comment]
@tillkamppeter Can we get this printing group created? I requested it over a year ago but haven't heard back from the LinuxFoundation folks...

**Comment by tillkamppeter** [comment]
I can try to contact the guys at the Linux Foundation, but could we perhaps create something in the OpenPrinting GitHub, as there we could do the admin by ourselves?

**Comment by michaelrsweet** [comment]
@tillkamppeter Github doesn't offer mailing lists, just ["discussions"](https://github.com/OpenPrinting/cups/discussions) which require a Github account. Similarly, Google Groups (something I also looked into) requires a Google account (doesn't have to be a gmail.com account but you do need to have a Google login associated with your email).

Most users don't have Github accounts. Some have Google accounts. But with a mailing list they just need to sign up for the mailing list to go to their email, and OpenPrinting is part of the Linux Foundation which already has infrastructure for this stuff...

**Comment by tillkamppeter** [comment]
@michaelrsweet who was your contact at the LF to ask for the list(s) getting created? Can you forward to me the e-mail(s) you sent?

**Comment by michaelrsweet** [comment]
@tillkamppeter Hopefully you got my email - tried once and it bounced. Jeff Licquia and Eric Searcy were on the message thread.

**Comment by michaelrsweet** [comment]
@tillkamppeter Any updates on this?

**Comment by tillkamppeter** [comment]
Sorry, I was very busy with the [Linux App Summit 2022](https://conf.linuxappsummit.org/event/4/overview) and came back today.

I have sent a mail to Jeff and Eric now, you CCed.

**Comment by tillkamppeter** [comment]
We generally do not get any IT resource support from the LF as long as we are not a full-fledged workgroup with budget, governance, ... We could use the GitHub "Discussions" platforms of OP projects. Perhaps we could also ask osuosl.org for whether they could put a mailing list server onto our lookup serer ...
