### ISSUE TITLE
does not read hp LaserJet cp1025nw printer on rosa r12

### ISSUE THREAD

**Issue by saber716rus** [OpenPrinting/cups#355]
Hello. The problem is that the cp1025nw printer does not print. I opened the jar, but the attendants could not help. https://bugzilla.rosalinux.ru/show_bug.cgi?id=11570

**Comment by zdohnal** [comment]
Hi @saber716rus ,

it would be great if you turned on CUPS debug logging:

```
$ cupsctl --debug-logging
```

tried to print and attached CUPS error_log here with .txt suffix.

Thank you in advance!

**Comment by saber716rus** [comment]
[error_log.zip](https://github.com/OpenPrinting/cups/files/8352466/error_log.zip)
made a log.

**Comment by zdohnal** [comment]
There is an error coming from the ```foo2xqx``` driver, which supports the device:

```
D [25/Mar/2022:19:40:46 +0300] [Job 1] Not a pbm file!
```

the filter exits after reporting the error, so the resulting file is not properly converted to the format the device expects - looks like a driver issue.

**Comment by saber716rus** [comment]
> There is an error coming from the `foo2xqx` driver, which supports the device:
> 
> ```
> D [25/Mar/2022:19:40:46 +0300] [Job 1] Not a pbm file!
> ```
> 
> the filter exits after reporting the error, so the resulting file is not properly converted to the format the device expects - looks like a driver issue.
> 
> Please report the issue to your driver provider.
Unfortunately, I have no one to go to. There is no connection with the developer.

**Comment by Pro-pra** [comment]
hmm, i not see in log who generate pbm file :(  

i not see in log foo2xqx! used foo2zjs-wrapper

**Comment by saber716rus** [comment]
The foo2zjs driver is usedhttps://abf.io/import/cups-drivers-foo2zjs06:32, 30 марта 2022 г., "Pro-pra" ***@***.***>:
hmm, i not see in log who generate pbm file :(
i not see in log foo2xqx! used foo2zjs-wrapper

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
С Уважением, Николай.Специалист IT-систем.+79625490833 (whatsapp)telegram: https://t.me/Saber716RUSinstagram: @saber716russkype: nicksab1491

**Comment by zdohnal** [comment]
foo2xqx is the driver provided by foo2zjs project and it supports the printer in question - I haven't got that deep in foo2zjs, but IMO foo2zjs-wrapper starts foo2xqx at some point.

The error about accepted file is not a pbm file can be spawn from several different filters from foo2zjs project, but since the model is supported by foo2xqx from foo2zjs, I've made my bet on foo2xqx generating the error.

**Comment by Pro-pra** [comment]
use old version of foo2zjs-20150211 fix problem.

**Comment by saber716rus** [comment]
And so he did. 04.04.2022, 03:59, "Pro-pra" ***@***.***>: use old version of foo2zjs-20150211 fix problem.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>  -- with respect,Nikolai Sabelnikov+79625490833 (cell and Whatsapp)telegram: https://t.me/Saber716RUSskype:nicksab1491instagramm: @saber716rus
