### ISSUE TITLE
Can i add signature?

### ISSUE THREAD

**Issue by alprde** [OpenPrinting/cups#358]
Can I print time information, user information or a special message at the bottom of each printed page?

**Comment by michaelrsweet** [comment]
@alprde Not directly, although perhaps solutions like PaperCut might be able to do so?

**Comment by michaelrsweet** [comment]
@alprde A CUPS filter *could* do this, but at present none of the bundled filters do.

**Comment by alprde** [comment]
> @alprde A CUPS filter _could_ do this, but at present none of the bundled filters do.

So can i write a custom filter and activate it? I tried several methods but it didn't work.

**Comment by michaelrsweet** [comment]
@alprde Which methods did you try? Pykota and other accounting solutions use a custom backend to intercept all print data.

**Comment by jsmeix** [comment]
@alprde 
if you intend to write a custom filter you may have a look at
this article which is rather old so some details are outdated
but the general ideas should be still vaild for CUPS 2.x:
https://en.opensuse.org/SDB:Using_Your_Own_Filters_to_Print_with_CUPS

To add a special message at the bottom of each printed page
I would insert a custom filter where the data format is known.
Nowadays the original print job data is first converted into PDF
(in contrast to the article that describes the traditional way
where original print job data was first converted into PostScript).
So I would insert a custom filter after the filter that made the PDF.
I think the custom filter would have to change its input PDF
to get the needed free space the bottom of the page
(i.e. scale the page content it a bit down and move it a bit up)
and then add the special message there as PDF text
or alternatively the custom filter may print the special message
simply over what there might be already in the PDF.
So you would need a PDF manipulating program that can do this
play around with it until you understand how it behaves with PDFs
and then call that program (with appropriate options) as custom filter.

**Comment by alprde** [comment]
I added a banner, but I decided that this is not the method I want. Then I tried to call the custom filter I created by adding this code `*cupsFilter: "application/vnd.cups-postscript 100 customfilter"` to the ppd file of the printer, but it didn't work. 

/usr/lib/cups/filter/customfilter

`#! /bin/bash
echo -en "TEST"`

Links I used:

[http://technik.blogs.nde.ag/2012/08/28/watermarking-printouts-in-the-linux-world/](url)
[https://stackoverflow.com/a/11194723/11497642](url)

**Comment by alprde** [comment]
> @alprde if you intend to write a custom filter you may have a look at this article which is rather old so some details are outdated but the general ideas should be still vaild for CUPS 2.x: https://en.opensuse.org/SDB:Using_Your_Own_Filters_to_Print_with_CUPS
> 
> To add a special message at the bottom of each printed page I would insert a custom filter where the data format is known. Nowadays the original print job data is first converted into PDF (in contrast to the article that describes the traditional way where original print job data was first converted into PostScript). So I would insert a custom filter after the filter that made the PDF. I think the custom filter would have to change its input PDF to get the needed free space the bottom of the page (i.e. scale the page content it a bit down and move it a bit up) and then add the special message there as PDF text or alternatively the custom filter may print the special message simply over what there might be already in the PDF. So you would need a PDF manipulating program that can do this play around with it until you understand how it bejhaves with PDFs and then call that program (with appropriate options) as custom filter.

I've looked at this link before, but I couldn't. The main problem is that I have little experience with cups, how should I write the filter, which folder should I add it to and how should I call the filter? I don't know them and I need to learn them.

**Comment by Naishuang** [comment]
Hi @alprde  , I have a similar task as your question mentioned. Have you resolved it? Please share to me. Thanks!
