### ISSUE TITLE
"lp -o sides=two-sided-long-edge" prints one-sided

### ISSUE THREAD

**Issue by debiantriage** [OpenPrinting/cups#359]
Debian user Rick Stanley has an HP LaserJet Plus Pro M148fdw and has submitted [this bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008175). The essence is that `lp -o sides=two-sided-long-edge test.pdf` always prints single-sided. An error_log has

>  Unable to do two-sided printing, setting sides to \'one-sided\'.

-- 
Brian.

**Comment by debiantriage** [comment]
The user supplied the printer attributes.
[M148fdw-attributes.txt](https://github.com/OpenPrinting/cups/files/8362522/M148fdw-attributes.txt)

**Comment by michaelrsweet** [comment]
... and the error_log doesn't seem to be attached to the original bug report? It would be helpful to see since it should contain a copy of the attributes and values from the Validate-Job operation that triggered this.

**Comment by zdohnal** [comment]
@michaelrsweet there is ```error.7z``` archive in the original report IIUC.

**Comment by zdohnal** [comment]
From get-printer-attributes response:

```
sides-supported (1setOf keyword) = one-sided,two-sided-short-edge,two-sided-long-edge
```

but from Validate-Job during printing:

IPP Validate-Job request:
```
2199 D [27/Mar/2022:10:44:35 -0400] [Job 238] ---- job-attributes-tag ----
2200 D [27/Mar/2022:10:44:35 -0400] [Job 238] output-bin keyword face-down
2201 D [27/Mar/2022:10:44:35 -0400] [Job 238] print-color-mode keyword auto-monochrome
2202 D [27/Mar/2022:10:44:35 -0400] [Job 238] print-quality enum normal
2203 D [27/Mar/2022:10:44:35 -0400] [Job 238] sides keyword two-sided-long-edge
```

IPP Validate-Job response:
```
2299 D [27/Mar/2022:10:44:36 -0400] [Job 238] Validate-Job: successful-ok-ignored-or-substituted-attributes (successful-ok-ignored-or-substituted-attributes)
2300 D [27/Mar/2022:10:44:36 -0400] [Job 238] ---- operation-attributes-tag ----
2301 D [27/Mar/2022:10:44:36 -0400] [Job 238] attributes-charset charset utf-8
2302 D [27/Mar/2022:10:44:36 -0400] [Job 238] attributes-natural-language naturalLanguage en
2303 D [27/Mar/2022:10:44:36 -0400] [Job 238] ---- unsupported-attributes-tag ----
2304 D [27/Mar/2022:10:44:36 -0400] [Job 238] sides keyword two-sided-long-edge
2305 D [27/Mar/2022:10:44:36 -0400] [Job 238] ---- end-of-attributes-tag ----
```

Based on this the backend switches to one-sided:

```
2320 D [27/Mar/2022:10:44:36 -0400] [Job 238] ---- job-attributes-tag ----
2321 D [27/Mar/2022:10:44:36 -0400] [Job 238] output-bin keyword face-down
2322 D [27/Mar/2022:10:44:36 -0400] [Job 238] print-color-mode keyword auto-monochrome
2323 D [27/Mar/2022:10:44:36 -0400] [Job 238] print-quality enum normal
2324 D [27/Mar/2022:10:44:36 -0400] [Job 238] sides keyword one-sided
```


@michaelrsweet  Looks like a printer bug?

**Comment by debiantriage** [comment]
The user supplied a log in the course of the conversation when it was requested. I attach it here.

[error_log.txt](https://github.com/OpenPrinting/cups/files/8363257/error_log.txt)

**Comment by zdohnal** [comment]
@debiantriage no problem, I've attached the same file some comments above.

**Comment by michaelrsweet** [comment]
@zdohnal Looks like it, yes. Probably a firmware update triggered the issue... :(

**Comment by zdohnal** [comment]
@debiantriage we're sorry, but the issue looks like a firmware bug - the printer reports it supports the duplex, but returns the IPP attribute as unsupported during IPP Validate-Job, which causes the switch to single sided setup.

It would be great if the user reported the issue to manufacturer and asked them for firmware update.

**Comment by Scotsgeek** [comment]
I have updated the firmware in the printer, and the issue remains.  Will contact HP.  It used to work with the old firmware, but then stopped a few months ago.

**Comment by Scotsgeek** [comment]
Problem solved.  Please ignore my previous reply.

Thanks all!

**Comment by Scotsgeek** [comment]
One more comment:

Using "HP LaserJet Pro M148f-M149f, driverless, cups-filters 1.28.7" it will NOT print two-sided, and tends to jam up the print queue.  I sometime have to force the print job in the queue.

Using "HP LaserJet Pro M148-M149 Postscript (recommended)", it does print two-sided, and does not jam the print queue.

Please look at the "Driverless cups-filters"

Thank you!
