### ISSUE TITLE
2 inch cuts

### ISSUE THREAD

**Issue by armando-ca** [OpenPrinting/cups#361]
Hi, 

Is there a way to program a default setting in cops to make 2 inch cuts on a DNP-DS-RXI? 2 inch cuts is available in windows 10. I just don't know how to set it up in cops.

**Comment by zdohnal** [comment]
Hi @armando-ca ,

it depends on how you install the printer in CUPS and whether printer is able to advertise its features via IPP or whether the driver you are using can do it.

How is the printer connected? What driver are you using?

**Comment by michaelrsweet** [comment]
Closing for lack of response.
