### ISSUE TITLE
How to know the maximum accepted length for a job title?

### ISSUE THREAD

**Issue by tsdgeos** [OpenPrinting/cups#367]
In Okular we are using "-J document_title" when printing.

In https://bugs.kde.org/show_bug.cgi?id=452339 seems to say that 100 characters is the max length this user can have for a print job title.

In https://bugs.kde.org/show_bug.cgi?id=326617 (a few years ago) we thought to have found that the limit was 255.

Is this limit in cups? or is it in the printer driver/somewhere else? If it is in cups, is there a way for us to query it programatically?

**Comment by michaelrsweet** [comment]
@tsdgeos The maximum length of the "job-name" attribute (which holds the job title string) is 255 octets (bytes). It's an IPP limit and not something we can change...

**Comment by tsdgeos** [comment]
Thanks, so we're doing it right, I wonder why that person says that it fails for them at 100 :shrug:
