### ISSUE TITLE
Update or remove Solaris scheduler/cups.xml.in

### ISSUE THREAD

**Issue by l1gi** [OpenPrinting/cups#368]
Hi,

could I ask you to update Solaris related cups/scheduler service manifest (scheduler/cups.xml.in) or is it better for you to remove the file completely? Attached is a patch to OpenPrinting version and complete file.

Regards, --m.
[patch.txt](https://github.com/OpenPrinting/cups/files/8440316/patch.txt)
[cups.xml.in.txt](https://github.com/OpenPrinting/cups/files/8440319/cups.xml.in.txt)

**Comment by michaelrsweet** [comment]
[master 0c1bbc5eb] Update Solaris smf file (Issue #368)
