### ISSUE TITLE
From cups-2.4b1, lpoptions fails to read the options "number-up" & "job-sheets"

### ISSUE THREAD

**Issue by tangyanli** [OpenPrinting/cups#370]
This issue is found on Fedora36 with cups-2.4.1
I investigated a bit, this issue happens from cups-2.4b1 after fixing https://github.com/OpenPrinting/cups/issues/71.

Reproduce step
(1) Call lpoptions to set the options "number-up" and "job-sheets"
$lpoptions -p PrinterName -o number-up=4 -o job-sheets=classified,classified
(2) Call lpoptions to display the options
$lpoptions -p PrinterName

Check the displayed options, the value of "number-up" is "1"; the value of "job-sheets" is "none,none"

**Comment by michaelrsweet** [comment]
Replicated the issue, investigating...

**Comment by tangyanli** [comment]
Tested, the issue is fixed.
Thanks.
