### ISSUE TITLE
CUPS can hold for authentication jobs on printers without `auth-info-required` attribute

### ISSUE THREAD

**Issue by EliaGeretto** [OpenPrinting/cups#373]
In my specific instance, this happens when an SMB printer that requires authentication does not have the `auth-info-required` attribute. When trying to print with it, the backend (`smbspool`) will exit with `CUPS_BACKEND_AUTH_REQUIRED`, leading to the following snippet of code, which holds the job for authentication: https://github.com/OpenPrinting/cups/blob/3a1a81d7b882c06451a39a19a87aca7ec44742e6/scheduler/job.c#L3458-L3474

Since the printer does not have an `auth-info-required` attribute specified, though, the UIs in `gnome-control-center` and`system-config-printer` (but I suspect other interfaces as well) break, because they cannot provide an authentication prompt given that CUPS replies that no authentication is needed. The job can, at that point, only be cancelled manually despite the "Job held for authentication" message.

Given that receiving a  `CUPS_BACKEND_AUTH_REQUIRED` exit code from the backend while having no `auth-info-required` on the printer is a clear sign of misconfiguration, I suspect that, in this situation, an error should be either printed in the logs or shown to the user. At the moment, no clear indication of a misconfiguration seems to be present.

**Comment by michaelrsweet** [comment]
@EliaGeretto So this sounds like a Samba bug - the backend should be sending the appropriate message to stderr when authentication is needed:

```
ATTR: auth-info-required=username,password
ATTR: auth-info-required=negotiate
```

In the meantime you can use the `lpadmin` command to tell GNOME what kind of authentication is required:

```
lpadmin -p PRINTER -o auth-info-required=username,password  (for username + password)
lpadmin -p PRINTER -o auth-info-required=negotiate          (for Kerberos)
```

**Comment by EliaGeretto** [comment]
So, just to clarify, you are supposed to be able to add a printer without specifying if it needs authentication and then the backend is responsible to tell CUPS what authentication info is needed? If that is the case, then I should report the bug to samba, indeed.

As for the workaround, I edited manually `/etc/cups/printers.conf` and added the appropriate `AuthInfoRequired` line there.

**Comment by EliaGeretto** [comment]
I have just tried to execute `smbspool`, is this the correct behavior?
AUTH_INFO_REQUIRED=none smbspool 'smb://printing.vu.nl/VU_Ricoh_Color_Printer' test test 1 1 /tmp/test.txt
ERROR: Session setup failed: NT_STATUS_ACCESS_DENIED
DEBUG: get_exit_code(nt_status=NT_STATUS_ACCESS_DENIED [c0000022])
ATTR: auth-info-required=none
DEBUG: Unable to connect to CIFS host: NT_STATUS_ACCESS_DENIED%

**Comment by michaelrsweet** [comment]
@EliaGeretto Yes, it is a Samba bug.

**Comment by EliaGeretto** [comment]
I gave another look at the logs and what is shown in the snippet above is indeed the problem. Since no `auth-info-required` is specified when adding the printer, CUPS will invoke `smbspool` with `AUTH_INFO_REQUIRED=none`. `smbspool` exits with the correct code, `CUPS_BACKEND_AUTH_REQUIRED`, but echoes back the `auth-info-required` attribute that was passed in instead of specifying which authentication information is required. I will report this to samba then, let me know if I made a mistake in my summary.

Regarding this issue, I still think it would be nice to check if a backend returning `CUPS_BACKEND_AUTH_REQUIRED` actually specifies which information is required for authentication. A nice error log reporting a possible bug in the backend would have made this easier to debug. In addition, maybe marking the job as failed in such a situation could be a better than holding it indefinitely. At this point, though, this is more of a feature request than a bug report. Let me know what you think.

**Comment by EliaGeretto** [comment]
I have reported the samba bug. See: https://bugzilla.samba.org/show_bug.cgi?id=15057

**Comment by michaelrsweet** [comment]
@EliaGeretto Another option is to force username,password if auth-info-required is none...

**Comment by michaelrsweet** [comment]
[master f4e8437dd] Set default auth-info-required='username,password' if a backend doesn't set an authentication method (Issue #373)

**Comment by michaelrsweet** [comment]
@EliaGeretto In those cases, the fix I made wouldn't be any worse - the default (none) would be replaced by username,password if the backend doesn't set one. But if you need Kerberos (negotiate) you just need to use lpadmin to change the default (`lpadmin -p PRINTER -o auth-info-required=negotiate`)

**Comment by EliaGeretto** [comment]
Fair, it's true that setting it to `username,password` by default when there is a bug in the backend will at least make it work in some cases. Still, when some other kind of authentication is required, users will now be shown a username and password authentication dialog that is unrelated to what they need. I don't know, I would have probably gone with logging an error as well, but you have definitely more experience here and this fixes my problem :+1:
