### ISSUE TITLE
Pausing issue between jobs while print few jobs consecutively 

### ISSUE THREAD

**Issue by skapas** [OpenPrinting/cups#377]
Hi,
I am from Lexmark driver development team. We have found an issue while printing through USB. The issue is while few consecutive few jobs are triggered through USB, we are getting 4-5 seconds pause between jobs. From our firmware log we came to know CUPS is trying to open/close connection for each job. Found some of thread containing this type issue and few workaround also. We have tried those but still encountering some problems. Detail is given below.

Workaround 1
===========
lpadmin -p <printer> -o usb-unidir-default=true

Observation - Performance increased but data loss happened. Within 10 consecutive jobs, only 6/7/8 jobs are getting printed.

Workaround 2
===========
lpadmin -p <printer> -R usb-unidir-default
and then
lpadmin -p <printer> -o usb-no-reattach-default=true

Observation - There is no improvement in performance but no data loss. 

Workaround 3
===========
lpadmin -p <printer> -o usb-no-reattach-default=true
and then
lpadmin -p <printer> -o usb-unidir-default=true

Observation - Performance increased and data loss also happened but less than in "Workaround 1" i.e most of the time 8/9/10 jobs are getting printed.

Please help as it is tagged with an urgent release.

Thanks & Regards,
Saptarshi

**Comment by michaelrsweet** [comment]
@skapas What version of CUPS? There *was* a USB performance issue introduced in CUPS 2.2.12 that was reverted in CUPS 2.4.

What models of printers (and their USB product IDs)? There are many Lexmark printers already listed in the USB quirks file shipped with CUPS...

**Comment by skapas** [comment]
Thanks for the information. We are using CUPS version 2.3.1 in ubuntu ARM 20.04. We will check whether the issue exists in CUPS 2.4.2 and let you inform the status.
Currently we are using PID=0x0260. Forget to mention earlier, we have also modified the quirks file manually by adding the line "0x043d 0x0260 unidir" and found performance increment but data loss. While adding the line "0x043d 0x0260 no-reattach" no performance increment was observed.
If any of this workaround would have been worked then should we need to put all of our device's VID/PID entries into the quirks file? What about the devices will be released in future?

**Comment by michaelrsweet** [comment]
@skapas Future products should stick to supporting IPP Everywhere/AirPrint and IPP-USB, so this nonsense of legacy USB support is no longer necessary.

**Comment by skapas** [comment]
@michaelrsweet We understand the scenario but our customers are still using the conventional way of printing. We will definitely discuss on IPP-USB in future.

Regarding this issue:
We have checked in CUPS version 2.4.2 (compiling cups code). The observation is given bellow. 

1. Modify quirks file with  0x043d 0x0260 unidir: Takes ~10 sec pause between two jobs also job loss is happening. 
2. Modify quirks file with  0x043d 0x0260 no-reattach: Takes ~10 sec pause between two jobs but no job loss is happening.
3. Set the options in printer queue "lpadmin -p <Printer_Queue> -o usb-no-reattach-default=true" and "lpadmin -p <Printer_Queue> -o usb-unidir-default=true" : Takes ~3-4 sec pause between two jobs but still facing the page loss issue (Out of 10 job, 6-7 job are printing ).

Error log attached
[error_pause.txt](https://github.com/OpenPrinting/cups/files/8619069/error_pause.txt)

**Comment by michaelrsweet** [comment]
@skapas Looking at the log I see job 465 finishing at 08:57:55 and job 466 starting (and connected to the printer) at 08:57:56, so at most 1 second later (depending on how far into the second the end of the job was - lots of messages at :55).

I strongly suspect that what you are seeing is a delay in the *printer* starting the first page from the device. And I also strongly suspect that the same printer would show similar delays over a network interface between jobs.

**Comment by skapas** [comment]
Hi Michael,
We are not getting any delays in network path.
Is there any update on this issue?

Regards,
Saptarshi

**Comment by zdohnal** [comment]
Closing due inactivity...
