### ISSUE TITLE
usblp "Backend returned status 2 (authentication required)"

### ISSUE THREAD

**Issue by david-bla** [OpenPrinting/cups#382]
Dear CUPS developers,  

I am searching quite a while and feel like stuck in multiple rabbit holes.  
I do not like bother you... but I am stuck.  

I am developing a IoT device based on Pi OS, it should simple detect and use an usb printer.
To be able to adjust settings on the fly and use a known interface I used cups.  
I added a default printer and set it to `usblp0:/dev/usb/lp0`, the system just checks for existence of `/dev/usb/lp0`.
The actual printing was done by piping something to `/usr/bin/lp -d 'myPrinter'` - and this was working stable for years.

Recently I renewed everything and noticed that `/dev/usb/lp0` was missing. I figured out that a dependency of cups `ipp-usb` was adding a udev rule that causes `usblp` to remove the `/dev/usb/lp0` file. I first worked around that issue and implemented printer detection through pyCups, but in production there were printer models where 3 cups entries were generated and some even stay if the printer was offline.  

So I tried to just remove `ipp-usb` and it seemed woking fine until I noticed that every print is now __"Held for authentication."__ no mather what I tried. Even releaseing those jobs from root did not working. I've absolute no Idea what causes it - if it was wrong to remove `ipp-usb` and if cups will not work this way or if there are just something I overlooked...   

Thank you in advance for any hint or point to some code or stuff to study... I will also very pleased about any hints to do it better :smile:

**Comment by michaelrsweet** [comment]
@david-bla First, the usblp backend is not a standard part of CUPS. Moreover, the kernel character device driver "usblp" is deprecated and has not been used with CUPS for almost 20 years!

This backend doesn't seem to conform to the CUPS backend interface (which has specific exit codes for different error conditions and *not* errno values as appears to be the case here), so it naturally does not work properly for you.

You want to use the "usb" backend supplied with CUPS. Run `lpinfo -v` to list the USB device URI for your printer.
