### ISSUE TITLE
no classes/printers when using -c config file 

### ISSUE THREAD

**Issue by sgohl** [OpenPrinting/cups#383]
I want to maintain `cupsd.conf` in a repository while having `/etc/cups` mounted from an external volume, so that added printers etc are being saved (which is ugly by itself but anyway)

Therefore I want to start CUPS with `cupsd -f -c /etc/cupsd.conf` - but then the Webserver does not show me any classes or printers etc

It seems that `classes.conf` and `printers.conf` etc are searched in the same location as `cupsd.conf` is located, is that assumption correct? How am I supposed to work around that?

thanks!

**Comment by michaelrsweet** [comment]
@sgohl That is correct, printers.conf and classes.conf are always located in the same directory as cupsd.conf and cups-files.conf. There is no way to change this.
