### ISSUE TITLE
Feature Request:  Filter or search options when adding a new queue/printer

### ISSUE THREAD

**Issue by jcdouglas** [OpenPrinting/cups#393]
Would it be possible to add search and filter options for the following areas when adding printers/print queues for the web admin interface?

"Discovered Network Printers" - search or filter via IP or other search criteria to narrow down from the list
     Based on the text that's auto populated in discovery it can be hard to determine which printer is which, especially if no IP is
     shown.  This can be problematic on networks with over 20 printers.

"Model" - search via model number to narrow PPD list
     This is especially difficult when setting up an HP printer as the selection list for PPD's is quite long.

Attaching screenshots of said areas.

Apologies if this is the wrong venue for feature requests.

![AddPrinterDiscoveredCUPS 2 3 3op2](https://user-images.githubusercontent.com/18452830/167877579-1ef451db-f71a-4e74-bb61-af40ee7141bf.png)
![AddPrinterModelCUPS 2 3 3op2](https://user-images.githubusercontent.com/18452830/167877580-941e1c8c-1e8e-4a62-b50b-47115c35bd98.png)

**Comment by zdohnal** [comment]
Hi @jcdouglas ,

thank you for the feature request!

Ad the first part - the PR #397 should help with that, so please check the PR in question.

Ad the second part - the listed models there are actually drivers which you have on your machine, and CUPS is going to remove the driver support in the near future, so we are not going to implement such filters for model lists.
