### ISSUE TITLE
Exception: unknown object type inspecting /Contents key in page dictionaryAdded option MediaType

### ISSUE THREAD

**Issue by zhangyonglin911** [OpenPrinting/cups#396]
cups  2.4.1

When I print some PDF documents, they can't work normally. I get these tips through CPUs. How can I fix them? I'm a novice. Welcome to give me some suggestions.

"Exception: unknown object type inspecting /Contents key in page dictionaryAdded option MediaType"

**Comment by zdohnal** [comment]
Hi @zhangyonglin911 ,

thank you for reporting the issue!

It would be great if you attached ```error_log``` file here with .txt suffix where you saw the exceptions you've mentioned. I expect you have CUPS debug logging enabled already (IIRC such exceptions aren't shown by default), but if no, please turn on CUPS debug logging before you reproduce the issue.

IMHO the exceptions come from libqpdf, which is used for implementation of ```pdftopdf``` filter in ```cups-filters```, but I would like to check the error_log file.

What is interesting is that this exception was removed in QPDF in 2018, so it looks like pdftopdf is built with old qpdf, but AFAIK there isn't such old QPDF on systems with CUPS 2.4.1. Unless you've installed the newest CUPS manually.

**Comment by zdohnal** [comment]
Ad how to fix them if really the exception comes from the old QPDF:

There could be a bug in QPDF (since it looks quite old, if the exception really comes from QPDF) or in the PDF generator, which generates the PDF for application and then the app sends it to CUPS.

In any case it would be great if you provided the PDF which goes to CUPS - located in ```/var/spool/cups``` as a file which is starting with ```d``` letter and contains job ID of your print job once you reported it to QPDF (if you can reproduce the issue on the QPDF latest version) or to your distribution, since QPDF (if it is the source of exception) looks old.

**Comment by zhangyonglin911** [comment]
D [17/May/2022:09:40:38 +0800] [Job 14077] Printer model: Brother HL-2240 Foomatic/hl1250 (recommended)
D [17/May/2022:09:40:38 +0800] [Job 14077] Job title: whatever.pdf
D [17/May/2022:09:40:38 +0800] [Job 14077] File(s) to be printed:
D [17/May/2022:09:40:38 +0800] [Job 14077] <STDIN>
D [17/May/2022:09:40:38 +0800] [Job 14077] Ghostscript extra search path (\'GS_LIB\'): /usr/share/cups/fonts
D [17/May/2022:09:40:38 +0800] [Job 14077] Printing system options:
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option \'fit-to-page\'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown boolean option \"fit-to-page\".
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option \'print-scaling=fit\'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option print-scaling=fit.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option \'sides=one-sided\'
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option \'page-ranges=1-8\'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option page-ranges=1-8.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option \'job-uuid=urn:uuid:fa348708-2068-337d-5b07-d4a6036f08d5\'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option job-uuid=urn:uuid:fa348708-2068-337d-5b07-d4a6036f08d5.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option \'job-originating-host-name=localhost\'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option job-originating-host-name=localhost.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option \'date-time-at-creation=\'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option date-time-at-creation=.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option \'date-time-at-processing=\'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option date-time-at-processing=.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option \'time-at-creation=1652751633\'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option time-at-creation=1652751633.
D [17/May/2022:09:40:38 +0800] [Job 14077] Pondering option \'time-at-processing=1652751633\'
D [17/May/2022:09:40:38 +0800] [Job 14077] Unknown option time-at-processing=1652751633.
D [17/May/2022:09:40:38 +0800] [Job 14077] Options from the PPD file:
D [17/May/2022:09:40:38 +0800] [Job 14077] ================================================
D [17/May/2022:09:40:38 +0800] [Job 14077] File: <STDIN>
D [17/May/2022:09:40:38 +0800] [Job 14077] ================================================
D [17/May/2022:09:40:38 +0800] [Job 14077] Sending stdin for job...
D [17/May/2022:09:40:38 +0800] [Job 14077] STATE: +connecting-to-device
D [17/May/2022:09:40:38 +0800] [Job 14077] Looking up \"xxxxx.xxx.xxx.com\"...
D [17/May/2022:09:40:38 +0800] [Job 14077] Set job-printer-state-message to "Exception: unknown object type inspecting /Contents key in page dictionary", current level=ERROR
D [17/May/2022:09:40:38 +0800] [Job 14077] Cannot process \"<STDIN>\": Unknown filetype.
D [17/May/2022:09:40:38 +0800] [Job 14077] Process is dying with \"Could not print file <STDIN>
D [17/May/2022:09:40:38 +0800] [Job 14077] \", exit stat 2
D [17/May/2022:09:40:38 +0800] [Job 14077] Cleaning up...
D [17/May/2022:09:40:38 +0800] [Job 14077] PID 14484 (/usr/lib/cups/filter/pdftopdf) stopped with status 5.
D [17/May/2022:09:40:38 +0800] [Job 14077] Hint: Try setting the LogLevel to "debug" to find out more.
D [17/May/2022:09:40:38 +0800] [Job 14077] PID 14485 (/usr/lib/cups/filter/foomatic-rip) stopped with status 2.
D [17/May/2022:09:40:38 +0800] [Job 14077] Hint: Try setting the LogLevel to "debug" to find out more.
D [17/May/2022:09:40:38 +0800] [Job 14077] STATE: -connecting-to-device
D [17/May/2022:09:40:38 +0800] [Job 14077] xxxxxxx.xxxx.xxxx.com=11x.15x.20x.11x
D [17/May/2022:09:40:38 +0800] [Job 14077] hrDeviceDesc=\"Unknown\"
D [17/May/2022:09:40:38 +0800] [Job 14077] prtGeneralCurrentLocalization type is 0, expected 2!
D [17/May/2022:09:40:38 +0800] [Job 14077] backendWaitLoop(snmp_fd=5, addr=0x563aed739d18, side_cb=0x563aec458e60)
D [17/May/2022:09:40:38 +0800] [Job 14077] PID 14486 (/usr/lib/cups/backend/ipp) exited with no errors.
D [17/May/2022:09:40:38 +0800] [Job 14077] End of messages
D [17/May/2022:09:40:38 +0800] [Job 14077] printer-state=3(idle)
D [17/May/2022:09:40:38 +0800] [Job 14077] printer-state-message="Exception: unknown object type inspecting /Contents key in page dictionary"
D [17/May/2022:09:40:38 +0800] [Job 14077] printer-state-reasons=none

**Comment by zhangyonglin911** [comment]
@zdohnal [@zdohnal  [ https://crp.tatax.com.cn/dl_preview?openid=issue&fs_id=d14086-001](url)](url)

**Comment by zhangyonglin911** [comment]
@zdohnal    https://crp.tatax.com.cn/dl_preview?openid=issue&fs_id=d14086-001

**Comment by zdohnal** [comment]
Ok, so the error really comes from pdftopdf and libqpdf library - please contact [QPDF upstream](https://github.com/qpdf/qpdf/) if you are able to reproduce with the latest qpdf version (10.6.3) or your OS maintainers for a further investigation.

**Comment by zhangyonglin911** [comment]
thanks  very much i`ll try do it
