### ISSUE TITLE
Missing asterisk for old driver

### ISSUE THREAD

**Issue by MGMehdi** [OpenPrinting/cups#398]
Hello,
I try to use the driver of a Dell 3115CN that I exported from Windows but when I import it it say 
```Unable to open PPD file:
    Missing asterisk in column 1
```
So I've check with cupstestppd and here is the output
```
**FAIL**  Unable to open PPD file - Missing asterisk in column 1 on line 81.
                REF: Page 15, section 3.2.
```
ppd error section
```
*TTRasterizer: Type42
*?TTRasterizer: "
  save  <--- This line
  42 /FontType resourcestatus
  { pop pop (Type42)} {pop pop (None)} ifelse = flush
  restore"
*End
```

If I place an asterisk at the beginning of the line 
```
**FAIL**  Unable to open PPD file - Missing value string on line 81.
                REF: Page 20, section 3.4.
```
I don't know what to do. Is it possible to add Dell driver ?
Thank you

**Comment by michaelrsweet** [comment]
@MGMehdi Can you attach the entire PPD file here (might need to add ".txt" to the extension)?

**Comment by zdohnal** [comment]
Closing due inactivity.
