### ISSUE TITLE
everywhere PPD generation fails on Brother VC-500W

### ISSUE THREAD

**Issue by agoode** [OpenPrinting/cups#399]
The Brother VC-500W is an AirPrint printer that works correctly in macOS but not on cups.

It has a quirk where, upon doing `get-printer-attributes` with `requested-attributes all,media-col-database`, will only return `media-col-database`. Two separate operations are required in order to get all attributes: one with `requested-attributes all`, then another with `requested-attributes media-col-database`.

**Comment by michaelrsweet** [comment]
@agoode please verify you are using the most current firmware for the printer. Even for AirPrint, not handling requested-attributes properly will cause a failed certification. Changing the current behaviour will cause other printers to fail…

**Comment by agoode** [comment]
Thanks for following up!

It is the latest firmware: 2021-03-21-02.

It turns out this is a somewhat unusual device! It seems to be running a full CUPS 1.6.1 instance, including the whole browse interface and API documentation. It can see the other printers on my network.

I've attached the 2 attr files from ipptool:
  * [vc-500w-all-attr.txt](https://github.com/OpenPrinting/cups/files/8748488/vc-500w-all-attr.txt)
  * [vc-500w-media-col-database-attr.txt](https://github.com/OpenPrinting/cups/files/8748487/vc-500w-media-col-database-attr.txt)

I do see it listed at https://support.apple.com/en-us/HT201311 under the AirPrint printers list. Is there a way to report this to Apple?

Alternatively, is there a way to implement some kind of fallback that doesn't break compatibility?

**Comment by michaelrsweet** [comment]
@agoode You can send a message to "airprint@apple.com". I'm not sure what to do beyond that, unfortunately, since I no longer work at Apple.

Implementing another kind of workaround would involve changes in many places, including places outside of CUPS. Really this needs to be fixed by Brother... :/

**Comment by zdohnal** [comment]
I concur with Mike, this really needs to be fixed in the firmware.

**Comment by agoode** [comment]
Thank you for all the investigation, I've sent a note to the airprint email address as suggested.

**Comment by pzelten** [comment]
@agoode  Thanks for the heads up.   
We received your feedback from Apple and believe we have a fix for it that will be in the next release from Brother.
I have attached the ipptool printer attribute tests and plist output for the 3 cases noted.

[IPP_printer_attribute_VC500W.zip](https://github.com/OpenPrinting/cups/files/8910136/IPP_printer_attribute_VC500W.zip)
.

**Comment by agoode** [comment]
Thank you to everyone for helping to get this issue resolved!

**Comment by AdamOnLinux** [comment]
> @agoode Thanks for the heads up. We received your feedback from Apple and believe we have a fix for it that will be in the next release from Brother. I have attached the ipptool printer attribute tests and plist output for the 3 cases noted.
> 
> [IPP_printer_attribute_VC500W.zip](https://github.com/OpenPrinting/cups/files/8910136/IPP_printer_attribute_VC500W.zip) .

I have ipptool working great with the latest firmware on VC-500W. Do you happen to know the ATTR needed to enable auto-cut on prints?  If not, any particular emails I can reach out to that would know? Thanks!

**Comment by michaelrsweet** [comment]
@AdamOnLinux If it implements IPP correctly it should use the "finishings" attribute with a value of '11' (trim), but I don't see that in the ipptool output...
