### ISSUE TITLE
Ipps connection to printer no longer works

### ISSUE THREAD

**Issue by clusterx** [OpenPrinting/cups#403]
libcups-1:2.4.2-1

Issue:
ipps connection to the printer no longer works, print job do not arrive at the print server and the local queue shows:
printer stopped

using:
ipps://192.168.0.20/printers/ML-1640-Series

temporary solution > downgrade to 1:2.4.1-1
sudo pacman -U /var/cache/pacman/pkg/libcups-1:2.4.1-1-x86_64.pkg.tar.zst

Operating System: EndeavourOS
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.94.0
Qt Version: 5.15.4
Kernel Version: 5.17.9-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 8 × AMD FX™-8350 Eight-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GT 630/PCIe/SSE2

**Comment by michaelrsweet** [comment]
@clusterx My guess is that this printer doesn't support anything newer than TLS/1.0, current OpenSSL no longer supports TLS/1.0 by default, and CUPS 2.4.2 adds support for OpenSSL and prefers it to GNU TLS by default. You may need to use "ipp" for this printer, unless there is a firmware update for it...

**Comment by clusterx** [comment]
> @clusterx My guess is that this printer doesn't support anything newer than TLS/1.0, current OpenSSL no longer supports TLS/1.0 by default, and CUPS 2.4.2 adds support for OpenSSL and prefers it to GNU TLS by default. You may need to use "ipp" for this printer, unless there is a firmware update for it...

You're right, the printer does not support new TLS protocols.
Many thanks!
