### ISSUE TITLE
Critical: selecting monochrome printing still prints in color with driverless printing

### ISSUE THREAD

**Issue by callegar** [OpenPrinting/cups#413]
Printing from ubuntu 22.04 (cups 2.4.1+patches) on a Canon iR-ADV C5850i. Printer is auto-recognized by the system for driverless printing. Unfortunately selecting monochrome printing from the print dialog does nothing. The printer still prints in color.

This is quite critical for the augmented printing costs. At the office we are explicitly asked not to print in color unless absolutely necessary and access to the printer may be precluded if this policy is violated.

**Comment by callegar** [comment]
Just noticing: maybe a duplicate of #401.

**Comment by zdohnal** [comment]
Yes, it is a duplicate.
