### ISSUE TITLE
Poor printing quality with driverless printing

### ISSUE THREAD

**Issue by callegar** [OpenPrinting/cups#414]
Printing from Ubuntu 22.04 (cups 2.4.1+patches) on a Brother MFC L6950DW. Printer is autodetected for driverless printing. Unfortunately the print quality is sub-par, almost sure, much worse than what the printer could do. Fonts look pixelated and thin lines in fonts are in multiple occasions not printed at all (very visible when printing the ballot character, where borders of the box often disappear).  Furthermore the printing is extremely small.

Don't know if this is actually the case, but it looks a lot as if everything was rasterized before printing and the rasterization happened at a wrong resolution (causing a lot of work on the printer for rescaling and detail loss).

**Comment by debiantriage** [comment]
What you get for

```
avahi-browse -rt _ipp._tcp
avahi-browse -rt _uscan._tcp
```

could be useful.

**Comment by zdohnal** [comment]
Hi @callegar ,

thank you for reporting the issue! Together with ```avahi-browse``` output it would be great if you attached a .txt file with output of ```ipptool``` command:

```
$ ipptool -tv <your_printer_uri> get-printer-attributes.test
```

and cupsd error_log when you print with debug logging enabled and you experience the issue. It happens often that printer doesn't support all quality options via driverless standards in comparison to the old driver. The other thing which could happen is assigning incorrect quality option in cupsd, problem in a filter etc.

Debug log and IPP response from the printer should help us with that.

**Comment by callegar** [comment]
Unfortunately the command

```
ipptool -tv implicitclass://Brother_MFC_L6900DW_series get-printer-attributes.test
```
errors out, proposing the *help* for `ipptool`.

**Comment by callegar** [comment]
From `avahi-browse` the relevant fragments appear to be:

```
= enx0050b61af5c1 IPv4 Brother MFC-L6900DW series                    Internet Printer     local
   hostname = [BRNB4220052FD43.local]
   address = [137.204.143.202]
   port = [631]
   txt = ["mopria-certified=1.2" "print_wfds=T" "UUID=e3248000-80ce-11db-8000-b4220052fd43" "PaperMax=legal-A4" "kind=document,envelope,label,postcard" "URF=W8,CP1,IS19-1,MT1-3-4-5-8,OB10,PQ4,RS300-600-1200,V1.4,DM1" "rfo=ipp/faxout" "TBCP=F" "Transparent=T" "Binary=T" "PaperCustom=T" "Scan=T" "Fax=T" "Duplex=T" "Copies=T" "Color=F" "usb_CMD=PJL,PCL,PCLXL,URF" "usb_MDL=MFC-L6900DW series" "usb_MFG=Brother" "priority=25" "adminurl=http://BRNB4220052FD43.local./net/net/airprint.html" "product=(Brother MFC-L6900DW series)" "ty=Brother MFC-L6900DW series" "note=" "rp=ipp/print" "pdl=application/octet-stream,image/urf,image/pwg-raster,application/pdf" "qtotal=1" "txtvers=1"]
```

and

```
= enx0050b61af5c1 IPv4 Brother MFC-L6900DW series                    _uscan._tcp          local
   hostname = [BRNB4220052FD43.local]
   address = [137.204.143.202]
   port = [80]
   txt = ["duplex=T" "is=adf,platen" "cs=binary,grayscale,color" "UUID=e3248000-80ce-11db-8000-b4220052fd43" "pdl=application/pdf,image/jpeg" "note=" "ty=Brother MFC-L6900DW series" "rs=eSCL" "representation=http://BRNB4220052FD43.local./icons/device-icons-128.png" "adminurl=http://BRNB4220052FD43.local./" "vers=2.5" "txtvers=1"]
```

hope I am not missing anything...

**Comment by zdohnal** [comment]
@callegar 

> ```
> ipptool -tv implicitclass://Brother_MFC_L6900DW_series get-printer-attributes.test
> ```

Ok, so the URI tells us the printer is created and managed by ```cups-browsed``` from ```cups-filters``` project. The PPD is generated by ```driverless``` generator as well.

It would be great if you turned on CUPS debugging, printed the file where you experience quality issues and attached the CUPS error_log file here with .txt suffix - avahi-browse output shows the device advertises 3 types of quality for AirPrint - 300dpi, 600dpi and 1200dpi, it would be great to see which one is used during printing.

Ad ipptool command - I'm sorry I didn't expect cups-browsed, ipptool works with clean IPP uris. So please try this one (to keep it simple I use the IP address instead of mDNS hostname)

```
$ ipptool -tv ipp://137.204.143.202:631/ipp/print get-printer-attributes.test
```
Please attach the PPD you have for the printer in /etc/cups/ppd as well.

Once we gather all info, I'll pass this to cups-filters, because the printer is managed by the daemon from it.

Thank you in advance!

**Comment by debiantriage** [comment]
Thank you @callegar; everything is there.
>    pdl=application/octet-stream,image/urf,image/pwg-raster,application/pdf

The Brother MFC L6950DW accepts PDF. On Ubuntu 22.04 production of a PDF to send to the printer is the priority route. Raster format is not involved.

A PDF can be sent *directly* to the printer with
```
netcat 137.204.143.202 9100 < ANY_PDF
```
Check that 9100 is an open port with  `nmap 137.204.143.202`

How does that go on as regards quality?

**Comment by zdohnal** [comment]
There has been no response since the end of June, Brian's question hasn't been answered and the requested files haven't been provided, so I'm going to close the issue. In case the problem persists, please let us know and provide the requested information.

Thank you in advance!
