### ISSUE TITLE
Driverless printers do not remember their default options

### ISSUE THREAD

**Issue by callegar** [OpenPrinting/cups#415]
Printing from ubuntu 22.04 using cups 2.4.1+distro patches.

When I look for the printers in the distro settings, I can set "default options" for it. But these options are not retained.

This means that over and over I am facing again a printer that does not automatically duplex. This is inconvenient and environmentally unfriendly. I believe that for driverless printers cups every time gets the configuration from the printer. If so, it is true that the admin who set up the printer probably did it in a suboptimal way. Still, I would like my system to remember how I want to print on that printer. Furthermore, it does not seem very sensible to have the possibility to set "default options" even for driverless printers if these options cannot be retained.

**Comment by zdohnal** [comment]
Hi @callegar ,

I'm sorry, I've maybe misunderstood your issue (I have been dealing with issues when users couldn't set a default color on permanent driverless printers, so I thought it is the same).

If you are talking about driverless printers, do you mean the ones you've installed manually with ```everywhere``` or those which appear in print dialogs (the temporary ones)?

In case it is the former, I can check whether I can reproduce it - AFAIK the problem with setting defaults for driverless permanent is only for color settings.

In case it is the latter - temporary queues - can change their defaults via ```lpoptions -p <name> -o <option>=<value>```, which will override the option for user which called the command. Printer configuration tools can do it via ```cupsSetDests()``` API function as well.

**Comment by rilian-la-te** [comment]
@zdohnal I saw this issues for temporary queries with 
```
cups 1:2.4.2-6
```
