### ISSUE TITLE
scheduler/ipp.c create_local_bg_thread function set printer->device_uri to local variable address.

### ISSUE THREAD

**Issue by jiaojinxing** [OpenPrinting/cups#419]
Line 5300:

```
  if (strstr(printer->device_uri, "._tcp"))
  {
    cupsdLogMessage(CUPSD_LOG_DEBUG2, "%s: Resolving mDNS URI \"%s\".", printer->name, printer->device_uri);

    if (!_httpResolveURI(printer->device_uri, uri, sizeof(uri), _HTTP_RESOLVE_DEFAULT, NULL, NULL))
    {
      cupsdLogMessage(CUPSD_LOG_ERROR, "%s: Couldn't resolve mDNS URI \"%s\".", printer->name, printer->device_uri);
      return (NULL);
    }

    cupsdSetString(&printer->device_uri, uri); // Fixed printer->device_uri = uri;
  }
```

**Comment by michaelrsweet** [comment]
Yes, this needs to be fixed...

**Comment by zdohnal** [comment]
(facepalm) I'm sorry for this elementary mistake - @michaelrsweet if you don't mind, I'll fix this since I made that mistake.

**Comment by zdohnal** [comment]
I've created PR for the issue - I didn't want to be impolite to push the change when you assigned yourself to the issue.

**Comment by michaelrsweet** [comment]
@zdohnal Go for it! :)

**Comment by zdohnal** [comment]
@jiaojinxing thank you for the patch and letting us know!

**Comment by jiaojinxing** [comment]
@zdohnal No thanks, I'm porting cups to EdgerOS(our intelligent edge operating system), and found the issue during testing, thanks for developing the cups project.
