### ISSUE TITLE
Unsuccessful everywhere queue creation not reported to the console

### ISSUE THREAD

**Issue by debiantriage** [OpenPrinting/cups#422]
I am using CUPS 2.4.2-1 on Debian and have crippled resolution of hosts in the local domain by removing libnss-mdns from the system. Execution of 
```
lpadmin -p testq ipp://ENVY4500._ipp._tcp.local -E -m everywhere
```
 completes without any console output. That is, it was successful.

However, a PPD is not generated and the error_log shows

> testq: Unable to connect to envy4500.local:631: Name or service not known

I would have expected this message to be displayed.

**Comment by zdohnal** [comment]
Hi Brian,

thank you for reporting the issue!

This is basically the same #347 - we use a separate thread in cupsd to generate PPD, but currently we don't report/check the result from the background thread, which causes the issue you reported and synch issue described in #347.

I'm going to close this issue and leave the comment in the issue #347 .

**Comment by zdohnal** [comment]
Mentioned in #347 .
