### ISSUE TITLE
Trying to display non-existing printer/class in web ui doesn't return 404.

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/cups#423]
I took this one from https://github.com/apple/cups/issues/6045 . Currently we see an empty template if you go to web interface page for non-existing printer/class f.e. (class ```testclass``` and printer ```testprinter``` don't exist):

```
http://localhost:631/classes/testclass
http://localhost:631/printers/testpriner
```

We should show error when we try to access an non-existing printer directly by uri.

**Comment by tillkamppeter** [comment]
Seems that one can influence this by the `error-policy` setting. See
https://github.com/bhavish-1/cups/commit/e73bb3025f34a44d15c8654cfbd7fab369857490
But if this actually works, it is not very intuitive and the web interface should also behave correctly if the user prefers another `error-policy` .

**Comment by zdohnal** [comment]
@tillkamppeter I don't get a different behavior by setting the ErrorPolicy in cupsd.conf - still the same empty template.

**Comment by michaelrsweet** [comment]
[master 2325d3707] Return HTTP status 404 for non-existing classes and printers (Issue #423)

[2.4.x 9a9f9b380] Return HTTP status 404 for non-existing classes and printers (Issue #423)
