### ISSUE TITLE
Auto discovered printers don't show up in Qt Print dialog

### ISSUE THREAD

**Issue by callegar** [OpenPrinting/cups#425]
In some linux distros (arch derived distros are an example) auto-discovered printers don't show up in the qt print dialog, so it is actually impossible to use them for printing from Qt applications.

This may be an issue with Qt, or an issue in how some distros configure for compilation or patch Qt.  Yet, because it is not really very clear how auto-discovered printers should work with the toolkits I would like a confirmation in this sense.

Where should the Print dialog get the list of printers available for printing? From the local cups server? From the printer itself via its bonjour announcements?  If the latter is the case, where should the print dialog get the printer default options?

I understand that the role of the cups-browsed helper is to make auto-discovered printer behave as if they were locally installed. Why does this work for things like `lpstat -a` and not for Qt applications?

In case this is a Qt bug, are there known patches? Given the importance of being able to print onto printers for which there may not be linux drivers but that are capable of driverless printing, is there some workaround for the Qt issue?

**Comment by michaelrsweet** [comment]
@callegar I can't comment on Qt or packaging on Linux, perhaps another maintainer can help there.

WRT how the Qt print dialog can get the list of available printers, the `cupsGetDests` and `cupsEnumDests` APIs have been available for a very long time and are the recommended method for getting the list of available printers/classes on a system. These APIs also report auto discovered printers, and the corresponding CUPS APIs handle creating a temporary print queue as needed. These are all documented in the CUPS Programming Manual, and the APIs themselves have been unchanged for the last 10 years...

**Comment by debiantriage** [comment]
@callegar I can only speak of what happens on Debian. Printers auto-discovered by cups-browsed are shown in Okular's print dialog and match what `lpstat -a` gives.

Presumably, your Qt dialog shows a printer listing. What leads you to think they are not auto-discovered entries?

**Comment by zdohnal** [comment]
I haven't checked how qt5 is packaged in distros and which patches are there, but IMHO the difference is Debian has running cups-browsed by default, which installs the printer permanently, and Manjaro doesn't.

The only workaround would be to permanently install any autodiscovered printer, which goes against the idea of having the queues temporary and spare resources in case the device and the network are capable of doing it.

It would be great if you reported the issue to Qt [bug tracker](https://bugreports.qt.io/secure/Dashboard.jspa) - we probably won't have a time for reviewing the existing downstream patches, but if QT devs have questions/problems with implementing temp queue feature, most stuff is covered by CUPS Programming manual, CUPS tools can be taken as a working example or we can give advice as well.

**Comment by callegar** [comment]
@[zdohnal](https://github.com/zdohnal)

No, unfortunately the difference is not only in cups-browsed running by default, otherwise solving the issue would be as easy as starting cups-browsed. I think that the issue is that the Qt5 print dialog needs patching to do the right thing wrt autodiscovered printers and all major distros patch it. Probably it all goes down to the fact that when autodiscovered printers came out, also Qt6 was coming out, so the usual flow of updates in Qt5 got interrupted and a lot of useful patches got lost or at best only available in some distros.

**Comment by callegar** [comment]
Created issue [QTBUG-105167](https://bugreports.qt.io/browse/QTBUG-105167)

**Comment by debiantriage** [comment]
@callegar Debian unstable has libqt5printsupport5 (5.15.4+dfsg-4) and  okular (4:22.04.3-1). I took a quick look at the patches in qtbase-opensource-src_5.15.4+dfsg-4.debian.tar.xz and none of them conserns printining.

@zdohnal I'll relate what I observe with printing and Okular when cups-browsed is stopped:

- An opened dialog enumerates the same printers as _lpstat -e_.
- Selecting a printer does not, as shown by _lpstat -a_, lead to the formation of a temporary queue.
- Printing on a printer does lead to the formation of a temporary queue and printer attributes appearing in the dialog. Mmm, a bit late in the day!
- The temporary queue disappears after about a minute.

For obvious reasons, cups-browsed masks this behaviour of Qt, which is also seen on Ubuntu.
