### ISSUE TITLE
Konica Minolta "Reset Modes" status with IPP Everywhere

### ISSUE THREAD

**Issue by dkosovic** [OpenPrinting/cups#428]
I have a CUPS-2.4.2 server with an IPP Everywhere print queue setup for a Konica Minolta bizhub C458. I see the following error message in the CUPS Jobs web interface after printing a job :
```
Print job canceled at printer
```

Yet the physical print job gets printed, but on the printer's panel looking at the job log, I see _"Reset Modes"_ for the print job status.

The Konica Minolta manual for this model (and others) states the status values for print jobs can be:
* Job Complete
* Deleted Due To Error
* Deleted by User
* Reset Modes

It is not explained anywhere what _"Reset Modes"_ means and if it is an actual error status. I've read in a forum _"Reset Modes"_  for Fax jobs happens if detect blank pages is enabled, but that doesn't seem applicable for print jobs.

Looking at the CUPS code, the `Print job canceled at printer` error happens on the following line :
    https://github.com/OpenPrinting/cups/blob/v2.4.2/backend/ipp.c#L2280

with a bit of simple debugging by modifying that line of code, I determined `ipp_status == 0` and `job_canceled == -1`.

I was testing with Win11 and macOS 12.4 clients.

Does anybody have any idea what might be causing the  _"Reset Modes"_  on the Konica Minolta bizhub C458 printer?

**Comment by michaelrsweet** [comment]
@dkosovic Best thing is do enable debug logging (`cupsctl --debug-logging`) and attach a copy of your "/var/log/cups/error_log" file after printing something. That will provide the state information coming back from the printer so we can further diagnose things...

**Comment by dkosovic** [comment]
Please find attached a `/var/log/cups/error_log` file after printing something that caused the "Reset Modes" status on the Konica Minolta and `Print job canceled at printer` message on the CUPS server.

I should add that it is an intermittent issue, but happens more often than not, even when printing the same document.
[error_log.txt](https://github.com/OpenPrinting/cups/files/9099679/error_log.txt)

**Comment by michaelrsweet** [comment]
OK, so the printer is reporting the job is aborted with no additional state reasons keywords, so all CUPS can do it flag it and abort the job locally as well... :/

Unfortunately, I don't see the initial job submission request going to the printer, so I'm not sure what is going wrong. If you can try collecting logs that include the initial print job submission, that might be more illuminating.

**Comment by dkosovic** [comment]
I was able to reproduce the "Print job canceled at printer error" error in the CUPS server web interface.

Turns out "Reset Modes" on the printer's panel corresponds to "Mode Cancelled" in the printer's web interface Job History, e.g. : 

| Detail   | |
| ------------- | ------------- |
| No. | 1326 |
| Job | Print |
| User Name | EAIT\uqdkosov |
| Authentication Server |  |
| File Name | *Untitled - Notepad |
| Output Tray | Tray 1 |
| Time Stored | 19/07/2022 16:09 |
| Time Finished | 19/07/2022 16:10 |
| No. of Copies | 1 |
| # of Originals | 1 |
| # of Sets | 1 |
| Result | Mode Cancelled  |
| Error Code |  | 

I guess "_Reset Modes_" and "_Mode Cancelled_" are very loose synonyms if translated from another language.

Interesting how "Error Code" is empty and separate from the result which is "Mode Cancelled".

I have a suspicion  "_Mode Cancelled_"  is something to do with the printer's *Print without Authentication* setting which can be:
* `[Full Color/Black]`: Allows both color and black and white printing.
* `[Black Only]`: Allows black and white printing only. Color printing jobs are also printed in black and white.
* `[Restrict]` (default) : Restricts a print job without authentication information.

For some reason `[Restrict]` is the default, will try changing to `[Full Color/Black]` tomorrow.

Elsewhere the *IPP Authentication Setting* is still set to the default `requesting-user-name`.

Weird thing is that I don't have this issue if I use AppSocket port 9100 instead of IPP to connect to the Konica Minolta printer.

**Comment by dkosovic** [comment]
Changing  **Print without Authentication** setting from `[Restrict]` to `[Full Color/Black]` made no difference.

If I put a Win11 PC on the same VLAN as the printers and use the Mopria based "Microsoft IPP Class Driver", I get the same "Reset Modes" / "Mode Cancelled" result on the Konica Minolta bizhub C458 printers I tested with.

**Comment by michaelrsweet** [comment]
@dkosovic OK, so that definitely sounds like a printer firmware bug. Have you checked to see whether KM has a firmware update available for this printer?

**Comment by dkosovic** [comment]
I get the same issue on a Konica Minolta bizhub C453e MFP. I believe the firmware is fairly recent from last year. I agree it is a firmware bug.

Superficially using a macOS client or mobile client, nothing is wrong with IPP printing directly to the Konica Minolta bizhub C458 MFP apart from the Mode Cancelled / Reset Modes status in the job log on the printer itself.  If I enable IPP authentication on the printer and don't supply credentials from the client, the status on the printer changes to "Deleted Due To Error" and get flashing amber light on the printer and a very obvious error on the printer's panel. I have a suspicion " Mode Cancelled / Reset Modes" isn't treated as a real error and they never tested with a Win10/Win11 mDNS "Microsoft IPP Class Driver" client.

I'm going to try and contact Konica Minolta and report the bug.

As this isn't a CUPS bug, I'll close this issue.
