### ISSUE TITLE
No duplex printing on Brother MFC-J6920DW

### ISSUE THREAD

**Issue by DrMartinus** [OpenPrinting/cups#429]
Hi,
I run Manjaro on my PC and have for several years A Brother MFC-J6920DW connected to it. After a system update about one month ago, the printer stopped printing duplex. I have the printer set up in CUPS as different printers each with different settings (like A3 foto, A4 duplex, A5...), so I can choose just one of those printers, and it would print - until that upgrade. I can continue to print one-sided. Only when I start a duplex job, the printer pulls in a sheet and then begins to wait for approximately 1 minute, before it spits out the empty page. CUPS treats the job as printed. It can be a hundred page document or a 2 page document, it's all the same.
I have tried different places for help, like the Manjaro forums, but no luck. I am quite sure that his has to do with some settings within CUPS, but I don't know enough to try to fix it myself. The driver is provided by Brother and has worked flawlessly until... There was no driver update.
Since then I have noticed, how often I need this functionality. In view of increasing scarcity of resources, environmental issues etc., it's a very valuable thing, and I need it back.

**Comment by debiantriage** [comment]
Assuming a network connection (USB will require ipp-usb). obtain a URI with `driverless` and set up a print queue, substituting for URI:
```
lpadmin -p testq -v "URI" -o Duplex-default=DuplexNoTumble -E -m everywhere
```
Print to testq. Duplex works?

**Comment by DrMartinus** [comment]
This is a USB connected printer. I installed ipp-usb - it was not originally installed. But so far no luck. When I enter the above with a proper URI (I guess, it looks like this: "ipp://Brother%20MFC-J6920DW._ipp._tcp.local/"), it actually prints duplex.

**Comment by DrMartinus** [comment]
Here the output of `lsusb -v | grep -A 3 bInterfaceClass.*7
`
`      bInterfaceClass         7 Printer
      bInterfaceSubClass      1 Printer
      bInterfaceProtocol      2 Bidirectional
      iInterface              0 
Couldn't open device, some information will be missing
`
The last line ("Couldn't open device...") was also repeated for severeal times before the quote, I thought it's not necessary to copy them, too.
So it works as driverless printer. But then some options are missing. I need to check if any of those are crucial. Thanks for your help. Still I don't understand why it doesn't work with the original drivers any more (it used to work flawlessly).

**Comment by DrMartinus** [comment]
Now a new problem: I could print some docs with duplex set to on, and it printed duplex. Then I wanted to print another, though similar, doc, and all of a sudden I get this message:
`Color manager: no profiles specified in PPD`
I tried to print in monochrome, but that doesn't help, it still won't print with the same error message. I'm pretty sure all settings are the same as with the other docs, and the docs are very similar. The only difference is the text (all are letters with the same template).

**Comment by DrMartinus** [comment]
And the problems continue: When I print duplex, it seems that when it's set to flip pages along the long side, it prints them as flipped over the short side, and vice versa. I am not sure if that happens in every program every time, but it seems to be the case. I waste a lot of paper currently and desire strongly to have it as it was working for such a long time only a few months ago. But I have no clue what could be gone wrong. I did not change any config files, except the ones available in the print dialogs.

**Comment by zdohnal** [comment]
@DrMartinus it would be great if you provided the debug logs for both of your problems together with information mentioned in the link: https://docs.fedoraproject.org/en-US/quick-docs/how-to-debug-printing-problems/#_my_printer_doesnt_print_correctly_or_at_all_but_i_can_see_the_printer_in_print_dialog .

**Comment by DrMartinus** [comment]
@zdohnal Thank you for pointing that out. While trying to do everything that's listed there, I took a look at the ppd and found that duplex printing was set like this:
`*Duplex DuplexNoTumble/On (Portrait): "<</Duplex true/Tumble false>>setpagedevice"
*Duplex DuplexTumble/On (Landscape): "<</Duplex true/Tumble true>>setpagedevice"`
I took the liberty and changed it to
`*Duplex DuplexNoTumble/On (Portrait): "<</Duplex true/Tumble true>>setpagedevice"
*Duplex DuplexTumble/On (Landscape): "<</Duplex true/Tumble false>>setpagedevice"`
and now at least the second problem (flipping along the short side, when it was supposed to do it along the long side, and along the long side, when it was supposed to do it along the short side) is resolved.
For the other, earlier problem I have to try to recreate it in order to send log data, please be patient. I wonder if I should do it with the original driver, because I guess it will be better to fix that problem than to fix new problems that arise when using the driverless option.

**Comment by zdohnal** [comment]
@DrMartinus it has been one month since the your last comment, so I'm going to close the issue for now - in case you can  trigger the issue again, please let me know, provide the information requested and I reopen the issue.
