### ISSUE TITLE
Printout gets truncated

### ISSUE THREAD

**Issue by bachpro1** [OpenPrinting/cups#432]
I am printing from a Fedora 36 environment.  I am running cups.x86_64 1:2.4.2-1.fc36.  I am printing to an HP Color LaserJet Pro 400 (M451dn) printer.  The interface is provided by the hplip.x86_64 version 3.22.4-1.fc36 package.  The computer to printer connection is via Ethernet running IPv4.

In several different instances the printout gets truncated.  If errors are being logged, I don't know where.  In one case I do a "man -t vsftpd.conf | lp" command.  The printout abruptly ends at the end of page 9.  If I direct the MAN output to a file and transfer it to a Windows PC, the file (a .ps file) prints fine to exactly the same printer across exactly the same Ethernet/IPv4 network connection.

Lately I have been trying to print "C" source code (plain text).  I do something like "lp sysutil.c".  Several pages print.  Then I get what to be some diagnostic information and the rest of the C source does not print.  Line 1 reads "ERROR:".  Line 2 reads "undefined".  Line 3 reads "OFFENDING COMMAND".  Line 4 reads "....Undefined".  Line 5 reads "STACK:".  Line 6 reads "1".  Line 7 reads "/R74".  Line 8 reads "-mark-".  Lines 9 and 10 are identical to line 8.  Generally, the problem is completely repeatable.  If I try to print the same thing in the same way I will get the same error at the same place in the printout.  I have experienced the MAN page problem (always with the same MAN page - other MAN pages seem to print just fine) under several releases of Fedora, 34 and 35 as well as 36.   In all cases I am using the version of CUPS and the HP package that comes with Fedora.

I don't know where to look to figure out where the problem is.  It does not appear to be with the MAN command as "lp"-ing a piece of "C" code also produces problems, just different ones.  I don't know that it is a CUPS problem.  This just seemed to be a good starting point.

Any ideas or suggestions?  I am tired of having to jump through hoops (move it to Windows and print it from there) just to print some text.  Thanks.

**Comment by zdohnal** [comment]
Hi @bachpro1 ,

thank you for reporting the issue!

It looks like there is an error in filtering chain - I usually check the printing by using PDFs or small text files.

> I am printing from a Fedora 36 environment. I am running cups.x86_64 1:2.4.2-1.fc36. I am printing to an HP Color LaserJet Pro 400 (M451dn) printer. The interface is provided by the hplip.x86_64 version 3.22.4-1.fc36 package. The computer to printer connection is via Ethernet running IPv4.

The device supports AirPrint, you can try using driverless printing instead of classic hplip driver once you enable IPP port on the printer. You can install it by f.e.:

$ lpadmin -p <choose_name> -v ipp://<printer_ip>:631/ipp/print -m everywhere -E && sleep 10

Both issues you investigate further by checking the debug logs. You can follow the steps [here](https://docs.fedoraproject.org/en-US/quick-docs/how-to-debug-printing-problems/#_my_printer_doesnt_print_correctly_or_at_all_but_i_can_see_the_printer_in_print_dialog) and attach them here, so I can investigate.

**Comment by bachpro1** [comment]
Thanks for the help.  I can print most documents just fine.  It's just a few documents.  Other MAN pages print fine.  Other C source files print fine.  But, if a certain file fails to print, it always fails, and at the same place, and in the same way.  I took a look at the documentation you pointed me at.  I will go ahead and use that process.  I was really looking for a way to figure out what was going wrong.  The documentation you pointed me to, should help a lot.

**Comment by zdohnal** [comment]
@bachpro1 it would be great if you tried the driverless printing - we will drop the direct driver support in CUPS in the near future, so you can find out whether you can communicate with CUPS directly or whether you will need a printer application. It can solve the printing issue as well.

If you experience this for the specific files, it would be great if you could attach their copy/clone from /var/spool/cups (every file which is sent to CUPS for printing is copied/cloned by an application and once CUPS receives it, it is stored in the mentioned directory under name beginning with 'd' + job number + the ordering number of the file in the job). You can add the .txt suffix to it and attach them here.

**Comment by bachpro1** [comment]
I went through the process in the documentation.  Specifically -
- I made teh suggested changes to cupsd.conf and cups-files.conf and restarted CUPS.
- I then ran the two problematic print jobs.  They both failed at the place and in the way they have been failing.
- In spite of this I couldn't find anything helpful in either jouranlctl or /var/log/messages.

At this point I suspect a problem with HPLIP.  There is a debugging parameter I can set there.  I can also enable the "save the files" option in CUPS.  But I am inclined to take your suggestion and jettison HPLIP.  But what do I replace it with?

I did RedHat system administration for a living more than a decade ago.  At that time RedHat provided a CLI tool for configuring printers that was easy to use.  I was able to connect various HP printers using it with no problem.  But then RedHat retired the tool.  When I went back to playing with Linux, specifically Fedora, a few years ago I looked around to try to figure out how to connect my HP printer to my Linux system.  Ther was DOC on how to use the GUI printer configurator but nothing when it came to CLI printer configuration.

Then I found HPLIP.  It did just what I wanted.  It had a command line interface.  I could plug an IP address in, and it would take care of the rest.  For instance, it autodetected the model number and configured everything accordingly.

My printer (HP LaserJet 400 color m451dn) is relatively new.  So, it supports Postscript and other features that simplify things and increase usability.  I like wired, so both the Linux computer and the printer are wired into my home IPv4 network.  I want to continue to use a wired connection.

If you could point me to the documentation containing the installation procedure that uses one of the methods that will be supported going forward, I would be happy to give it a try.  Is it just a matter of doing a "dnf remove hplip" and then following the procedure outlined in the "Installation via CLI commands" section of Quick Docs?

If so, I have a couple of questions -
- When I do a "lpinfo -v" command I get a bunch of entries, including two that look like the ones in the example.  One is a "network dnssd:// . . ." entry.  The other is a "network ipp:// . . .". entry.  So, what do I use for my "device uri"?
- When I do a "lpinfo -m" I get a long list of results.  There are many entries that start "drv:".  I presume these are old fashioned printer drivers.  Then there are a bunch that start "lsb/usr/".  I'm not sure what these are.  A "drv:" and an "/lsb/usr" entry seem to match my specific model of HP LaserJet.  but there is also an "everywhere IPP Everywhere" entry listed.  I'm guessing that is the one you are recommending I use.  So do I just plug "everywhere" in where the "driver" name goes.

And, of course, I will report back as to whether the new configuration makes the printing problems I am currently having go away.

Thanks.

**Comment by zdohnal** [comment]
> At this point I suspect a problem with HPLIP. There is a debugging parameter I can set there. I can also enable the "save the files" option in CUPS. But I am inclined to take your suggestion and jettison HPLIP. But what do I replace it with?

AFAIU your situation, your printer is located in the same network, so just enable mdns in firewall, start avahi-daemon and the printer will appear in print dialogs supporting temporary queues without your intervention
- if the printer is in different network or you use applications which don't show such printers, you will have to install it manually and it would be great if you reported to them the fact they cannot show all printers available.

With the command I mentioned in the previous comment, once you enabled IPP port on the printer, you can install it via CLI:

$ lpadmin -p <choose_name> -v ipp://<printer_ip_or_hostname>:631/ipp/print -m everywhere -E && sleep 10

or via CUPS Web UI on localhost:631 via browser. In both cases use ```IPP Everywhere``` model for installation and define the URI instead using the found ones.

More info in tips&tricks - https://docs.fedoraproject.org/en-US/quick-docs/cups-useful-tricks/ .

> 
> I did RedHat system administration for a living more than a decade ago. At that time RedHat provided a CLI tool for configuring printers that was easy to use. I was able to connect various HP printers using it with no problem. But then RedHat retired the tool. When I went back to playing with Linux, specifically Fedora, a few years ago I looked around to try to figure out how to connect my HP printer to my Linux system. Ther was DOC on how to use the GUI printer configurator but nothing when it came to CLI printer configuration.

For CLI configuration you can check CUPS Web UI and its help pages - it's running on your localhost:631 by default - especially interesting are http://localhost:631/help/network.html and http://localhost:631/help/admin.html

> If you could point me to the documentation containing the installation procedure that uses one of the methods that will be supported going forward, I would be happy to give it a try. Is it just a matter of doing a "dnf remove hplip" and then following the procedure outlined in the "Installation via CLI commands" section of Quick Docs?

You don't have to remove hplip - just in case you don't want to have several printers in the list, remove the old printer. Then either use a [temporary queue](https://docs.fedoraproject.org/en-US/quick-docs/cups-useful-tricks/#_how_to_setup_cups_temporary_queues_with_network_printer) or install the IPP Everywhere printer, either via [CLI](https://docs.fedoraproject.org/en-US/quick-docs/cups-useful-tricks/#_installation_via_cli_commands) or via CUPS [Web UI](https://docs.fedoraproject.org/en-US/quick-docs/cups-useful-tricks/#_installation_via_cups_web_ui). 

> 
> If so, I have a couple of questions -
> 
>     * When I do a "lpinfo -v" command I get a bunch of entries, including two that look like the ones in the example.  One is a "network dnssd:// . . ." entry.  The other is a "network ipp:// . . .". entry.  So, what do I use for my "device uri"?

I prefer constructing uri as I wrote in the previous comment ```ipp://<printer_IP_or_hostname>:631/ipp/print``` - it does not depend on mDNS as the other found uris and uses IPP as well.

> 
>     * When I do a "lpinfo -m" I get a long list of results.  There are many entries that start "drv:".  I presume these are old fashioned printer drivers. Then there are a bunch that start "lsb/usr/".  I'm not sure what these are. 

Both are classic drivers - the difference is in their source - the former are classic drivers provided by PPD generators, the latter are real files, which exists somewhere on filesystem.

> A "drv:" and an "/lsb/usr" entry seem to match my specific model of HP LaserJet.  but there is also an "everywhere IPP Everywhere" entry listed.  I'm guessing that is the one you are recommending I use.  So do I just plug "everywhere" in where the "driver" name goes.

Yes, if you want to bypass filters from hplip, which can cause the issue, use the "everywhere" model/driver.

**Comment by bachpro1** [comment]
Thanks for all the EXTREMELY helpful information.  My feedback:

- temporary queues -- I saw that but decided that I wanted a permanent link.
- Command example -- That was exactly what I was looking for.
- HPLIP -- It's nice to know that I can leave it installed.  I only have one printer.  So, if I can get it to work through IPP there is no reason to keep HPLIP around.
- Web access -- I don't run a GUI interface.  When I try to access the CUPS web interface from a Windows PC on the local net, it fails to connect.  Is there a way to enable access to admin web site from an external machine?
- Thanks for the info on the "drv:" and "/lsb/usr" entries.  I was pretty sure what the story was with the "drv: entries.  I had my suspicions about the other form.  But it is nice to have confirmation.

**Comment by michaelrsweet** [comment]
@bachpro1 WRT remote access, run the following command:

    cupsctl --remote-admin

If the Windows system is on a different subnet:

    cupsctl --remote-admin --remote-any

**Comment by bachpro1** [comment]
Joy!!!!

Well mostly -

- I have successfully switched my printer over to using IPP.  Other than a few typos, it went smooth as silk.
- I deleted HPLIP from my system.  Unfortunately, that took CUPS with it.
- But after I reinstalled CUPS and re-setup my printer, I was able to get everything back to working.
- I reran both problematic print tests.  Everything now prints perfectly.
- And the printer seems to run more smoothly and print faster.

So, it looks like the problems I was having were caused by HPLIP.  Many years ago, I did system admin work on HP-UX boxes, so at the time I was very familiar with HP process for opening, working, and closing cases.  But that was a long time ago.  I no longer have the kind of account with HP that you need for that sort of thing.  And, since I am not using HPLIP anymore, I now have no interest in chasing bugs in that product, 

The only thing that I can't seem to get to work is the CUPS web interface.  I executed both commands, even though I shouldn't need the second form.  No joy.  I restarted CUPS.  Still no joy.  BTW, if this functionality requires Apache (or another web server) to be installed, then that's the problem.  I'm not into web server development so I didn't install it.

When it comes to Unix/Linux, I am a CLI kind of guy.  If I want to use a GUI then my preferred option is Windows.  So, not having a GUI option for doing CUPS administration is not a problem I am going to worry about.  As a result, I am just going to close this issue.

Again, much, much, much thanks for all the help.
