### ISSUE TITLE
Asan (address sanitizer) issue with 

### ISSUE THREAD

**Issue by janwilmans** [OpenPrinting/cups#437]
I'm getting sanitizer issues when using `cupsEnumDests`.

![image](https://user-images.githubusercontent.com/5933444/180934685-07b5f107-d66e-4eea-be58-6368b60ade97.png)

It looks to me that it reports a leak for every call to the callback function.
First I thought I was getter ownership of `cups_dest_t *dest` (even though the documentation doesn't state that), but free'ing those in the callback (using cupsFreeDests) causes a segfault.

https://www.cups.org/doc/cupspm.html#cupsEnumDests
This example from "Compiling Programs That Use the CUPS API"

```
#include <stdio.h>
#include <cups/cups.h>

int print_dest(void *user_data, unsigned flags, cups_dest_t *dest)
{
  if (dest->instance)
    printf("%s/%s\n", dest->name, dest->instance);
  else
    puts(dest->name);

  // cupsFreeDests(1, dest); // causes segfault
  return (1);
}

int main(void)
{
  cupsEnumDests(CUPS_DEST_FLAGS_NONE, 1000, NULL, 0, 0, print_dest, NULL);
  return (0);
}
```

**Comment by zdohnal** [comment]
Hi @janwilmans ,

what OS and what CUPS version do you use? I've tried the sample code with 2.4.2 and the latest master branch and I'm not able to get the leak - neither via asan or valgrind.

**Comment by janwilmans** [comment]
It's Debian 10, which comes with cups 2.2.1

**Comment by zdohnal** [comment]
@janwilmans the version 2.2.10 is pretty old and I cannot reproduce with the current master branch. Please report this to Debian.

**Comment by janwilmans** [comment]
I investigated some more and I'm seeing flaky results that seems to depend on the detection of printers, it maybe related to what kind of printer is detected. This is for future reference only, it's fine to keep the issue closed.
