### ISSUE TITLE
test pages using US letter on English language systems even when A4 selected

### ISSUE THREAD

**Issue by Stoatwblr** [OpenPrinting/cups#439]
This is a nasty hangover of Adobe's default selections in postscript 

Reminder: Adobe PS 4.3 defaults are US Letter for English and A4 for everything else - a source of HUGE frustration for several billion english speaking computer users around the world

When printing test pages in cups, the printer's paper size selections are ignored and test pages are specified in US letter if the system language is English

Depending on whether the printer has automatic override enabled, the job may (or may not) print, but this is generally a matter of "pot luck" 

This has been a pain in the a*** for more than 40 years for non-american english speaking printing users and I believe I speak for all of us in saying that it would be nice to detect AND USE the locale paper size instead of continuing the dain bramaged behaviour perpetuated by someone at Adobe in the 1970s

The amount of time spent fighting systems and printers which insist on switching to US letter paper sizes at every possible opportunity when 90% of the world uses A4 paper is utterly unbelievable. Millions of manhours must be wasted every year dealing with this issue

**Comment by michaelrsweet** [comment]
@Stoatwblr What version of CUPS are you using? How are you printing the test page? Can you supply a copy of your /var/log/cups/error_log file with debug logging enabled (`cupsctl --debug-logging` then print a test page)?

There should be nothing in the default test page to force a particular page size - it should use the default for the queue.

**Comment by Stoatwblr** [comment]
Michael, I'm using 2.3.3op2 on Rhel9

**Comment by michaelrsweet** [comment]
Also the PPD file in `/etc/cups/ppd` for the queue in question would be useful...

**Comment by Stoatwblr** [comment]
The logfiles rolled while I was woprking on it so I'll have to regenerate it. As it contains potentially site-sensitive info, can I send it to you privately?

As I pointed out in the first posting, this is something that's baked into postscript and PDF thanks to adobe assumptions back in the 1970s. It's also a feature of MS software

**Comment by michaelrsweet** [comment]
@Stoatwblr Sure - msweet AT msweet.org.

**Comment by michaelrsweet** [comment]
@zdohnal No, I never saw anything...

**Comment by zdohnal** [comment]
Ok, I'll close this for now - @Stoatwblr I see you use RHEL 9 - if you have subscription you can contact the official support at https://access.redhat.com or send the requested data to zdohnal AT redhat.com.
