### ISSUE TITLE
So what is causing the problem? The ppd is created when adding the printer with lpadmin and "-m everywhere". Is it the printers fault??

### ISSUE THREAD

**Issue by chalmerssys** [OpenPrinting/cups#44]
So what is causing the problem? The ppd is created when adding the printer with lpadmin and "-m everywhere". Is it the printers fault??

_Originally posted by @chalmerssys in https://github.com/OpenPrinting/cups/issues/20#issuecomment-724522339_

**Comment by chalmerssys** [comment]
I don't think it's got anything to do with papercut, the ipp backend did the same thing.

**Comment by michaelrsweet** [comment]
I'll make a change for it to use the first supported media-source value instead. This just means that the printers "media-col-default" doesn't specify a default tray...

**Comment by michaelrsweet** [comment]
[master be8848be1] Don't use "unknown" default InputSlot value for IPP Everywhere PPDs (Issue #44)
