### ISSUE TITLE
Add quirk for GoDEX printers

### ISSUE THREAD

**Issue by Alt37** [OpenPrinting/cups#440]
By default GoDEX printers on Linux can't print more than ~32 pages at a single run. Printing ends with an error on the printer side. 
Tested with models DT2, DT2x, RT200.   

Quirk found in the installer from the [official GoDEX website](https://www.godexintl.com/downloads?locale=en) (currently it's "[CUPS Printer Driver V1.1.6 _ (Linux system) (For Ubuntu OS only](https://godex.s3-accelerate.amazonaws.com/k04UyXD52ZZz47lj5jWLmg.file?v01)") fixes it  

```
# GoDEX Printer:
0x195f 0x0001 unidir no-reattach
```
The problem with installer is that the file "/usr/share/cups/usb/org.cups.usb-quirks" gets overwritten with updates so users need to create additional file (e.g. "/usr/share/cups/usb/org.cups.additional.usb-quirks"). with an aforementioned content.

**Comment by zdohnal** [comment]
I've sent a PR fixing the issue.
