### ISSUE TITLE
Question: state of support for printing to Windows servers

### ISSUE THREAD

**Issue by sesu-bio** [OpenPrinting/cups#446]
I am investigating ways to print from CUPS to printers that are behind Windows print servers.
I am able to print using raw LPD and SMB queues. However, I am looking for a way that will still be supported by CUPS 3.X.
My attempts to use IPP with the everywhere model have so far been unsuccessful. I wonder whether printing to Windows servers is generally supported and especially what the plans for CUPS 3.X look like.

If this is a supported use case, I can of course provide logs and more details about what I tried so far.

**Comment by michaelrsweet** [comment]
Microsoft's Universal Print Service (available for cloud and local printing) supports IPP Everywhere printing directly. For legacy Windows printing you'll use one or more printer applications that will send jobs to Windows via SMB/spoolss using the appropriate legacy "driver" (typically PCL or PostScript).

**Comment by sesu-bio** [comment]
Thanks! I will have a look at Universal Print.
