### ISSUE TITLE
All other webpages admin, classes, etc header disappears

### ISSUE THREAD

**Issue by voncloft** [OpenPrinting/cups#447]
When visiting localhost:631 Upon clicking other links at the top of the site the header dissapears and instead of being horizontal accross the site its just blue click links going vertical.

**Comment by michaelrsweet** [comment]
What version of CUPS are you using?

What OS/Linux distribution?

**Comment by voncloft** [comment]
2.36

Arch

**Comment by michaelrsweet** [comment]
@voncloft There is no 2.36 version of CUPS.

**Comment by voncloft** [comment]
https://github.com/apple/cups/archive/refs/tags/v2.3.6.tar.gz


I switched over to

https://github.com/OpenPrinting/cups/releases/download/v2.4.2/cups-2.4.2-source.tar.gz

And it works now

Using compiled using https://www.linuxfromscratch.org/blfs/view/svn/pst/cups.html

**Comment by michaelrsweet** [comment]
Oh, Apple's 2.3.6 release... Yes, please stick with OpenPrinting's version because we are actually maintaining CUPS now...
