### ISSUE TITLE
Including /ipp/print in the URI does not work with specified drivers

### ISSUE THREAD

**Issue by mcp292** [OpenPrinting/cups#448]
In my experience, including `/ipp/print` in the URI, as specified by [the docs](https://openprinting.github.io/cups/doc/admin.html):
> `lpadmin -p printername -E -v ipp://11.22.33.44/ipp/print -m everywhere`

results in a misconfigured setup.

`lpstat -p` will reveal:
> The printer configuration is incorrect or the printer no longer exists.

but only after printing. Before printing it seems everything is okay, and `lpoptions -p printer -l` works.

It took a lot of poking to find out that the problem was the trailing `/ipp/print` in the URI. The working command looks like:  
`lpadmin -p printername -E -v ipp://11.22.33.44 -m Model/Driver.ppd.gz`

I am not sure if this is because I am using a printer that does not support `-m everywhere`, but if so, this is not documented and should be.

**Comment by michaelrsweet** [comment]
What printer are you trying to use?

WRT using "/" for (or omitting) the resource path, that doesn't always work. "/ipp/print" is the best-practice path that AirPrint 1.4 requires that will soon be required for IPP Everywhere (for v2.0). Older printers (before standardization) used a variety of paths, but that is impossible to fully document and even harder for ordinary users to discover, so the documentation doesn't focus on that point. The driverless/queueless support in CUPS uses the DNS-SD TXT record to obtain the correct resource path for the user, and if you want to do things by hand you can use the "lpinfo -v" command to discover available printer URIs as well (which is part of the documentation...)

**Comment by mcp292** [comment]
I'm using a Konica Monica Bizhub C360i. I retrospectively believe this was the issue with setting up a Xerox B210 as well.

`lpinfo -v` giving the correct URI makes sense, but the printer doesn't show up there for me.

**Comment by mcp292** [comment]
> lpinfo -v giving the correct URI makes sense, but the printer doesn't show up there for me.

It's worth mentioning that older printers might exclude the resource path (`/ipp/print`). A simple parenthesis statement in that part of the documentation would suffice.
