### ISSUE TITLE
How do I set a cups-shared printer as the default printer using lpadmin? 

### ISSUE THREAD

**Issue by jaimet** [OpenPrinting/cups#452]
I have an old HP1100 (parallel-connect!) connected to an old laptop that I am using as a printer server. I have the drivers installed on that printer server and when I ssh into the printer server, I can print to that printer perfectly. All is good:

```
user@server:~$ lpstat -a
laser accepting requests since Fri 22 Jul 2022 16:50:33 BST
user@server:~$ lp -d laser file.pdf # Success!
```

I set cups on that printer server to share the printer, and from my main computer I can see it and print to it perfectly too. All is still good:
```
user@client:~$ lpstat -e
laser_server
user@client:~$ lp -d laser_server file.pdf # Still success!
```
On my main computer, I have no default printer:
```
user@client:~$ lpstat -d
no system default destination
```
So I try to add the network-detected printer as the default:
```
user@client:~$ sudo lpadmin -d laser_server
lpadmin: The printer or class does not exist.
```
Ok, let's try by specifying its local name (to the print server) along with the name of the print server:
```
user@client:~$ sudo lpadmin -h server -d laser
lpadmin: Forbidden
```
Should I specify a username with sufficient authority?:
```
user@client:~$ sudo lpadmin -U root -h server -d laser
lpadmin: Forbidden
```
How do other people achieve this?

FWIW, both printer server and main computer are running Debian stable with cups version 2.3.3op2-3+deb11u2. (I understand that debian stable has a comparatively old version, but surely this must still be achieveable, no?)

**Comment by michaelrsweet** [comment]
Use the `lpoptions` command to set a default remote printer, e.g.:

    lpoptions -d printer

**Comment by zdohnal** [comment]
@michaelrsweet unfortunately it doesn't work - meaning you can set the temp queue pointing to a shared remote queue:

```
$ lpstat -a
lpstat: No destinations added.
$ lpstat -e
hp_fedora
test2_fedora
$ lpstat -t
scheduler is running
system default destination: test2_fedora
...
```

but printing to it doesn't work:

```
$ lp -P 25 ~/cslh-pravidla2018-22-web.pdf 
lp: Error - ~/.cups/lpoptions file names default destination that does not exist.
```

It happens because we use ```_cupsGetDests()```, which sends get-printer-attributes to ```ipp://localhost:631/printers/<name>```, which doesn't exist for temp queue, so it fails, and further down we check only ```name``` variable, which is NULL in case of default printer, in ```cupsGetNamedDest()```.

To sum it up, we don't look on network when using default printer...
