### ISSUE TITLE
lpinfo and the -U option.

### ISSUE THREAD

**Issue by debiantriage** [OpenPrinting/cups#453]
In [Debian bug #998004](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=998004) Roland Hieber reports a disparity that also existts between the lpinfo manual and lpinfo's Usage information.

The -U option is not present in the manual ([I know why](https://github.com/apple/cups/pull/4822)) but it is in Usage. An oversight?

**Comment by zdohnal** [comment]
Hi Brian!

Yep, I've missed that, thank you! I've fixed it in the latest commit.
