### ISSUE TITLE
lpoptions -d as root

### ISSUE THREAD

**Issue by debiantriage** [OpenPrinting/cups#454]
Yair Yarom submitted [Debian bug #1008053](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008053) and observed that running lpoptions as root does not update /etc/cups/lpoptions but /root/.cups/lpoptions. He was using 2.3.3op2-3+deb11u1 and included a patch in the report.

I observe the same behaviour with 2.4.2 but not with 2.2.10-6+deb10u4.

**Comment by zdohnal** [comment]
Hi Brian,

thank you for the report and the patch! I've created PR with it and once it is reviewed, I'll merge it.
