### ISSUE TITLE
ippeveprinter -F flag doesn't work

### ISSUE THREAD

**Issue by benwiggy** [OpenPrinting/cups#460]
The `ippeveprinter` doesn't seem to respect the` -F` flag for setting the output MIME type. This command:

`ippeveprinter -D file:///Users/Shared/Print -F application/pdf -c /usr/libexec/cups/command/ippeveps -P path/to/myPPD.ppd myPrinterName`

produces PostScript (with .prn file extension) on the first job; and then gives an error for all subsequent jobs:

Validate-Job client-error-attributes-or-values-not-supported (Unsupported media-col collection value.)

I did briefly manage to get PDFs using:

`*cupsFilter: "application/pdf 0 cgpdftopdf"`

in the PPD, but I thought the whole point of using ippeveprinter was to get away from PPDs and filters.

**Comment by michaelrsweet** [comment]
@benwiggy The `-F` option by itself does not force a particular output format, it merely sets the `OUTPUT_TYPE` environment variable for the command to use. The `ippeveps` command only generates PostScript.

If you want to influence the *input* formats, use the `-f` option.

**Comment by benwiggy** [comment]
Thanks. If I may: So when the deprecated parts of CUPS are removed (filters, backends, PPDs), will there be a method of creating a print-to-disk queue? I had hoped that ippeveprinter would be it, but it doesn't look like it.

**Comment by michaelrsweet** [comment]
@benwiggy There are a bunch of ways to do it already, including using ippeveprinter to accept PDF content and store it to a file. But generally speaking the easiest way is to pick "Save as PDF" from the application and/or print dialog.

**Comment by benwiggy** [comment]
A dedicated print-to-file queue is very useful for automation. I've written a backend, but don't want to be caught out when they get removed.
