### ISSUE TITLE
copies

### ISSUE THREAD

**Issue by debiantriage** [OpenPrinting/cups#464]

**Comment by zdohnal** [comment]
Hi Brian ,

the issue description has not been saved, would you mind adding the details about the issue?

Thank you in advance!

**Comment by debiantriage** [comment]
Hello Zdenek,

I have not forwarded any Debian CUPS bugs upstream in the pat week. Nor have I submitted any on my own behalf. Also, I would never use such an uninformative subject header.

I do have two computers connected to the same screen and, on occasion, use the wrong keyboard (the output would not be on the screen). Then, if I pressed a mouse button anf the ponter happened to be on _Comment_...

Closing. Apologies for the unintended noise.
