### ISSUE TITLE
Can CUPS run customized scripts？

### ISSUE THREAD

**Issue by fayehoo** [OpenPrinting/cups#481]
My CUPS is installed in an arm set-top box as a wifi shared printer. I hope that when the set-top box receives the print job， it can flash the LED light on the set-top box, the flashing LED function is coded in a shell script. How can CUPS be set to run the script when receiving the print information.

**Comment by georgeraraujo** [comment]
Looks like a job for [Tea4CUPS](http://www.pykota.com/software/tea4cups/), more specifically with a prehook.
The Debian Wiki has [an entry](https://wiki.debian.org/CUPSTea4CUPS) with a description of the capabilities of Tea4CUPS with examples.
