### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by victor-oliveira1** [OpenPrinting/cups#482]
Hi!

The brazillian portuguese translation is wrong.
The **"Next"** button is translated to **"Continar"**, but the correct is **"Continuar"**.

The files are:

templates/pt_BR/modify-printer.tmpl line 35
templates/pt_BR/choose-make.tmpl line 44
templates/pt_BR/choose-device.tmpl line 44

**Comment by zdohnal** [comment]
Hi Victor!

Thank you for letting us know! I'll update the translations.
