### ISSUE TITLE
"lpoptions -l" doesn't highlight default page size anymore

### ISSUE THREAD

**Issue by AngusMcGyver** [OpenPrinting/cups#491]
Hi,
I recently did an upgrade of Ubuntu 20.04 to 22.04 and with this upgrade cups from 2.3.1 to 2.4.1

Since the upgrade the default page size isn't highlighted by an * anymore via `lpoptions -l`.

cups 2.4.1:
```
# /usr/bin/lpoptions -p HP-LJ-M476dw -l

PageSize/Media Size: Letter Legal Executive FanFoldGermanLegal 4x6 5x8 A4 A5 A6 B5 4x6.Photo Oficio 195x270mm 184x260mm 7.75x10.75 Postcard DoublePostcardRotated Env10 EnvMonarch EnvISOB5 EnvC5 EnvDL Custom.WIDTHxHEIGHT
Duplex/Two-Sided: *None DuplexNoTumble DuplexTumble
InputSlot/Paper Feed: *Auto Tray1 Tray1_Man Tray2 Tray3
HPOption_Duplexer/Duplex Unit: *True False
HPOption_Tray3/Tray 3: *False True
…
```
cups 2.3.1:
```
# /usr/bin/lpoptions -p HP-LJ-M476dw -l

PageSize/Media Size: Letter Legal Executive FanFoldGermanLegal 4x6 5x8 *A4 A5 A6 B5 4x6.Photo Oficio 195x270mm 184x260mm 7.75x10.75 Postcard DoublePostcardRotated Env10 EnvMonarch EnvISOB5 EnvC5 EnvDL Custom.WIDTHxHEIGHT
Duplex/Two-Sided: *None DuplexNoTumble DuplexTumble
InputSlot/Paper Feed: *Auto Tray1 Tray1_Man Tray2 Tray3
HPOption_Duplexer/Duplex Unit: *True False
HPOption_Tray3/Tray 3: *False True
…
```
Notice the difference between `A4` and `*A4` in the first line of each output. The default marking for other options works just fine, only the pagesize is not working correctly.

In the ppd file the default page size seams okay and it also change there, if switched in GUI to another value
```
# cat /etc/cups/ppd/HP-LJ-M476dw.ppd | grep DefaultPageSize
*DefaultPageSize: A4
```

**Comment by debiantriage** [comment]
I have a minimal (test mode plus CUPS) Ubunty 22.04. Settin[g up a queue for the M476 with
```
lpadmin -p testq -v file:/dev/null -E -m postscript-hp:2/ppd/hplip/HP/hp-color_laserjet_pro_mfp_m476-ps.ppd
```
I observe the same as @AngusMcGyver. Adding 

`-o PageSize-default=A4`

to the lpadmin command gets `*A4` from lpoptions.

OTOH, on Debian unstable (which is upstream for Ubuntu) I do not observe the same as @AngusMcGyver with the first lpadmin invocation and have `*Letter` on the PageSize line.

I am inclined to think the issue is distro-specific.

**Comment by debiantriage** [comment]
More investigation: the issue happens on Ubuntu 22.04 with other PPDs from the printer-driver-postscript-hp package.

**Comment by zdohnal** [comment]
Hi all,

I have CUPS 2.4.2 and hplip 3.22.6 on Fedora 37 and I can see the default page size highlighted as well:

```
$ lpadmin -p hpm476 -v file:/tmp/ps -m lsb/usr/HP/hp-color_laserjet_pro_mfp_m476-ps.ppd.gz -E
lpadmin: Printer drivers are deprecated and will stop working in a future version of CUPS.
$ lpoptions -p hpm476 -l
PageSize/Media Size: *Letter Legal Executive FanFoldGermanLegal 4x6 5x8 A4 A5 A6 B5 4x6.Photo Oficio 195x270mm 184x260mm 7.75x10.75 Postcard DoublePostcardRotated Env10 EnvMonarch EnvISOB5 EnvC5 EnvDL Custom.WIDTHxHEIGHT
...
```

I've briefly checked git log between 2.4.1 and 2.4.2 and I didn't see anything relevant at the first sight - please contact Ubuntu maintainers for further help.
