### ISSUE TITLE
job completed, but no paper printed

### ISSUE THREAD

**Issue by robert-everis** [OpenPrinting/cups#492]
I'm running out of ideas, I appreciate any feedback, please let me know what log files to attach.

I have the following setup:

1. CUPS 2.4.1 on Raspberry PI 4
2. EPSON L310, using linux drivers from gutenprint 5.3.3 (no other drivers officially available for this model from EPSON, nor working drivers from manually compiled sources)
3. LAN PC (Win10) who can successfully print (self found drivers)
4. Macbook Pro (12.6) who cannot print (also drivers from gutenprint 5.3.3)

I'm losing my mind to find out why the mac cannot print. The job is successfully sent to CUPS, I can see it in the jobs list and the status is complete! But no paper comes out :)

The printer is working well from the PC, also while printing test jobs from within CUPS.

The printer was previously connected to the PC and shared on LAN, and I was able to print successfully from the macbook in this setup.

Thanks!

**Comment by debiantriage** [comment]
> I'm losing my mind to find out why the mac cannot print. 

I do not know anything about Macbook Pros. However, you have drivers from gutenprint 5.3.3 for an Epson L310 processing a print job on the Mac. The job will result in a file  suitable to be sent to **directly** to the printer.

But my understanding is that this file is sent to CUPS 2.4.1 on Raspberry PI 4. CUPS probably doesn't have a clue what the file type is. Therefore, it cannot be printed.

All processing should take place on the Raspberry PI. That is, no processing on the client.

**Comment by robert-everis** [comment]
Thanks for the reply! 

Fair point! Didn't consider that about gutenprint driver. 

If I use the Epson official driver on the mac when I add the network printer (found via Bonjour), I get "communication error" for the printer, data doesn't seem to reach the raspberry pi queue at all, without any extra error being shown.

But again, it worked fine when the printer was shared over the network from the windows PC, with the same Epson drivers. It also works fine when I plug the printer directly into the mac.

**Comment by debiantriage** [comment]
Having an error_log from The Mac is not going to hurt.

`cupsctl --debug-logging` followed by `>/var/log/cups/error_log` to empty the file. Print and send error_log here after adding **.txt** to the file name.

**Comment by robert-everis** [comment]
Thanks for the help man. 

I think I narrowed it down a little and the problem might be related to the fact that I have CUPS pre-installed & working on my mac and can't seem to get rid of it without a cost. 

I'm attaching the CUPS error_log from the mac - the one from the rasperry pi is empty, even if one line is printed in the access_log whenever I try to send a document. 

Why I can't say I can't get rid of it - I only tried to do a "sudo launchctl unload -w /System/Library/LaunchDaemons/org.cups.cupsd.plist" so far, but when I do this, I can't seem to add a new printer at all - "An error occurred while trying to add the selected device. Bad file descriptor" (s.s.1) - I'm getting this error when I select "Generic PostScript Printer" for the driver. I also don't have the possibility to select something else, as the drivers list is empty when CUPS is disabled on the mac (s.s.2). For the same reason I can't add it manually either, by entering the pi's IP address.

Again, if it helps, it works just fine on a Windows PC in the same LAN.

Thanks again!


<img width="536" alt="Screenshot 2022-10-03 at 13 12 02" src="https://user-images.githubusercontent.com/84085219/193553870-d0035402-10b9-4470-b9f9-850ee8358bcf.png">

<img width="1035" alt="Screenshot 2022-10-03 at 13 13 24" src="https://user-images.githubusercontent.com/84085219/193553879-9d9646ae-8c9e-448e-b0d2-1293d780a24b.png">


[cups_error_log_mac.txt](https://github.com/OpenPrinting/cups/files/9696579/cups_error_log_mac.txt)

**Comment by debiantriage** [comment]
Three filters are invoked. Two (pstoappleps and pstocupsraster) complete successfully. The third fails when sending application/vnd.cups-raster to L310,  presumably because it cannot find the print queue on the Pi:

> Unable to queue job for destination "L310".

We also have

> "DEVICE_URI=ipp://192.168.1.120/"

I would expect that to be something like "DEVICE_URI=ipp://192.168.1.120/printers/L310". This appears to be a setup issue rather than a CUPS bug. On Debian I would possibly be asking to see `lpinfo -v` from the client.

**Comment by robert-everis** [comment]
I tried multiple combinations of ip addresses when manually adding the printer, besides the self discovered one from Bonjour, that's why you see that URI for the device.

I'm attaching the result of lpinfo -v from the macbook. 

Thanks!

<img width="957" alt="Screenshot 2022-10-03 at 17 55 31" src="https://user-images.githubusercontent.com/84085219/193609354-71f68e3b-10a9-4a68-b447-2585b243c687.png">

**Comment by robert-everis** [comment]
But again, the log file is from the macbook - the client - not from the raspberry pi, where the printer is connected. Is it normal to have the print request go through the internal CUPS queue and be forwarded to the destination afterwards? On the windows machine I didn't install CUPS, and the printer is discovered fine over the network and also working fine.

**Comment by debiantriage** [comment]
CUPS on the client does any needed processing and sends the job to the server on the Pi. It is an essential part of the process. Your jobs do not even appear to get there.

`lpinfo -v` shows a dnssd URI. My advice to a Debian user would be to set up a print queue on the Mac with `lpadmin -p testq -v "URI"  -E -m  raw`, substituting for URI, of course. Test printing to testq.

**Comment by robert-everis** [comment]
I managed to make it work!

Sharing my approach maybe somebody else stumbles upon a similar situation.

I went to the cups webinterface on my mac (localhost:631) - which is version 2.3.3 atm btw - Administration - Manage Printers - selected the L310 network printer (shared from the raspberry pi within the same LAN, cups v. 2.4.1) which I previously added from the "Printers & Scanners" main menu from Mac Settings using the only Epson L310 driver available on the list - and clicked on "modify printer". I didn't touch any other setting from this page except the driver - I selected "EPSON L310 Series (en, nl, fr, de, it, ja, pt, pt_PT, es, da, fi, no, sv, pl, ko, zh_TW, zh_CN, ru, ar, th, tr, el, id, cs, hu, ro, ms, uk, he)" from the list instead of the default one that was used (Current Driver - L310 - CUPS+Gutenprint v5.3.3 - IPP Everywhere). 

Thanks for the help Brian!

![Uploading Screenshot 2022-10-04 at 11.41.42.png…]()

**Comment by zdohnal** [comment]
For the record:

The attached error_log contains two jobs - the first fails due filter error:

```
D [03/Oct/2022:12:18:37 +0300] [Job 1] PID 72016 (/Library/Printers/EPSON/InkjetPrinter2/Filter/rastertoescpII.app/Contents/MacOS/rastertoescpII) stopped with status 238 (Unknown error: 138)
```

the second is not even queued:

```
E [03/Oct/2022:13:00:56 +0300] [Job 3] Unable to queue job for destination "L310".
```

The first job is certainly not sent to IPP Everywhere queue (there is a epson driver in play), the second I'm not sure about, because debug logs are missing there... . The last comment mentions the queue was IPP Everywhere on the MacOS, but there is no error_log which shows the fact it was IPP Everywhere and what was the problem with IPP Everywhere, so I'm not able to investigate further.

Closing for now as a question, @robert-everis are you willing and do you have time to dig in further regarding why IPP Everywhere did not work for you? We in OpenPrinting do not support CUPS in the official MacOS repositories, but the possible issue can show us a problem which can be hit even with OpenPrinting CUPS.

**Comment by dpfrakes** [comment]
Not aiming to revive an old thread, just posting to thank @robert-everis for the still-applicable fix and to confirm for posterity my fix for the same issue:

CUPS 2.4.1
EPSON Stylus NX420
Dell XPS 13 running Ubuntu 22.04 (USB-connected, printer discovered, system-discovered drivers installed, print jobs "complete" with no errors and no actual printing done)

| Step | Description | Screenshot |
|-----|----------|----------|
| 1 | Navigate to http://localhost:631, go to Printers tab, select your printer, then select Modify Printer from the dropdown | ![Screenshot from 2024-08-17 22-19-33](https://github.com/user-attachments/assets/0c2b3cb0-b44a-4929-b5ea-17641e4ad15a) |
| 2 | Select your printer under Discovered Network Printers | ![Screenshot from 2024-08-17 22-19-02](https://github.com/user-attachments/assets/a4396b07-fef2-4882-ab2a-8a74fca9984a) |
| 3 | Keep default values and click Continue | ![Screenshot from 2024-08-17 22-19-46](https://github.com/user-attachments/assets/26972233-80e1-41a8-a334-43a092d0d740) |
| 4 | Select your printer model from the Model options and click Modify Printer | ![Screenshot from 2024-08-17 22-20-02](https://github.com/user-attachments/assets/82f3f3b5-a7fd-445c-8ca9-8af5c3c4fcc8) |
| 5 | Print document from GUI or CLI (e.g. `lp ~/Downloads/MyDocument.pdf`) | ![image](https://github.com/user-attachments/assets/29bd0e7c-10ee-4a14-8a14-b1c451aebb05) |
