### ISSUE TITLE
dyesub printing broken on Ricoh geljets

### ISSUE THREAD

**Issue by wyliecoyoteuk** [OpenPrinting/cups#493]
Cups 2.4.1on Ubuntu and Mint
Recently had density and colour issues with Ricoh SG3110DN and an SG7100DN when printing with Dyesub inks (Sawgrass on the 3110 and and InkTec on the 7100). 
Prints very pale, Magenta is red, Red is pale orange, Black is brown, (which suggests composite black).
Overall prints have a greenish cast.
The print itself does not appear that bad, but when Pressing, there is very poor colour transference.
First appeared in Jan 2022, then partially cleared in February, returned in August 2022
Coincidentally, Ricoh RPCS was updated in July 2022
Only way to get proper quality on the SG3110 was to roll back CUPS to before December 2021.
The SG7100, despite looking like an A3 version of the 3100, is in fact RPCS only, so we have been unable to fix this.
The problems also affect the RPCS driver for the 7100 in Windows.

**Comment by wyliecoyoteuk** [comment]
Hi zdhonal, Actually I didn't realise the 7100 is a GDI printer, so that is a bit of a red herring as it is using the Ricoh driver. sorry.
The RPCS drivers were updated by Ricoh in in July, which made me think it was associated.
It was my daughter's partner who fixed it but he rolled back all CUPS packages and filters to be sure of fixing it.
I'll see if I can get more info from him, I thought it was the device-n profile that was the problem, but changing the profiles with colormgr commands made little difference.

**Comment by wyliecoyoteuk** [comment]
Sorry to be slow replying. Here is the information he sent me

I've managed to downgrade cups, I describe it below. I'm just wondering whether I need to remove any custom config before we reboot and try a test print.

Downgrade process:

Claires cups update history
===========================


Raw output from history.log.3.gz
================================


Start-Date: 2022-06-02  06:57:12
Commandline: /usr/bin/unattended-upgrade
Upgrade: libcups2:amd64 (2.3.1-9ubuntu1.1, 2.3.1-9ubuntu1.2), cups-server-common:amd64 (2.3.1-9ubuntu1.1, 2.3.1-9ubuntu1.2), cups-common:amd64 (2.3.1-9ubuntu1.1, 2.3.1-9ubuntu1.2), cups-bsd:amd64 (2.3.1-9ubuntu1.1, 2.3.1-9ubuntu1.2), cups-core-drivers:amd64 (2.3.1-9ubuntu1.1, 2.3.1-9ubuntu1.2), cups-daemon:amd64 (2.3.1-9ubuntu1.1, 2.3.1-9ubuntu1.2), libcupsimage2:amd64 (2.3.1-9ubuntu1.1, 2.3.1-9ubuntu1.2), cups:amd64 (2.3.1-9ubuntu1.1, 2.3.1-9ubuntu1.2), cups-client:amd64 (2.3.1-9ubuntu1.1, 2.3.1-9ubuntu1.2), cups-ipp-utils:amd64 (2.3.1-9ubuntu1.1, 2.3.1-9ubuntu1.2)
End-Date: 2022-06-02  06:57:29

Start-Date: 2022-06-02  06:57:35
Commandline: /usr/bin/unattended-upgrade
Upgrade: gir1.2-webkit2-4.0:amd64 (2.36.2-0ubuntu0.20.04.1, 2.36.3-0ubuntu0.20.04.1), gir1.2-javascriptcoregtk-4.0:amd64 (2.36.2-0ubuntu0.20.04.1, 2.36.3-0ubuntu0.20.04.1)
End-Date: 2022-06-02  06:57:35

Start-Date: 2022-06-02  06:57:41
Commandline: /usr/bin/unattended-upgrade
Upgrade: cups-ppdc:amd64 (2.3.1-9ubuntu1.1, 2.3.1-9ubuntu1.2)
End-Date: 2022-06-02  06:57:44




apt policy - available packages based upon the repo
===================================================

isaac@Quasar:~/apt$ apt policy cups
cups:
  Installed: 2.3.1-9ubuntu1.2
  Candidate: 2.3.1-9ubuntu1.2
  Version table:
 *** 2.3.1-9ubuntu1.2 500
        500 http://gb.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
        100 /var/lib/dpkg/status
     

      500
        500 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 Packages
isaac@Quasar:~/apt$


Notes
1. Installed: 2.3.1-9ubuntu1.2 is currently installed
2. The current version (2.3.1-9ubuntu1.2) is available via the focal-updates/main repo, and the focal-security repo.
3. There is also an older version (2.3.1-9ubuntu1) available in the focal/main repo

Lets try to downgrade the cups packages from version 2.3.1-9ubuntu1.2 to 2.3.1-9ubuntu1

isaac@Quasar:~/apt$ sudo apt install cups=2.3.1-9ubuntu1
[sudo] password for isaac:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 cups : Depends: libcups2 (= 2.3.1-9ubuntu1) but 2.3.1-9ubuntu1.2 is to be installed
E: Unable to correct problems, you have held broken packages.


Downgrading cups alone doesn't work because it depends upon libcups2=2.3.1-9ubuntu1.2
Lets downgrade the other packages too.




cups-bsd=2.3.1-9ubuntu1
cups-client=2.3.1-9ubuntu1
cups-common=2.3.1-9ubuntu1
cups-core-drivers=2.3.1-9ubuntu1
cups-daemon=2.3.1-9ubuntu1
cups-ipp-utils=2.3.1-9ubuntu1
cups-server-common=2.3.1-9ubuntu1
cups=2.3.1-9ubuntu1
libcups2=2.3.1-9ubuntu1
libcupsimage2=2.3.1-9ubuntu1

sudo aptitude install cups-bsd=2.3.1-9ubuntu1 cups-client=2.3.1-9ubuntu1 cups-common=2.3.1-9ubuntu1 cups-core-drivers=2.3.1-9ubuntu1 cups-daemon=2.3.1-9ubuntu1 cups-ipp-utils=2.3.1-9ubuntu1 cups-server-common=2.3.1-9ubuntu1 cups=2.3.1-9ubuntu1 libcups2=2.3.1-9ubuntu1
libcupsimage2=2.3.1-9ubuntu1

APT refuses to downgrade:
=========================

isaac@Quasar:~/apt$ sudo apt install cups-bsd=2.3.1-9ubuntu1 cups-client=2.3.1-9ubuntu1 cups-common=2.3.1-9ubuntu1 cups-core-drivers=2.3.1-9ubuntu1 cups-daemon=2.3.1-9ubuntu1 cups-ipp-utils=2.3.1-9ubuntu1 cups-server-common=2.3.1-9ubuntu1 cups=2.3.1-9ubuntu1 libcups2=2.3.1-9ubuntu1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 cups : Depends: cups-ppdc
E: Unable to correct problems, you have held broken packages.


Lets try with Aptitude, famed for better work arounds with dependencies

isaac@Quasar:~/apt$ sudo aptitude install cups-bsd=2.3.1-9ubuntu1 cups-client=2.3.1-9ubuntu1 cups-common=2.3.1-9ubuntu1 cups-core-drivers=2.3.1-9ubuntu1 cups-daemon=2.3.1-9ubuntu1 cups-ipp-utils=2.3.1-9ubuntu1 cups-server-common=2.3.1-9ubuntu1 cups=2.3.1-9ubuntu1 libcups2=2.3.1-9ubuntu1 

The following packages will be DOWNGRADED:

  cups cups-bsd cups-client cups-common cups-core-drivers cups-daemon cups-ipp-utils cups-server-common libcups2 

The following packages will be REMOVED:

  mypaint-brushes{u} mypaint-data{u} mypaint-data-extras{u} 

0 packages upgraded, 0 newly installed, 9 downgraded, 3 to remove and 111 not upgraded.

Need to get 1,728 kB of archives. After unpacking 13.7 MB will be freed.

The following packages have unmet dependencies:

 cups-ppdc : Depends: cups-common (>= 2.3.1-9ubuntu1.2) but 2.3.1-9ubuntu1 is to be installed

 libcupsimage2 : Depends: libcups2 (= 2.3.1-9ubuntu1.2) but 2.3.1-9ubuntu1 is to be installed

The following actions will resolve these dependencies:

      Remove the following packages:                                         

1)      epson-inkjet-printer-escpr [1.6.11-1lsb3.2 (now)]                    

2)      ipsiosg [4.5.1-0 (now)]                                              

3)      kyodialog [7.0-0 (now)]                                              

4)      libcupsimage2 [2.3.1-9ubuntu1.2 (focal-security, focal-updates, now)]

5)      lsb [11.1.0ubuntu2 (focal, now)]                                     

6)      lsb-printing [11.1.0ubuntu2 (focal, now)]                            

7)      printer-driver-c2esp [27-6 (focal, now)]                             

8)      printer-driver-ptouch [1.4.2-3 (focal, now)]                         

9)      printer-driver-splix [2.0.0+svn315-7fakesync1build1 (focal, now)]    

      Keep the following packages at their current version:                  

10)     cups-common [2.3.1-9ubuntu1.2 (focal-security, focal-updates, now)]  

      Leave the following dependencies unresolved:                           

11)     ubuntu-mate-core recommends printer-driver-c2esp                     

12)     ubuntu-mate-core recommends printer-driver-ptouch                    

13)     ubuntu-mate-core recommends printer-driver-splix                     


q


isaac@Quasar:~/apt$ apt policy cups-ppdc        

cups-ppdc:

  Installed: 2.3.1-9ubuntu1.2

  Candidate: 2.3.1-9ubuntu1.2

  Version table:

 *** 2.3.1-9ubuntu1.2 500

        500 http://gb.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages

        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages

        100 /var/lib/dpkg/status

     2.3.1-9ubuntu1 500

        500 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 Packages




Lets add cups-ppdc to the list



cups-bsd=2.3.1-9ubuntu1 

cups-client=2.3.1-9ubuntu1 

cups-common=2.3.1-9ubuntu1 

cups-core-drivers=2.3.1-9ubuntu1 

cups-daemon=2.3.1-9ubuntu1 

cups-ipp-utils=2.3.1-9ubuntu1 

cups-server-common=2.3.1-9ubuntu1 

cups=2.3.1-9ubuntu1 

libcups2=2.3.1-9ubuntu1 

libcupsimage2=2.3.1-9ubuntu1 

cups-ppdc=2.3.1-9ubuntu1 

sudo apt install cups-bsd=2.3.1-9ubuntu1  cups-client=2.3.1-9ubuntu1  cups-common=2.3.1-9ubuntu1  cups-core-drivers=2.3.1-9ubuntu1  cups-daemon=2.3.1-9ubuntu1  cups-ipp-utils=2.3.1-9ubuntu1  

cups-server-common=2.3.1-9ubuntu1  cups=2.3.1-9ubuntu1  libcups2=2.3.1-9ubuntu1  libcupsimage2=2.3.1-9ubuntu1  cups-ppdc=2.3.1-9ubuntu1 

isaac@Quasar:~/apt$ sudo apt install cups-bsd=2.3.1-9ubuntu1  cups-client=2.3.1-9ubuntu1  cups-common=2.3.1-9ubuntu1  cups-core-drivers=2.3.1-9ubuntu1  cups-daemon=2.3.1-9ubuntu1  cups-ipp-utils=2.3.1-9ubuntu1  cups-server-common=2.3.1-9ubuntu1  cups=2.3.1-9ubuntu1  libcups2=2.3.1-9ubuntu1  libcupsimage2=2.3.1-9ubuntu1  cups-ppdc=2.3.1-9ubuntu1 

Reading package lists... Done

Building dependency tree       

Reading state information... Done

The following packages were automatically installed and are no longer required:

  mypaint-brushes mypaint-data mypaint-data-extras

Use 'sudo apt autoremove' to remove them.

Suggested packages:

  cups-pdf inetutils-inetd | inet-superserver

The following packages will be DOWNGRADED:

  cups cups-bsd cups-client cups-common cups-core-drivers cups-daemon cups-ipp-utils cups-ppdc cups-server-common libcups2 libcupsimage2

0 to upgrade, 0 to newly install, 11 to downgrade, 0 to remove and 111 not to upgrade.

Need to get 1,826 kB of archives.

After this operation, 10.2 kB disk space will be freed.

Do you want to continue? [Y/n] 

isaac@Quasar:~/apt$ sudo apt install cups-bsd=2.3.1-9ubuntu1  cups-client=2.3.1-9ubuntu1  cups-common=2.3.1-9ubuntu1  cups-core-drivers=2.3.1-9ubuntu1  cups-daemon=2.3.1-9ubuntu1  cups-ipp-utils=2.3.1-9ubuntu1  cups-server-common=2.3.1-9ubuntu1  cups=2.3.1-9ubuntu1  libcups2=2.3.1-9ubuntu1  libcupsimage2=2.3.1-9ubuntu1  cups-ppdc=2.3.1-9ubuntu1

Reading package lists... Done

Building dependency tree

Reading state information... Done

The following packages were automatically installed and are no longer required:

  mypaint-brushes mypaint-data mypaint-data-extras

Use 'sudo apt autoremove' to remove them.

Suggested packages:

  cups-pdf inetutils-inetd | inet-superserver

The following packages will be DOWNGRADED:

  cups cups-bsd cups-client cups-common cups-core-drivers cups-daemon cups-ipp-utils cups-ppdc cups-server-common libcups2 libcupsimage2

0 to upgrade, 0 to newly install, 11 to downgrade, 0 to remove and 111 not to upgrade.

Need to get 1,826 kB of archives.

After this operation, 10.2 kB disk space will be freed.

Do you want to continue? [Y/n] Y

Get:1 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 libcupsimage2 amd64 2.3.1-9ubuntu1 [6,208 B]

Get:2 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 cups-ipp-utils amd64 2.3.1-9ubuntu1 [141 kB]

Get:3 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 cups-ppdc amd64 2.3.1-9ubuntu1 [91.3 kB]

Get:4 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 cups-core-drivers amd64 2.3.1-9ubuntu1 [28.1 kB]

Get:5 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 cups-daemon amd64 2.3.1-9ubuntu1 [308 kB]

Get:6 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 cups amd64 2.3.1-9ubuntu1 [259 kB]

Get:7 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 cups-bsd amd64 2.3.1-9ubuntu1 [35.5 kB]

Get:8 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 cups-client amd64 2.3.1-9ubuntu1 [124 kB]

Get:9 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 cups-common all 2.3.1-9ubuntu1 [196 kB]

Get:10 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 libcups2 amd64 2.3.1-9ubuntu1 [233 kB]

Get:11 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 cups-server-common all 2.3.1-9ubuntu1 [403 kB]

Fetched 1,826 kB in 1s (1,789 kB/s)

Preconfiguring packages ...

dpkg: warning: downgrading libcupsimage2:amd64 from 2.3.1-9ubuntu1.2 to 2.3.1-9ubuntu1

(Reading database ... 296813 files and directories currently installed.)

Preparing to unpack .../00-libcupsimage2_2.3.1-9ubuntu1_amd64.deb ...

Unpacking libcupsimage2:amd64 (2.3.1-9ubuntu1) over (2.3.1-9ubuntu1.2) ...

dpkg: warning: downgrading cups-ipp-utils from 2.3.1-9ubuntu1.2 to 2.3.1-9ubuntu1

Preparing to unpack .../01-cups-ipp-utils_2.3.1-9ubuntu1_amd64.deb ...

Unpacking cups-ipp-utils (2.3.1-9ubuntu1) over (2.3.1-9ubuntu1.2) ...

dpkg: warning: downgrading cups-ppdc from 2.3.1-9ubuntu1.2 to 2.3.1-9ubuntu1

Preparing to unpack .../02-cups-ppdc_2.3.1-9ubuntu1_amd64.deb ...

Unpacking cups-ppdc (2.3.1-9ubuntu1) over (2.3.1-9ubuntu1.2) ...

dpkg: warning: downgrading cups-core-drivers from 2.3.1-9ubuntu1.2 to 2.3.1-9ubuntu1

Preparing to unpack .../03-cups-core-drivers_2.3.1-9ubuntu1_amd64.deb ...

Unpacking cups-core-drivers (2.3.1-9ubuntu1) over (2.3.1-9ubuntu1.2) ...

dpkg: warning: downgrading cups-daemon from 2.3.1-9ubuntu1.2 to 2.3.1-9ubuntu1

Preparing to unpack .../04-cups-daemon_2.3.1-9ubuntu1_amd64.deb ...

Unpacking cups-daemon (2.3.1-9ubuntu1) over (2.3.1-9ubuntu1.2) ...

dpkg: warning: downgrading cups from 2.3.1-9ubuntu1.2 to 2.3.1-9ubuntu1

Preparing to unpack .../05-cups_2.3.1-9ubuntu1_amd64.deb ...

Unpacking cups (2.3.1-9ubuntu1) over (2.3.1-9ubuntu1.2) ...

dpkg: warning: downgrading cups-bsd from 2.3.1-9ubuntu1.2 to 2.3.1-9ubuntu1

Preparing to unpack .../06-cups-bsd_2.3.1-9ubuntu1_amd64.deb ...

Unpacking cups-bsd (2.3.1-9ubuntu1) over (2.3.1-9ubuntu1.2) ...

dpkg: warning: downgrading cups-client from 2.3.1-9ubuntu1.2 to 2.3.1-9ubuntu1

Preparing to unpack .../07-cups-client_2.3.1-9ubuntu1_amd64.deb ...

Unpacking cups-client (2.3.1-9ubuntu1) over (2.3.1-9ubuntu1.2) ...

dpkg: warning: downgrading cups-common from 2.3.1-9ubuntu1.2 to 2.3.1-9ubuntu1

Preparing to unpack .../08-cups-common_2.3.1-9ubuntu1_all.deb ...

Unpacking cups-common (2.3.1-9ubuntu1) over (2.3.1-9ubuntu1.2) ...

dpkg: warning: downgrading libcups2:amd64 from 2.3.1-9ubuntu1.2 to 2.3.1-9ubuntu1

Preparing to unpack .../09-libcups2_2.3.1-9ubuntu1_amd64.deb ...

Unpacking libcups2:amd64 (2.3.1-9ubuntu1) over (2.3.1-9ubuntu1.2) ...

dpkg: warning: downgrading cups-server-common from 2.3.1-9ubuntu1.2 to 2.3.1-9ubuntu1

Preparing to unpack .../10-cups-server-common_2.3.1-9ubuntu1_all.deb ...

Unpacking cups-server-common (2.3.1-9ubuntu1) over (2.3.1-9ubuntu1.2) ...

Setting up cups-server-common (2.3.1-9ubuntu1) ...

Setting up cups-common (2.3.1-9ubuntu1) ...

Setting up libcups2:amd64 (2.3.1-9ubuntu1) ...

Setting up cups-ipp-utils (2.3.1-9ubuntu1) ...

Setting up cups-ppdc (2.3.1-9ubuntu1) ...

Setting up cups-client (2.3.1-9ubuntu1) ...

Setting up libcupsimage2:amd64 (2.3.1-9ubuntu1) ...

Setting up cups-daemon (2.3.1-9ubuntu1) ...

Setting up cups-core-drivers (2.3.1-9ubuntu1) ...

Setting up cups (2.3.1-9ubuntu1) ...

Updating PPD files for cups ...

Setting up cups-bsd (2.3.1-9ubuntu1) ...

Processing triggers for ufw (0.36-6ubuntu1) ...

Processing triggers for systemd (245.4-4ubuntu3.15) ...

Processing triggers for man-db (2.9.1-1) ...

Processing triggers for libc-bin (2.31-0ubuntu9.7) ...





Checking the policy now shows downgraded versions

isaac@Quasar:~/apt$ apt policy cups-ppdc

cups-ppdc:

  Installed: 2.3.1-9ubuntu1

  Candidate: 2.3.1-9ubuntu1.2

  Version table:

     2.3.1-9ubuntu1.2 500

        500 http://gb.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages

        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages

 *** 2.3.1-9ubuntu1 500

        500 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 Packages

        100 /var/lib/dpkg/status


I may have to mark these packages as on "hold" to prevent future upgrades.

Isaac

**Comment by zdohnal** [comment]
@wyliecoyoteuk thank you for letting me know!

Were you able to get the good result with the downgraded CUPS? Are you able to get CUPS debug logs for working and broken cases?

**Comment by michaelrsweet** [comment]
No response, closing.
