### ISSUE TITLE
Drive addition

### ISSUE THREAD

**Issue by 18690819111** [OpenPrinting/cups#498]
Hello, I hope the printer that supports Canon MF230 can not be found in the driver list.

**Comment by 18690819111** [comment]
zheng18690819111@Gmail.com

**Comment by zdohnal** [comment]
Hi,

I was not able to find your printer model on the internet - the closest ones are Canon ImageRunner MF232w and Canon PIXMA MP230, and both support AirPrint, so you don't need a specific driver to make them work.

**Comment by 18690819111** [comment]
Hello, I'm glad you saw my question. However, the driver of my Canon MF230 is common to the MF232. Unfortunately, my Canon MF230 does not have the function of space printing. Can you help me add this model of printer?
