### ISSUE TITLE
Unable to print on Canon MFP with OpenPrinting PPD driver

### ISSUE THREAD

**Issue by bfg01** [OpenPrinting/cups#511]
Printer is Canon iR-ADV 4245.

I got the PPD from here (well, actually tried **both** there):
https://openprinting.org/printer/Canon/Canon-iR-ADV_4245_4251
then added it with "lpadmin" and the socket://<ip_address> URI, which succeeded with exit code 0.

Then I tried printing the CUPS testing doc with "lp" command, and the result I get is:
A single page with just these -truncated- lines:
```
%!PS-Adobe-3.0
              %Produced by poppler pdftops version: 22.01.0 (http://poppler.free
```

followed by infinite blank pages popping out and out until I cancel the print job.
Trying to use any -o options didn't change the result.

So I then tried with Canon's CQue drivers from canon-europe website.
The package has 3 available PPDs for this MFP: PostScript, PCL, PXL.

Canon's PS didn't work at all: "lpstat" does show a print job running, MFP does say "recieving data...", but other than this absolutely nothing happens. MFP gets back to idle state, and trying to "cancel" the print job pops an error "this job was already finished, cannot cancel". Using any combination of this PPD's -o options makes no difference neither.

PXL does work, but not properly: it totally ignores any of its -o options.

Leaving just the PCL driver, which is the only one properly working.

I didn't feel like trying the Canon UFR II drivers, at least right now; they don't seem to use PPDs at all and it's actually a whole installer on its own...

Is the OpenPrinting PPD not working anymore?

Thanks for your attention.

**Comment by zdohnal** [comment]
Hi @bfg01 !

Thank you for reporting the issue!

I would like to ask you for the same thing as I wanted for #510 - error_log.txt with debug logs during printing (when you print to the queue )  :)

But this printer you have connected via network, so if you enabled IPP on the printer, you should be able to use it without PPD.

You can check whether IPP support is alright via:

```
$ ipptool -tv ipp://<ip_address>:631/ipp/print get-printer-attributes.test
```

and if it was successful, then create the printer via:

```
$ lpadmin -p <name> -v ipp://<ip_address>:631/ipp/print -m everywhere -E
```

**Comment by bfg01** [comment]
So I did the same process, trying in 2 distros: Leap 15.4 itself and Debian 11.
Logs attached with .txt suffix.

In Debian, the only difference was the content of the printed sheet:
```
%!PS-Adobe-3.0
               %%Invocation: gs -q -dNOPAUSE -dBATCH -dSAFER -dNOMEDIAATTRS -sstd
```

What I use for adding printer:
`lpadmin -p canon -Ev socket://192.168.120.233[/?contimeout=30] -i path/to/Canon-iR-ADV_4245_4251-Postscript-Canon.ppd`

What I use to for printing CUPS testing page:
`lp -d canon /usr/share/cups/data/testprint`

The **only** working thing was @jsmeix 's advice of using "-o raw" mentioned here:
#510
Albeit with the testing page this just prints:
```
#PDF-BANNER
                Template default-testpage.pdf
                                              Show printer-name printer-info printer-l
```

In nutshell, other than "-o raw" option, any document gives this issue...

[error_log-Leap.txt](https://github.com/OpenPrinting/cups/files/9882555/error_log-Leap.txt)
[error_log-Debian.txt](https://github.com/OpenPrinting/cups/files/9882558/error_log-Debian.txt)

**Comment by bfg01** [comment]
I searched all around the printer's settings:

Status Monitor:
--Device Features:
----Basic Features:
------Other: PDL: UFR II, PCL

Function Settings:
--Common Settings: (no PS-related stuff)
--Printer: (no PS-related stuff)

So strangely this "particular piece" has no existing PS support at all.
Canon's website also says that, while driver updates still been seemingly released, this is not the case for firmware: "latest firmware is the one already installed, no updates here".

We got this MFP through a local renting reseller, who also does the maintenance jobs/service once in a while
Not sure if this could be related...

**Comment by zdohnal** [comment]
@bfg01 in that case I would recommend asking the reseller, whether the device has a possibility of turning on PostScript support, otherwise this specific driver won't work :( .

In case you would like to use a PCL driver from system instead from the one from Canon, you can try the ones from foomatic, gutenprint or CUPS - here are the [models]https://github.com/OpenPrinting/cups/files/9907914/pcl-models.txt) from ```lpinfo -m | grep -i generic | grep -i pcl``` from my Fedora - gutenprint uri will different based on the version you have. I would try PCL 5, PCL 5e and PCL 6 drivers first, the older PCLs are for much older devices IMHO.
