### ISSUE TITLE
Request: Job type "Send to Document Server" to web interface

### ISSUE THREAD

**Issue by AbdelazizSharaf001** [OpenPrinting/cups#513]
### Summary
Need : "Send to Document Server" jop type
Target machine : any (or fix if existing for Ricoh)
Target interface : web interface

### Issue
I tried going throgh this [link](http://support.ricoh.com/bb_v1oi/pub_e/oi_view/0001038/0001038625/view/ps3/unv/0090.htm) to send to the document server 
- From windows and it was successful
- From many applications on linux (didn't even find the option unless from WPS PDF)
    and the result was just printing (the file never saved to printing server)
- From CUPS web interface `http://localhost:631/`
    never found options for sending to document server

### Suggestions
1. Add an option for printing from web interface (at least using PDF or LIST OF IMAGES)
2. Add this feature to "Send to Document Server" to `web interface`, `cli` and `Programming API`
    so that it's applicable from CUPS itself independantly and from any application
3. Switch to GUI application (Long Term)

### Notes
- These suggestion are based on what I lack as a user
- I understand that this is a printing server, but find no capable application of managing the jop,
    so I thought about the source (CUPS) and thus: why not to have it as a printing application besides server
- I'm not comfortable with printing with cups yet (I can't even install scanner for my all-in-one machine)
    So, If these are existing features, I'll appriciate any guidance

**Comment by michaelrsweet** [comment]
So there are a LOT of GUI applications that can print through CUPS, not to mention "lp" and "lpr" from the command-line.

Adding a web interface for printing files has been requested before, but there are a lot of issues we'd need to address (starting first with security) to ensure that it would be secure.

**Comment by AbdelazizSharaf001** [comment]
Then what about send to Document server? I think it's strait forword and the same way for alll types of printers that support it, and for security it just need to ensure file type and validate name ..
is it applicable ?
or even any way from command line ..
I realy have 3 office suites installed to test that, and one of them has a windows version (were it works fine) and 2 pdf readers that is linked to system

**Comment by AbdelazizSharaf001** [comment]
I finally catched a working tool
`Okular` did a perfect job with Document Server
however I still think having a printing interface is a very good way to improve CUPS
While I'm not even famalier with C, I wish I could contribute either in CUPS 2.x or 3.x some how

**Comment by zdohnal** [comment]
@michaelrsweet do you think it is something for 2.x series? IMHO it is not critical, so would move it to 3.x.

**Comment by AbdelazizSharaf001** [comment]
> @zdohnal We have to decide whether this is something we want to support at all.

If it's for long term support that would be hopeful for a fully functional printing solution

**Comment by zdohnal** [comment]
@AbdelazizSharaf001 the web interface is usually just configuration tool for now and since it is planned for to be available only on CUPS Sharing module, it probably stays this way for now.

It would be great to have all printing functionality in the web interface as well, but we usually just provide API and CLI tools which can be used for printing, and leave the GUI printing on the applications. So for me printing via web UI alone is nice to have feature for now and our focus is currently elsewhere.

What we could consider implementing the job type into libcups, enhance CLI tools to support it and any GUI application using libcups could use 'Send to document server' job type - files would be saved in /var/spool/cups, connected to one job object, and once client sends print command, all files are sent to the destination - @michaelrsweet WDYT? It would be nice to have again, but slightly more important than implementing it in web UI - because I don't recall that we implement such functionality.

**Comment by michaelrsweet** [comment]
IPP has no explicit notion of document servers or job types. Without fully understanding *what* you mean by "send to document server", it is hard to have an opinion. In any case, it MUST be defined in terms of IPP, otherwise it is a non-starter.

**Comment by zdohnal** [comment]
The idea would be:

'Document server' would local or remote (based on ServerName directive) IPP server (cupsd/IPP printer), client can be GUI application, CLI tool or web client. Document server would have the directive ```DocumentSpace``` which will define how much space saved documents can take, so we can prevent eating up too much memory. ```DocumentRetentionTime``` directive will define for how long we keep the files saved (timer would start from the last uploaded file).

1. The client sends a new IPP operation ```Add-document``` with required attributes ```docname``` and ```docsize``` for every file which will be in the transaction, and optional attribute ```job-id``` (in case there is/are other documents already for the specific job)
2. The server checks whether it can store the document (checks the document size and free pool size) -> if it fits, server does Create-Job operation with ```job-hold-until=infinite``` attribute&value.
4. The server returns job ID on success, or NO_SPACE/ERROR_CREATE_JOB on error, to the client
5. The client starts sending documents for storage with IPP Send Document operation 
6. The client can send other documents via ```Add-Document``` operation with ```docname``` and ```docsize``` attributes and together with ```job-id``` it could add a new files into a job
7. Once user uploads all files he wants to print in one job, the client sends IPP Set Job Attributes request to resume the job

It is just a pseudocode for the process, which can be enhanced in case printer vendors see a benefit in this function.

Or simply adjust ```lp -i <job-id>``` to accept files as well, which would result into adding new files to the job, and once all files in place, the user just resumes the job.

**Comment by michaelrsweet** [comment]
@zdohnal A Client can already create a multi-document job, hold it, etc. over a period of time (default is 5 minutes but you can configure the multiple document timeout value with the `MultipleOperationTimeout` directive.

There are pending and published PWG standards for retaining/saving complete jobs for reprinting on the books already as well.

**Comment by michaelrsweet** [comment]
I think for now I want to close this out - *if* we add something for this it will be in the 3.0 timeframe for cups-sharing.
