### ISSUE TITLE
Samsung M2070W prints PDF as a text-file

### ISSUE THREAD

**Issue by Heimdell** [OpenPrinting/cups#521]
**Setup**

OS: Ubuntu-20.04.03
CUPS: 2.3.1
Printer: Samsung M2070W

I have my printer installed both in default manner and via PPD torn off oficial Samsung driver from their site. I also tried installing their driver via install-script, to no difference.

**What happens**

In both cases, when I attempt to print a PDF file, it produces ![image](https://user-images.githubusercontent.com/1784505/200380888-42077257-7ae2-42a0-ac52-e6122db0e246.png)

The test page looks like ![image](https://user-images.githubusercontent.com/1784505/200381161-b1dd1c44-6e4d-4b6e-8cf5-83f125ed6e47.png)

**What should happen**

A PDF-file printed.

**Additional steps**

```
~/Downloads/uld » cat /var/log/cups/error_log
...
E [19/Oct/2022:19:06:38 +0400] Samsung-M2070W: File \"/usr/lib/cups/filter/rastertospl\" not available: No such file or directory
```
so I added one from some cups-related package.

`gpep cups-raster` on PPD file returns
```
*cupsFilter:  "application/vnd.cups-raster 0 rastertospl"
```

@alexpevzner recommended pinging @tillkamppeter, so I do.

**Comment by georgeraraujo** [comment]
I have some M2070s (sans W), and they require the `libcupsimage2` package. Install it and try again.

**Comment by zdohnal** [comment]
Hi @Heimdell ,

have the @georgeraraujo piece of advice helped you? If it hasn't, it would be great if you copied the ```/var/log/cups/error_log``` file into ```error_log.txt``` and attached it here together with your PPD (from ```/etc/cups/ppd``` - add .txt suffix as well).

Thank you in advance!

**Comment by Heimdell** [comment]
Hi! No, I've installed the library and it still produces text dumps instead of printing.

[error_log.txt](https://github.com/OpenPrinting/cups/files/10238166/error_log.txt)
[m2070w.ppd.txt](https://github.com/OpenPrinting/cups/files/10238178/m2070w.ppd.txt)

**Comment by yuvraj-aseri** [comment]
Hiii @Heimdell ,

Could you please post your `/var/log/cups/error_log` file after a job with the problem? Set CUPS to debug logging before sending the job (`cupsctl --debug-logging`) and when attaching your error_log after the job, rename the file to have a `.txt` extension so that GitHub accepts it.

**Comment by yuvraj-aseri** [comment]
@Heimdell ,

Please provide required details.

**Comment by michaelrsweet** [comment]
No response from reporter, closing.
