### ISSUE TITLE
unable to encrypt connection: Unable to create server credentials.

### ISSUE THREAD

**Issue by Firgen** [OpenPrinting/cups#529]
When I try to print over the network, for example from an android device, I get an error and `/var/log/cups/error_log` has this: `unable to encrypt connection: Unable to create server credentials.`

It has probably something to do with the reintroduction of LibreSSL/OpenSSL in 2.4.2 because 2.4.1 works.

**Comment by sevens** [comment]
Same issue when trying to open the web-interface over HTTPS; using plain old HTTP works fine.  Downgrading to 2.3.3 (don't have 2.4.1 easily available) fixed it.

OS: Slackware64-15.0

**Comment by oynqr** [comment]
This happens because the server keychain path is always set to the MacOS one when building with OpenSSL. The following patch fixes this, but a proper fix would probably be a bit more involved.
```
--- a/scheduler/conf.c
+++ b/scheduler/conf.c
@@ -605,11 +605,11 @@ cupsdReadConfiguration(void)
   ClassifyOverride  = 0;
 
 #ifdef HAVE_TLS
-#  ifdef HAVE_GNUTLS
+#  if defined HAVE_GNUTLS || defined HAVE_OPENSSL
   cupsdSetString(&ServerKeychain, "ssl");
 #  else
   cupsdSetString(&ServerKeychain, "/Library/Keychains/System.keychain");
-#  endif /* HAVE_GNUTLS */
+#  endif /* HAVE_GNUTLS || HAVE_OPENSSL */
 
   _httpTLSSetOptions(_HTTP_TLS_NONE, _HTTP_TLS_1_0, _HTTP_TLS_MAX);
 #endif /* HAVE_TLS */
```

**Comment by michaelrsweet** [comment]
That's actually a reasonable fix.

**Comment by michaelrsweet** [comment]
[master 8bec88ade] Fix default cupsd keychain with OpenSSL (Issue #529)
