### ISSUE TITLE
CUPS API: Printing to a printer.

### ISSUE THREAD

**Issue by SonnyX** [OpenPrinting/cups#57]
I'm trying to look for some clarification on what the correct way to print to a printer using the C API.
As far as I understood from https://github.com/apple/cups/issues/5271, the raw queues and drivers are dissapearing and that any `dest` api should be the way to go.
I've read somewhere that by sending an ipp request cups would set up an temporary queue itself, however I have not yet figured out how, as after connecting to the destination, I cannot get `cupsCopyDestInfo` to return anything but a `NULL pointer`.
Therefor I am never able to create a `cupsCreateDestJob`, as I am unable to provide `cups_dinfo_t`.

Code flow I have so far:
```
cupsGetDests -> take a dest -> cupsConnectDest -> cupsCopyDestInfo -> x -> cupsCreateDestJob -> cupsFreeDests
```

The cups version I am using is `2.2.10`
Thanks in advance for any help.

**Edit: Additional question:** 
is this route even the correct one? I'm trying to be able to print automatically to any/most printer / labelprinter on a network, and cups seems to be perfect for this, however the entirety of having to select an driver per printer seems to be a bit of a detriment, hence I hoped the dest api could help me out.

**Comment by michaelrsweet** [comment]
@SonnyX Can you provide some code snippets showing what you are trying to do. In general, this should all just work...

**Comment by SonnyX** [comment]
Sure, I was writing C# Interops, so it may not seem as familiar, and I've omitted most of the classes, but this is the important bits:
```csharp
        static void Main(string[] args)
        {
            ICups cups = new Cups();
            
            cups.SetHostname("127.0.0.1:631");
            cups.SetUser("print");
            cups.SetPassword("print");
            
            // Destinations
            Destinations destinations;
            while ((destinations = cups.GetDestinations()).Inner.Count == 0)
            {
                Console.WriteLine("Couldn't find printers.");
                Thread.Sleep(2000);
            }
            Console.WriteLine(JsonSerializer.Serialize(destinations.Inner));

            Console.WriteLine(cups.GetUser()); // returns "print"
            cups.ConnectAndPrint(destinations.Last());
        }

        void ICups.ConnectAndPrint(IntPtr destinationPtr)
        {
            Console.WriteLine($"Before connect: {Functions.CupsLastError()} - {LastErrorDescription()}");
            CancellationTokenSource cts = new CancellationTokenSource();
            CancellationTokenInterop cancel = new CancellationTokenInterop(cts.Token);
            
            IntPtr connectionPtr = Functions.cupsConnectDest(destinationPtr, EDestinationFlags.Device, 30_000, cancel, null, null, Null);
            Http connection = new Http(connectionPtr);
            Console.WriteLine($"After connect: {Functions.CupsLastError()} - {LastErrorDescription()}");
            
            IntPtr destinationInfo = Functions.cupsCopyDestInfo(connectionPtr, destinationPtr);

            Console.WriteLine($"cupsCopyDestInfo: {Functions.CupsLastError()} - {LastErrorDescription()}");

            EIppStatus status = Functions.cupsCreateDestJob(connectionPtr, destinationPtr, destinationInfo, out int jobId, "Title", 0, Null);
            Console.WriteLine($"cupsCreateDestJob: {status.ToString()}, {Functions.CupsLastError()} - {LastErrorDescription()}");
            // todo

            connection.Close();
        }
```

**Comment by michaelrsweet** [comment]
@SonnyX A bit hard to help with this since *we* don't provide or support any sort of C# interfaces, but I *think* that you are trying to connect to the device, when you should be connecting to the spooler:

```
IntPtr connectionPtr = Functions.cupsConnectDest(destinationPtr, EDestinationFlags.Device, 30_000, cancel, null, null, Null);
```

Without knowing how your C# wrapper defines the constants, `cupsConnectDest` should be passed `CUPS_DEST_FLAGS_NONE`. You only connect to the device to get ready media or do maintenance things directly with an IPP printer. Without the local queue you probably won't be able to print anything.

**Comment by SonnyX** [comment]
It's a 1 to 1 conversion at the moment, with some updated namings.
I'm not expecting any help on any of the C# interfaces either, as I'm building those myself.
I am mostly confused on what the newest/best way to use CUPS programatically is, since I did not see any way of adding a new local (temporary) queue using the C API.

**Comment by michaelrsweet** [comment]
As long as the cups_dest_t structure contains all of the values from cupsGetDests or cupsEnumDests, you should be able to connect with cupsConnectDest and have it auto-create a queue for you.

Ideally you should be running the latest CUPS release, and it is certainly possible there could have been a bug in libcups concerning this that was subsequently fixed (2.2.10 is over two years old, 2.2.13 was released at the end of 2019, 2.3.3op1 is the most current for Linux). What might be useful is for you to try a simple C application using the CUPS API to verify *that* much is working.

**Comment by SonnyX** [comment]
In C I have the same issue, I've upgraded cups to `2.3.3op1`.

To be perfectly clear: 
I am trying to print to a printer, that I have not configured, hoping cups will create a temporary queue and do whatever configuration automatically (using IPP everywhere or a preferred driver).


```c
#include <stdio.h>
#include <cups/cups.h>

int main(void) {
  printf("Setting server hostname\n");
  cupsSetServer("127.0.0.1:631");
  printf("Setting username\n");
  cupsSetUser("print");
  cups_dest_t *dests;
  printf("Getting destinations\n");
  int amount = cupsGetDests(&dests);
  while (amount == 0) {
    printf("Found no destinations, retrying in 2 seconds.\n");
    cupsFreeDests(amount, dests);
    sleep(2);
    amount = cupsGetDests(&dests);
  }
  printf("Found destinations, including: %s\n", dests[amount-1].name);
  printf("Error report: 0x%x - %s\n", cupsLastError(), cupsLastErrorString());
  int cancel = 0;
  http_t *connection = cupsConnectDest(&dests[amount-1], CUPS_DEST_FLAGS_NONE, 30000, &cancel, NULL, 0, NULL, NULL);
  printf("Connection: %x, Error report: 0x%x - %s\n", connection, cupsLastError(), cupsLastErrorString());

  cups_dinfo_t *dinfo = cupsCopyDestInfo(connection, &dests[amount-1]);
  printf("Destination Info: %x, Error report: 0x%x - %s\n", dinfo, cupsLastError(), cupsLastErrorString());
  cupsFreeDests(amount, dests);
  return 0;
}
```
Output:
```bash
Setting server hostname
Setting username
Getting destinations
Found destinations, including: HP_PageWide_Pro_477dw_MFP_omitted_
Error report: 0x0 - No such file or directory
Connection: 0, Error report: 0x500 - No such file or directory
Destination Info: 0, Error report: 0x500 - No such file or directory
```

**Comment by SonnyX** [comment]
Allright, figured out my issue with that.
I'm connecting to a cups system that's not technically on my system (it's in a docker container), this somehow prevents me from connecting.
Please let me know if you know how to allow external IP's to communicate with cups.

**Comment by michaelrsweet** [comment]
@SonnyX OK, so some preliminaries:

0. *When you have a totally non-standard configuration, it helps to tell us about it up front...*

1. There is no "preferred driver" support for temporary queues. The printer has to support IPP Everywhere or AirPrint, which is how we detect it in the first place.

2. Temporary queues can only be created via domain socket or loopback address. This is a security feature that cannot be overridden.

That said, what you are doing *should* work. Try compiling CUPS with debug printf support, e.g.:

    ./configure --enable-debug --enable-debug-printfs && make clean && make all && make install

Then run your test program with:

    CUPS_DEBUG_LOG=- CUPS_DEBUG_LEVEL=4 your-test-program

and attach the results.

**Comment by SonnyX** [comment]
My apologies, with my last comment, I changed where I run my program from outside the docker container, to inside of it, with that change I did manage to connect to the destination and create a temporary queue. Hence I said I figured out my issue.

It is sad to hear that the security feature cannot be overridden as it would make containerization of cups more feasible for wide-spread adoption. As I doubt I (and others) can work around this security feature.

Thanks for the info, my issues are resolved for now.

**Comment by michaelrsweet** [comment]
@SonnyX The security restriction (only local connections can make temporary queues) protects against (known) trivial attacks against cupsd, which could easily lead to jobs being redirected elsewhere, DoS, etc. One of the reasons of using container technology is to improve security and confidentiality through isolation, so why would you want to give that up?

**Comment by michaelrsweet** [comment]
I'll also note that Ubuntu is going to be putting CUPS in a snap, which is another type of containerization and provides similar but lighter-weight isolation that doesn't have the "I'm not running locally" issue. A docker container is effectively a VPS.
