### ISSUE TITLE
Can't Find Legacy Printers Default Drivers

### ISSUE THREAD

**Issue by JasonFengHot** [OpenPrinting/cups#571]
Can't Find Legacy Printers Default Drivers

Driver | PPD Name
-- | --
Dymo Label Printers | drv:///sample.drv/dymo.ppd
Intellitech Intellibar | drv:///sample.drv/intelbar.ppd
EPSON 9-pin Series | drv:///sample.drv/epson9.ppd
EPSON 24-pin Series | drv:///sample.drv/epson24.ppd
Generic PCL Laser Printer | drv:///sample.drv/generpcl.ppd
Generic PostScript Printer | drv:///sample.drv/generic.ppd
HP DeskJet Series | drv:///sample.drv/deskjet.ppd
HP LaserJet Series | drv:///sample.drv/laserjet.ppd
OKIDATA 9-Pin Series | drv:///sample.drv/okidata9.ppd
OKIDATA 24-Pin Series | drv:///sample.drv/okidat24.ppd
Zebra CPCL Label Printer | drv:///sample.drv/zebracpl.ppd
Zebra EPL1 Label Printer | drv:///sample.drv/zebraep1.ppd
Zebra EPL2 Label Printer | drv:///sample.drv/zebraep2.ppd
Zebra ZPL Label Printer | drv:///sample.drv/zebra.ppd

./configure --enable-libusb --prefix=/root/Github_OpenPrinting_cups/build --enable-debug-printfs --with-components=all && make && make install

root@develop:~/Github_OpenPrinting_cups/build# ./sbin/lpinfo -m
lpinfo: Internal Server Error

**Comment by michaelrsweet** [comment]
OK, assuming that cupsd is actually running, can you provide a debug error_log file that shows when this command is run?

**Comment by JasonFengHot** [comment]
![image](https://user-images.githubusercontent.com/27603930/205600773-3f57bd25-8d8d-46e7-91db-9b4b8bdca42e.png)

Sorry! I Can't Find Any error_log Files

**Comment by JasonFengHot** [comment]
> OK, assuming that cupsd is actually running, can you provide a debug error_log file that shows when this command is run?

I [07/Dec/2022:11:41:04 +0000] Listening to [v1.::1]:631 (IPv6)
I [07/Dec/2022:11:41:04 +0000] Listening to 127.0.0.1:631 (IPv4)
I [07/Dec/2022:11:41:04 +0000] Listening to /root/Github_OpenPrinting_cups/build/var/run/cups/cups.sock (Domain)
I [07/Dec/2022:11:41:04 +0000] Remote access is disabled.
D [07/Dec/2022:11:41:04 +0000] Added auto ServerAlias develop
I [07/Dec/2022:11:41:04 +0000] Loaded configuration file "/root/Github_OpenPrinting_cups/build/etc/cups/cupsd.conf"
D [07/Dec/2022:11:41:04 +0000] Using keychain "/Library/Keychains/System.keychain" for server name "develop".
I [07/Dec/2022:11:41:04 +0000] Configured for up to 100 clients.
I [07/Dec/2022:11:41:04 +0000] Allowing up to 100 client connections per host.
I [07/Dec/2022:11:41:04 +0000] Using policy "default" as the default.
D [07/Dec/2022:11:41:04 +0000] cupsdMarkDirty(--p--)
D [07/Dec/2022:11:41:04 +0000] cupsdSetBusyState: newbusy="Dirty files", busy="Not busy"
I [07/Dec/2022:11:41:04 +0000] Partial reload complete.
I [07/Dec/2022:11:41:04 +0000] Listening to [v1.::1]:631 on fd 5...
I [07/Dec/2022:11:41:04 +0000] Listening to 127.0.0.1:631 on fd 7...
I [07/Dec/2022:11:41:04 +0000] Listening to /root/Github_OpenPrinting_cups/build/var/run/cups/cups.sock on fd 8...
I [07/Dec/2022:11:41:04 +0000] Resuming new connection processing...
D [07/Dec/2022:11:41:04 +0000] cupsdSetBusyState: newbusy="Dirty files", busy="Dirty files"
D [07/Dec/2022:11:41:04 +0000] Discarding unused server-restarted event...
D [07/Dec/2022:11:41:05 +0000] Report: clients=0
D [07/Dec/2022:11:41:05 +0000] Report: jobs=0
D [07/Dec/2022:11:41:05 +0000] Report: jobs-active=0
D [07/Dec/2022:11:41:05 +0000] Report: printers=0
D [07/Dec/2022:11:41:05 +0000] Report: stringpool-string-count=641
D [07/Dec/2022:11:41:05 +0000] Report: stringpool-alloc-bytes=3048
D [07/Dec/2022:11:41:05 +0000] Report: stringpool-total-bytes=6624
D [07/Dec/2022:11:41:12 +0000] cupsdSetBusyState: newbusy="Active clients and dirty files", busy="Dirty files"
D [07/Dec/2022:11:41:12 +0000] [Client 8] Server address is "/root/Github_OpenPrinting_cups/build/var/run/cups/cups.sock".
D [07/Dec/2022:11:41:12 +0000] [Client 8] Accepted from localhost (Domain)
D [07/Dec/2022:11:41:12 +0000] [Client 8] Waiting for request.
D [07/Dec/2022:11:41:12 +0000] cupsdAddCert: Adding certificate for PID 0
D [07/Dec/2022:11:41:12 +0000] [Client 8] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [07/Dec/2022:11:41:12 +0000] [Client 8] Closing connection.
D [07/Dec/2022:11:41:12 +0000] cupsdSetBusyState: newbusy="Dirty files", busy="Active clients and dirty files"
I [07/Dec/2022:11:41:30 +0000] Listening to [v1.::1]:631 (IPv6)
I [07/Dec/2022:11:41:30 +0000] Listening to 127.0.0.1:631 (IPv4)
I [07/Dec/2022:11:41:30 +0000] Listening to /root/Github_OpenPrinting_cups/build/var/run/cups/cups.sock (Domain)
I [07/Dec/2022:11:41:30 +0000] Remote access is disabled.
D [07/Dec/2022:11:41:30 +0000] Added auto ServerAlias develop
I [07/Dec/2022:11:41:30 +0000] Loaded configuration file "/root/Github_OpenPrinting_cups/build/etc/cups/cupsd.conf"
D [07/Dec/2022:11:41:30 +0000] Using keychain "/Library/Keychains/System.keychain" for server name "develop".
I [07/Dec/2022:11:41:30 +0000] Using default TempDir of /root/Github_OpenPrinting_cups/build/var/spool/cups/tmp...
I [07/Dec/2022:11:41:30 +0000] Configured for up to 100 clients.
I [07/Dec/2022:11:41:30 +0000] Allowing up to 100 client connections per host.
I [07/Dec/2022:11:41:30 +0000] Using policy "default" as the default.
I [07/Dec/2022:11:41:30 +0000] Full reload is required.
I [07/Dec/2022:11:41:30 +0000] Loaded MIME database from "/root/Github_OpenPrinting_cups/build/share/cups/mime" and "/root/Github_OpenPrinting_cups/build/etc/cups": 36 types, 4 filters...
I [07/Dec/2022:11:41:30 +0000] Loading job cache file "/root/Github_OpenPrinting_cups/build/var/cache/cups/job.cache"...
I [07/Dec/2022:11:41:30 +0000] Full reload complete.
D [07/Dec/2022:11:41:30 +0000] cupsdCleanFiles(path="/root/Github_OpenPrinting_cups/build/var/spool/cups/tmp", pattern="(null)")
I [07/Dec/2022:11:41:30 +0000] Cleaning out old files in "/root/Github_OpenPrinting_cups/build/var/spool/cups/tmp".
D [07/Dec/2022:11:41:30 +0000] cupsdCleanFiles(path="/root/Github_OpenPrinting_cups/build/var/cache/cups", pattern="*.ipp")
I [07/Dec/2022:11:41:30 +0000] Cleaning out old files in "/root/Github_OpenPrinting_cups/build/var/cache/cups".
D [07/Dec/2022:11:41:30 +0000] service_checkin: pid=64846
D [07/Dec/2022:11:41:30 +0000] Creating KeepAlive/PID file "/root/Github_OpenPrinting_cups/build/var/run/cups/cupsd.pid".
E [07/Dec/2022:11:41:30 +0000] Unable to open listen socket for address [v1.::1]:631 - Address already in use.
E [07/Dec/2022:11:41:30 +0000] Unable to open listen socket for address 127.0.0.1:631 - Address already in use.
I [07/Dec/2022:11:41:30 +0000] Listening to /root/Github_OpenPrinting_cups/build/var/run/cups/cups.sock on fd 6...
I [07/Dec/2022:11:41:30 +0000] Resuming new connection processing...
D [07/Dec/2022:11:41:30 +0000] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
D [07/Dec/2022:11:41:30 +0000] cupsdAddCert: Adding certificate for PID 0
D [07/Dec/2022:11:41:30 +0000] Discarding unused server-started event...
D [07/Dec/2022:11:41:30 +0000] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [07/Dec/2022:11:41:31 +0000] Report: clients=0
D [07/Dec/2022:11:41:31 +0000] Report: jobs=0
D [07/Dec/2022:11:41:31 +0000] Report: jobs-active=0
D [07/Dec/2022:11:41:31 +0000] Report: printers=0
D [07/Dec/2022:11:41:31 +0000] Report: stringpool-string-count=292
D [07/Dec/2022:11:41:31 +0000] Report: stringpool-alloc-bytes=3080
D [07/Dec/2022:11:41:31 +0000] Report: stringpool-total-bytes=3848
I [07/Dec/2022:11:41:35 +0000] Generating printcap /etc/printcap...
D [07/Dec/2022:11:41:35 +0000] cupsdSetBusyState: newbusy="Not busy", busy="Dirty files"
D [07/Dec/2022:11:41:45 +0000] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [07/Dec/2022:11:41:45 +0000] [Client 1] Server address is "/root/Github_OpenPrinting_cups/build/var/run/cups/cups.sock".
D [07/Dec/2022:11:41:45 +0000] [Client 1] Accepted from localhost (Domain)
D [07/Dec/2022:11:41:45 +0000] [Client 1] Waiting for request.
D [07/Dec/2022:11:41:45 +0000] [Client 1] POST / HTTP/1.1
D [07/Dec/2022:11:41:45 +0000] cupsdSetBusyState: newbusy="Active clients", busy="Active clients"
D [07/Dec/2022:11:41:45 +0000] [Client 1] Read: status=200, state=6
D [07/Dec/2022:11:41:45 +0000] [Client 1] No authentication data provided.
D [07/Dec/2022:11:41:46 +0000] [Client 1] 2.0 CUPS-Get-PPDs 1
D [07/Dec/2022:11:41:46 +0000] CUPS-Get-PPDs
D [07/Dec/2022:11:41:46 +0000] [CGI] argv[0] = "/root/Github_OpenPrinting_cups/build/lib/cups/daemon/cups-driverd"
D [07/Dec/2022:11:41:46 +0000] [CGI] argv[1] = "list"
D [07/Dec/2022:11:41:46 +0000] [CGI] argv[2] = "1"
D [07/Dec/2022:11:41:46 +0000] [CGI] argv[3] = "0"
D [07/Dec/2022:11:41:46 +0000] [CGI] argv[4] = "requested-attributes=all"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[0] = "CUPS_CACHEDIR=/root/Github_OpenPrinting_cups/build/var/cache/cups"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[1] = "CUPS_DATADIR=/root/Github_OpenPrinting_cups/build/share/cups"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[2] = "CUPS_DOCROOT=/root/Github_OpenPrinting_cups/build/share/doc/cups"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[3] = "CUPS_REQUESTROOT=/root/Github_OpenPrinting_cups/build/var/spool/cups"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[4] = "CUPS_SERVERBIN=/root/Github_OpenPrinting_cups/build/lib/cups"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[5] = "CUPS_SERVERROOT=/root/Github_OpenPrinting_cups/build/etc/cups"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[6] = "CUPS_STATEDIR=/root/Github_OpenPrinting_cups/build/var/run/cups"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[7] = "HOME=/root/Github_OpenPrinting_cups/build/var/spool/cups/tmp"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[8] = "PATH=/root/Github_OpenPrinting_cups/build/lib/cups/filter:/root/Github_OpenPrinting_cups/build/bin:/root/Github_OpenPrinting_cups/build/sbin:/bin:/usr/bin"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[9] = "SERVER_ADMIN=root@develop"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[10] = "SOFTWARE=CUPS/2.4.3"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[11] = "TMPDIR=/root/Github_OpenPrinting_cups/build/var/spool/cups/tmp"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[12] = "USER=root"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[13] = "CUPS_MAX_MESSAGE=2047"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[14] = "CUPS_SERVER=/root/Github_OpenPrinting_cups/build/var/run/cups/cups.sock"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[15] = "CUPS_ENCRYPTION=IfRequested"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[16] = "LANG=en_US.UTF8"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[17] = "REDIRECT_STATUS=1"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[18] = "GATEWAY_INTERFACE=CGI/1.1"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[19] = "SERVER_NAME=localhost"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[20] = "SERVER_PORT=0"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[21] = "REMOTE_ADDR=localhost"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[22] = "REMOTE_HOST=localhost"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[23] = "SCRIPT_NAME=/"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[24] = "SCRIPT_FILENAME=/root/Github_OpenPrinting_cups/build/share/doc/cups/"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[25] = "SERVER_PROTOCOL=HTTP/1.1"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[26] = "HTTP_USER_AGENT=CUPS/2.4.3 (Linux 5.15.0-56-generic; x86_64) IPP/2.0"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[27] = "REQUEST_METHOD=POST"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[28] = "CONTENT_LENGTH=75"
D [07/Dec/2022:11:41:46 +0000] [CGI] envp[29] = "CONTENT_TYPE=application/ipp"
D [07/Dec/2022:11:41:46 +0000] [CGI] Started /root/Github_OpenPrinting_cups/build/lib/cups/daemon/cups-driverd (PID 64916)
I [07/Dec/2022:11:41:46 +0000] [Client 1] Started "/root/Github_OpenPrinting_cups/build/lib/cups/daemon/cups-driverd" (pid=64916, file=10)
D [07/Dec/2022:11:41:46 +0000] [Client 1] Waiting for CGI data.
D [07/Dec/2022:11:41:46 +0000] [CGI] execv failed: Permission denied
D [07/Dec/2022:11:41:46 +0000] [Client 1] CGI data ready to be sent.
D [07/Dec/2022:11:41:46 +0000] PID 64916 (/root/Github_OpenPrinting_cups/build/lib/cups/daemon/cups-driverd) stopped with status 113 (Permission denied)
D [07/Dec/2022:11:41:46 +0000] [Client 1] con->http=0x55ab6d86d0c0
D [07/Dec/2022:11:41:46 +0000] [Client 1] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=2147483647, response=(nil)(), pipe_pid=64916, file=10
D [07/Dec/2022:11:41:46 +0000] [Client 1] Waiting for CGI data.
D [07/Dec/2022:11:41:46 +0000] [Client 1] cupsdSendHeader: code=500, type="text/html", auth_type=0
D [07/Dec/2022:11:41:46 +0000] [Client 1] Waiting for request.
D [07/Dec/2022:11:41:46 +0000] [Client 1] Closing because Keep-Alive is disabled.
D [07/Dec/2022:11:41:46 +0000] [Client 1] Closing connection.
D [07/Dec/2022:11:41:46 +0000] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"

**Comment by zdohnal** [comment]
Hi @JasonFengHot ,

since there is no new response from you, I take it as the issue is solved. Let us know in case there is still a problem.
