### ISSUE TITLE
How to purge all print tasks when CUPS start up?

### ISSUE THREAD

**Issue by fayehoo** [OpenPrinting/cups#576]
How to set the CUPS  to clear all print tasks once it is restarted (for example, the print server is powered on),  including the unfinished print tasks previously cached, or the print tasks paused in case of errors ,etc.

**Comment by michaelrsweet** [comment]
The only way would be to purge the spool (/var/spool/cups) directory before starting cupsd, and that will cause all job history to be lost... You can just delete the "d" files in the spool directory to keep the history, but there will be some cleanup when cupsd starts with errors logged about the missing document files for printing...
