### ISSUE TITLE
Log backend scheme/name in error_log

### ISSUE THREAD

**Issue by mgoppold** [OpenPrinting/cups#579]
This is my request for enhence the log for backend status.

Until now the log show:

```
W [23/Nov/2022:08:42:23 +0100] [Job 532618] Backend returned status 1 (failed)
```
In our printing environement are diffrent backends active (lpd, ipp, cups-pdf). 

In order to filter out errors like "The printer did not respond" it is necessary to know the backend where it is coming from.

Because all lpd or ipp errors are temporary (the printer will be switched on the next day, admin has finished the network migration,...) and backend errors from cups-pdf are usually not.

The log could look like this:

```
W [23/Nov/2022:08:42:23 +0100] [Job 532618] Backend lpd returned status 1 (failed)
```

**Comment by zdohnal** [comment]
Fixed by https://github.com/OpenPrinting/cups/pull/580 .
