### ISSUE TITLE
Adding an IPP-Everywhere printer only creates a 'Local Raw Printer'

### ISSUE THREAD

**Issue by haba-beton** [OpenPrinting/cups#582]
Hello,

since Cups version 2.4.x, the command:

/usr/sbin/lpadmin -p 'GAR-P-08' -D '' -L '' -o printer-is-shared=false -E -v ipp://10.1.2.208/ipp/print -m everywhere

only creates a 'Local Raw Printer' printer. With Cups 2.3.3 the printer was added correctly.

The Log shows the following:

D [11/Jan/2023:10:43:15 +0000] [Client 117] Returning IPP successful-ok for CUPS-Add-Modify-Printer (ipp://localhost:631/printers/GAR-P-08) from localhost.
D [11/Jan/2023:10:43:15 +0000] [Client 117] Content-Length: 75
D [11/Jan/2023:10:43:15 +0000] [Client 117] cupsdSendHeader: code=200, type="application/ipp", auth_type=0
D [11/Jan/2023:10:43:15 +0000] [Client 117] con->http=0x55dc534b0120
D [11/Jan/2023:10:43:15 +0000] [Client 117] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=75, response=0x55dc534a4220(IPP_STATE_DATA), pipe_pid=0, file=-1
D [11/Jan/2023:10:43:15 +0000] [Client 117] Writing IPP response, ipp_state=IPP_STATE_DATA, old wused=0, new wused=0
D [11/Jan/2023:10:43:15 +0000] [Client 117] bytes=0, http_state=0, data_remaining=75
D [11/Jan/2023:10:43:15 +0000] [Client 117] Flushing write buffer.
D [11/Jan/2023:10:43:15 +0000] [Client 117] New state is HTTP_STATE_WAITING
D [11/Jan/2023:10:43:15 +0000] [Client 117] Waiting for request.
D [11/Jan/2023:10:43:15 +0000] cupsdSetBusyState: newbusy="Dirty files", busy="Active clients and dirty files"
D [11/Jan/2023:10:43:15 +0000] [Notifier] state=3
D [11/Jan/2023:10:43:15 +0000] [Notifier] PrinterStateChanged
D [11/Jan/2023:10:43:15 +0000] [Notifier] state=3
D [11/Jan/2023:10:43:15 +0000] [Notifier] PrinterStateChanged
D [11/Jan/2023:10:43:15 +0000] [Notifier] state=3
D [11/Jan/2023:10:43:15 +0000] [Notifier] PrinterAdded
D [11/Jan/2023:10:43:15 +0000] [Client 117] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [11/Jan/2023:10:43:15 +0000] [Client 117] Closing connection.
D [11/Jan/2023:10:43:15 +0000] cupsdSetBusyState: newbusy="Dirty files", busy="Dirty files"
D [11/Jan/2023:10:43:15 +0000] [Client 114] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [11/Jan/2023:10:43:15 +0000] [Client 114] Closing connection.
D [11/Jan/2023:10:43:15 +0000] cupsdSetBusyState: newbusy="Dirty files", busy="Dirty files"
D [11/Jan/2023:10:43:15 +0000] GAR-P-08: Connected to 10.1.2.208:631, sending Get-Printer-Attributes request...
D [11/Jan/2023:10:43:16 +0000] GAR-P-08: Get-Printer-Attributes returned server-error-internal-error (Success)
E [11/Jan/2023:10:43:16 +0000] GAR-P-08: PPD creation failed: Keine IPP-Attribute.
I [11/Jan/2023:10:43:16 +0000] Expiring subscriptions...

The PPD File was not created.

But i don't know the reason, and what to do, can anybody help me please. Thank You.

best regrads
franz

**Comment by zdohnal** [comment]
Hi Franz,

I guess 10.1.2.208 is your printer's IP, not a print server's IP, so you can try the following:

```
$ ipptool -tv ipp://10.1.2.208/ipp/print get-printer-attributes.test
```

it does the same request as cupsd during permanent queue's installation, so it can give  you an additional info if it fails.

**Comment by haba-beton** [comment]
Hi zdohnal,

yes, it's the IP of the printer and i have executed the command and it returns the following:

root@cups:/var/log/cups# ipptool -tv ipp://10.1.2.208/ipp/print get-printer-attributes.test
"/usr/share/cups/ipptool/get-printer-attributes.test":
    Get-Printer-Attributes:
        attributes-charset (charset) = utf-8
        attributes-natural-language (naturalLanguage) = en
        printer-uri (uri) = ipp://10.1.2.208:631/ipp/print
        requested-attributes (1setOf keyword) = all,media-col-database
    Get printer attributes using get-printer-attributes                  [FAIL]
        RECEIVED: 0 bytes in response
        status-code = server-error-internal-error (Unable to read response.)
        IPP request failed with status server-error-internal-error (Unable to read response.)

I also executed it on the old machine with cups 3.3 and it returns the following:

"/usr/share/cups/ipptool/get-printer-attributes.test":
    Get-Printer-Attributes:
        attributes-charset (charset) = utf-8
        attributes-natural-language (naturalLanguage) = en
        printer-uri (uri) = ipp://10.1.2.208:631/ipp/print
        requested-attributes (1setOf keyword) = all,media-col-database
    Get printer attributes using get-printer-attributes                  [FAIL]
        RECEIVED: 0 bytes in response
        status-code = server-error-internal-error (IPP 1setOf Attribut mit inkompatiblen Werte-Markierung.)
        IPP request failed with status server-error-internal-error (IPP 1setOf Attribut mit inkompatiblen Werte-Markierung.)

The return is nearly similar, but the printer is created correctly.

Thank you and best regards
Franz

**Comment by zdohnal** [comment]
I've checked the code of ```create_local_bg_thread()```, which does the installation now, and ```get_printer_ppd()``` which did it in the past and the only change I can find there is that we set IPP version to 2.0 now.

To simulate this we can adjust ```/usr/share/cups/ipptool/get-printer-attributes.test``` by commenting out the line:

```
VERSION 2.0
```

Now if the ipptool command passes, then the setting of IPP version is really the culprit.

Can you make the change and call the ipptool command again? If the output is different, please put it into a file and attach it here.

What is your printer model?

**Comment by haba-beton** [comment]
I have commented out the line, but the return of the ipptool command is the same. 

[10.1.2.208.txt](https://github.com/OpenPrinting/cups/files/10402188/10.1.2.208.txt)

The Printer Model is: Canon iR-ADV DX C5840i MFP

I tried it with many Canon models. It did not work with all of them except for one. A new Canon iR-ADV C257 (IP 10.1.5.202) was added successfully. Please see the follwoing output:

[10.1.5.202.txt](https://github.com/OpenPrinting/cups/files/10402191/10.1.5.202.txt)

**Comment by zdohnal** [comment]
Interesting - so you are still able to install the printer with CUPS 2.3.3op2? It would be great if you uploaded the PPD it created from ```/etc/cups/ppd``` and two network captures - one when you install the printer with CUPS 2.3.3op2 and one when you install it with CUPS 2.4.x.

You can get a network capture via:

```
$ sudo tcpdump -w net.pcap -s0 -i any host 10.1.2.208
```

It is really strange to me that two same requests give a different response...

BTW, I have problems with Canon ImageRunner Advance printers in our office as well - I've found out printer's firmware puts an IPP collection into attribute which accepts only keywords, so that firmware breaks Airprint specification IMO. Maybe the same firmware bug is your printers.

**Comment by haba-beton** [comment]
Now I found out what to do to add a printer successfully. I have to restart the printer, and after the restart, I have to wait for about a minute, then the printer can be added successfully.

At first glance, it looks like the same behavior exists with CUPS 2.3.3op2.

But I don't know why I haven't stumbled upon this problem before. We've been using CUPS for about 2 years now with about 50 printers and until now, this hasn't occurred to me.

I will do more testing this weekend. Also with a new installed CUPS 2.4.

**Comment by haba-beton** [comment]
It is as described before. If it is not possible to add a printer, then a restart of it can help. After that, it is possible to add it successfully for a certain period of time. This applies to Canon printers.
