### ISSUE TITLE
"hpijs: command not found"

### ISSUE THREAD

**Issue by vindicatorr** [OpenPrinting/cups#584]
`Printer model: Brother HL-2140 Foomatic/hpijs-pcl5e (recommended)`
```
*FoomaticRIPCommandLine: "gs -q -dBATCH -dPARANOIDSAFER -dQUIET -dNOPA&&
USE -dNOMEDIAATTRS -dNOINTERPOLATE -sDEVICE=ijs -sIjsServer=hpijs -sDe&&
viceManufacturer=&quot;HEWLETT-PACKARD&quot; -sDeviceModel=&quot;HP La&&
serJet&quot;%A%B%C -dIjsUseOutputFD%Z -sOutputFile=- -"
*End
```
You may want to be looking at the `-sIjsServer=hpijs` for your `ppd`s. `hpijs` isn't shipped in `hplip` anymore.
https://wiki.archlinux.org/title/CUPS/Troubleshooting#CUPS:_%22Filter_failed%22

EDIT0: I managed to print a test page using `hp-laserjet_2200_series.ppd` from `hplip`.
I thought I'd see if I could (port?) that ppd to the `Brother-HL-2140-hpijs-pcl5e.ppd` you have.
I began with replacing
```
*cupsFilter:	"application/vnd.cups-postscript 100 foomatic-rip"
*cupsFilter:	"application/vnd.cups-pdf 0 foomatic-rip"
```
with `*cupsFilter: "application/vnd.cups-raster 0 hpcups"`.
It didn't like that, so I added what it was mentioning: `*hpPrinterLanguage: "ljmono"`.
Except now it prints some strange barcode-looking stuff for any printed page (test page or whatever else).

**Comment by zdohnal** [comment]
Hi @vindicatorr ,

CUPS does not ship the driver, Foomatic does.

HPLIP project still ships the ```hpijs``` filter - I always unpack the latest upstream source tarball [here](https://github.com/zdohnal/hplip) to track changes between releases, since HP doesn't have a public hplip git - but it seems the ArchLinux maintainer configured hplip to don't ship it - in such case he should make sure there are no drivers in the distro, which require ```hpijs```.

**Comment by vindicatorr** [comment]
https://developers.hp.com/hp-linux-imaging-and-printing/release_notes
```
HPLIP 3.9.6 - This release has the following changes:

Significant Changes
The new native CUPS driver (HPCUPS) is now the default printer driver. HPCUPS requires CUPS 1.2 or higher and is a complete replacement for HPIJS. For now HPIJS is still included in the tarball and if necessary can co-exist with HPCUPS. 
```
Note the `For now` part. To me that says "deprecated", though I will say that 13 years seems like a long time for deprecation to be fulfilled, so I'm not sure what to make of that.

**Comment by zdohnal** [comment]
`Deprecated` doesn't mean `removed` - in case ArchLinux community wants to remove hpijs, they should remove/migrate any hpijs drivers they ship in OS.

Please report the issue to Arch Linux, since they are shipping not-working drivers.
