### ISSUE TITLE
Canon ts6200 with IPP everywhere has duplicated grayscale option in color mode

### ISSUE THREAD

**Issue by SungHwan-J** [OpenPrinting/cups#59]
os : arch linux
cups : 2.3.3op1

I installed canon ts6200 series with IPP everywhere and there are one color and two grayscale options  in color mode.

previously I installed this printer with IPP everywhere on ubuntu 20.04, it had one color and one grayscale in color mode.

Please check that, thanks.

**Comment by michaelrsweet** [comment]
@SungHwan-J Can you attach the PPD file that was generated along with the output from:

    ipptool --ippserver canon-attributes.txt DEVICE-URI get-printer-attributes.test

where "DEVICE-URI" is the URI reported by `lpstat -v`.

Thanks!

**Comment by SungHwan-J** [comment]
[canon-atrributes.txt](https://github.com/OpenPrinting/cups/files/5632160/canon-atrributes.txt)
is this right?

**Comment by michaelrsweet** [comment]
[master c9e871e09] Fix duplicate ColorModel entries for AirPrint printers (Issue #59)
