### ISSUE TITLE
POSTEK driverless label printer

### ISSUE THREAD

**Issue by AndroidDesigner** [OpenPrinting/cups#600]
Hello everyone.
I have a [POSTEK](http://postekchina.com/) label printer that does not have linux driver and I want to use it with my raspberry pi.
I installed cups in the raspberry pi (sudo apt install cups) but none of available drivers are matched with it.
How can I use it?

**Comment by zdohnal** [comment]
Hi,

you can find out which PDL the printer accepts and try some of CUPS generic drivers for the PDL or ask the printer manufacturer to develop a printer application (new way for printer drivers) https://openprinting.github.io/documentation/01-printer-application/ .
