### ISSUE TITLE
Shows printing job was completed but nothing is printed

### ISSUE THREAD

**Issue by lmm1191** [OpenPrinting/cups#601]
Hi -

So I did test it both on my canon USB printer and Brother DCP-T420W printer (both USB and wireless). Basically, it shows on cups that the printing job has completed (e.g., test print) but nothing really gets printed. I first thought that the issue was with my canon printer which worked previously on past installs, but now, on 2 laptops, it just won't print.

here are some outputs I get in running lpstat and lpinfo

`❯ lpstat -r printserver -o
scheduler is running
Brother-DCPT420W-23 user 1024 Thursday, 26 January, 2023 06:43:40 PM

❯ lpinfo -v
network beh
file cups-brf:/
network http
network https
network ipp
network ipps
network lpd
direct usb://Brother/DCP-T420W?serial=E8071*********
network socket
network smb
network lpd://BRW10B1DFA23670/BINARY_P1

❯ lpstat -t
scheduler is running
system default destination: Brother-DCPT420W
device for Brother-DCP-T420W: usb://Brother/DCP-T420W?serial=E8071*********
device for Brother-DCPT420W: lpd://BRW10B1DFA23670/BINARY_P1
Brother-DCP-T420W accepting requests since Thursday, 26 January, 2023 06:44:54 PM
Brother-DCPT420W accepting requests since Thursday, 26 January, 2023 06:57:09 PM
printer Brother-DCP-T420W is idle. enabled since Thursday, 26 January, 2023 06:44:54 PM
printer Brother-DCPT420W is idle. enabled since Thursday, 26 January, 2023 06:57:09 PM
Brother-DCPT420W-23 user 1024 Thursday, 26 January, 2023 06:43:40 PM
`

Both printers works on windows and brother DCP-t420w even works on mobile so the printers are all good. I'm assuming it's with the drivers, but for 2 different make and model printers both not working, there must be something wrong.

**Comment by debiantriage** [comment]
Mmm. The Brother is from 2020 but this model does not support AirPrint! You're using the Brother drivers? Which OS?

As a matter of interest, give the outputs of

`avahi-browse -rt _ipp._tcp`
`avahi-browse -rt _uscan._tcp`
`driverless`

with the machine network connected.

**Comment by lmm1191** [comment]
So, I got it working now. I reconnected my brother DCP-T420W printer and for some reason it now have the IPP Everywhere driver. It was certainly not there earlier when I posted the issue using driverless. Thanks

**Comment by debiantriage** [comment]
@lmm1191 Well done! Using PP Everywhere is good.

However, the outputs of the commands asked for and your OS would still be very useful to know. Everything we learn helps other users.

**Comment by lmm1191** [comment]
This are the uoptuts.

`❯ **avahi-browse -rt _ipp._tcp**
+ enp8s0 IPv6 Brother DCP-T420W                             Internet Printer     local
+ enp8s0 IPv4 Brother DCP-T420W                             Internet Printer     local
= enp8s0 IPv6 Brother DCP-T420W                             Internet Printer     local
   hostname = [BRW10B1DFA23670.local]
   address = [192.168.1.14]
   port = [631]
   txt = ["mopria-certified=2.0" "print_wfds=T" "UUID=e3248000-80ce-11db-8000-10b1dfa23670" "TBCP=F" "Transparent=T" "Binary=T" "PaperCustom=T" "Scan=T" "Fax=F" "Duplex=F" "Copies=F" "Color=T" "usb_CMD=HBP,PJL" "usb_MDL=DCP-T420W" "usb_MFG=Brother" "priority=25" "adminurl=http://BRW10B1DFA23670.local./" "product=(Brother DCP-T420W)" "ty=Brother DCP-T420W" "note=" "rp=ipp/print" "pdl=application/octet-stream,image/pwg-raster,application/vnd.brother-hbp" "qtotal=1" "txtvers=1"]
= enp8s0 IPv4 Brother DCP-T420W                             Internet Printer     local
   hostname = [BRW10B1DFA23670.local]
   address = [192.168.1.14]
   port = [631]
   txt = ["mopria-certified=2.0" "print_wfds=T" "UUID=e3248000-80ce-11db-8000-10b1dfa23670" "TBCP=F" "Transparent=T" "Binary=T" "PaperCustom=T" "Scan=T" "Fax=F" "Duplex=F" "Copies=F" "Color=T" "usb_CMD=HBP,PJL" "usb_MDL=DCP-T420W" "usb_MFG=Brother" "priority=25" "adminurl=http://BRW10B1DFA23670.local./" "product=(Brother DCP-T420W)" "ty=Brother DCP-T420W" "note=" "rp=ipp/print" "pdl=application/octet-stream,image/pwg-raster,application/vnd.brother-hbp" "qtotal=1" "txtvers=1"]
+ wlp0s20f3 IPv6 Brother DCP-T420W                             Internet Printer     local
+ wlp0s20f3 IPv4 Brother DCP-T420W                             Internet Printer     local
= wlp0s20f3 IPv6 Brother DCP-T420W                             Internet Printer     local
   hostname = [BRW10B1DFA23670.local]
   address = [192.168.1.14]
   port = [631]
   txt = ["mopria-certified=2.0" "print_wfds=T" "UUID=e3248000-80ce-11db-8000-10b1dfa23670" "TBCP=F" "Transparent=T" "Binary=T" "PaperCustom=T" "Scan=T" "Fax=F" "Duplex=F" "Copies=F" "Color=T" "usb_CMD=HBP,PJL" "usb_MDL=DCP-T420W" "usb_MFG=Brother" "priority=25" "adminurl=http://BRW10B1DFA23670.local./" "product=(Brother DCP-T420W)" "ty=Brother DCP-T420W" "note=" "rp=ipp/print" "pdl=application/octet-stream,image/pwg-raster,application/vnd.brother-hbp" "qtotal=1" "txtvers=1"]
= wlp0s20f3 IPv4 Brother DCP-T420W                             Internet Printer     local
   hostname = [BRW10B1DFA23670.local]
   address = [192.168.1.14]
   port = [631]
   txt = ["mopria-certified=2.0" "print_wfds=T" "UUID=e3248000-80ce-11db-8000-10b1dfa23670" "TBCP=F" "Transparent=T" "Binary=T" "PaperCustom=T" "Scan=T" "Fax=F" "Duplex=F" "Copies=F" "Color=T" "usb_CMD=HBP,PJL" "usb_MDL=DCP-T420W" "usb_MFG=Brother" "priority=25" "adminurl=http://BRW10B1DFA23670.local./" "product=(Brother DCP-T420W)" "ty=Brother DCP-T420W" "note=" "rp=ipp/print" "pdl=application/octet-stream,image/pwg-raster,application/vnd.brother-hbp" "qtotal=1" "txtvers=1"]

❯ **avahi-browse -rt _uscan._tcp**
+ enp8s0 IPv6 Brother DCP-T420W                             _uscan._tcp          local
+ enp8s0 IPv4 Brother DCP-T420W                             _uscan._tcp          local
= enp8s0 IPv4 Brother DCP-T420W                             _uscan._tcp          local
   hostname = [BRW10B1DFA23670.local]
   address = [192.168.1.14]
   port = [80]
   txt = ["mopria-certified-scan=1.3" "usb_MFG=Brother" "duplex=F" "is=platen" "cs=binary,grayscale,color" "UUID=e3248000-80ce-11db-8000-10b1dfa23670" "pdl=application/pdf,image/jpeg" "note=" "ty=Brother DCP-T420W" "rs=eSCL" "representation=http://BRW10B1DFA23670.local./icons/device-icons-128.png" "adminurl=http://BRW10B1DFA23670.local./" "vers=2.63" "txtvers=1"]
= enp8s0 IPv6 Brother DCP-T420W                             _uscan._tcp          local
   hostname = [BRW10B1DFA23670.local]
   address = [192.168.1.14]
   port = [80]
   txt = ["mopria-certified-scan=1.3" "usb_MFG=Brother" "duplex=F" "is=platen" "cs=binary,grayscale,color" "UUID=e3248000-80ce-11db-8000-10b1dfa23670" "pdl=application/pdf,image/jpeg" "note=" "ty=Brother DCP-T420W" "rs=eSCL" "representation=http://BRW10B1DFA23670.local./icons/device-icons-128.png" "adminurl=http://BRW10B1DFA23670.local./" "vers=2.63" "txtvers=1"]
+ wlp0s20f3 IPv6 Brother DCP-T420W                             _uscan._tcp          local
+ wlp0s20f3 IPv4 Brother DCP-T420W                             _uscan._tcp          local
= wlp0s20f3 IPv6 Brother DCP-T420W                             _uscan._tcp          local
   hostname = [BRW10B1DFA23670.local]
   address = [192.168.1.14]
   port = [80]
   txt = ["mopria-certified-scan=1.3" "usb_MFG=Brother" "duplex=F" "is=platen" "cs=binary,grayscale,color" "UUID=e3248000-80ce-11db-8000-10b1dfa23670" "pdl=application/pdf,image/jpeg" "note=" "ty=Brother DCP-T420W" "rs=eSCL" "representation=http://BRW10B1DFA23670.local./icons/device-icons-128.png" "adminurl=http://BRW10B1DFA23670.local./" "vers=2.63" "txtvers=1"]
= wlp0s20f3 IPv4 Brother DCP-T420W                             _uscan._tcp          local
   hostname = [BRW10B1DFA23670.local]
   address = [192.168.1.14]
   port = [80]
   txt = ["mopria-certified-scan=1.3" "usb_MFG=Brother" "duplex=F" "is=platen" "cs=binary,grayscale,color" "UUID=e3248000-80ce-11db-8000-10b1dfa23670" "pdl=application/pdf,image/jpeg" "note=" "ty=Brother DCP-T420W" "rs=eSCL" "representation=http://BRW10B1DFA23670.local./icons/device-icons-128.png" "adminurl=http://BRW10B1DFA23670.local./" "vers=2.63" "txtvers=1"]

`

**Comment by lmm1191** [comment]
❯ driverless
ipp://Brother%20DCP-T420W._ipp._tcp.local/

**Comment by lmm1191** [comment]
I'm on arch linux

**Comment by lmm1191** [comment]
I can confirm it's using mopria as per printer settings by accessing its IP. I am also able to scan wirelessly using xsane. It automatically detected my brother printer. No changes made as well on dbus and avahi conf. I also removed the driver from brother just to avoid any conflicting processes that may arise.

**Comment by debiantriage** [comment]
@lmm1191 Removing the Brother drivers was a good move. I would now say you are in a good position to close this report. Thanks for all the good info.

**Comment by lmm1191** [comment]
Thanks. Will close it.
