### ISSUE TITLE
CUPS-Supplied Brother DPL3510CDW PPD Cannot Print Colours Accurately

### ISSUE THREAD

**Issue by alexkemp9** [OpenPrinting/cups#611]
**Describe the bug**
CUPS itself seems to work fine ... except that ALL colours are wrong.
I have & am willing to upload Microsoft-supplied PPDs that (mostly) work OK with the printer
(unfortunately, this page will NOT accept a ZIP file, nor bare PPD)
(I will try again with a bare PPD renamed as TXT; nope, it refused that file as well)

**To Reproduce**
(using DCP3510W-RGB obtained from Brother website & installed shortly after obtaining printer)
1. Print anything from anywhere containing a colour
2. The printed colour does not match the screen colour (nor the actual colour values)
3. Install (an older) PPD extracted from the Microsoft driver supplied on CD with the printer when purchased
(this is BRPPL3510CDW-CMYK)
4. Most colours are now accurate
5. Install CUPS-supplied PPD
(this turns out to be byte-identical to DCP3510W-RGB)

**Expected behavior**
That printed colours are accurate

**Screenshots**
No point. The screen preview looks fine, the actual printouts are wrong.

**System Information:**
Linux ng3 6.0.0-0.deb11.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19) x86_64 GNU/Linux
LibreOffice 7.4.5.1
CUPS: 2.3.3op2-3+deb11u2

**Additional context**
$ lpstat -e
BRPPL3510CDW-CMYK
DCP3510W-RGB

$ lpstat -a
BRPPL3510CDW-CMYK accepting requests since Sat 04 Feb 2023 02:33:08 GMT
DCP3510W-RGB accepting requests since Sat 04 Feb 2023 02:39:20 GMT

$ lpoptions -p BRPPL3510CDW-CMYK
copies=1 device-uri=usb://Brother/%20series?serial=E79016L8N315916 finishings=3 job-cancel-after=10800 job-hold-until=no-hold job-priority=50 job-sheets=none,none marker-change-time=0 media=3 number-up=1 output-bin=face-down print-color-mode=color printer-commands=AutoConfigure,Clean,PrintSelfTestPage printer-info=DCPL3510CDW printer-is-accepting-jobs=true printer-is-shared=true printer-is-temporary=false printer-location printer-make-and-model='Brother DCP-L3510CDW BR-Script3' printer-state=3 printer-state-change-time=1675477988 printer-state-reasons=none printer-type=8425564 printer-uri-supported=ipp://localhost/printers/BRPPL3510CDW-CMYK sides=two-sided-long-edge

**Comment by zdohnal** [comment]
Hi @alexkemp9 ,

I'm not sure if I understand - so you have one PPD which is used for BRPPL3510CDW-CMYK queue and for BRPPL3510CDW-RGB queue, both uses usb device uri, but you get a different color output? And *-CMYK is the one which works and *-RGB doesn't?

Would you mind attaching the exact PPD file (you can rename it to have .txt suffix, then Github accepts it. .zip files are okay as well, so I'm not sure what kind of problem you hit with it, maybe you tried to load a different suffix?) for both queues?
Additionally do enable debug logging by ```cupsctl LogLevel=debug2```, print again to both queues and attach log files here as well.

Thank you in advance!

**Comment by alexkemp9** [comment]
Steps taken as requested, zip of all files attached.

On 08/03/2023 11:33, zdohnal wrote:
> |cupsctl LogLevel=debug2|

- AK

**Comment by zdohnal** [comment]
@alexkemp9 I'm sorry, could you attach it via web interface? Otherwise I don't see it in email notification and web page.
