### ISSUE TITLE
Build the unit test targets without immediately running them

### ISSUE THREAD

**Issue by NedoL98** [OpenPrinting/cups#612]
**Is your feature request related to a problem? Please describe.**
We would like to integrate cups unit tests into our repository. However, unit test targets do not only build tests but also run them. This is not very convenient as we would also like to use cross-compilation and to run test executables on different architectures. 

**Describe the solution you'd like**
Provide a way to build and run unit test targets separately. For instance, we can have an additional variable to switch launching tests immediately after building them.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by zdohnal** [comment]
Hi @NedoL98 ,

that's a good idea, I wanted something like this some time ago when I enabled CI tests for CUPS in our distributions (right now we create symlinks and trigger the build which is not ideal), but I haven't had time to implement it yet.

Ack from my POV.

**Comment by michaelrsweet** [comment]
This is already done in the libcups (v3) repository, shouldn't be too hard to adapt to the CUPS 2.x repo.

**Comment by michaelrsweet** [comment]
Will do this for CUPS 2.5.

**Comment by zdohnal** [comment]
I guess the main part of this commit implements this issue - https://github.com/OpenPrinting/cups/commit/b1d42061 .

**Comment by zdohnal** [comment]
Looks like some parts are still run during 'make unittests' - testcgi, testhi, testmime.

**Comment by michaelrsweet** [comment]
[master 61a9e419e] Final cleanup for 'make unittests' to be separate from 'make test' (Issue #612)
