### ISSUE TITLE
Apple clients printing to remote CUPS queue generate "pages per sheet" of  n*n  instead of  n

### ISSUE THREAD

**Issue by MathuserNik** [OpenPrinting/cups#615]
Jobs printed from Apple osx clients to a printer which is another CUPS queue will apply the "number-up" job option twice, ending up with a number-up output of n*n.

Is this a known problem with a work-around in cups?

For reference, the cups version being run on the server is 2.3.3op2 on debian.

I tested this for OSX 10.15 through 13, and all have this behavior. Windows and Linux clients do not show this behavior.

I notice that jobs created on an Apple computer client, sent to a CUPS queue, will locally bake in the number-up setting to the job document (via the cgpdftopdf filter) and send the job with a number-up ipp job attribute, which I assume causes the destination device to apply the number-up setting again.

When the job is sent directly to my printers, this does *not* occur. It appears that the number-up setting is baked into the document, and then the ipp-attribute is *not* sent (apparently, from logging). 

I notice that the ipp "get-printer-atttributes" response from the CUPS queue includes "number-up" as a "job-creation-attributes-supported" response, wherase the printers do not have this. 

Is there a way to manually adjust the ipp responses for a CUPS queue to test?

I attempted doing things like copying the PPD on the Apple client (not the cups server) for a direct-to-printer queue to the local queue for the CUPS server, looked at printers.conf for differences on the apple client, and looked in the cache directory for differences (and tried just copying those files as well, to see what would happen, heh). The difference in behavior does, indeed, appear to lie in the ipp conversation at the time a job is created, not with a particular setting of the local queue on the apple client.

I understand that cgpdftopdf, and obviously the behavior of Apple clients, is not part of the openprinting project, and that the source/solution to this issue may actually lie with the Apple cups. Also, I understand the specific case of an intermediate CUPS queue can possibly solve this by just adjusting how jobs coming from Mac clients are processed.

My intent is to:
1) See if the above assessment is sensible/possible or if I'm misunderstanding something
2) See if this is a known problem, or if there's a known solution (It seems like this would be something caught awhile ago if it really affects Apple cups generally, for several versions of OSX)
3) Perhaps see if there is a 'fix' to opencups or if the problem could be communicated to Apple to fix.  I see there's a project for Apple's cups, but it doesn't look like it gets used, so I assume there's not really much use in reporting an issue there at the moment.

Thanks for your time and work!

**Comment by michaelrsweet** [comment]
How are you adding the printers on the Macs?

**Comment by MathuserNik** [comment]
The printers in my testing were all added through the GUI interface (System Preferences).
In other cases outside this testing, I add printers via lpadmin, with the the ipp2ppd tool provided by Apple, along with a generic apple ppd.

This question caused me to realize I never tried the cups-based "ippeve" driver via the   -m everywhere   option to lpadmin. A printer queue created with this method does *not* exhibit the  " n*n " behavior.


The three different types of "drivers" (Apple Airprint, OEM driver, and ipp everwhere driver) each produce different chains of events. Here is the top section of each PPD type. Notice the different cupsfilters2 lines, which cause a different chain. This is created from an OSX 13 client, connecting to a Cups 2.3.3op2 CUPS server (debian).

The first couple cause the problem, the latter two couples do not. 

<details>
<summary>PPD for "Airprint" type to CUPS queue, created via GUI</summary>

```
*PPD-Adobe: "4.3"
*% PPD created by ipp2ppd (v3:Aug  9 2022)
*FormatVersion: "4.3"
*FileVersion: "3.0"
*LanguageVersion: English
*LanguageEncoding: ISOLatin1
*PSVersion: "(3010.000) 0"
*LanguageLevel: "3"
*FileSystem: False
*cupsVersion: 2.0
*cupsModelNumber: 0
*cupsSNMPSupplies: False
*APAirPrint: True
*APAirPrintVersion: 1.1
*APURFVersion: 1.1
*% WARNING missing printer-firmware-name and/or printer-firmware-string-version.
*% WARNING no printer-strings for the language "en"
*cupsLanguages: "en"
*APPrinterIconPath: "/Library/Printers/Icons/AA3E2625-9FDF-4965-B899-9D35D939BC5E.icns"
*PCFileName: "APLASERJ.PPD"
*ModelName: "LaserJet M806 - IPP Everywhere"
*Product: (LaserJet M806 - IPP Everywhere)
*ShortNickName: "LaserJet M806 - IPP Everywhere"
*Manufacturer: "LaserJet"
*NickName: "LaserJet M806 - IPP Everywhere-AirPrint"
*Throughput: 1
*cupsSingleFile: True
*cupsFilter2: "application/vnd.cups-pdf application/pdf 0 maxsize(237903003648) -"
*cupsFilter: "application/vnd.cups-pdf 0 -"
*cupsFilter2: "image/jpeg image/jpeg 0 maxsize(237903003648) -"
*cupsFilter: "image/jpeg 0 -"
*cupsFilter2: "image/urf image/urf 10 -"
*cupsFilter: "image/urf 10 -"
```
</details>

<details>
<summary>Filters log  section for "Airprint" type to CUPS queue, created via GUI</summary>

```
D [20/Feb/2023:11:52:58 -0600] [Job 21] 3 filters for job:
D [20/Feb/2023:11:52:58 -0600] [Job 21] cgpdftopdf (application/pdf to application/vnd.cups-pdf, cost 25)
D [20/Feb/2023:11:52:58 -0600] [Job 21] - (application/vnd.cups-pdf to printer/PRINTER_DNS/application/pdf, cost 0)
D [20/Feb/2023:11:52:58 -0600] [Job 21] - (printer/PRINTER_DNS/application/pdf to printer/PRINTER_DNS, cost 0)
```
</details>

<details>
<summary>PPD using HP-provided driver to CUPS queue, created via GUI</summary>

```
*PPD-Adobe: "4.3"
*%%%% PPD file for HP LaserJet M806 with CUPS.
*%%%% Created by the CUPS PPD Compiler CUPS v2.1.0.
*% © Copyright 2012-2016 HP Development Company, L.P.
*FormatVersion: "4.3"
*FileVersion: "19.21"
*LanguageVersion: English
*LanguageEncoding: ISOLatin1
*PCFileName: "HPP00034.PPD"
*Product: "(HP LaserJet M806)"
*Manufacturer: "HP"
*ModelName: "HP LaserJet M806"
*ShortNickName: "HP LaserJet M806"
*NickName: "HP LaserJet M806"
*PSVersion: "(3010.107) 3"
*LanguageLevel: "3"
*ColorDevice: False
*DefaultColorSpace: Gray
*FileSystem: False
*Throughput: "55"
   ...
*cupsFilter: "application/vnd.cups-command 0 /Library/Printers/hp/cups/filters/commandtohp.filter/Contents/MacOS/commandtohp"
*cupsFilter: "application/vnd.cups-postscript 0 /Library/Printers/hp/filter/hpPostProcessing.bundle/Contents/MacOS/hpPostProcessing"
```
</details>

<details>
<summary>Filters log  section for HP-provided driver to CUPS queue, created via GUI</summary>

```
D [20/Feb/2023:11:45:29 -0600] [Job 19] 3 filters for job:
D [20/Feb/2023:11:45:29 -0600] [Job 19] cgpdftops (application/pdf to application/postscript, cost 25)
D [20/Feb/2023:11:45:29 -0600] [Job 19] pstops (application/postscript to application/vnd.cups-postscript, cost 66)
D [20/Feb/2023:11:45:29 -0600] [Job 19] /Library/Printers/hp/filter/hpPostProcessing.bundle/Contents/MacOS/hpPostProcessing (application/vnd.cups-postscript to printer/IPP_ToCups, cost 0)
```
</details>


<details>
<summary>PPD for IPP everywhere driver, created via CLI ( -m everywhere)</summary>

```
*PPD-Adobe: "4.3"
*FormatVersion: "4.3"
*FileVersion: "2.3"
*LanguageVersion: English
*LanguageEncoding: ISOLatin1
*PSVersion: "(3010.000) 0"
*LanguageLevel: "3"
*FileSystem: False
*PCFileName: "ippeve.ppd"
*Manufacturer: "LaserJet"
*ModelName: "M806 - IPP Everywhere"
*Product: "(M806 - IPP Everywhere)"
*NickName: "M806 - IPP Everywhere - IPP Everywhere"
*ShortNickName: "M806 - IPP Everywhere - IPP Everywhere"
*ColorDevice: False
*cupsVersion: 2.3
*cupsSNMPSupplies: False
*cupsLanguages: "en_US"
*APSupplies: "https://CUPS.SERVER.DNS/printers/PRINTERNAME"
*cupsJobPassword: "11111111111111111111111111111111"
*cupsFilter2: "image/jpeg image/jpeg 0 -"
*cupsFilter2: "image/png image/png 0 -"
*cupsFilter2: "application/pdf application/pdf 0 -"
*cupsFilter2: "image/urf image/urf 100 -"
```
</details>

<details>
<summary>Filters log  section for IPP everywhere driver, created via CLI</summary>

```
D [20/Feb/2023:12:05:14 -0600] [Job 22] 2 filters for job:
D [20/Feb/2023:12:05:14 -0600] [Job 22] - (application/pdf to printer/PRINTERNAME/application/pdf, cost 0)
D [20/Feb/2023:12:05:14 -0600] [Job 22] - (printer/PRINTERNAME/application/pdf to printer/PRINTERNAME, cost 0)
```
</details>

If you want the full logs or PPDs or whatever, let me know.


As an unrelated note, I looked back at my notes from a few years ago...  It looks like I initially created the print queues  in CLI-installed printer setups via CLI with -m everywhere  model-type, but had reports of problems. Testing showed that this caused some print jobs to the HP printers to print very slowly, and occasionally crash the older HP printers. Switching to the CLI creation with the ipp2ppd tool ( "as the GUI setup appears to use" ) got around this.. that's why that was used instead of "everywhere".

**Comment by michaelrsweet** [comment]
OK, so the problem with using ipp2ppd or adding through System Preferences (presumably with the AirPrint driver) is that the filtering gets done locally but as soon as the IPP backend sees it is talking to another CUPS server it passes all of the options over, even if things like "copies" have already been applied.

Choosing the shared printer from the "nearby printers" list in the print dialog is the recommended way to "get things right", but ultimately this is a macOS bug and not something we can fix in OpenPrinting.

**Comment by MathuserNik** [comment]
Thanks for taking the time to respond. To ensure understanding:

> as soon as the IPP backend sees it is talking to another CUPS server it passes all of the options over, even if things like "copies" have already been applied.

A local CUPS client will "know" when talking to a remote CUPS queue, and behaves differently than if talking to a printer, is that correct? I observe that some of the advertised capabilities in the ipp conversation to a CUPS queue include CUPS-* attributes, however if, say, a printer and a remote CUPS queue otherwise advertised identical capabilities, the local CUPS client will follow a different code path than when talking to a printer?

Ultimately, the question is:
If a printer also advertised "number-up" as a capability, do you think this problem would occur, or is this actually specific to printing to a remote CUPS queue?

Thanks again

**Comment by michaelrsweet** [comment]
@MathuserNik The IPP backend looks specifically for the "cups-version" attribute; if this is present, the other options are passed as-is, otherwise a mapping algorithm is used from IPP Everywhere attributes (options) and values to PPD options and values.
