### ISSUE TITLE
AirPrint Object has Offset 0

### ISSUE THREAD

**Issue by wakille** [OpenPrinting/cups#618]
Hello,

everytime I try to print documents from my IPhone, the cups server shows the status:

"/var/spool/cups/d00001-001 (object 48 0): object has offset 0"

and and nothing gets printed. As I unterstand it is the bug 321. There you said, it is an intended behavior and AirPrint sends wrong formatted data.  Well, thats bad, but how can I change this? Or do you have a workaround for this issue or a configuration setting to ignore this error ?

System:
Cups 2.4.2 Running in Docker
iOS 16.3.1

Thanks in advance!

**Comment by zdohnal** [comment]
Hi,

this is a dup of #321 - to sum it up, it is a Mac issue.
