### ISSUE TITLE
SHARP-MX-C357F doesn't respect 'copies' count

### ISSUE THREAD

**Issue by thibaultmol** [OpenPrinting/cups#622]
**Describe the bug**
When I send print jobs to my MX-C257F with the 'copies' set to anything higher than 1, it continues to only print one copy.

**To Reproduce**
Install printer using normal steps in the webui.
![Screenshot_1281](https://user-images.githubusercontent.com/1010226/220338892-d4cad9e9-87b9-4108-87b0-5058af63ca94.png)
Use any app (have tested with both Okular and Firefox) to print a pdf to to the printer and set copies to anything higher than 1.
![image](https://user-images.githubusercontent.com/1010226/220339862-3dfd4f9d-c6df-4a76-8f1f-46c92a0c5212.png)

**Expected behavior**
Print that amount of copies. But it only prints one copy.
So if I print a 2 page pdf 6 times. It shows 12 pages in the cups interface but only 2 pages come out (one copy).

**System Information:**
- Operating System: Garuda Linux 
KDE Plasma Version: 5.27.0
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.12-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2
 - CUPS version 2.4.2

**Additional context**
Follow the instructions from the [REPORTING-ISSUES](https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md) document and provide all information regarding the issue.
lpstat -e and lpstat -a both show the printer. driver has driverless in it's name. 

```
lpoptions -p SHARP-MX-C357F\(installed\)
copies=1 device-uri=socket://192.168.1.167 finishings=3 job-cancel-after=10800 job-hold-until=no-hold job-priority=50 job-sheets=none,none marker-change-time=1676973017 marker-colors=#00FFFF,#FF00FF,#FFFF00,#000000 marker-high-levels=100,100,100,100 marker-levels=20,1,1,7 marker-low-levels=20,20,20,20 marker-names=Cyan,Magenta,Yellow,Black marker-types=toner-cartridge,toner-cartridge,toner-cartridge,toner-cartridge number-up=1 print-color-mode=color printer-commands=AutoConfigure,Clean,PrintSelfTestPage printer-info=SHARP-MX-C357F(installed) printer-is-accepting-jobs=true printer-is-shared=true printer-is-temporary=false printer-location printer-make-and-model='SHARP MX-C357F, driverless, cups-filters 1.28.17' printer-state=3 printer-state-change-time=1676977507 printer-state-reasons=none printer-type=8433756 printer-uri-supported=ipp://localhost/printers/SHARP-MX-C357F(installed)
```

Can confirm that this issue also happens when I run this command
```
lp -d "SHARP-MX-C357F(installed)" -n 6 "/home/thibaultmol/Downloads/frans/APB patientenfolder FR Turbohaler.pdf"
request id is SHARP-MX-C357F(installed)-193 (1 file(s))
```
[network.pcap.zip](https://github.com/OpenPrinting/cups/files/10793535/network.pcap.zip)
[error_log.txt](https://github.com/OpenPrinting/cups/files/10793539/error_log.txt)
[attr.log](https://github.com/OpenPrinting/cups/files/10793541/attr.log)

**Comment by michaelrsweet** [comment]
The socket device URI won't work with the "driverless" driver, as that driver requires IPP...

**Comment by thibaultmol** [comment]
Sorry, was focused on adding all the logs that I forgot to mention I also tried ipp. Which resulted in the same problem

**Comment by thibaultmol** [comment]
https://support.lexmark.com/en_gb/printers/printer/XC2235/article/SO4094/unable-to-print-color-and-double-sided-printing-in-linux-ubu.html

It's a known problem that it doesn't work. So a modification in CUPS could fix it for the sharp printers and it's lexmark equivalent
