### ISSUE TITLE
Better to use while in pthread_cond_wait to avoid deadlocks

### ISSUE THREAD

**Issue by ycaibb** [OpenPrinting/cups#624]
Hi, is it better to use while to replace the if while using pthread_cond_wait? For example, accroding to [this](https://stackoverflow.com/questions/33186280/why-we-must-use-while-for-checking-race-condition-not-if), one reason is the "spurious wakeup", which means the wait method can return without the thread having been notified: it's not valid to infer, based on the thread exiting the wait method, that it must have gotten notified. This may not happen a lot but it is a possibility that has to be handled.
https://github.com/OpenPrinting/cups/blob/a6d91a2316cbb17c34b934133b442dde71c67e84/scheduler/sysman.c#L369-L377

Other places use the while.
https://github.com/OpenPrinting/cups/blob/e04821c38b614a43cf5d77f6a8fe51e584174bee/backend/usb-libusb.c#L396-L400
https://github.com/OpenPrinting/cups/blob/6885402a639a33d4da9ee814c691b01a46b887f5/backend/usb-darwin.c#L622-L626

**Comment by michaelrsweet** [comment]
It may indeed cause harm in this cause because if the condition is still true after the wait then something bad happened.
