### ISSUE TITLE
SSLListen / port from configuration file partially used in cups

### ISSUE THREAD

**Issue by kabassanov** [OpenPrinting/cups#638]
Hello,

Trying to set a distinct port for SSL connections on a cups server, I remarked that cups starts listening on this port, but still keeps the default port in both SRV and TXT records sent to clients (Port and adminurl respectively).

It is quite simple to reproduce: just put SSLListen myname.mydomain:632 into cupsd.conf and restart server.

I think that the expected behaviour should be to keep the default port for _ipp and switch to the secured port for _ipps.

I'm using cups 2.4.2.

It is quite simple to modify the source code and register (dnssdRegisterInstance) _ipps with the SSL port; and change dnssdBuildTxtRecord to call httpAssembleURIf with this port if encryption is not set to never...

The goal is to face an issue with some equipments that start directly encrypted connections to the server for ipps uris... Actually, cups servers are unable to decode these packets.

PS: These modifications reveal another issue in cups-browsed, but I'll create a report in the corresponding branch.

**Comment by michaelrsweet** [comment]
The default port for both `_ipp` and `_ipps` is 631. And unless you explicitly disable it, ALL ports support encryption by default, automatically, both for traditional HTTPS and HTTP upgrade to TLS. If *that* isn't working then we might have something to debug/fix.

Given that this is *not* a common configuration, and there is NO way for us to reliably know which port should be used for which service, I don't think we want to support this configuration.
