### ISSUE TITLE
Unable to print multiple files to a local printer

### ISSUE THREAD

**Issue by Japhier** [OpenPrinting/cups#643]
**Describe the bug**
i use command: lp -d printer 1.png 2.png;
but result is only printing 1.png and cups report error: print job canceled at printer(but i didn't cancel at printer)
i have test in HP printer and deli printer, see also as [#5819](https://github.com/apple/cups/issues/5819)

in code , i haved used cupsPrintFiles api, but have the same problem

cups version: v2.4.2

**Comment by michaelrsweet** [comment]
Does adding `*cupsSingleFile: true` to the PPD file and restarting cupsd help?

**Comment by Japhier** [comment]
> Does adding `*cupsSingleFile: true` to the PPD file and restarting cupsd help?

If this parameter is configured, multiple images can be printed. However, the printer pauses for 1 to 2 seconds (from printing to idle) before printing the next file. User experience is poor.

**Comment by zdohnal** [comment]
@Japhier is the PPD generated by CUPS/cups-filters (there is IPP Everywhere/driverless in the PPD file) or classic one?

**Comment by Japhier** [comment]
> @Japhier is the PPD generated by CUPS/cups-filters (there is IPP Everywhere/driverless in the PPD file) or classic one?

@zdohnal I use the IPP Everywhere print ppd file generated by cups. By default, there is no cupsSingleFile attribute, but I set single_file in cups/-ppd-cache.c to true, which also works.

**Comment by zdohnal** [comment]
@michaelrsweet can I add the PPD keyword by default when we generate the PPD?

**Comment by michaelrsweet** [comment]
@zdohnal Yes.

**Comment by Japhier** [comment]
@michaelrsweet @zdohnal Hello, two experts. I want to learn the filter development process. I plan to develop a PDFtoraster filter based on the PDFium open source library. Is this solution feasible?

**Comment by michaelrsweet** [comment]
@Japhier You could certainly write a filter - the useful life of the filter will only be a few years, however, but assuming that PDFium can be packaged outside of Chrome it would be useful to have a starting point for a standalone PDF RIP that doesn't have an unfriendly license...
