### ISSUE TITLE
CUPS can't print files if the job name is nearly 255 characters long

### ISSUE THREAD

**Issue by JohnHughesAtlantech** [OpenPrinting/cups#644]
cups prepends job number to job-name so job names near 255 characters may be too long

I was trying to print a webpage from firefox, the URL was very, very, long so firefox used the first 255 characters of the URL as the job name. the file just got stuck in the queue and was never printed.

Try to print a file with a job name of around 250-odd characters:

 `lp -o 'job-name=https://xxxxxxxxxxx/xxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' file`

Since the job name is less than 255 characters I'd expect the file to be printed.

However internally CUPS prepends the job number to the job name and so makes a name that is over 255 characters, an error message is written to the log file and the job is just stuck in the queue.

In the log file I see:
`D [28/Mar/2023:18:14:44 +0200] [Job 365] job-name nameWithoutLanguage 365 - https://xxxxxxxxxxx/xxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

`D [28/Mar/2023:18:27:36 +0200] [Job 369] Validate-Job: client-error-request-value-too-long (client-error-request-value-too-long)`

Debian Release: 11.6
Cups version: 2.3.3op2-3+deb11u2

This is Debian bug [1033616](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1033616)

**Comment by michaelrsweet** [comment]
OK, so the fix here is to reduce the size of print_job_name in backend/ipp.c to 256 bytes. However, this only happens when the destination does not support the "Create-Job" operation, so I would only expect this to be a problem for older printers.
