### ISSUE TITLE
Get human-readable media options

### ISSUE THREAD

**Issue by Avriox** [OpenPrinting/cups#646]
I am currently trying to obtain a list of all supported media options for a printer in a human-readable format such as "A4", "letter 8.5x11", etc. Currently, I am using `ippAttributeString()` to obtain the media options, but they are returned in a format that is not easily readable, such as "om_a-4-borderless_210x297mm".

I was wondering if there is a correct method to obtain a human-readable form for media options. If not, can it be assumed that the results obtained from `ippAttributeString()` will always strictly follow the format "prefix_medianame-[borderless]_size", and can thus be parsed safely following this structure?

I also had a look at how media options are returned in lpoptions, where they are simply displayed as "A4", "A5", "A6", etc. However, I noticed that this uses PPD files, but the PPD API has been deprecated so this may not be a suitable solution.

Any help or guidance on this issue would be highly appreciated. Thank you!

**Comment by michaelrsweet** [comment]
See the `cupsLocalizeDestMedia` API for getting localized media names.
