### ISSUE TITLE
Query:Can command fitler update all selection of PageSizes in the PPD

### ISSUE THREAD

**Issue by tangyanli** [OpenPrinting/cups#647]
**Is your feature request related to a problem? Please describe.**
Assume that the following scenario exists, a printer is installed and connected to a device; many page sizes (e.g Letter/Legal/B4/A3/A4/A5) are recorded in the PPD file, but only two kinds of paper are placed in the device (e.g A3/A4).
I suppose to retrieve the supported page size (A3/A4) placed in the device by the "AutoConfigure" command through some protocol (e.g SNMP or PS or some vendor-defined).
Can the command filter change all selection of page size as "A3/A4" in the PPD?

**Additional context**
I investigate a bit and read the commandtops.c source. It seems that command filter can only modify the default value of page size, not all selections of page size.
Are there some methods to update all selection of page size?

**Comment by michaelrsweet** [comment]
So you can't change the list of media in the PPD, just the default media. Ready (loaded) media support is limited to a configured list that is matched against the PPD.
