### ISSUE TITLE
Pantum M6559NW remains in 'printing' state even after a document is printed

### ISSUE THREAD

**Issue by gustingonzalez** [OpenPrinting/cups#648]
Hello,

I'm having an issue with a Pantum M6559NW printer. When I send a print job via IPP or the local network, the printer successfully prints the document. However, the printer remains in 'printing' state for 60 seconds, causing a delay for subsequent jobs. So, when the printer exits the 'printing' state, the corresponding 'job finished' message appears in Ubuntu, starting the next job. Interestingly, I found that pressing the 'cancel' button on the printer immediately completes the job, without any further delays or issues. Furthermore, canceling the job by terminal has the same effect, although Ubuntu displays the 'job canceled' message.

After reviewing the `ipp-usb` logs, it appears that CUPS attemps to make multiple HTTP requests to check the job completion state. These repeated requests are shown in [232b-5e20-CH8D003284-Pantum-M6550NW-series.log](https://github.com/OpenPrinting/cups/files/11182567/232b-5e20-CH8D003284-Pantum-M6550NW-series.log) as follow:
```
08-04-2023 01:07:03: > HTTP[028]: POST http://localhost:60000/ipp/print
08-04-2023 01:07:03: > HTTP[028]: request body: got 342 bytes; EOF
08-04-2023 01:07:03: > HTTP[028]: body is small (342 bytes), prefetched before sending
08-04-2023 01:07:03: > HTTP[028]: HTTP request header:
08-04-2023 01:07:03: >   POST /ipp/print HTTP/1.1
08-04-2023 01:07:03: >   Host: localhost:60000
08-04-2023 01:07:03: >   User-Agent: CUPS/2.4.1 (Linux 5.19.0-38-generic; x86_64) IPP/2.0
08-04-2023 01:07:03: >   Content-Length: 342
08-04-2023 01:07:03: >   Content-Type: application/ipp
08-04-2023 01:07:03: >   Date: Sat, 08 Apr 2023 04:07:03 GMT
08-04-2023 01:07:03: >
08-04-2023 01:07:03:   USB[1]: connection allocated, 2 in use: --- a-- ar-
08-04-2023 01:07:03:   HTTP[028]: connection 1 allocated
08-04-2023 01:07:03: > USB[1]: write: wanted 548 sent 548 total 548
08-04-2023 01:07:03: < USB[1]: read: wanted 4096 got 215 total 215
08-04-2023 01:07:03: < HTTP[028]: POST http://localhost:60000/ipp/print - 200 OK
08-04-2023 01:07:03: < HTTP[028]: HTTP response header:
08-04-2023 01:07:03: <   HTTP/1.1 200 OK
08-04-2023 01:07:03: <   Cache-Control: no-cache
08-04-2023 01:07:03: <   Connection: keep-alive
08-04-2023 01:07:03: <   Content-Length: 239
08-04-2023 01:07:03: <   Content-Type: application/ipp; charset=utf-8
08-04-2023 01:07:03: <   Server: Mrvl-R1_0
08-04-2023 01:07:03: <   X-Content-Type-Options: nosniff
08-04-2023 01:07:03: <   X-Frame-Options: SAMEORIGIN
```

Could it be the printer stays in 'printing' state because of these requests? Apart from this, something noticeable is that the server responds to all these requests with the `Connection` header in `keep-alive`, even though I attempted to use ipp-usb's quirks to force the printer to `close` the connection. To rule out a printer issue, I printed a test document from my phone, which completed without any delays or issues. Furthermore, this probem does not happen with the native driver.

I experimented this issue in Ubuntu 22.04 and Ubuntu 22.04. For the latter case, the CUPS version is `2.4.1op1-1ubuntu4.1`.

Please let me know if you require more information, or if there's anything I can do to resolve this issue.

**Comment by p21nc3** [comment]
[gustingonzalez](https://github.com/gustingonzalez) Check if the printer is using the correct driver. Make sure that you have installed the correct driver for your printer model and that it is configured properly in CUPS.

**Comment by gustingonzalez** [comment]
@p21nc3, although the native driver works fine, the problem occurs when using the driverless approach, via IPP.

**Comment by zdohnal** [comment]
IIUC the issue happens with IPP, regardless over USB or network, but then I see a IPP-USB log - have you tried it via ethernet or wifi? It would be great if you set it over network and tested it, so I can rule out ipp-usb.

In any case, there is a link in issue template - https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md - please follow it and provide the requested data.

**Comment by gustingonzalez** [comment]
@zdohnal, thanks for the response.

I've tested the printer over the network and happens the same issue.

 Below are the required data:
1. Ubuntu 22.04.2 LTS (but tested on 20.04 too, with same problem).
2. Cups version 2.4.1op1-1ubuntu4.1
3. N/A
4. When a document is printed, the printer remains in 'printing' state for 60 seconds, causing a delay for subsequent jobs.
5. M6559NW
6. Done.
7. Done.
8. Done.
9. Here is the [error_log.txt](https://github.com/OpenPrinting/cups/files/11240781/error_log.txt) and the journalctl [log.txt](https://github.com/OpenPrinting/cups/files/11240803/log.txt).
10.

`lpstat -e`
      Pantum_M6550NW_series_3D8C80_USB

`lpstat -t` (the output is in spanish):
```
el planificador de tareas se está ejecutando
no hay un destino predeterminado del sistema
dispositivo para Pantum_M6550NW_series_3D8C80_USB: implicitclass://Pantum_M6550NW_series_3D8C80_USB/
Pantum_M6550NW_series_3D8C80_USB aceptando peticiones desde sáb 15 abr 2023 18:22:36
la impresora Pantum_M6550NW_series_3D8C80_USB está inactiva.  activada desde sáb 15 abr 2023 18:22:36
```

`lpinfo -v`:
```
network beh
file cups-brf:/
network ipp
network lpd
network socket
network https
network http
network ipps
network ipp://Pantum%20M6550NW%20series%5B3D8C80%5D%20(USB)._ipp._tcp.local/
```
11. 
[Pantum_M6550NW_series_3D8C80_USB.ppd.txt](https://github.com/OpenPrinting/cups/files/11240794/Pantum_M6550NW_series_3D8C80_USB.ppd.txt)
12. The problem ocurrs with all tested files.
13. [d00245-001.txt](https://github.com/OpenPrinting/cups/files/11240795/d00245-001.txt)
14. That problem happens with LibreOffice, Document Viewer, printing from terminal, etc.

**Comment by zdohnal** [comment]
@gustingonzalez please provide the requested data when you print over the network and without cups-browsed (your printer is installed as implicitclass, which means it is installed via cups-browsed), so we can narrow the issue.

So it would be great if you turned off cups-browsed service, removed Pantum_M6550NW_series_3D8C80_USB printer if it still exists, unplug USB cable, use network connection (your printer seems to be in your local network, so you don't have to install it at all and it is available in ```lpstat -e```), reproduce the issue via network and provide error_log with debug messages, attr.log and network capture via wireshark.
