### ISSUE TITLE
Unable to encrypt connection: A TLS fatal alert has been received.

### ISSUE THREAD

**Issue by Slavik27** [OpenPrinting/cups#649]
Hello.
Please tell me how to fix this error

Unable to encrypt connection: A TLS fatal alert has been received.

E [11/Apr/2023:11:35:42 +0000] [Client 1] Unable to encrypt connection: A TLS fatal alert has been received.
E [11/Apr/2023:11:35:42 +0000] [Client 2] Unable to encrypt connection: A TLS fatal alert has been received.
E [11/Apr/2023:11:50:43 +0000] [Client 5] Unable to encrypt connection: A TLS fatal alert has been received.
E [11/Apr/2023:11:50:43 +0000] [Client 6] Unable to encrypt connection: A TLS fatal alert has been received.
E [11/Apr/2023:11:54:51 +0000] [Client 8] Unable to encrypt connection: A TLS fatal alert has been received.

**Comment by zdohnal** [comment]
Hi,

please follow the template and links in it and provide all requested information. Thank you!
