### ISSUE TITLE
Incorrect size is used for string comparison in copy_page function

### ISSUE THREAD

**Issue by GrosQuildu** [OpenPrinting/cups#658]
**Describe the bug**

The `copy_page` function uses `strncmp` to compare lines with constant strings. Most of the times length of the constant string (without trailing null-byte) is used as the `size` argument to the `strncmp`. However, for the `%%PageRequirements:` string of size 19, size `18` is provided:

https://github.com/OpenPrinting/cups/blob/12ff481989924fc82ffdf1b8699753a486a33547/filter/pstops.c#L1432-L1438

https://github.com/OpenPrinting/cups/blob/12ff481989924fc82ffdf1b8699753a486a33547/filter/pstops.c#L1400

Impact of the bug is probably minimal, but still it seems to be a valid bug.

**Comment by zdohnal** [comment]
Hi @GrosQuildu ,

thank you for the report! You're right, that's a bug.

@michaelrsweet IMO that's an easy fix, so I won't create a PR for it.
