### ISSUE TITLE
Manjaro Linux Print service not available

### ISSUE THREAD

**Issue by javychen-cn** [OpenPrinting/cups#66]
Error message：
Print service not available
Bad file description symbol

System information：
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.76.0
Qt Version: 5.15.2
Kernel Version: 5.9.11-3-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-4460 CPU @ 3.20GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4600

**Comment by javychen-cn** [comment]
But the version before 2.3.3 works normally

**Comment by jimersylee** [comment]
same as @javychen-cn

**Comment by michaelrsweet** [comment]
I don't have any experience with this particular Linux distribution, but one common problem I've seen when people update their CUPS installation is that they don't update the CUPS libraries as well as the rest of the software. Make sure all of your CUPS packages are the same version (or maybe you can attach the output of `pacman -Qi 'cups*'`?)

**Comment by javychen-cn** [comment]
@michaelrsweet  
Of course, they are updated synchronously. and the version before 2.3.3 has been working normally.
Can the version be reduced without upgrading?

**Comment by michaelrsweet** [comment]
@javychen-cn I'm the wrong person to ask, I've never used Manjaro (nor, honestly, heard of Manjaro before this bug report) so I don't know what the process is for reverting an update. Have you tried contacting the Manjaro or ArchLinux developers about this?

**Comment by andyrtr** [comment]
Manjaro users should report their bugs to the Manjaro packaging team and their bug tracker. If you find out it's not a packaging bug or a bad system configuration please come back with logs. 
(I guess what's happening here but since we at Arch Linux never get back anything useful form your distribution and Manjaro tries to make money out of our/my work I refuse to help here)

**Comment by javychen-cn** [comment]
@michaelrsweet  This has little to do with manjaro linux system, because as long as you do not upgrade cups, the problem will be solved. It may be that the content updated in version 2.3.3 is not compatible with the manjaro linux system

**Comment by javychen-cn** [comment]
@andyrtr thank you

**Comment by javychen-cn** [comment]
Restore, disable update,Fixed.

**Comment by javychen-cn** [comment]
Detailed steps（Chinese）:
https://gitee.com/javychen-cn/disupgrade

I hope it can help you.

**Comment by michaelrsweet** [comment]
Doesn't look like there is anything *we* can do to fix this...
