### ISSUE TITLE
CUPS not sending credentials to IPP printer

### ISSUE THREAD

**Issue by rhysperry111** [OpenPrinting/cups#660]
**Describe the bug**
I am trying to set up cups so that I can print to my school's print queue. In order to do this, I need to authenticate with the IPP print queue for each job. To do this, I have both added my credentials to the URL (e.g. `http://user:pass@server:port/path/to/printer`, and also set `AuthInfoRequired` so that CUPS requests credentials from the app sending the print job.

Whenever I send a job, the application correctly asks for credentials and I can see in the CUPS dashboard that the job is being processed. However, after a few seconds the job halts with the message "Held for authentication". It seems that CUPS isn't sending the credentials at all, which I verified using wireshark (capture attached).

**To Reproduce**
1. Add IPP printer that requires authentication
2. Attempt to send a job to printer
3. Job gets "held for authentication"

**Expected behavior**
I send a job to the printer, and it is successfully added to the school's print queue system.

**System Information:**
 - OS and its version: Arch Linux
 - Application: Any
 - CUPS version: 2.4.2

**Additional context**

Wireshark capture: http://0x0.st/H8RR.pcapng (my device is 10.109.9.30 and the printer is 192.168.60.58)

**Comment by michaelrsweet** [comment]
OK, so using the "http" scheme isn't supported for this - that was just for IPP/1.0 - and putting the username and password in the device URI is not recommended (for obvious reasons).

We'll need a debug `error_log` file (run `cupsctl --debug-logging` and then try printing) to further debug this issue.

**Comment by rhysperry111** [comment]
Removed the credentials from the URI, and switched to `ipp` while manually specifying port 80. Same thing happens: client submits job, credentials are requested from client, credentials are sent, job still ends up held for authentication.

[
[cups_error.log](https://github.com/OpenPrinting/cups/files/11646376/cups_error.log)
](url)

**Comment by zdohnal** [comment]
@rhysperry111 thank you for the logs!

The Microsoft IIS/10.0 server you are connecting to expects Kerberos authentication:

```
D [04/Jun/2023:19:21:47 +0100] [Job 91] Getting supported attributes...
D [04/Jun/2023:19:21:48 +0100] [Job 91] password_cb(prompt=\"Password for rhysperry on 192.168.60.58? \", http=0x556406856710, method=\"POST\", resource=\"/printers/PrintQueue/.printer\", password_tries=0x7ffe3f84a164(0)), password=0x7ffe3f852fcb
D [04/Jun/2023:19:21:48 +0100] [Job 91] Get-Printer-Attributes: cups-authentication-canceled (Unauthorized)
D [04/Jun/2023:19:21:48 +0100] [Job 91] Get-Printer-Attributes returned cups-authentication-canceled.
D [04/Jun/2023:19:21:48 +0100] [Job 91] ATTR: auth-info-required=negotiate
```

the last message goes from this code:

```
      else if (ipp_status == IPP_STATUS_ERROR_FORBIDDEN ||
               ipp_status == IPP_STATUS_ERROR_CUPS_AUTHENTICATION_CANCELED)
      {    
        const char *www_auth = httpGetField(http, HTTP_FIELD_WWW_AUTHENTICATE);
                                        /* WWW-Authenticate field value */

        if (!strncmp(www_auth, "Negotiate", 9))
          auth_info_required = "negotiate";
        else if (www_auth[0])
          auth_info_required = "username,password";

        fprintf(stderr, "ATTR: auth-info-required=%s\n", auth_info_required);
```

where you can see it gets the data from ```http``` structure, which represents HTTP connection with the destination and currently it contains HTTP header fields from the response - HTTP header WWW Authenticate from the response contains ```negotiate```, which means Kerberos for CUPS.

You will have to set your local queue to use Kerberos and get the ticket, or reconfigure Microsoft server (if possible - but I haven't seen such configuration yet) to accept username,password auth.
