### ISSUE TITLE
Regression: snprintf emulation function calls snprintf, causing recursion problem

### ISSUE THREAD

**Issue by michaelrsweet** [OpenPrinting/cups#67]
I was a little too eager to replace the sprintf calls with sprintf in cups/snprintf.c, need to make them sprintf again and add a comment so we don't do this again.

Also investigate options for not using snprintf emulation on Windows... :/

**Comment by sicklittlemonkey** [comment]
I see this in config.h, but no notes about what the breaking behaviour is:
`/* Windows snprintf/vsnprintf are non-conforming */`

What (if any) versions of Windows or Visual Studio are targeted now? Today's MS is not my father's son's MS. ; - )

I noticed this in the [docs for snprintf](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l):
> "Beginning with the UCRT in Visual Studio 2015 and Windows 10, snprintf is no longer identical to _snprintf. The snprintf function behavior is now C99 standard compliant."

A small victory after so many years, I know, but things are [changing](https://devblogs.microsoft.com/cppblog/a-multitude-of-updates-in-visual-studio-2019-version-16-8-preview-3/):

> All required features of C11 and C17 are now supported ... Note that the optional features are not supported, so we do not claim C99 compliance. Learn more in our [C11/C17 blogpost](https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/).

> For many years Visual Studio has only supported C to the extent of it being required for C++. Things are about to change now that a conformant token-based preprocessor has been added to the compiler. With the advent of two new compiler switches, /std:c11 and /std:c17, we are officially supporting the latest ISO C language standards.

**Comment by michaelrsweet** [comment]
@sicklittlemonkey I did some digging but wasn't able to find the original reason this was added. I suspect there was, at some point, some difference in behavior between the MSVC runtime and POSIX/C99, but I didn't bother to include that information in the comment or any of the various commit messages.

In my HTMLDOC project, I just use _snprintf, so maybe that is the solution here vs. using the emulation functions... 🤷‍♂️

**Comment by michaelrsweet** [comment]
Reading through the documentation, I think the issue was the return value - the old MS snprintf didn't support passing a NULL buffer or returning the total formatted length (vs. the length of the string), which is used in the cupsd logging functions to format an arbitrarily long line. But since cupsd isn't something that can be compiled with Visual Studio, that doesn't seem particularly important... Also, it looks like the new, more standard snprintf implementation doesn't have this problem anyways so...

**Comment by michaelrsweet** [comment]
[master af4fae4f8] Fix snprintf emulation function (Issue #67)
[master 5be9389db] Update config header files.
