### ISSUE TITLE
No color on CUPS 2.4.2

### ISSUE THREAD

**Issue by ve2tmq** [OpenPrinting/cups#672]
After upgrade (Ubuntu 23.04)  CUPS is passed to 2.4.2.  They is no way to print in color.  Print in black only.
Purge and reinstall will get same issue.

**Expected behavior**
Unable to print in color.

**System Information:**
 - OS and its version: Ubuntu 23.04
 - Application: any
 - CUPS version 2.4.2

**Comment by ve2tmq** [comment]
The solution is simple.  Do not use PPD anymore.  Delete printer then reinstall as RAW / IPP Everywhere.

**Comment by zdohnal** [comment]
There are several fixes in upstream regarding this issue for PPD files. Contact your distro support for backporting them until there is new CUPS release.
