### ISSUE TITLE
Why macOS tests take so long

### ISSUE THREAD

**Issue by AtariDreams** [OpenPrinting/cups#673]
**The issue is not cups in itself, but macOS**
macOS has cups running in the background, owned by the root user. This process immediately respawns even when one force-quits the process.

As a result,  lpstat's "Waiting for jobs to finish" ALWAYS reports 1 job running, and this goes until the timeout happens

There needs to be a workaround for this when running the tests for macOS.

**Comment by AtariDreams** [comment]
<img width="810" alt="Screen Shot 2023-04-24 at 9 45 02 AM" src="https://user-images.githubusercontent.com/83477269/234015151-362104f6-ff37-42b9-bd0c-ec71daca0346.png">

**Comment by AtariDreams** [comment]
Update: Now happening on linux when I compile with clang and run the tests @michaelrsweet compiler bug maybe?

**Comment by AtariDreams** [comment]
> No, it is using the wrong domain socket. Investigating...

CUPS or lstat? what is using the wrong socket?

**Comment by michaelrsweet** [comment]
CUPS

**Comment by michaelrsweet** [comment]
Hmm, I can no longer reproduce this issue but there have been a bunch of fixes in the last year...

**Comment by michaelrsweet** [comment]
Looks like things started working after my CUPS-Create-Local-Printer fixes in 9383b37...
