### ISSUE TITLE
Will repeated lp and lpoptions options be removed?

### ISSUE THREAD

**Issue by bfg01** [OpenPrinting/cups#683]
First, very sorry if this is not the correct place to ask something like this; not justified but I'm a bit slightly desperate...

At office I deal with both fairly recent and ancient printers.

The later ones can only work with old PPDs; this is, by adding with lpadmin -i or -P option.
The thing is, even after reading the manual and docs, I simply don't understand what the actual difference is, even if in "historic context", and when each one used to be used.

As well, for cancelling failed print jobs, there are the commands "lprm" and "cancel".
The same question, what's the difference? Which one to use when?

Thanks beforehand, and again sorry if this is not the right place.

**Comment by debiantriage** [comment]
A better place to have put this would have been here [here.](https://github.com/OpenPrinting/cups/discussions)

The difference between -i and -P isn't of any consequence. I would use -P. Note that both options will be removed in CUPS 3.0 and you will have to use a Printer Application for your classic (ancient) printers.

Broadly speaking, `lprm` and `cancel` do the same thing. I would forget about using `lprm`.
