### ISSUE TITLE
cups-pki-invalid error on CUPS 2.3.3op2 on RaspberryOS

### ISSUE THREAD

**Issue by Rallyefahrer** [OpenPrinting/cups#689]
Hi,

After a fresh installation of RaspberryOS Bullseye 64bit and CUPS 2.3.3op2 as print server, using brlaser v6 driver
(status Idle, Accepting Jobs, Shared, Server Default) any printing attempt from network will abort always with the error "cups-pki-invalid".
Error message in /var/log/cups/error_log: [Client 50] Unable to encrypt connection: Error in the push function.

Same setup worked flawless in the past on this RPi.

Regards, Markus

**System Information:**
 - OS and its version: RaspberryPi OS bullseye 64bit

**Comment by michaelrsweet** [comment]
Check the permissions of /etc/cups/ssl.

**Comment by Rallyefahrer** [comment]
drwx------ 2 root lp    4096 May  5 19:33 ssl
-rw-r--r-- 1 root root 1489 May  5 19:33 raspberrypi<xyz>.crt
-rw-r--r-- 1 root root 1675 May  5 19:33 raspberrypi<xyz>.key

**Comment by michaelrsweet** [comment]
Try deleting the raspberrypi.crt/key files - it is possible the generated certificate is invalid or no longer supported (i.e. newer certificate requirements)

That said, 2.3.3op2 is OLD and doesn't have the certificate fixes from newer OpenPrinting CUPS releases. You should be able to get at least 2.4.2...

**Comment by Rallyefahrer** [comment]
Did now a complete purge and reinstallation of cups, now it seems to work again. Will close the ticket. Thank you for your efforts !

**Comment by Rallyefahrer** [comment]
Closed, see above comment.
