### ISSUE TITLE
Detection of media-ready for ipp printer

### ISSUE THREAD

**Issue by ggodlewski** [OpenPrinting/cups#696]
**Is your feature request related to a problem? Please describe.**

I have Brother QL-710W label printer.

It is able to detect inserted label type:

```
ipptool -tv ipp://Brother%20QL-710W._ipp._tcp.local/ get-printer-attributes.test | grep media | grep ready
        media-ready (keyword) = roll_current_62x0mm
        media-col-ready (collection) = {media-type=roll media-size={x-dimension=6200 y-dimension=1270-100000} media-bottom-margin=303 media-left-margin=154 media-right-margin=154 media-top-margin=303 media-source=main media-source-properties={media-source-feed-direction=short-edge-first media-source-feed-orientation=3}}
```

Because it's using image/urf format I have to print through cups. Unfortunately cups is not reporting media-type:

```
ipptool -tv ipp://localhost:631/printers/QL710W-net get-printer-attributes.test | grep media | grep ready
# Nothing
```

**Describe the solution you'd like**
**Describe alternatives you've considered**

I'd like to have media-ready properties in ipp query response.
I don't want to entry two addresses in my app. One for media query, second for printing.

1. It can be automatic query brother printer by cups each time I query localhost:631
2. It can be manually set. I will create script which will query brother every x seconds and somehow reconfigure cups.

There is a `cups_update_ready` function which seems to do something like that but I have no idea where it's called from and how does it work.

I cannot change `media-ready` manually:

```
lpadmin -p QL710W-net -o media-ready=roll_current_62x0mm
# Changes nothing
```

**Additional context**

I'm writing app for printing shipping labels, qr codes, etc.

**Comment by michaelrsweet** [comment]
OK, so cupsd does not (generally) report ready media from the printer because the values will basically always be out of date. Instead, the `cupsGetDestMedia*` APIs can be used to get the current ready media for a print queue (destination), using the `CUPS_MEDIA_FLAGS_READY` flag. For CUPS 2.x, this does not include the "media-type" value but it will give you the current roll width (for example).
