### ISSUE TITLE
Update SECURITY.md for GitHub security vulnerability reports

### ISSUE THREAD

**Issue by tillkamppeter** [OpenPrinting/cups#703]
All OpenPrinting GitHub repositories support private security vulnerability reports now, including CUPS. Also, most repos have a template selector page when reporting a new issue, including a button for security reports, also CUPS has this functionality.

The reports are visible to a security team defined in the OpenPrinting GitHub.

So the SECURITY.md file should reflect this.

**Comment by zdohnal** [comment]
Hi Till,

I've updated the SECURITY.md and added the required steps for release managers regarding vulnerabilities on the wiki. Check https://github.com/OpenPrinting/cups/wiki/How-to-Be-a-Release-Manager .

**Comment by tillkamppeter** [comment]
Thank you very much @zdohnal ! Looks all great, especially also the instructions for the maintainer how to handle security bug reports.
