### ISSUE TITLE
Printer instances no more working

### ISSUE THREAD

**Issue by michaelweghorn** [OpenPrinting/cups#71]
Since commit c5f5c5a, printer instances don't work anymore.

They can be created, e.g. using

    lpoptions -p myprinter/myinstance -o Duplex=None

and then show up in `~/.cups/lpoptions`. However, they are not listed when e.g. running `lpstat -v` or in print dialogs.

(This was originally reported for https://github.com/apple/cups , s. https://github.com/apple/cups/pull/5679 and https://github.com/apple/cups/issues/5716 for some more information.)

**Comment by pranjanpr** [comment]
@michaelweghorn Is the CUPS code not reading `~/.cups/lpoptions` file properly only for printer instances or for default printers too?

**Comment by michaelweghorn** [comment]
> @michaelweghorn Is the CUPS code not reading `~/.cups/lpoptions` file properly only for printer instances or for default printers too?

@pranjanpr: This only affects CUPS printer instances. Other printers were working just fine in my tests and user settings from `~/.cups/lpoptions` were also properly taken into account for those.

**Comment by pranjanpr** [comment]
@michaelweghorn What is the expected output after `lpstat -v` command. Should it be showing the instances too. Eg. Apart from listing all printers should it be showing something like `instance for printer_name: instance_name`. Also can you please provide a screenshot of the terminal how the `lpstat -v` command behaved before the commit `c5f5c5a` .

**Comment by michaelweghorn** [comment]
> @michaelweghorn What is the expected output after `lpstat -v` command. Should it be showing the instances too. Eg. Apart from listing all printers should it be showing something like `instance for printer_name: instance_name`. Also can you please provide a screenshot of the terminal how the `lpstat -v` command behaved before the commit `c5f5c5a` .

@pranjanpr: Sample output with CUPS 2.2.1 in Debian 9:

Before setting up a printer instance (with only the cups-pdf printer set up):

    $ lpstat -v
    device for PDF: cups-pdf:/

Command to set up an instance "myinstance" for the printer "PDF":

    $ lpoptions -p PDF/myinstance -o Resolution=600dpi

lpstat output after setting up the instance:

    $ lpstat -v
    device for PDF: cups-pdf:/
    device for PDF/myinstance: cups-pdf:/

-> has a line for the instance as well; this is no more there with current CUPS versions

**Comment by michaelrsweet** [comment]
[master b53ad5bf3] Fix printer instances (Issue #71)
