### ISSUE TITLE
 USB communication with device fails from CUPS 2.2.12 due to CUPS code change (Issue #5583).

### ISSUE THREAD

**Issue by AveekBasu** [OpenPrinting/cups#72]
Lexmark Linux Print Driver is failing while communicating with our devices over USB from CUPS 2.2.12.

Details of the issue is given below:

**API Used:**
We use CUPS backend channel APIs while doing Bi-Di (Auto Configuration) through our filter in USB mode. The APIs we have been using are:

1. cupsBackChannelRead()
2. cupsSideChannelDoRequest()

**Problem:**
In Linux Distros like Ubuntu 20.04, Fedora 32/33 with CUPS version 2.2.12 and higher, our Filter is failing while trying Bi-Di through USB. We checked our log and found the reply from "cupsBackChannelRead()" API is incorrect. Some unnecessary data is coming in front of the original data which is also incomplete.

**Analysis & Findings:**
1. The problem doesn't exist in CUPS 2.2.10 (Debian 10.7).
2. The problem exists in Linux Distros with CUPS version 2.2.12 and higher like Ubuntu 20.04, Fedora 32/33 e.t.c.

**CUPS Release Notes:**
In CUPS's release notes there were some libusb changes which were done in CUPS 2.2.12

The libusb-based USB backend now enforces read limits, improving print speed in many cases (Issue #5583). 
(https://github.com/apple/cups/commit/35e927f83529cd9b4bc37bcd418c50e307fced35)

**Observation:**
We downloaded the CUPS's source code from GIT and reverted the particular change mentioned above, and the issue was not observed.
<img width="762" alt="Screenshot 2021-01-06 at 8 15 44 PM" src="https://user-images.githubusercontent.com/43844537/103781184-01a90700-505c-11eb-96ff-0bbb802bbe80.png">

**Comment by michaelrsweet** [comment]
[master bc2c17ad8] Just use a simple 250ms sleep in the read loop (Issue #72)

**Comment by AveekBasu** [comment]
Thanks for the updates Mike. We will test it out and let you know.

**Comment by AveekBasu** [comment]
Mike,

The issue is still reproducible. Please let me know if you need some logs or other details.

Regards,
Aveek

**Comment by michaelrsweet** [comment]
@AveekBasu Hmm, well, yes debug logs would be useful. It would also be useful to know how frequently you are reading and what timeout you are using in the call to cupsBackChannelRead.

**Comment by AveekBasu** [comment]
@michaelrsweet sure. Sending you the details soon.

**Comment by AveekBasu** [comment]
@michaelrsweet Hi Mike,

Here is the code snippet for your reference. Also attached is the CUPS error log.
[FilterFailedLog.txt](https://github.com/OpenPrinting/cups/files/6002967/FilterFailedLog.txt)




Data npaStart(START_NPA_MODE, sizeof(START_NPA_MODE));
iRet = pConnection_->doWrite(&npaStart);

iRet = pConnection_->doWrite(pCommand);
int iContinue = DATAREAD_CONTINUE;

      if(iRet == ERROR_SUCCESS)
       {
                   sequenceNumber_ = 0;
                    while((iRet == ERROR_SUCCESS) && (iContinue == DATAREAD_CONTINUE))
                    {
                        Data readData;
                        iRet = pConnection_->doRead(readData);             

                        if(iRet == ERROR_SUCCESS)
                        {
                            iContinue = processResponse(&readData, pCommand->getErrorCheckingByte(), errorCheckVal);
                            bReadSuccess = true;
                        }
                    }                   
        }

           .............................................
           ............................................
int CupsBackendConnection::doRead(Data& readData)
{
    int iRet = ERROR_FAIL; //read error
    int dataRead = 0;
    unsigned char tmpBuffer[512];
    memset(tmpBuffer, 0, sizeof(tmpBuffer));    

    for(int retryCnt = 0; retryCnt < 2; retryCnt++)
    {
        dataRead = (int)cupsBackChannelRead((char*)tmpBuffer, sizeof(tmpBuffer), getTimeoutVal());     
        if(dataRead > 0)
        {
            setTimeoutVal(0.200);
            break;
        }
    }
......
}

**Comment by michaelrsweet** [comment]
@AveekBasu Can you test the changes @zdohnal has proposed in #160? I'm wondering if they might fix the issues you are seeing?

**Comment by AveekBasu** [comment]
Sure @michaelrsweet will check and confirm..

**Comment by AveekBasu** [comment]
@michaelrsweet unfortunately the changes proposed by @zdohnal is not working for us...However doing the following changes seem to be working for us... 

if ((readstatus != LIBUSB_SUCCESS || rbytes == 0) &&
   (g.wait_eof || !g.read_thread_stop))
    usleep(250000);

in place of

if ((g.wait_eof || !g.read_thread_stop))
    usleep(250000);

**Comment by michaelrsweet** [comment]
OK, we are just going to revert this change and see how things fall out for the original reporters of this issue...

**Comment by michaelrsweet** [comment]
Pushed #174 which reverts the CUPS 2.2.12 change causing this issue.

**Comment by ChristianNext** [comment]
How can I find out when this patch will land in Ubuntu 21.04? Compiling cups-2.3.3op1 did not help.  Samsung ML-1640, many tks
