### ISSUE TITLE
Test failed: httpdaddrGetList fails to execute when hostname contains capital letters

### ISSUE THREAD

**Issue by wenpei-z** [OpenPrinting/cups#723]
**Describe the bug**

httpdaddrGetList fails to execute when hostname contains capital letters

**To Reproduce**
1.git clone https://github.com/OpenPrinting/cups.git
2.Compile and make check

**Expected behavior**

httpdaddrGetList() executed successfully

**Screenshots**
![image](https://github.com/OpenPrinting/cups/assets/107899637/1f3b4da8-a2a2-4d21-ac62-1bae7ecb7d23)

**Comment by zdohnal** [comment]
Hi,

I can't reproduce with the latest version.

Can you try with the latest version? What is your OS?

**Comment by michaelrsweet** [comment]
Also, CUPS is just passing the hostname through getnameinfo, and DNS is case-insensitive.

**Comment by zdohnal** [comment]
No response here for 3 months, closing the issue.
