### ISSUE TITLE
client-error-conflicting-attributes

### ISSUE THREAD

**Issue by ghostman-git** [OpenPrinting/cups#725]
VMware-workstation
ubuntu-22.04.2
cups-2.4.4

var/log/cups/error_log:
W [10/Jun/2023:17:24:38 +0800] Printer drivers are deprecated and will stop working in a future version of CUPS. See https://github.com/OpenPrinting/cups/issues/103
E [10/Jun/2023:17:25:25 +0800] [Client 24] Returning IPP client-error-conflicting-attributes for Print-Job (ipp://localhost/printers/Zebra-Technologies-ZTC-ZT410R-203dpi-ZPL) from localhost.

![image](https://github.com/OpenPrinting/cups/assets/13376074/23407835-c273-47ee-9d15-807dded9f29f)

**Comment by zdohnal** [comment]
No response for two months, closing. If you provide requested data, I'll investigate.
