### ISSUE TITLE
12 decimal place PageSize values with IPP Everywhere generated PPD

### ISSUE THREAD

**Issue by dkosovic** [OpenPrinting/cups#728]
With an IPP Everywhere generated PPD file, `PageSize` lines like some of the following get generated that have points sizes with 12 decimal places:

```C
*PageSize 195x270mm: "<</PageSize[552.755905511811 765.354330708661]>>setpagedevice"
*PageSize 270x390mm: "<</PageSize[765.354330708661 1105.511811023622]>>setpagedevice"
*PageSize 4x6: "<</PageSize[288 432]>>setpagedevice"
*PageSize 8x13: "<</PageSize[576 936]>>setpagedevice"
*PageSize 98x148mm: "<</PageSize[277.795275590551 419.527559055118]>>setpagedevice"
*PageSize A3: "<</PageSize[841.889763779528 1190.551181102362]>>setpagedevice"
*PageSize A4: "<</PageSize[595.275590551181 841.889763779528]>>setpagedevice"
*PageSize A5: "<</PageSize[419.527559055118 595.275590551181]>>setpagedevice"
*PageSize A6: "<</PageSize[297.637795275591 419.527559055118]>>setpagedevice"
*PageSize ARCHB: "<</PageSize[864 1296]>>setpagedevice"
*PageSize B4: "<</PageSize[728.503937007874 1031.811023622047]>>setpagedevice"
*PageSize B5: "<</PageSize[515.905511811024 728.503937007874]>>setpagedevice"
*PageSize B6: "<</PageSize[362.834645669291 515.905511811024]>>setpagedevice"
*PageSize Executive: "<</PageSize[522 756]>>setpagedevice"
*PageSize ISOB5: "<</PageSize[498.897637795276 708.661417322835]>>setpagedevice"
*PageSize Legal: "<</PageSize[612 1008]>>setpagedevice"
*PageSize Letter: "<</PageSize[612 792]>>setpagedevice"
*PageSize SRA3: "<</PageSize[907.086614173228 1275.590551181102]>>setpagedevice"
*PageSize Statement: "<</PageSize[396 612]>>setpagedevice"
*PageSize Tabloid: "<</PageSize[792 1224]>>setpagedevice"
```

Most manufacture supplied PPD files use integer points size values for PageSize, e.g. A4:
```C
*PageSize A4: "<</PageSize[595 842]>>setpagedevice"
```

Extract from PWG's IPP Job Extensions v2.1 candidate standard:
* https://ftp.pwg.org/pub/pwg/candidates/cs-ippjobext21-20230210-5100.7.pdf
> **6.3.1.15 media-size (collection)**
> 
> A requested media size dimension matches a supported media dimension if it is within an implementation-defined tolerance. For example, PostScript specifies a tolerance of 5 points (5/72 of an inch = 1.7 mm) of a supported dimension, i.e., within 176 units of the value of the dimension.

I'm wondering does CUPS actually needs 12 decimal place points sizes for `PageSize` and if rounded integers could be used instead? Possibly the same question for `PageRegion`, `PaperDimension` and `ImageableArea`?

**Comment by michaelrsweet** [comment]
We need at least 4 places to ensure the correct pixel dimensions of any raster data. WRT the matching tolerance, that is for selecting between supported sizes. Since an IPP printer may report/support non-standard sizes, we can't rely on matching to generate pages at the proper size...

I don't think we need to make a change here - this code is no longer used in CUPS 3.0 (where the native units are used instead of PostScript points) and having the extra digits doesn't dramatically increase the size of the generated PPDs.
