### ISSUE TITLE
The CUPS out of order on my arm board  [Website shows not found] [lpinfo cannot normally execute]

### ISSUE THREAD

**Issue by qq645327806** [OpenPrinting/cups#732]
Hello, Dear every developer:
  I am new to CUPS. Recently, I want to port the CUPS to my arm board. When I finished the work of cross compilation and run CUPS on my board, I found that I only can visit the home page. When I click other pages , it shows NOT FOUND. 
  At the same time , when i input command "lpinfo -v" and "lpinfo -m", the screen show me "lpinfo: cups-deviced failed to execute." and "lpinfo: cups-drived failed to execute." . I don't know what went wrong with CUPS. 
  Here are my log files and conf file.
                            
[github_issue_cups_20230620202209.zip](https://github.com/OpenPrinting/cups/files/11800302/github_issue_cups_20230620202209.zip)

Thank you.

**Comment by qq645327806** [comment]
These log files, I do something, and the steps are as follows:
1. dbus-daemon --system
2. avahi-daemon & 
3. ./cups start
4. I clicked the PRINTER page and JOB page.
5. I input "lpinfo -v" and "lpinfo -m" command.
6. I input command "kill" to kill the cups.

**Comment by zdohnal** [comment]
Directories where you put the installation don't have the correct permissions:

```
E [01/Jan/1970:00:08:51 +0000] Directory \"/mnt/app/printer/lib/cups/cgi-bin\" has insecure permissions (040777/uid=0/gid=0).
...
E [01/Jan/1970:00:08:59 +0000] Directory \"/mnt/app/printer/lib/cups/daemon\" has insecure permissions (040777/uid=0/gid=0).
```

Usually they have 755 and root:root.

**Comment by qq645327806** [comment]
@zdohnal Hi zdohnal, I meet a new question.  I do the cmd "chmod 777 -R" , it shows "has insecure permissions (0100777/uid=0/gid=0)" . But，  I do the cmd "chmod 755 cgi-bin -R " , the error_log shows "stopped with status 113 (permission denied)". Could you tell me why ? I dont't dnow how to solve this problem. Here's the log.
[error_log_20230627112309.zip](https://github.com/OpenPrinting/cups/files/11877326/error_log_20230627112309.zip)

**Comment by qq645327806** [comment]
Is there anything I can do to keep him it checking permissions？

**Comment by qq645327806** [comment]
@zdohnal Hi zdohnal, I did what you said. And I meet new question:  I do the cmd "chmod 755 printers.cgi" and error_log shows "(/mnt/app/printer/lib/cups/cgi-bin/printers.cgi) stopped with status 113 (Permission denied)". Then I do the cmd "chmod 777 printers.cgi" and error_log shows "File \"/mnt/app/printer/lib/cups/cgi-bin/printers.cgi\" has insecure permissions (0100777/uid=0/gid=0)". Seems to be either 755 or 777, the CUPS still run abnormally. 
 Did I do something wrong? Is there any way to not check permissions？ Here 's error_log. Thank you.
[error_log_20230627144746.zip](https://github.com/OpenPrinting/cups/files/11878562/error_log_20230627144746.zip)

**Comment by zdohnal** [comment]
What are the configure option you used for building CUPS?

I'm sorry, I haven't done any cross compilation stuff, so I'm not entirely sure, but are you running cupsd under root? It could be the reason.

**Comment by qq645327806** [comment]
Hi zdohnal，my configure option is as follow:
./configure --prefix=/mnt/app/printer --host=aarch64-mix210-linux CFLAGS="-I/mnt/app/printer/include" CXXFLAGS="-I/mnt/app/printer/include" LDFLAGS="-L/mnt/app/printer/lib -lssp -lavahi-client -lavahi-common -lgnutls -lz -lffi -lgmodule-2.0 -lglib-2.0 -ldbus-1 -lunistring -lp11-kit -ltasn1 -lnettle -lhogweed -lgmp -ludev -lusb-1.0" --enable-libusb --enable-debug --enable-debug-guards --enable-debug-printfs --disable-gssapi --with-adminkey --with-operkey --with-cachedir=/mnt/app/printer/var/cache/cups --with-tls=gnutls --with-dnssd=avahi --with-systemd=/mnt/app/printer/systemd/cups --with-log-level=debug --with-access-log-level=debug --with-idle-exit-timeout=60 --with-dbusdir=/mnt/app/printer/etc/dbus-1

**Comment by qq645327806** [comment]
And I use "sudo make DESTDIR=${PWD}/_n2 install " to install in my PC. Then I copy the files to my arm board. After copying, I change permission by using "chown" and "chgrp". I start service use "root".
But at now I find that, when I change permission "700" for "printers.cgi" it also shows "permission denied", I suspect CUPS is not run as root. But I use command "stat cgi-bin" and "ls -l" to view the permission, it shows root. And I use cmd "ps aux|grep cups", it also shows runing as root.

**Comment by qq645327806** [comment]
One more thing, my arm board only have root 1 user.

**Comment by qq645327806** [comment]
I also use other configure option , but the result is same. As follow:
./configure --prefix=/mnt/app/printer --host=aarch64-mix210-linux CFLAGS="-I/mnt/app/printer/include" CXXFLAGS="-I/mnt/app/printer/include" LDFLAGS="-L/mnt/app/printer/lib -lssp -lavahi-client -lavahi-common -lgnutls -lz -lffi -lgmodule-2.0 -lglib-2.0 -ldbus-1 -lunistring -lp11-kit -ltasn1 -lnettle -lhogweed -lgmp -ludev -lusb-1.0" --enable-libusb --enable-debug --enable-debug-guards --enable-debug-printfs --disable-gssapi --with-adminkey --with-operkey --with-cachedir=/mnt/app/printer/var/cache/cups --with-tls=gnutls --with-dnssd=avahi --with-systemd=/mnt/app/printer/systemd/cups --with-exe-file-perm=0777 --with-config-file-perm=0777 --with-cupsd-file-perm=0777 --with-log-file-perm=0777 --with-log-level=debug --with-access-log-level=debug --with-idle-exit-timeout=60 --with-dbusdir=/mnt/app/printer/etc/dbus-1

**Comment by zdohnal** [comment]
I'm sorry, I don't know how to help you further :( @michaelrsweet do you know what culprit can be or how to debug further? The only thing I can think of is capture syscalls with strace, which can give some insight...

**Comment by qq645327806** [comment]
@zdohnal It doesn't matter, zdohnal. I found the same question on(https://stackoverflow.com/questions/32462340/cups-permission-denied).  I do the same thing , but cups still shows permission denied or insecure permission. Could I modify the code for skipping the permission checking? And how to modify?

**Comment by qq645327806** [comment]
Hello, can someone help me ?

**Comment by qq645327806** [comment]
HI, By modifying the code in process.c,  I had solved my question. Thanks.
