### ISSUE TITLE
Performance issues when adding printers with the "lpadmin" command

### ISSUE THREAD

**Issue by ggdaboit** [OpenPrinting/cups#748]
Hello everyone!

We have a shell script to add printers to CUPS using lpadmin in a productive environment that has more or less 378 printers. 

This script runs on an EC2 on AWS upon startup, ensuring that all printers in the environment are registered if the instance is restarted.

In the CUPS version 1.7.5 + Alma Linux 9.2, 378+ printers are added in a few seconds (5~10s) of the shell script execution, as expected.

However, in CUPS version 2.3.3op2 + Alma Linux 9.2, the time to add printers via lpadmin using shell script upped dramatically, taking about 10+ minutes to add all the printers and this is impacting our environments. Each printer is taking about 2 seconds, independent of the driver used.

The script contains several printers, following the standard below:

/usr/sbin/lpadmin -p PRINTER1 -E -o printer-error-policy=retry-current-job -o "job-sheets=none, none media=na_letter_8.5x11in, cutter=page" -v "smb://user:password@domain/10.61.32.203/PRINTER1" -m drv:///sample.drv/generpcl.ppd
/usr/sbin/lpadmin -p PRINTER2 -E -o "job-sheets=none, none media=na_letter_8.5x11in" -v "socket://10.61.32.205" -m drv:///sample.drv/generpcl.ppd
... and repeat for more 376+ printers

Remembering that the printers are added, we have no error in the CUPS logs, even with debug mode activated. Our only issue is the performance of lpadmin for adding printers.

Both tests were tested with the same instance size on AWS, what is really impacting performance is the CUPS version, but we were unable to identify the cause.

We needed to use the latest versions for security reasons and also to be able to use the updated HPLIP in our production environments.

Can anyone help us with troubleshooting this situation? Any suggestions for the case? Why the time to add printers using lpadmin

**Comment by michaelrsweet** [comment]
CUPS 2.x does a lot more when adding printers than 1.x, particularly to support localization and IPP Everywhere attribute mapping. There isn't a lot *we* can do, but *you* can  archive the contents of the /etc/cups and /var/cache/cups directories and then restore them prior to starting cupsd - that will be significantly faster if you are spinning up fresh servers with the same set of printers.

**Comment by ggdaboit** [comment]
Thanks for the speedy reply!
