### ISSUE TITLE
Error with paper size when trying to print from Android device to Ricoh MFP

### ISSUE THREAD

**Issue by bfg01** [OpenPrinting/cups#757]
After trying, and reading about the topic, I understood that since Android 8 there's this Default Print Service, which seemingly already includes a vast number of printer drivers and uses IPP protocol; so no other 3rd-party apps are needed in most cases.
Please correct me if wrong.

So I tried printing to a Ricoh MP 402SFP from an Android device. Sorry, I cannot recall which exact version, just that it was between 10 and 12...
I tried printing from the particular app I was using. The app directly calls the Default Print Service, and finds the printer if they're in the same local network.

So tried. The print job is always successfully sent to the printer, but the printer pops an error: "no recognized paper size". I have to go into printer's events, manually select the tray with correct size, and click "continue". Only with this it prints, instead of just automatically printing without errors.

All of this even when I'm already positive that printer has the correct sizes configured (Letter, in this case). It's the correct 8.5x11. So other PCs printing to it have no problems.
I already did everything in printer's size to be positive that problem is not from there; thus the problem comes from the Android device, and I think from the print service rather than the app.
I do select "Letter" size there; though certainly there's no way to further customize the sizes...

If trying to print with Ricoh's proprietary app instead of default print service, it prints directly with no errors. But the app is just an app, not a service; thus cannot print directly from apps.

Oh, BTW, printing to other more "common" printers such as HP LaserJet ones via WiFi as well yields no problems at all.

By chance, is there something I could do regarding this?
Could there be alternate IPP Everywhere "drivers" for Android to try?

Thanks very much; sorry if this was the wrong section to ask in...

**Comment by michaelrsweet** [comment]
> After trying, and reading about the topic, I understood that since Android 8 there's this Default Print Service, which seemingly already includes a vast number of printer drivers and uses IPP protocol; so no other 3rd-party apps are needed in most cases. Please correct me if wrong.

The default Android print service is a generic IPP Everywhere client, so it supports any printer that supports IPP and a handful of standard document formats. It has a lot of limitations WRT media support, but for standard sizes should have no problem.

More than likely you are running into firmware bugs - the first place I'd go is the Ricoh web site to see whether there are any available firmware updates for your printer. If that doesn't work, contact Google and/or try one of the other print services available on the Google Play store...
