### ISSUE TITLE
My cups install doesn't seem to have IPP working as the server isn't discoverable on any device

### ISSUE THREAD

**Issue by adam-jones-net** [OpenPrinting/cups#758]
I'm using CUPS 2.4.1 and a clean Armbian (v 23.05.1 jammy) install on a Tinker Board.    It works fantastically printing text and raster images to my Brother printer (connected locally via USB).

The only issue is that on previous installs of CUPS I've made, the server was instantly discoverable on absolutely every device on my LAN, thanks to the magic of IPP from what I understand.    I could just go to "Find printers" in Windows, browse printers in Android, iOS, whatever I used the printer was automatically discovered via the os.    However with this new install of CUPS that isn't happening.

I worked out the local ipp:// address of my printer and so was able to setup a printer in Windows with just a few more steps.  However, for printing from phones it's a different matter.   I really want to get this working so I can just locate the CUPS server on my LAN automatically with it appearing in the printers list, like I was able to with a previous install.   

Where do I begin to troubleshoot this ?

I can't see any errors in the log file btw.

**Comment by debiantriage** [comment]
It is always useful to know the printer make and model. The outputs of `lpstat -t` and `lpstat -l -e` on the Tinker could also be of help.

**Comment by adam-jones-net** [comment]
lpstat isn't installed it seems.  I just tried to install it and I get 

Read_file_list: cannot stat required or included file '/etc/printcap' - No such file or directory

**Comment by debiantriage** [comment]
What is given by `which lpstat`? Printer make and model?

**Comment by adam-jones-net** [comment]
lpstat is now working for some reason, not quite sure why.  It reports...

system default destination: Brother_HL-L2320D_Living
device for Brother_HL-L2320D_Living: usb://Brother/HL-L2320D%20series?serial=U63877C2N833460
Brother_HL-L2320D_Living accepting requests since Thu Jul 20 12:39:56 2023
printer Brother_HL-L2320D_Living is idle.  enabled since Thu Jul 20 12:39:56 2023

**Comment by debiantriage** [comment]
Please give `sudo cupsctl` and `avahi-browse -rt _ipp._tcp`.

**Comment by adam-jones-net** [comment]
Ah fantastic  @debiantriage it was avahi.  It wasn't installed.   
When i installed CUPS on a Raspberry Pi this seems to have been installed as well but on Armbian it wasn't.   As soon as that was installed it works!  Thanks a lot, really appreciated.
