### ISSUE TITLE
Glossy paper not showing up in printing dialog for hp photosmart 5510

### ISSUE THREAD

**Issue by belegdol** [OpenPrinting/cups#766]
**Describe the bug**
Even though glossy paper is available in the hplip driver for photosmart 5510 printer, it is not showing for selection when printing.

**To Reproduce**
1. Install a hp 5510 series printer using hpcups driver from hplip-3.23.5
2. Open a photo in eog
3. Pick print
4. Go to page setup
5. Open paper type dropdown

**Expected behavior**
Plain paper, Glossy paper and Transparency film are available

**System Information:**
 - Fedora 38
 - I tried eog, gnome-text-editor and libreoffice calc. All are affected
 - CUPS 2.4.6
 
 **Additional context**
Glossy paper is shown if one goes to localhost:631 and goes to set up default printer options.

**Comment by zdohnal** [comment]
Hi,

CUPS is able to show the option via lpoptions and via IPP Get-Printer-Attributes request:

```
$ lpoptions -p hp5510 -l
PageSize/Media Size: Card3x5 Card4x6 PhotoL L.FB Photo3.5x5 PhotoL.FB Photo4x6 Photo4x6.FB Photo4x6tab Photo4x6tab.FB A6 A6.FB Hagaki Hagaki.FB Photo5x7 Photo5x7.FB Card5x8 A5 A5.FB Cabinet Cabinet.FB 2L 2L.FB Oufuku JB5 Executive *Letter Letter.FB A4 A4.FB Legal Photo10x15 Photo10x15.FB Photo10x15tab Photo10x15tab.FB Photo2L Photo13x18 Photo8x10 8x10.FB EnvA2 EnvC6 EnvChou4 Env6 EnvCard EnvMonarch EnvDL Env10 EnvChou3 EnvC5 Custom.WIDTHxHEIGHT
ColorModel/Output Mode: *RGB CMYGray KGray
MediaType/Media Type: *Plain Glossy TransparencyFilm
OutputMode/Print Quality: *Normal FastDraft Best Photo
InputSlot/Media Source: *Auto PhotoTray Upper
```

```
$ ipptool -tv ipp://localhost:631/printers/hp5510 get-printer-attributes.test | grep -i glossy
        media-type-supported (1setOf keyword) = stationery,photographic-glossy,transparency
```

thus IMO the issue is not in CUPS.

Please report the issue to specific applications.

**Comment by belegdol** [comment]
I am happy to report it to a specific application, but would you mind giving some pointers where to or how to debug this further? Gnome-text-editor uses a gtk4 print dialog, eog uses a gtk3 one whereas libreoffice uses its own dialog. All seem to be affected.
The only two apps I was able to find which is not affected are:
- scribus (which uses qt5) but it appears to work on a lower level. 
- firefox, if one switches to the system dialog. This is an interesting one as the dialog looks exactly like the eog one otherwise.
Oddly enough, system print dialog reports setting conflicts for the glossy paper:
![Bildschirmfoto vom 2023-07-27 09-36-09](https://github.com/OpenPrinting/cups/assets/1208329/26043ca7-def4-47d6-a478-c04b55b314ad)
![Bildschirmfoto vom 2023-07-27 09-36-19](https://github.com/OpenPrinting/cups/assets/1208329/ace703df-9a5b-42f8-88c8-f2ab557e9595)
While there are UIConstraints listed in the ppd file, glossy paper only appears to conflict with fast draft and some page sizes. Borderless Photo 4x6in from the screenshot does not conflict with the glossy paper, yet it is shown as such. I am guessing this is related.
If this is a wrong place for this discussion, would you mind sharing where to the gnome-print-dialog issues should be reported? I was looking for this yesterday but did not find the proper place. Thanks in advance.

**Comment by belegdol** [comment]
Reported to gnome as well:
https://gitlab.gnome.org/GNOME/gtk/-/issues/5987

**Comment by zdohnal** [comment]
>If this is a wrong place for this discussion, would you mind sharing where to the gnome-print-dialog issues should be reported? I was looking for this yesterday but did not find the proper place. Thanks in advance.

Gtk for GNOME print dialogs (and system dialogs, if you run GNOME), Libreoffice, Firefox, Chromium have their own, okular and other KDE apps use Qt.

Probably the restriction is applied to all settings instead of only with specified options...
