### ISSUE TITLE
missing header file

### ISSUE THREAD

**Issue by surajkulriya** [OpenPrinting/cups#77]
In `cups/cups/http-private.h` `cups/cups/language-private.h` `cups/cups/string-private.h` and `cups/cups/thread-private.h` , we are including config.h header file but it's not there.  Although there is config.h header file in there parent dir i.e. in `cups/` dir.

**Comment by surajkulriya** [comment]
@michaelrsweet  can you please look into this.

**Comment by michaelrsweet** [comment]
Those are not public header files and are not intended for use by programs.
