### ISSUE TITLE
"lpstat -a" @ AIX endless loop

### ISSUE THREAD

**Issue by StefCoene** [OpenPrinting/cups#773]
AIX requires a patch so lpstat -a does not hang for 15 minutes.
After 15 minutes, the command completes as expected.

This patch is also needed for the master version.

See also https://www3.software.ibm.com/aix/freeSoftware/aixtoolbox/PATCHES/cups-2.0.2-aix.patch
I moved the patch higher up in the file:

```
diff --git a/cups/request.c b/cups/request.c
index 66c803a04..059920e49 100644
--- a/cups/request.c
+++ b/cups/request.c
@@ -29,6 +29,10 @@
 #  define MSG_DONTWAIT 0
 #endif /* !MSG_DONTWAIT */
 
+#ifdef _AIX
+#define MSG_DONTWAIT MSG_NONBLOCK
+#endif
+
```

Stef

**Comment by zdohnal** [comment]
@michaelrsweet I'll apply combination of the @StefCoene patch and your proposal directly to master  - I take your comment as review.
