### ISSUE TITLE
unable to add my g2010 printer

### ISSUE THREAD

**Issue by shawn3308** [OpenPrinting/cups#774]
i can't add my printer

**Comment by debiantriage** [comment]
We assume the device is a Canon PIXMA G2010 All-in-One Ink Tank Colour Printer. It is a USB-only printer, so is not likely to provide IPP-over-USB. However, we can investigate. Give the output from
```
lsusb -v | grep -A 3 bInterfaceClass.*7
```
Also state the exact OS being used.

**Comment by shawn3308** [comment]
This is the os i am  using on my PI
![image](https://github.com/OpenPrinting/cups/assets/60691117/4883b0cd-587c-49b0-9c64-c0d38f0f8947)

and this is the out for your command 
![image](https://github.com/OpenPrinting/cups/assets/60691117/8e083408-f5dc-442e-90d4-8c23f6931cb1)

**Comment by shawn3308** [comment]
> We assume the device is a Canon PIXMA G2010 All-in-One Ink Tank Colour Printer. It is a USB-only printer, so is not likely to provide IPP-over-USB. However, we can investigate. Give the output from
> 
> ```
> lsusb -v | grep -A 3 bInterfaceClass.*7
> ```
> 
> Also state the exact OS being used.

https://in.canon/en/consumer/pixma-g2010/product

**Comment by debiantriage** [comment]
The G2010 does not offer the IPP-over-USB protocol. Therefore, driverless printing is not possible.

Canon India do have drivers, but not, it seems, for Ubuntu/Linux. Your searching might be more productive. The printer-driver-gurenprint package also does not appear to have a driver.

Personally, I do not see this issue as one for CUPS.

**Comment by shawn3308** [comment]
ok

**Comment by CreeperAWA** [comment]
I am using a Canon G2810 printer, which shares the same driver as the Canon G2010. Canon has now released a Linux version of the driver: [UFR II/UFRII LT Printer Driver for Linux V6.10](https://asia.canon/en/support/0100924010). This driver package includes source code. Is it compatible with CUPS?

**Comment by szlt5** [comment]
> I am using a Canon G2810 printer, which shares the same driver as the Canon G2010. Canon has now released a Linux version of the driver: [UFR II/UFRII LT Printer Driver for Linux V6.10](https://asia.canon/en/support/0100924010). This driver package includes source code. Is it compatible with CUPS?

The [UFR II/UFRII LT Printer Driver for Linux V6.10] is compatible with CUPS; and the driver package is for Canon Laser printer.
The Canon G2810 is inkjet printer, isn't it?

**Comment by CreeperAWA** [comment]
> > I am using a Canon G2810 printer, which shares the same driver as the Canon G2010. Canon has now released a Linux version of the driver: [UFR II/UFRII LT Printer Driver for Linux V6.10](https://asia.canon/en/support/0100924010). This driver package includes source code. Is it compatible with CUPS?
> 
> The [UFR II/UFRII LT Printer Driver for Linux V6.10] is compatible with CUPS; and the driver package is for Canon Laser printer. The Canon G2810 is inkjet printer, isn't it?

Oh, it seems like this. Sorry, I didn't see it clearly before

**Comment by CreeperAWA** [comment]
I've tried looking up some related resources, not sure if they'll be helpful. Perhaps you could try installing drivers for similar printer models to see if they function properly?
https://asia.canon/en/support/0302919101
https://ph.canon/en/support/0101091901?model=4465C
https://askubuntu.com/questions/1328309/how-to-install-canon-pixma-g2010-on-ubuntu-20-10
https://launchpad.net/~thierry-f/+archive/ubuntu/fork-michael-gruz
