### ISSUE TITLE
After error Printer doesn‘t work

### ISSUE THREAD

**Issue by Crazyfeet** [OpenPrinting/cups#779]
Hey there,

I‘ve installed cups on a raspberry pi. The Printer is a Mitsubishi CP D80 DW. I‘ve managed printing with SolomonPeaches drivers.
Everything works fine until the Printer ist in an „unusual“ state (for example: no paper left on roll). After reloading, the printer doesn‘t work until I do a complete new installation of this Printerdriver. After that new installation the printer works properly.

I‘m a complete noob at cups and raspi. I tried deleting the queue, but this also doesn‘t help. Nothing on the localhost:631 works for me either.

Background information:

I've programmed a Photobooth with Nikon DSLR, Touchscreen and the Raspberry pi. the complete programm is written in Python with Shell-Commands.

So there are two possible options for me, which could work:
Getting the printer new "activated" or so after a restart, that the printer works fine (like ->delete printer queue ->deactivate printer ->activate printer ->start program). This would be the best solution.
Second possibility is an automated new installation of this printer and the whole driver. This is for me very risky, because it could be, that the printer isn't connected to the raspberry and so the programm could possibly crash, at the Moment it should start. Another problem is, that i don't know how to install the printer automatically with shell or python commands.

Could someone please help me?

I'm sorry for my bad english. Hope you can understand my wirting. :-)

Thank you all!

**Comment by zdohnal** [comment]
Hi @Crazyfeet ,

please follow https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md and get us data when you get the unusual state and the failed printing afterwards.

I usually use ```cancel -a && cupsenable <printer_name>``` (fill <printer_name> with your printer's name from ```lpstat -a```) after I fix the error, because the printer gets disabled in some configurations.

**Comment by zdohnal** [comment]
No response for several months, closing.
