### ISSUE TITLE
Zing label printer driver

### ISSUE THREAD

**Issue by drumstick77** [OpenPrinting/cups#780]
Hi, I'm just wondering if anyone has got the ppd file for zing printer? it's a label printer driver, so I'm not sure if it can be installed in CUPS.
I've got the mac and windows drivers too, so potentially can make PPD file from them, but I've been reading around and the method is still a mystery to me.
please advise. thanks

**Comment by zdohnal** [comment]
Hi,

I haven't heard about a Linux driver for Zing printers, but IMO there are two options (I haven't studied your printer manual):


1. if your printer supports a driverless standard, so you don't need a classic driver - see [the article](https://docs.fedoraproject.org/en-US/quick-docs/cups-useful-tricks/#_how_to_find_out_whether_my_printer_is_capable_of_driverless_printing) about how to find out and how to set the printer.
2. If the printer does not support driverless and there is no Linux driver, contact your printer manufacturer to provide one. 

Alternatively, in case you can extract PPD file from Win/Mac driver and if the PPD file does not define an additional filter for printing which is not in Linux (keyword ```*cupsFilter(2)``` in ppd file), there is a good chance the PPD can work with CUPS. Then you can install it like:

```
$ lpadmin -p <name> -v <connection> -P <PPD file> -E
```

where ```<name>``` is a name how you want to call your printer, ```<connection>``` is device uri for your device - depends on how you connect the printer and it can be found by ```lpinfo -v```, and <PPD file> is a path to PPD file you've extracted.

Either way, CUPS (with several exceptions) does not provide specific printer drivers (and drivers are deprecated in CUPS and substituted by printer applications, which are currently available as SNAPs), so this is better question for your printer manufacturer.

**Comment by BasketCase808** [comment]
You need the PPD Driver to get this Thermal Label Printer working over USB (not tried wifi). The Manufacturers (Zing) website has Win and Mac Drivers. The Win Drivers do not work over VM w. USB FWD on Win 7.

FIX:
Found a website that sells the same printer but in a different brand name. Found a Driver that matches.

Original Driver:

https://labelrange.com/uploads/soft/20231201/1-231201134541647.zip

Patched Driver:
https://drive.google.com/drive/u/0/folders/15dfXKVV1a1zNZNdTYf_NuyoN5r3_lLTD

(short link: **https://tinyurl.com/zing-driver**)
