### ISSUE TITLE
filter failed

### ISSUE THREAD

**Issue by draculalaa** [OpenPrinting/cups#790]
**Describe the bug**
Can't print after adding printer, job state shows "stopped 'Filter failed' ".

**To Reproduce**
1. try to print with `lp -d Lenovo-M7208W -o Duplex=DuplexNoTumble Documents/test.pdf`, the printer doesn't work and http://127.0.0.1:631/jobs/ shows job state is "stopped 'Filter failed' "
2. retry and collect log
```
$ cupsctl LogLevel=debug2
$ lp -d Lenovo-M7208W -o Duplex=DuplexNoTumble Documents/test.pdf
$ sudo cp /var/log/cups/error_log ~/error_log.txt
```

**Expected behavior**
Print sucessfully.

**Screenshots**
None

**System Information:**
 - OS and its version: archlinux (6.5.2 kernel)
 - Application: cups, system-config-printer to attach printer , vivaldi-browser to open http://localhost:631/
 - CUPS version: 2.4.6
 - printer model: [LENOVO M7208W](https://www.manualslib.com/manual/1281882/Lenovo-M7208w.html)

**Additional context**
- [error_log.txt](https://github.com/OpenPrinting/cups/files/12617555/error_log.txt) cups log output
- [ppd_and_fliter.zip](https://github.com/OpenPrinting/cups/files/12617707/ppd_and_fliter.zip) .ppd file and fliter file (LNTHR1Z) , I got them form manufactor's website (https://newsupport.lenovo.com.cn/driveList.html?fromsource=driveList&selname=m7208w)
- [stat.txt](https://github.com/OpenPrinting/cups/files/12617904/stat.txt) output of lpstat -e, lpstat -t and lpinfo -v
- nothing changed with the default configuration of cups
- [test.pdf](https://github.com/OpenPrinting/cups/files/12618039/test.pdf) the file to be printed. not sure it's necessary or not
- [network_pcap.zip](https://github.com/OpenPrinting/cups/files/12618002/network_pcap.zip) output of `sudo tcpdump -s0 -w network.pcap -i any host 192.168.0.108`. not sure it's necessary and correct, or not

**Comment by zdohnal** [comment]
Hi,

thank you for all the data! It helps a lot!

From the logs you've provided I see you had problems with running the filter - I see some ```file not found```, ```permission denied``` - and lastly ```execv()``` is not able to run the filter and ends with error:

```
D [15/Sep/2023:16:36:54 +0800] [Job 14] execv failed: Exec format error
```

The source of this error is that the driver you've installed is for MacOS, not Linux.

I searched a little and found this page [LENOVO M7208W](https://www.manualslib.com/manual/1281882/Lenovo-M7208w.html) where they mention some ways what to try to fix it, but I haven't tried any myself. Or ask the manufacturer for Linux driver.

Or you can try whether the printer can work without driver (it is a model from 2012, it could) - [how-to](https://docs.fedoraproject.org/en-US/quick-docs/cups-useful-tricks/#_how_to_find_out_whether_my_printer_is_capable_of_driverless_printing)

**Comment by draculalaa** [comment]
@zdohnal Really appreicate your help! I'll try these methods you metioned above later.
