### ISSUE TITLE
Include a difference to Apple's CUPS in README

### ISSUE THREAD

**Issue by TheEvilSkeleton** [OpenPrinting/cups#8]
Hello, I would appreciate if the README provides an explanation to why this fork has been created.

I'd advise to change the name to make it stand out even more. Something like `cups-ng` (CUPS New Generation).

**Comment by unquietwiki** [comment]
@TheEvilSkeleton  it definitely needs to be reconciled with the status of https://www.pwg.org/ipp/everywhere.html , https://openprinting.github.io/projects/02-foomatic/ , https://developers.hp.com/hp-linux-imaging-and-printing , and other open-source & CUPS-dependent printer projects.

**Comment by michaelrsweet** [comment]
Right now this is a holding ground for the common patches used by the various Linux distributions, *BSD, etc. since Apple hasn't been keeping up with the issues on the main repository. Our intention is to provide Apple with well-tested pull requests that ultimately end up in the Apple CUPS repository.

Changing the name is always a possibility, but the current goal isn't to develop away from the Apple CUPS code so changing the name might send the wrong message.

**Comment by Scaledi** [comment]
Is it worth marking this issue as resolved or wontfix?

**Comment by michaelrsweet** [comment]
@Scaledi I'd like to keep this open until we make some sort of change to the README file. I *did* update the repository description to better reflect its purpose, but the README will be a more visible place. I'd also like to do named releases (e.g., 2.3.3OP1 or something like that for the first OpenPrinting update after Apple CUPS 2.3.3) to make it easier to track changes, etc.

Similarly, I think we'll track the OpenPrinting changes in a separate file ("CHANGES-OP.md" or something like that) to help keep things clear.

**Comment by rubyFeedback** [comment]
> Changing the name is always a possibility, but the current goal isn't to develop away from the Apple CUPS code so
> changing the name might send the wrong message.

While I understand your mentioned design constraint (or design goal) here, right now probably not many people
know that even such an alternative exists. I found this via reddit, for instance.

Unfortunately the main README does not make any such mention. Perhaps in the long run, when someone has
time, it should be considered whether to mention that and make it more clearly that this is separate, even if
(or especially when) the name is retained.

**Comment by michaelrsweet** [comment]
@rubyFeedback @unquietwiki @TheEvilSkeleton OK, so now we have a short note at the top of the README file and a CHANGES-OPENPRINTING.md file to list the changes since the most recent Apple CUPS release. Let me know if you think more is necessary...

**Comment by TheEvilSkeleton** [comment]
Looks all good to me
