### ISSUE TITLE
Driverless printing doesn't work with Pantum BM5100ADW Series (investigated and fixed)

### ISSUE THREAD

**Issue by alexpevzner** [OpenPrinting/cups#804]
Cc: @michaelrsweet, @tillkamppeter, @zdohnal 

Dear colleagues,

I'm writing from Fedora 38 with cups 2.4.7, but the same issue exist for ALT Linux and ROSA Linux, so it seems to be common.

When Pantum BM5100ADW connected driverlessly, it scans perfectly well, but doesn't print. Attempt to print wakes up the printer, but job ends with "Print job canceled at printer" state.

The behaviour is the same regardless of how the device is connected: via network or via USB and `ipp-usb`. But on USB it causes more problems, because `ipp-usb` conflicts  with the proprietary driver (which prints and scans), so causing users to remove `ipp-usb` and complain.

After some investigations I've noticed the following facts:
* Device supports (`document-format-supported`) `image/urf,image/pwg-raster,application/octet-stream` and prefers (`document-format-default`) `image/urf`
* Cups sends `image/urf` to the device
* The resulting image is RGB
* Device rejects RGB images, while Grayscale images are printed perfectly well

After some deeper investigation I've found that generated PPD files are not the same when generated by `driverless cat` or by `cups` itself (and saved to `/etc/cups/ppd/`):
* PPD file, generated by cups: [Pantum_BM5100ADW_Series_2DFFA2.ppd.txt](https://github.com/OpenPrinting/cups/files/13064304/Pantum_BM5100ADW_Series_2DFFA2.ppd.txt)
* PPD file, generated by `driverless cat`: [driverless.txt](https://github.com/OpenPrinting/cups/files/13064306/driverless.txt)

The PPD file, generated by `driverless cat` command works correctly: Grayscale image is generated and prints perfectly well, while PPD file, generated by cups, doesn't work.

There are many differences between these two files, but essential difference is the one single line:

```
*cupsUrfSupported: "V1.4,W8,IS1,CP99,PQ4,OB10,RS600,DM1"
```

This line present on `driverless cat` output and missed in the file, generated by cups.

Most likely, this problem affects not only Pantum but many other devices with the common feature to require `image/urf` format and to reject RGB image.

The simple patch to the `cups/ppd-cache.c` fixes the problem -- PR comes soon.

**Comment by michaelrsweet** [comment]
FWIW, the CUPS-generated PPD file only reports grayscale support, so if the filter is producing RGB then that is a serious bug in the filter.

**Comment by alexpevzner** [comment]
> FWIW, the CUPS-generated PPD file only reports grayscale support, so if the filter is producing RGB then that is a serious bug in the filter.

Agree. Anyway, the supplied PR provides a hot fix for the problem.

I suggest to merge in this simple patch, as it quickly solves the real problem and doesn't seem to break anything, and I can look to the cups-filters too (I want to familiarize myself with the Linux printing stack anyway).
