### ISSUE TITLE
Make install fails to include base.h file

### ISSUE THREAD

**Issue by Kappuccino111** [OpenPrinting/cups#809]
**Describe the bug**
Make install command in cups fails to install base.h file in the include directory due to which libcupsfilters fails to make.

**Screenshots**
- Make commands in libcupsfilters gives the following error :
<img width="725" alt="image" src="https://github.com/OpenPrinting/cups/assets/120595108/84ab6352-4aa0-4c81-a72e-037aff1f3e93">

**Comment by michaelrsweet** [comment]
[master 200124285] Fix 'make install' for base.h (Issue #809)

> **Note:** CUPS 2.5 isn't even ready for beta testing and shouldn't be used for production builds...
