### ISSUE TITLE
Browsing is always "On" by default

### ISSUE THREAD

**Issue by trialuser02** [OpenPrinting/cups#82]
I compiled CUPS 2.3.3op1 with "--disable-browsing" configure option, but default cupsd.conf still contains "Browsing On".

**Comment by michaelrsweet** [comment]
Hmm, OK right now the default in cupsd is determined by this configure option but the default cupsd.conf file contains a Browsing directive that overrides the default... Should be easy enough to fix...

**Comment by surajkulriya** [comment]
@michaelrsweet  can we close this one now?
Thanks

**Comment by michaelrsweet** [comment]
Yes, surprised it wasn't already.
