### ISSUE TITLE
TSPL Filter from TSC

### ISSUE THREAD

**Issue by iamacarpet** [OpenPrinting/cups#820]
**Is your feature request related to a problem? Please describe.**

CUPS not only runs on Mac, normal Linux distros & FreeBSD, it has recently found another large user facing install base in Chrome OS.

Chrome OS is popular with consumers, small business and with a growing number of enterprise users, where TSC and (in small business) other cheap thermal label printers that speak TSPL (like iDPRT, Munbyn, Polono) are common for things like shipping labels.

Chrome OS will accept PPD files that are passed to CUPS for printer configuration, however, you can't install custom filters, as no custom binaries are allowed on the system at all - it's completely read only once built by Google.

They have acknowledged the problem and are open to including more filters, although, on clarification, they require them to be open source:

> ChromeOS ships a limited set of filters.  We don't provide a way to load additional user-supplied filters.  If your PPD requires a filter that isn't part of the OS image, it can't be loaded, as you've seen.
>  
> If there's an existing CUPS filter that would support SLCS, please feel free to open a bug here and we can evaluate whether it would be practical for us to include that with future OS versions.
>
> Thanks,
> Benjamin
 
_https://groups.google.com/a/chromium.org/g/chromium-os-discuss/c/fIo6PNOqam8/m/vxwnW03tAwAJ_ 

I'm in talks with TSC to open source their own filter, which they currently only distribute as a closed source binary.

It's helping their discussion that their competitor, Zebra, has support included by default in CUPS and even some basic PPDs bundled out of the box, which obviously isn't too favourable for them.

**Describe the solution you'd like**

If TSC agree to open source their filter, we hope Google will include it within Chrome OS.

However, for the best benefit of the community (and to give TSC more reason to cooperate), it would be great to integrate their filter into the main CUPS repository, to be bundled with every install by default, to match their competitor Zebra.

You mentioned here that nothing else will be included in CUPS by default:

https://github.com/OpenPrinting/cups/issues/331#issuecomment-1031726810

However, if it helps TSC cooperate & improves the ecosystem as a result, I hope you'll reconsider that position.

**Describe alternatives you've considered**

Once open sourced in an independent repository, asking Google to include it just within Chrome OS, to the determent of the wider CUPS community.

LPrint isn't an option for locally connected, USB printers, as no other applications can be loaded onto Chrome OS, and CUPS is the only printing service that is bundled.

**Comment by ikwach** [comment]
Leaving this here because the issue comes up when people search for a TSPL CUPS
filter: an open source one exists now. MIT licensed, no vendor code, filter plus
backend plus PPD, packaged for deb, rpm, Arch and Nix.
https://github.com/RunTheWall/tspl-cups-driver
