### ISSUE TITLE
"/var/spool/cups/d26756-001: reported number of objects (34) inconsistent with actual number of objects (33)"

### ISSUE THREAD

**Issue by sksundaramoorthy** [OpenPrinting/cups#825]
I am getting below message when I print PDF via cups. I used cups version "CUPS 2.2.6"

It takes 10 mins to print the PDF file. What is the issue?

"/var/spool/cups/d26756-001: reported number of objects (34) inconsistent with actual number of objects (33)"

**Comment by zdohnal** [comment]
Hi,

the message is probably from libqpdf which is core of the filter pdftopdf - your application sends incorrectly structured PDF, which can cause the delay - other things which can influence the delay is PDF size, network delays and final file format, which CUPS has to convert the PDF to. The final file format is set by the driver you installed your printer with.

Are you able to reproduce the behavior with CUPS 2.4.7?

**Comment by zdohnal** [comment]
No response for almost two months - feel free to reopen if you have the requested info.
