### ISSUE TITLE
github action for PR naming convention 

### ISSUE THREAD

**Issue by Min2who** [OpenPrinting/cups#861]
**Is your feature request related to a problem? Please describe.**
When a PR is open in the title it should contain what it is trying to fix ( for example if the PR is fixing a bug the title should be fix: ....,if it is adding a feature it shoub be feat: ...., if it is updating the doc it should be doc: .....)

**Describe the solution you'd like**
A github action to validate if the pr follows naming convention

**Comment by zdohnal** [comment]
Hi @Min2who ,

thank you for the idea!

@michaelrsweet tbh I don't recall if we have such PR conventions written (I just use the best practise from my daily work) - if we had had imposed something like that, we would have to provide a guidance in DEVELOPING.md. Wdyt? IMO we can always change PR title and desc when we merge it, so imposing such rules on contributors seems unnecessary to me.

What would benefit us is automatic check for code style (I don't know how to check tabs in PR in browser...) - IIRC bind or similar project has something for it, but I'm not sure atm.

**Comment by michaelrsweet** [comment]
@zdohnal We don't have any explicit instructions regarding PR titles, etc., and as you say there really isn't a need - we can always correct things.

Coding style *is* documented, but at the moment the various tools are not up to the task of validating the coding style. There is/was a PR for using clang-format, but thus far it doesn't actually reproduce the coding style... :/

**Comment by zdohnal** [comment]
Ack.

@Min2who thank you for the suggestion, but we don't want to pursue this at the moment.
