### ISSUE TITLE
Cups does not support a3 printing

### ISSUE THREAD

**Issue by MimLyn** [OpenPrinting/cups#891]
I own a Canon Pixma ip8750 and do a lot of a3 printing on it. I've changed to different Linux Distro's and could no longer print a3. I tried to change the cups default print size to a3, but default size a3 is not present. 

To recreate steps:
1.   Type in the http://localhost:631/printers URL in the address panel.
 2.   Click on my printer name under 'Queue Name', [Canon_iP8700_series].
 3.    Click on the 2nd tab 'Administration'.
 4.    Scroll down to 'set default options' in the drop down.
 5.    In the page that opens, under the 'Defaults' header, click the 'media size' button, scrolled down to the bottom and click custom. 
 6.   Two new boxes appear. Type in 297 and 420 and set size option to cm, to match the size units in LibreOffice Draw, which I use.
 7.    As soon as I clicked the set default option at the bottom the selection list, I realised that it had changed back to the last default.

I expected the size a3 to be a default size and not a custom size. I also expected Cups to not revert to the previous default size used and to send the new print instructions to my application.

**System Information:**
 -KDE  (also happened in Linux Mint 21.3, Fedora 39, Pop OS 22.04 LTS, Debian 12.5.0)
 - Application Plasma 5.27.10
 - CUPS version 2.4.1

I used to be able to print in a3, but I am not sure if it is a recent upgrade of Cups, but, I no longer see a3 in my applications either in the Print Manager, no matter which on I choose to use.

**Comment by zdohnal** [comment]
Hi,

please turn on CUPS debugging, reproduce the issue and upload the logs here with .txt suffix. See "REPORTING_ISSUES.md" for more info.
Either whether the device currently has A3 support depends on its IPP reponse or its driver - I cannot guess which one is your case - there is no note how the device is connected and I don't see the driver - please upload your printer's PPD from /etc/cups/ppd as well, and if your device is connected by network and uses IPP (you can find out how [here](https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md#how-to-find-out-that-i-use-driverless-printing)), get the [IPP response](https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md#information-requested-for-driverless-network-printers) too.

**Comment by MimLyn** [comment]
KDE Neon Plasma

CUPS version 2.4.1

I own a **Canon Pixma ip8750** and do a lot of a3 printing on it. I've changed to different Linux Distro's and can no longer print a3. I tried to change the cups default print size to a3, but default size a3 is not present. The size a3 is present in the list of sizes to work with in applications that I use, it just is not present in the list of sizes to print, whether in the application or in cups.

Lpstat -e
Canon_iP8700_series

lpstat -l -e 
Canon_iP8700_series permanent ipp://localhost/printers/Canon_iP8700_series usb://Canon/iP8700%20series?serial=
20CD6E

lpstat -t 
scheduler is running 
system default destination: Canon_iP8700_series 
device for Canon_iP8700_series: usb://Canon/iP8700%20series?serial=20CD6E 
Canon_iP8700_series accepting requests since Thu 15 Feb 2024 10:05:08 GMT 
printer Canon_iP8700_series is idle.  enabled since Thu 15 Feb 2024 10:05:08 GMT

Files attached
[journalctl -cups OUTPUT.txt](https://github.com/OpenPrinting/cups/files/14296038/journalctl.-cups.OUTPUT.txt)

[journalctl.txt](https://github.com/OpenPrinting/cups/files/14296040/journalctl.txt)

[lpinfo -v OUTPUT.txt](https://github.com/OpenPrinting/cups/files/14296042/lpinfo.-v.OUTPUT.txt)

[lsusb -v OUTPUT.txt](https://github.com/OpenPrinting/cups/files/14296043/lsusb.-v.OUTPUT.txt)

**Comment by zdohnal** [comment]
CUPS debug logging does not seem enabled or your OS does not send CUPS debug logs into journal. Please check it (see /etc/cups/cups-files.conf) and send CUPS debug logs when you try print A3 and when you try to set the custom option.
Second, I don't  see your PPD file - can you attach it as well?

**Comment by MimLyn** [comment]
Hi. I am not sure if I have attached what you requested properly or at all. Please advise. Thank you.

[CUPS PPD FILE.odt](https://github.com/OpenPrinting/cups/files/14322613/CUPS.PPD.FILE.odt)

[cupsd.txt](https://github.com/OpenPrinting/cups/files/14322616/cupsd.txt)

**Comment by zdohnal** [comment]
I can't read the first file and the second is configuration file. Please try again.

Find out where logs are:

```
$ sudo grep ErrorLog /etc/cups/cups-files.conf
ErrorLog <location>
```

if ```<location>``` is syslog, logs will be in journal, accessible by ```journalctl -u cups```.


Enable logs:

```
$ cupsctl LogLevel=debug2
```

and reproduce the issue (try print A3).

Take logs from the location (syslog is accessible via journalctl), put them into .txt file and attach the file here.

Ad PPD file, you can just copy it into .txt file (and make it world readable+writable):

```
$ sudo cp /etc/cups/ppd/Canon_iP8700_series.ppd ~/canon.ppd.txt
$ sudo chmod 666 ~/canon.ppd.txt
```

and attach ~/canon.ppd.txt here.

**Comment by dkosovic** [comment]
Your Canon Pixma ip8750 printer has driverless AirPrint support. You appear to be using a Gutenprint v5.3.3 driver. I suspect it is a Gutenprint bug for not listing A3 as a selectable page size.

You could try switching to "IPP Everywhere" or "Driverless" (which will use AirPrint) instead of the printer driver you currently have selected.

**Comment by MimLyn** [comment]
Thank you. I will give it a try. I'm grateful On 29/02/2024, 20:56 Douglas Kosovic ***@***.***> wrote:

   
  Your Canon Pixma ip8750 printer has driverless AirPrint support. You appear to be using a Gutenprint v5.3.3 driver. I suspect it is a Gutenprint bug for not listing A3 as a selectable page size. 
  You could try switching to "IPP Everywhere" or "Driverless" (which will use AirPrint) instead of the printer driver you currently have selected.

**Comment by dkosovic** [comment]
AirPrint and IPP Everywhere should work if the printer is connected to the network via Wi-Fi, might also work over USB, but not sure with that model, may need to configure `ipp-usb` :
* [https://fedoraproject.org/wiki/Changes/IPPUSBasPrintScanDependency](https://fedoraproject.org/wiki/Changes/IPPUSBasPrintScanDependency)
