### ISSUE TITLE
Codebase should be linted/audited for issues

### ISSUE THREAD

**Issue by unquietwiki** [OpenPrinting/cups#9]
https://github.com/caramelomartins/awesome-linters#cc

Especially with all the newer compilers out right now, I bet there is a fair amount of code that will not compile correctly without some Makefile tweaking. Do we even know right away if this is C99 or a newer standard?

**Comment by michaelrsweet** [comment]
@unquietwiki The CUPS code has been linted and scanned and fuzzed since its original release by every tool in existence. Current practice is to use the Clang static analyzer and LGTM on a regular basis.

The original target was C89 + POSIX. We still avoid C++ comments ("//") in C files.

**Comment by unquietwiki** [comment]
@michaelrsweet Holy crap, that is through, thank you. It also looks like you're dealing with #8 which would give us all a better idea what's going on.

**Comment by DemiMarie** [comment]
@michaelrsweet Is CUPS part of OSS-Fuzz?

**Comment by michaelrsweet** [comment]
@DemiMarie No, although I know Google does internally do a lot of fuzz testing of CUPS for ChromeOS.
