### ISSUE TITLE
Support of different PDLs in IPP Everywhere and Generic IPP Everywhere drivers

### ISSUE THREAD

**Issue by stavikpetr** [OpenPrinting/cups#906]
Is there a way how can IPP printer specify, which PDL should be generated when I add it to CUPS? For example if I have a printer, that only supports PCL XL PDL, is there a way how to make the IPP driver (either IPP Everywhere driver, or the Generic IPP Everywhere driver) to generate print job with such PDL? I thought that if the printer returns some specific attributes in the Get-Printer-Attributes operation, it can be achieved, but I tried all three `document-format-default, document-format-preferred, document-format-supported` attributes and I played with different values (e.g. `application/vnd.hp-PCLXL` for PCL XL), and with no success. The IPP Everywhere driver generates PDF, the Generic IPP Everywhere driver generates some PWGRaster. Any suggestions?

Btw I know it is possible to specify different drivers and it should be probably possible to add IPP Printer and as a driver choose some PCL XL driver, but I want to avoid this, use the generic driver and let the printer specify this.

CUPS version: 2.3.3

**Comment by zdohnal** [comment]
IPP Everywhere model is designed for document formats which are present in driverless printing - image/pwg-raster, image/urf, application/pdf - not for any existing PDL.
