### ISSUE TITLE
cups 2.3.3op2: waiting for printer to become available when printing

### ISSUE THREAD

**Issue by tomasmez** [OpenPrinting/cups#91]
Hello.

Since cups 2.3.3op2
Cups cant find the usb printer when printing on a HP1018 laserjet.

Trying to add the printer again to reinstall it will not list it as available (as it normally happens)

Cups 2.3.3op1 works ok.

**Comment by michaelrsweet** [comment]
@tomasmez Can you attach the output of:

    /usr/lib/cups/backend/usb

The only change to the USB backend was to alter the timing of backchannel reads (to fix a separate regression from back in 2.2.10)...

**Comment by michaelrsweet** [comment]
No response in 2 months, closing.
