### ISSUE TITLE
waitprinter parameter doesn't seem to take effect

### ISSUE THREAD

**Issue by fushengss** [OpenPrinting/cups#910]
**Describe the bug**
"I added the waitjob and waitprinter parameters when adding the printer. Based on my testing, it seems that only the waitjob parameter is taking effect. The next job, after connecting to the printer, displays 'the printer is in use' until the previous job is completed, and then it takes about 5 seconds to start printing the next job.

However, when I use Apple CUPS 2.3.3, all jobs (3 in total) are added to the printer's print queue, as shown in the following image:"
![image](https://github.com/OpenPrinting/cups/assets/36076659/44f02a8c-c965-452b-b892-290392fe0e7f)

**Screenshots**
This is the job page for Apple CUPS 2.3.3;

https://github.com/OpenPrinting/cups/assets/36076659/f9b586e7-8e60-40ad-b7bf-b99b0be3acc5

And this is the job page for CUPS 2.4.7;

https://github.com/OpenPrinting/cups/assets/36076659/79906423-a0a6-4069-831a-fad643a660ad

These are some configuration details of the printer in CUPS 2.4.7:
![image](https://github.com/OpenPrinting/cups/assets/36076659/956b5662-4223-4df2-b57e-4f8785beedcf)

**System Information:**
 Ubuntu 22.04
 chrome
 CUPS 2.4.7

**Additional context**
This is two log files, in which Apple CUPS is running on CentOS：
[error_log.zip](https://github.com/OpenPrinting/cups/files/14468326/error_log.zip)

**Comment by zdohnal** [comment]
You have a different backend with CUPS 2.3.3 - lpd - and with CUPS 2.4.7 - ipp. Their protocols which they implement behaves differently.

ipp has a delay because your printer reports internal server error (looks it is busy):

```
  522 D [02/Mar/2024:14:25:15 +0800] [Job 810] Get-Printer-Attributes: server-error-service-unavailable (Internal Server Error)
  523 D [02/Mar/2024:14:25:15 +0800] [Job 810] Get-Printer-Attributes returned server-error-service-unavailable.
  524 D [02/Mar/2024:14:25:15 +0800] [Job 810] The printer is in use.
```

Either way, waitprinter on ipp backend does not seem to make sense - the backend sends the data as soon as the printer says it is ready.
