### ISSUE TITLE
Several options for EPSON Ecotank ET-8500 do not appear when using ipp driverless. (Despite appearing in airprint)

### ISSUE THREAD

**Issue by Bitwolfies** [OpenPrinting/cups#915]
**Describe the bug**
Certain options, such as the "best" quality option, or CD page size simply do not appear when using ipp and the aforementioned printer, despite them showing up fine when using airprint, which is just ipp again.
**To Reproduce**
1. Connect an ecotank et-8500
2. Try to switch quality to best 
3. There is no best

**Expected behavior**
Options like best quality to appear 

**System Information:**
 - OS and its version: Arch, latest stable repos as of March 28th.
 - Application: KDEs print settings, cups web interface 
 - CUPS version  1:2.4.7-2

**Additional context**
It's interestingly able to generate the borderless page setups, which airprint does not.

**Comment by ValdikSS** [comment]
Try the current git master, there were multiple changes for DPI detection and quality.

**Comment by ValdikSS** [comment]
Try cups-browsed then. It would add the printer by using cups-filters, not cups.

**Comment by michaelrsweet** [comment]
Can you attach the PPD file from /etc/cups/ppd and the output from the following command so we can duplicate your setup?

    ipptool --ippserver epson.conf ipp://HOSTNAME/ipp/print get-printer-attributes.test

"HOSTNAME" is the hostname or IP address of your EPSON printer.

**Comment by michaelrsweet** [comment]
The output from the ipptool command should end up in a file named "epson.conf".

**Comment by michaelrsweet** [comment]
So the PPD is actually generated by the "driverless" backend (as opposed to the built-in IPP Everywhere PPD generator) which *could* be an issue. It has cupsPrintQuality options for normal and high (best) quality, but I'm not sure how well this is plumbed up in the standard Linux print dialogs...

Using the following command to setup a print queue should yield the most predictable (and for our purposes in the CUPS project, the most supportable/testable) results:

    lpadmin -p PRINTERNAME -E -v ipps://HOSTNAME/ipp/print -m everywhere
