### ISSUE TITLE
Ignores job-originating-host-name

### ISSUE THREAD

**Issue by psz2036** [OpenPrinting/cups#916]
CUPS ignores (overrides) the value of job-originating-host-name sent. 
Issue observed at version 2.4.2 in Debian bookworm, present still in
current "master" version. Patch tested against Debian, but for current
version, below (in plain-text and as attached file).

Cheers, Paul
--
Paul Szabo       psz@maths.usyd.edu.au       www.maths.usyd.edu.au/u/psz
School of Mathematics and Statistics   University of Sydney    Australia

```
--- scheduler/ipp.c.ORIG	2024-03-31 07:47:17.630302410 +1100
+++ scheduler/ipp.c	2024-03-31 07:49:31.802244933 +1100
@@ -1635,9 +1635,20 @@
     * Request contains a job-originating-host-name attribute; validate it...
     */
 
+   /*
+    * PSz 18 Mar 24
+    * Override if the value is clearly wrong or impossible, or if
+    * the value is "localhost" but relative to some remote machine.
+    * Do not override just because we are not talking to localhost;
+    * in particular, keep and treasure the value sent to us from
+    * some intermediate or proxy server.
+    *if (attr->value_tag != IPP_TAG_NAME ||
+    *    attr->num_values != 1 ||
+    *    strcmp(con->http->hostname, "localhost"))
+    */
     if (attr->value_tag != IPP_TAG_NAME ||
         attr->num_values != 1 ||
-        strcmp(con->http->hostname, "localhost"))
+        !strcmp(attr->values[0].string.text, "localhost"))
     {
      /*
       * Can't override the value if we aren't connected via localhost.
```

[psz-patch.txt](https://github.com/OpenPrinting/cups/files/14813322/psz-patch.txt)

**Comment by michaelrsweet** [comment]
No. The intent of this feature is to allow a local proxy (cups-lpd, samba, etc.) to pass through the hostname from its remote connection. Changing things like this makes the value of job-originating-host-name *less* valid.

**Comment by psz2036** [comment]
I knew that was your intent, but your code did not do that.
Your code, your bug.
