### ISSUE TITLE
'*cupsManualCopies: true' should be '*cupsManualCopies: True'

### ISSUE THREAD

**Issue by jsmeix** [OpenPrinting/cups#93]
According to
https://github.com/OpenPrinting/cups-filters/issues/242
`*cupsManualCopies: true` should be `*cupsManualCopies: True`

I found `*cupsManualCopies: true` at
https://github.com/OpenPrinting/cups/blob/master/doc/help/spec-ppd.html#L1961
and at
https://github.com/OpenPrinting/cups/blob/master/filter/spec-ppd.shtml#L1406

I don't know if it is also somewhere else implicitly.
https://github.com/OpenPrinting/cups-filters/issues/242#issuecomment-657516232
reads
```
As libppd is completely copied from libcups
the bug still exists in libcups and would need to get reported there.
```
but that comment is from Jul 13 2020 so it is perhaps already fixed?

**Comment by surajkulriya** [comment]
@michaelrsweet  What if we make `true` case insensitive in such cases. I mean
         `*cupsManualCopies: true`
         `*cupsManualCopies: True`
         `*cupsManualCopies: TrUe`
all should be valid.
The process will become less error prone if we somehow do it and we will face less issues like [this](https://github.com/OpenPrinting/cups-filters/issues/242#issuecomment-657516232). 
We can do this for `AccurateScreensSupport`, `ColorDevice`, `ContoneOnly`, `cupsFlipDuplex` and `cupsManualCopies` options.
What's your thoughts ?

**Comment by michaelrsweet** [comment]
@surajkulriya It makes sense for the PPD APIs to use case-insensitive comparisons going forward, but existing clients will expect "True" so we should also make *that* change to be 100% conforming.

**Comment by surajkulriya** [comment]
@michaelrsweet  Can we close this one now ?
Thanks

**Comment by michaelrsweet** [comment]
Yep.
