### ISSUE TITLE
DNP QW-410 wrong paper size

### ISSUE THREAD

**Issue by tapeo** [OpenPrinting/cups#941]
Hi, thanks for your work.

I have problems with a DNP QW-410.

I installed CUPS via ubuntu (22.04) apt and then installed Gutenprint 5.3.4 compiling it. Then I setup the printer via CUPS web interface correctly by selecting the gutenprint driver and selecting the 4x6 paper.

I added the printer successfully through Ubuntu settings but when I try to print a 4x6 picture (the one that comes from DNP as test picture), the printer prints not a 4x6 but a 4x4 I think (see attachments).

I tried the last two days by tweaking the original PPD related to the QW-410 but all the attempts print wrong image sizes.

Can anyone help with that?

Thanks!

Ubuntu 22.04
CUPS version 2.4.1

**Comment by michaelrsweet** [comment]
I think you need to report this to the Gutenprint folks - there are no attachments but ordinarily these sorts of issues turn out to be either Gutenprint or cups-filters issues and are not specific to CUPS itself.
