### ISSUE TITLE
[CI MacOS] Linking the library fails

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/cups#949]
MacOS CI build fails on master and 2.4x - looks like a change in the testing machine, not caused by commit:

ld: warning: -single_module is obsolete
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libcups.2.dylib] Error 1

@michaelrsweet looks like openssl is used from homebrew, did something break on that side?

**Comment by michaelrsweet** [comment]
The macOS CI wasn't installing prerequisites... Testing a fix now.

**Comment by michaelrsweet** [comment]
Apparently OpenSSL is always installed, but the pkg-config info doesn't appear to be correct... I'd say this is a Homebrew bug but I'm trying something with setting LDFLAGS...

**Comment by michaelrsweet** [comment]
OK, so this seems to be resolved now.
