### ISSUE TITLE
100% CPU usage when printing files

### ISSUE THREAD

**Issue by Stempel98** [OpenPrinting/cups#956]
Hey!
I have some problems when printing files via cups.  It takes few minutes until file will print

Printer: HP Deskjet 1510
Board: Raspberry Pi Zero

<img width="1471" alt="image" src="https://github.com/OpenPrinting/cups/assets/102163083/36df2f59-b24d-4ed9-9766-23b499373f60">

**Comment by Stempel98** [comment]
Yes, I have the same issue in every file I'm printing :/ Right now I'm receiving different error "Filter failed"

**Comment by zdohnal** [comment]
Can you turn on debug logging, print again and attach the file with logs here?

**Comment by michaelrsweet** [comment]
No response, closing...
