### ISSUE TITLE
Do not include the "configure" script in the GIT repository

### ISSUE THREAD

**Issue by tillkamppeter** [OpenPrinting/cups#96]
I am currently working on a commit to make CUPS supporting to work with snapped clients and to work snapped by itself. This adds several build-time options (a snapped CUPS needs some changes) and so the `configure` script will get changed, by an additional `.m4` file in the `config-scripts/` directory.

`configure` is a machine-generated file completely generated by `autoconf`, but if I run `autoconf` I get many more changes that just what comes from my new `.m4` file, as everyone has a different `autoconf` version. I have 2.69, @michaelrsweet  AFAIR you are using 2.70? Right? And in addition `autoconf` can have distro patches. This means that when different contributors commit to CUPS that we will get an unnecessary, confusing forth-and-back in `configure`.

Therefore machine-generated files like `configure` are not included in version control repositories. For releases to include in the tarball, `configure` is generated by something like `make dist`.

Could CUPS get changed in this way, too.

**Comment by michaelrsweet** [comment]
@tillkamppeter I used to do this a while back but it sometimes causes issues if the developer system has an incompatible version of autoconf installed or (as sometimes happens) somebody decides to (incorrectly) run automake instead of autoconf.

Let me think about this, as it will also affect the CI workflows we have setup...

**Comment by michaelrsweet** [comment]
@tillkamppeter I would also like to see the snapcraft changes you are adding to CUPS merged here - no need for that code to sit on the sidelines anymore...

**Comment by tillkamppeter** [comment]
OK, will do this soon, with appropriate `./configure` switches.

**Comment by tillkamppeter** [comment]
Seems that this issue needs to get fixed first before I complete applying all CUPS-Snap-related patches, as my commit 0cdf79ef5e fails the CI tests due to the fact that they do not rebuild `./configure`.

**Comment by michaelrsweet** [comment]
@tillkamppeter I'd appreciate it if we all create temporary "feature" branches for large changes like that so that we can get some CI time, then merge the change once you know the big change passes all the build tests.

**Comment by michaelrsweet** [comment]
@tillkamppeter I left some comments against the commit - overall the changes look reasonable but there is room for improvement (as always :)

Also, I pushed an updated configure script to fix the build issues: [master a99c6102c] Update configure script and changelog.

**Comment by tillkamppeter** [comment]
I need your help again, could you push another rebuild of `configure`? Thanks.

**Comment by tillkamppeter** [comment]
To make contributions easier (independent of directly or in a separate branch) we really need to remove `configure` or as an interim workaround at least let the CI builds run `autoconf` before building.

Note that I do not generate `configure` files as I do not have `autoconf` 2.70 and if I use the 2.69 of Ubuntu Hirsute there are too many changes which cause a lot of confusion/distraction in the commit.

**Comment by michaelrsweet** [comment]
@tillkamppeter "too many changes" is not a problem for the configure script, you can go ahead an use 2.69 until you can upgrade. And the reverse problem is that if you don't notice that the configure script sources have changed then you'll end up with a broken build as well.

**Comment by tillkamppeter** [comment]
Thanks for the update, nicely small, my 2.69 version changed more than 1000 lines and the poor reader than has to find the relevant changes which are in the 5 or 6 other files.

**Comment by tillkamppeter** [comment]
The Snap-related patches which are available are all applied now. If one would spin a release now the CUPS Snap build does not need the patches any more, but the problem with the call of the external `snapctl` executable is solved on the snapd side now, so I will do an update soon to implement the solution on the CUPS side.

**Comment by michaelrsweet** [comment]
@tillkamppeter Given that we've resolved the configure patch issue you were having, I'm going to close this issue as "wontfix". It is hard enough to ensure that there is a working configure script without also needing a new enough version of autoconf to build it. And we don't need to break existing users of the Git repository.
