### ISSUE TITLE
Zebra Label Print Invalid characters.

### ISSUE THREAD

**Issue by rkumaresgit** [OpenPrinting/cups#962]
**Is your feature request related to a problem? Please describe.**
We are using CUPS server for printing and Zebra printers. We are seeing invalid characters from time to time.
ZPL print starts with ^XA and ends with ^XZ and it prints successfully in Zebra printers, but few times on a daily basis we are seeing invalid characters **^xa^xa END** at the end, which is showing in the Zebra print logs and didn't print the label.  Print request transferred from CUPS to Zebra, invalid characters shows up in the Zebra print logs. From the application to CUPS, we are seeing the correct print characters. When we check the print logs in the CUPS, we are seeing the labels with correct ZPL characters.

**Describe the solution you'd like**
In the CUPS server when we check the print log it is showing correct print commands starts with ^XA and ends with ^XZ. We are expecting this behavior all the time.

**Describe alternatives you've considered**
After trying reprints few time(s) the label gets printed in the zebra printer. 

**Additional context**
We wanted to know if there was any prior issue like this, is there any bug reported for this issue.

**Comment by michaelrsweet** [comment]
What version of CUPS are you using?

What OS/Linux distribution?

What printer model(s)?

What driver are you using?

**Comment by rkumaresgit** [comment]
Thank you for the email. It has been a while we logged this issue.It was the network issue and they resolved it 
    On Tuesday, August 13, 2024 at 09:22:26 PM PDT, Michael R Sweet ***@***.***> wrote:  
 
 


What version of CUPS are you using?

What OS/Linux distribution?

What printer model(s)?

What driver are you using?
