### ISSUE TITLE
Missing Drivers for Canon.

### ISSUE THREAD

**Issue by HansHeering** [OpenPrinting/cups#969]
Hi there, 

I would like to note, that in I have the newest cups version and there seems to be no driver for my Canon Pixma G6050.
Indeed, there seem to be no drivers for the entire series of G6000 and G5000. 
I would just like to note it in hopes of it being rectified in the next update.

Thanks for your time
HansHeerng

**Comment by tangyanli** [comment]
The driver for Pixma G6050 can be downloaded from:
https://www.canon-europe.com/support/consumer/products/printers/pixma/g-series/pixma-g6050.html?type=drivers&language=EN&os=Linux%20(64-bit)
