### ISSUE TITLE
Webinterface admininstration part buttons: Manage Printers & Classes broken

### ISSUE THREAD

**Issue by JorgenJan** [OpenPrinting/cups#972]
**Describe the bug**
In the webinterface in the Administration tab the buttons Manage Printers and Manage Classes do not work, return 'Not Found'

**Steps to reproduce the behavior:**
1. Go to url: localhost:631/admin
2. Click on 'Manage Printers'
3. the url  is localhost:631/printers/? and produces 'Not Found'
4. work around: change the url to: localhost:631/printers
5. Similar problem with 'Manage Classes', but somehow 'Manage Jobs' works fine non the less.

**Expected behavior:**
 showing the right webpages.

![Screenshot_2024-06-02_13-05-58](https://github.com/OpenPrinting/cups/assets/171484476/a06865ae-a277-4dc9-9f5e-2184032ead2a)

![Screenshot_2024-06-02_13-06-21](https://github.com/OpenPrinting/cups/assets/171484476/c7ca5218-2f77-4703-8b55-48142ab2c6b1)

**System Information:**
 - ArchLinux
 - browser Firefox for Arch Linux 126.0.1 (64 bit)
 - CUPS version 2..4.8

**Additional context**
See also: [https://bbs.archlinux.org/viewtopic.php?id=296377](https://bbs.archlinux.org/viewtopic.php?id=296377)

**Comment by zdohnal** [comment]
Fixed in the past by https://github.com/OpenPrinting/cups/commit/3826de00c582 .
