### ISSUE TITLE
Alexa cannot discover printer

### ISSUE THREAD

**Issue by centauri61032** [OpenPrinting/cups#975]
OK, I'm not even sure if CUPS has this capability. But...

I have an HP LaserJet Pro MFP M426fdn printer. It is an older monochrome printer, without WIFI connectivity built in. I would like to be able to print to it from the built-in Alexa functions, like printing shopping lists. But Alexa only finds WIFI attached devices. 

I have successfully installed CUPS on a Raspberry pi 3B+, and added this particular printer. I have also successfully found this printer on my Windows 10 pc, and I can print to it from Windows without any issue. (Basically, everything installed and working on WIFI.)

However when I ask Alexa to 'find my printer', it does not located any device. 

Is there something else that needs to be done to accomplish this? Or is my application not supported?

Thanks!

**Comment by zdohnal** [comment]
The system you use Alexa on has to be able to find IPP devices on local network via mDNS - CUPS is able to do it, but I don't know whether there is CUPS on your machine with Alexa or how Alexa looks for printers.

Check with ```lpstat -l -e``` whether you see the Raspberry shared printer from another Linux/Mac machine, and if you do, then there is an issue on your machine with Alexa, and contact its support.
