### ISSUE TITLE
Can not get the value of number-up-layout-supported by cupsFindDestSupported

### ISSUE THREAD

**Issue by xiaowen581** [OpenPrinting/cups#980]
**Describe the bug**
Can not get the value of number-up-layout-supported by cupsFindDestSupported.

**To Reproduce**
1. lpadmin to setup printer as local printer (create permanent queue)
2. call cupsFindDestSupported to query number-up-layout-supported from local printer ("printer-uri-supported")

**Expected behavior**
[btlr,btrl,lrbt,lrtb,rlbt,rltb,tblr,tbrl] should be returned.

**System Information:**
 - CUPS version 2.4.2

**Additional context**
"number-up-layout-supported" is settled in scheduler\printers.c\cupsdCreateCommonData, but not defined in cups\ipp-support.c\job_template. So the cups_dinfo_t * returned by cupsCopyDestInfo does not contains "number-up-layout-supported" in it.
The same as :
job-cancel-after-supported
notify-attributes-supported
notify-lease-duration-supported
notify-max-events-supported
notify-events-supported
notify-pull-method-supported
...

**Comment by michaelrsweet** [comment]
number-up-layout has been deprecated since CUPS 2.0.
