### ISSUE TITLE
Add Kyocera FS-1020MFP Driver Support to CUPS Repository

### ISSUE THREAD

**Issue by geugenm** [OpenPrinting/cups#981]
# Is your feature request related to a problem? Please describe.

A problem that driver is not in CUPS database. 

# Describe the solution you'd like

I propose integrating the Kyocera FS-1020MFP driver available on the official Kyocera website into the CUPS driver repository.

# Describe alternatives you've considered

> Downloaded directly from official website, run the script - https://www.kyoceradocumentsolutions.eu/en/support/downloads.name-L2V1L2VuL21mcC9GUzEwMjBNRlA=.html

# Additional context

*I didn't found another place(like driver mirror or something) to create a request especially for this driver that's why I'm writing here(don't have much time for searching, but would like to contribute or simply mark the problem).*

**Comment by zdohnal** [comment]
CUPS includes drivers only for several models and we don't plan on adding new, because the classic drivers are deprecated.

If the driver provided by Kyocera are under open source free license, you can start a project on Github and write a printer application for it ( https://openprinting.github.io/documentation/02-designing-printer-drivers/ ), which will be discovered and used by CUPS.

**Comment by geugenm** [comment]
Thanks for getting back to me! I'll give it a try later.

**Comment by geugenm** [comment]
Not about the issue, just a comment if someone will google it.

If someone has the issue with one of the following Kyocera printer models:
    - Kyocera FS-1020MFP
    - Kyocera FS-1025MFP
    - Kyocera FS-1040
    - Kyocera FS-1060DN
    - Kyocera FS-1120MFP
    - Kyocera FS-1125MFP
   
And the official drivers from the website are not working, you can try the following commands: 
```sh
wget https://raw.githubusercontent.com/mnorin/kyocera-ppd-installer/master/kyocera_ppds_installer.sh
```
```sh
chmod +x kyocera_ppds_installer.sh
```
```sh
sudo ./kyocera_ppds_installer.sh
```

This script will help you install the necessary Kyocera printer drivers, which may resolve the "Filter Failed" or "cfFilterChain: ghostscript (PID 16292) exited with no errors" issues. For me it was printing a test page successfully, but other jobs failed.
