### ISSUE TITLE
Connection refused from android but works for windows

### ISSUE THREAD

**Issue by cmg198** [OpenPrinting/cups#986]
I've set up a cups server on a raspberry pi, I can print fine from windows pcs on the local network but when I try to print from android I get a connection refused error ECONNREFUSED.

**Comment by SeeleVolleri** [comment]
Yes, I have same result. on android it just refused, but fine on iOS

**Comment by SeeleVolleri** [comment]
Holdon I accidently have package capturing enviorment, let me get some fresh pcap

**Comment by SeeleVolleri** [comment]
oh god it works again for no reason

**Comment by SeeleVolleri** [comment]
Try restarting cups, use a english printer name(whatever with description). probably becaused of that.

**Comment by michaelrsweet** [comment]
If you can reproduce again, it would be useful to know which Raspberry Pi you are using, the version of OS, the version of CUPS, etc.

**Comment by SeeleVolleri** [comment]
> If you can reproduce again, it would be useful to know which Raspberry Pi you are using, the version of OS, the version of CUPS, etc.

Use japanese or chinese words as device name can reproduce the error.

**Comment by michaelrsweet** [comment]
> Use japanese or chinese words as device name can reproduce the error.

Well that could be a client or a server issue - what does the error_log report when you try to access from the Android device?
